### ISSUE TITLE
Drop non-preemptive auth

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#1002]
AHC 1 auth is non-preemptive by default, meaning that, even as the user explicitly set a Realm on the config, a request, or a proxy, there's always a penalty of a useless 401/407 request.

Honestly, I don't see a use case for non-preemptive auth. Auth has always been preemptive in Gatling and no one ever complained.

I think we should drop it in AHC2.

@jfarcand @jroper @dotta @wsargent Asking for a friend

**Comment by slandelle** [comment]
@jfarcand Ping

**Comment by jroper** [comment]
Agreed.

**Comment by slandelle** [comment]
Mmm, I realize this would be an issue if someone was to ever contribute #840

**Comment by slandelle** [comment]
Some auth scheme are only non preemptive.
