### ISSUE TITLE
AsyncHttpClient fails silently when encountering a proxy error

### ISSUE THREAD

**Issue by drmaas** [AsyncHttpClient/async-http-client#1008]
If I execute a request against a URL that requires a proxy, but do not provide the proxy, using the BoundRequestBuilder, e.g. builder.execute(handler), no error message is logged. When using client.execute(request, handler), a NPE exception is thrown.

Ideally a proxy exception should be thrown in both cases to indicate the underlying error.

**Comment by slandelle** [comment]
Could you reproduce with latest master?

**Comment by slandelle** [comment]
What's your NPE stacktrace?

Do you see a way to reproduce when you're not in an organization that requires a proxy?

The behavior I'd expect would probably be a connection timeout because the host cannot be reached.

**Comment by drmaas** [comment]
I'll add a stacktrace (or lack thereof) when I'm back behind the proxy tomorrow.

No, I don't see a way to reproduce this when not in an org that requires a proxy.

**Comment by slandelle** [comment]
@drmaas Then I'm afraid you're in the best position to fix this :)

**Comment by drmaas** [comment]
Sorry I haven't had a chance to get to this. It's highly dependent on being in the office :)

**Comment by slandelle** [comment]
Ping @drmaas :)

**Comment by drmaas** [comment]
Haven't had a chance to get to it yet - will try to take a look next week. If I don't you can close it out.

**Comment by slandelle** [comment]
OK, thanks!

**Comment by slandelle** [comment]
Feel free to reopen if you can provide more information some day.
