### ISSUE TITLE
com.ning.http.client.RequestBuilderBase#build & query parameters

### ISSUE THREAD

**Issue by hugebdu** [AsyncHttpClient/async-http-client#1016]
com.ning.http.client.RequestBuilderBase#build seems to mess the uri when called more than once.
Multiple calls to build with query params defined generates uri with query params appended for each build call.

**Comment by slandelle** [comment]
That's how this builder is implemented in AHC1: its internal state is the request itself. In short: it's not supposed to be reused.
It changes in upcoming AHC2 and builder and request are properly isolated.

**Comment by hugebdu** [comment]
@slandelle, thanks for your quick feedback.

We're currently using 1.7 and calling 'build' several times during the construction without any problem.
I know that builder pattern doesn't guarantee reuse of builder instance.
But it worked fine and does not any more with 1.9

**Comment by slandelle** [comment]
RequestBuilder was broken in 1.7 for many other reasons.

**Comment by hugebdu** [comment]
I see.
Is there any migration guide for 1.7 to1.8?

I found one for 1.8 to 1.9.

Thanks!

**Comment by slandelle** [comment]
No, but 1.7 and 1.8 are quite close and migrating should be pretty easy. Bigger changes come with 1.9.
