### ISSUE TITLE
Did something change in 1.4.7 without a new release tag?

### ISSUE THREAD

**Issue by cpiggott** [AsyncHttpClient/async-http-client#1022]
Hello,

I was running 1.4.7 on an application that I was building and making a call to the Google Places API without any problems. 

Randomly one day, the API stopped working. At first I thought it was something with my API access or tokens, but everything on that side was working fine as I was able to make the same call from POSTman without issue. 

I updated to 1.4.9 and the call is still not working, while debugging I have found that JSON is being returned from the call, but none of the 'onSuccess' or 'onFailure' calls are being triggered.

Any help or information would be appreciated!

Thanks

**Comment by slandelle** [comment]
Wrong project: https://github.com/loopj/android-async-http/issues/876
Please ask those people to properly advertise where to ask on THEIR side!

**Comment by cpiggott** [comment]
My fault. Long day.

**Comment by slandelle** [comment]
Well, sadly, you're far from being the only one to make this mistake, and you won't be the last one either...

**Comment by cpiggott** [comment]
Glad I landed on it though!
Reading your documentation, this will work better than what I have been doing in the past for a class project.

Thanks.

**Comment by slandelle** [comment]
This project is focused on being a fast server side library, and it doesn't support Android.

If you were looking for this loop4j thingy, I guess you're an Android dev and are not looking for a server-side scale performance library. If so, you should definitively go with OkHttp from Square.

**Comment by cpiggott** [comment]
I used loop4j library for android, but I am currently designing an application for my masters project that I think I could use your tool for. 

The loop4j was something that I used in the past that is now randomly having problems. I might have to loop at the OkHttp or android.
