### ISSUE TITLE
Problem with custom FeedableBodyGenerator.

### ISSUE THREAD

**Issue by mielientiev** [AsyncHttpClient/async-http-client#1028]
Hello
I want to implement my custom FeedableBodyGenerator, but the problem is that it suspends forever (timeout) when I return BodyState.SUSPEND from transferTo method.
After a while, I've found out that resumeTransfer method wasn't called because you add this callback only for the SimpleFeedableBodyGenerator
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/request/body/NettyBodyBody.java#L70-L79

How can I implement my custom FeedableBodyGenerator with 'resumeTransfer' method feature?

**Comment by slandelle** [comment]
This was a regression introduced with the reactive streams support: https://github.com/AsyncHttpClient/async-http-client/commit/71c658c2938e6c158770f5f3c1eac3408a491f2a#diff-5ff1e79bd9d5712a41945ad9b0644cc5R70

Fixing

**Comment by mielientiev** [comment]
Great. Thanks. 
When this fix will be released?
