### ISSUE TITLE
When max connections per host exceeded, block instead of throwing "Too many connections"

### ISSUE THREAD

**Issue by agherardi** [AsyncHttpClient/async-http-client#1033]
Hi,
I call setMaxConnectionsPerHost() to limit the number of connections to individual destination hosts.

When all connections-per-host are tied up by other outstanding requests, AHC throws a "Too many connections" exception. I'd like to understand if there is a way to block new requests, instead, and avoid the exception.

ThrottleRequestFilter does something similar, however it can't do that on a per-destination host basis.

Is my only option to write a destination-aware throttle filter? Or are there other options?

Thank you in advance.

**Comment by slandelle** [comment]
No, we definitively don't want to block, that would break the whole engine.
You'd have to implement this manually, the built in feature only acts as a safety.

Then, for questions, please ask on the Google Group.
