### ISSUE TITLE
POST body is dropped on following 301 redirect

### ISSUE THREAD

**Issue by yuppie-flu** [AsyncHttpClient/async-http-client#1042]
### Environment:
async-http-client 1.9.31
netty 3.10.4.Final
AsyncHttpClientConfig.Builder().setFollowRedirect(true)

### Preconditions
"url-original" accepts POST and redirect to "url-redirected" with HTTP 301 status

### Steps:
Send request with asyncHttpClient.preparePost("url-original").setBody("not empty body").execute().get()

### Expected 
Request redirected to "url-redirected" with original body

### Actual
Request redirected to "url-redirected" with empty body

### Notes
1.8.14 version works as expected for this case

**Comment by slandelle** [comment]
No, actually, behaviour was wrong in 1.8.
Check what browsers do: on 301, method is transformed to GET and body is dropped.

**Comment by yuppie-flu** [comment]
Ok, may be this is the case for default behaviour.
But don't you think It will be worth to provide some configuration option to make client follow the rfc2616 specification.
For example, **curl** has the one called: **--post301**

**Comment by slandelle** [comment]
As you API obviously doesn't work with web browsers, I really suspect that you don't need the "Permanent Redirect" semantics you get with 301 that makes the redirect cached by web browsers.

Then, why not use another status code that would keep both original method and body: 307?
