### ISSUE TITLE
Problem with getting complete body from get request

### ISSUE THREAD

**Issue by andertun** [AsyncHttpClient/async-http-client#1047]
I try to load an bunch of XML files asynchronously, but I only get the first ~10.000 bytes of each. What am I doing wrong in the following code?

    AsyncHttpClient httpClient = new AsyncHttpClient(
        new AsyncHttpClientConfig.Builder()
            .setRequestTimeout(10000)
            .setMaxConnections(10)
            .build()
    );

    String url = "http://regnskaber.virk.dk/08007111/ZG9rdW1lbnRsYWdlcjovLzAzLzBjLzFmLzI2LzQ5LzU5YmMtNGM3Ni1hOTc4LWQxMmJhZjU2MzI3Mg.xml";
    Future<String> f = httpClient.prepareGet(url)
        .execute(new AsyncCompletionHandler(){
            @Override
            public String onCompleted(Response response) throws Exception{
                return response.getResponseBody("UTF-8");
            }
    });
    String xmlString = f.get();
    // xmlString.length() is 10906

I use async-http-client-1.9.31.

**Comment by slandelle** [comment]
Which provider are you using?

**Comment by slandelle** [comment]
Can't reproduce w/ Netty, I get a length of 54955.

**Comment by andertun** [comment]
I'm a unsure what you mean with "provider". I don't know which. Probably not Netty.
...and I use JavaSE-1.8

**Comment by slandelle** [comment]
Please read README. https://github.com/AsyncHttpClient/async-http-client#installation

**Comment by andertun** [comment]
Ahh, I missed the importance of Netty and went with the bare JDK. It works with netty. Thank you!

**Comment by slandelle** [comment]
Yeah, the bare JDK implementation is just a toy and should be used. AHC2 will only support Netty 4.
