### ISSUE TITLE
1.9 migration guide lies about compression being enabled by default

### ISSUE THREAD

**Issue by technocoreai** [AsyncHttpClient/async-http-client#1050]
The [1.9 migration guide](https://github.com/AsyncHttpClient/async-http-client/blame/master/MIGRATION.md#L22) documents request compression as being enabled by default, which is a rather sensible default value. However, the default value of `compressionEnforced` is actually `false`, so one of these things should change.

**Comment by slandelle** [comment]
You're right, this change was reverted, see https://github.com/AsyncHttpClient/async-http-client/issues/711
