### ISSUE TITLE
allow to configure executor in NioEventLoopGroup

### ISSUE THREAD

**Issue by rmannibucau** [AsyncHttpClient/async-http-client#1055]
Hi

is there any reason https://github.com/AsyncHttpClient/async-http-client/blob/1326cd2dcbcb9dc4b478ee398324c1464111eef5/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L169 is not configurable? Typically I'd like to be able to configure:

    NioEventLoopGroup(int nEventLoops, Executor executor)

**Comment by slandelle** [comment]
First, don't use issues for questions. We have a Google Group for this.

Then, you can pass your own EventLoopGroup via config: https://github.com/AsyncHttpClient/async-http-client/blob/1326cd2dcbcb9dc4b478ee398324c1464111eef5/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L174

**Comment by rmannibucau** [comment]
Well it is an issue since it is not configurable so thread are not controllable on a per client basis.

**Comment by slandelle** [comment]
Why is that so, if you can pass your own?

**Comment by rmannibucau** [comment]
In AsyncClientConfig you can't. You can pass the ThreadFactory which is not linked to the thread pool at all. Only configurable solution is using the netty system property which is then global to all client (and netty).

**Comment by slandelle** [comment]
> In AsyncClientConfig you can't.

Yes you can...
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/DefaultAsyncHttpClientConfig.java#L934-L937

**Comment by rmannibucau** [comment]
ok I see, expected something closer to threads but it works. Thanks!
