### ISSUE TITLE
AHC should accept a classloader at creation

### ISSUE THREAD

**Issue by dotta** [AsyncHttpClient/async-http-client#1057]
When creating an AHC instance, the classloader used to load the ahc-default.properties is the thread's context classloader. While this is a good default, it would be good if AHC would offer an explicit constructor taking a classloader.

**Comment by slandelle** [comment]
Hey @dotta 
You know the usual answer: contributions welcome! ;-)

**Comment by dotta** [comment]
@slandelle Of course! :-)

**Comment by hepin1989** [comment]
@dotta for Play's need for dynamic classloader?

**Comment by dotta** [comment]
@hepin1989 I'd say just to make things explicit and not having to side-effect the context classloader to successfully create AHC instances when done from a different classloader, e.g., when starting a Play server from a sbt task.

**Comment by slandelle** [comment]
ping @dotta :)

**Comment by dotta** [comment]
@slandelle Hey Stephane, this is not a priority for me, I just filed a ticket to keep track of it but I don't have spare cycles atm to work on this. Hope it's alright.

**Comment by slandelle** [comment]
No pro. Just that I expect to be able to release AHC 2 within one month, so if there's changes you want to push for Play, now's the time :)

**Comment by dotta** [comment]
Alright. Thanks for pinging me!

**Comment by slandelle** [comment]
Feel free to ping if you want to contribute and I'll reopen.
