### ISSUE TITLE
Grizzly: Value of keepAliveTimeout<=0 disables persistent connections

### ISSUE THREAD

**Issue by dfeist** [AsyncHttpClient/async-http-client#1063]
IMO Instead of disabling persistent connections, this should instead just propagate the negative timeout to grizzly which will disable the KeepAliveCleaner such that connections don't timeout if idle, but not disable persistent connections completely in AHC as seems to be the case currently.

Is it possible that this was introduced by mistake as part of the fix for https://github.com/AsyncHttpClient/async-http-client/issues/885? 

/cc @oleksiys

**Comment by oleksiys** [comment]
just updated
https://github.com/AsyncHttpClient/async-http-client/commit/f6fd24c385e65cf537c9e2c02a00de999db76d88

could you pls. check if it works for you?

**Comment by dfeist** [comment]
This change makes sense, but got two questions:
i) Is it compatible with whats in org.glassfish.grizzly.connectionpool.SingleEndpointPool#release0?  Here keepAlive is only false if idleTimeout is 0 and pool is larger than coreSize. Might there be a situation where AHC is setting "Connection: close" but grizzly doesn't close connection because poolSize is greater than coreSize.
ii) Is the tri-state behaviour of attribute compatible with the netty implementation?

**Comment by slandelle** [comment]
> Is the tri-state behaviour of attribute compatible with the netty implementation?

I don't get you.
In Netty impl, maxIdleTimeDisabled <= 0 means cleaner is disabled, not that pooling is disabled: https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/providers/netty/channel/pool/DefaultChannelPool.java#L81

**Comment by dfeist** [comment]
Yes that is consistent. What i was asking @oleksiys was if disabling persistent connections when maxIdletimeout == 0 was consistent with netty implemntation, as i'm not sure it is.

**Comment by slandelle** [comment]
No it isn't.

**Comment by oleksiys** [comment]
Hi,

This change makes sense, but got two questions:
> i) Is it compatible with whats in
> org.glassfish.grizzly.connectionpool.SingleEndpointPool#release0? Here
> keepAlive is only false if idleTimeout is 0 and pool is larger than
> coreSize. Might there be a situation where AHC is setting "Connection:
> close" but grizzly doesn't close connection because poolSize is greater
> than coreSize.
>
"Connection: close" has to be handled by HTTP-aware layer and explicitly
close connection, once the request/response processing is finished. In that
connection-pool will see that the Connection is already closed and will
throw it away ignoring its keep-alive settings.



> ii) Is the tri-state behaviour of attribute compatible with the netty
> implementation?
>
Looks like not.
We treat < 0 values - as no timeout, and all the other values >= 0 are
treated as timeout, including 0, that means close immediately.

Please let me know if you see any problem.

Thanks.

WBR,
Alexey.

**Comment by dfeist** [comment]
This all makes sense yes.  I just couldn't find the code in netty provider,  that handles the idleTimeout==0 in the same way.  It may be just I couldn't find it, or if could be that Betty provider doesn't handle this in the same way. 

Commit looks good,  if was more a question about consistency with netty provider.

**Comment by dfeist** [comment]
@slandelle I agree with @oleksiys comments about what the correct behavior is when "maxIdleTimeDisabled==0". You may want to review the NettyProvider behaviour here, as from what I can see the cleaner is disabled, but connections will be put back in the pool and never cleaned up, which make sense for "-1" maybe, but not for "0".

**Comment by slandelle** [comment]
Well, I disagree. Disabling connection pooling is controlled by a dedicated parameter.

**Comment by dfeist** [comment]
For sure from a pooling perspective, but the current netty provider behaviour is inconsistent IMO because when the  idleTimeout is 0 (i.e. it should timeout immediately after being put back in the pool) this doesn't happen happen and instead it goes back into the pool and never times out (because there is no cleaner running).

This really is just an edge case though, that I only ever considered as part of this grizzly bug, and it's not a huge issue for the providers to be slightly inconsistent in this regard.  Main thing I wanted to do was make sure you'd considered this case and that we'd closed the loop.
