### ISSUE TITLE
can't see http traffic in http debug monitor

### ISSUE THREAD

**Issue by AndyGu** [AsyncHttpClient/async-http-client#1073]
when I upgraded my async-http-client to 1.4.9, I can't see the HTTP and SSL / HTTPS traffic in the tools(like charles/fiddler) any more

**Comment by slandelle** [comment]
I'm not exactly mad at you, but you're the 30st LoopJ users who gets confused and don't use the proper project.

Then, I'm pretty mad at the LoopJ guy who doesn't want to lift a finger and help his users like you find their way to the proper project. See https://github.com/loopj/android-async-http/issues/876.

**Comment by AndyGu** [comment]
Oh, sorry bro

**Comment by slandelle** [comment]
No pro, but if every lost LoopJ user I have to redirect could try and get some sense into the LoopJ maintainer so he makes an effort in showing you the right direction, it would be really helpful. :)
