### ISSUE TITLE
Closing client when using RX

### ISSUE THREAD

**Issue by paulbakker** [AsyncHttpClient/async-http-client#1076]
The RX tests seem to work nicely with an auto closable client:

```java
 try (AsyncHttpClient client = asyncHttpClient()) {
  Observable<Response> o1 = AsyncHttpObservable.observe(new Func0<BoundRequestBuilder>() {
    @Override
    public BoundRequestBuilder call() {
      return client.prepareGet("https://github.com/AsyncHttpClient");
    }
  });
  o1.subscribe(tester);
}
```
(example from AsyncHttpObservableTest.java)
This works because the connection is now closed after the test completes, due to the blocking nature of the TestSubscriber.

In non-test code, this doesn't work unfortunately. Something like the code below fails because the connection get closed too early.

```java
@Override
public Observable<Response> example() {
  try(AsyncHttpClient client = new DefaultAsyncHttpClient()) {
    return AsyncHttpObservable.toObservable(new Func0<BoundRequestBuilder>() {
      @Override
      public BoundRequestBuilder call() {
        return client.prepareGet("https://github.com/AsyncHttpClient");
      }
    });
  } 
}
```
This is understandable because the close happens as soon as this method returns, not when the subscribe (and actual connection) happens.

An somewhat ugly solution is the following code, but I'm not too happy with it. I'm not sure how to fix this nicely either, but I wanted to point out the issue because it might require an API change to handle this better.

```java
@Override
public Observable<Response> example() {
  AsyncHttpClient client = new DefaultAsyncHttpClient();
  return AsyncHttpObservable.toObservable(new Func0<BoundRequestBuilder>() {
    @Override
    public BoundRequestBuilder call() {
    return client.prepareGet("https://github.com/AsyncHttpClient");
    }
  }).doOnTerminate(() -> closeUnchecked(client));
}
```

**Comment by slandelle** [comment]
In a real work application, you wouldn't use auto closing, right?

**Comment by paulbakker** [comment]
You're probably making a really good point, but why not? It needs to be closed in both a success and error scenario right?

**Comment by slandelle** [comment]
You're not supposed to open and close a client instance on every call. You usually have one single singleton instance that you only close when you close your application.

**Comment by paulbakker** [comment]
Got you, I didn't actually know that (new to this library) :) In that case, I guess this isn't an issue after all, I'm closing it.

**Comment by udayravuri** [comment]
Hi, 
Started using this library just now. I have a spring boot application. Based on the discussion above, is the suggestion to instantiate only 1 AsyncHttpClient at the start of the application as a singleton and use it through out until app is shutdown?

Thank you.

**Comment by BEllis** [comment]
You want to use the http://reactivex.io/documentation/operators/using.html operator here, it will auto open and close the connection when necessary. Unfortunately, it does not use the AutoCloseable interface but a Resource interface instead, so you'll have to write a AsyncHttpClientResource wrapper class for the AsyncHttpClient.

**Comment by slandelle** [comment]
@BEllis It might not even be sufficient. You might be willing to use the same client instance for multiple Observables. Client lifecycle is usually the same as the application.

**Comment by BEllis** [comment]
@slandelle I was going to follow up mentioning it may be worth having some type of ref counter resource instead, so it only closes the client when all references to it are lost, but it feels like an over engineered solution.

**Comment by udayravuri** [comment]
Thanks for your input @BEllis  and @slandelle
