### ISSUE TITLE
Cookie duplication

### ISSUE THREAD

**Issue by sanjarbek** [AsyncHttpClient/async-http-client#1078]
http://grokbase.com/t/gg/play-framework/151w0rkdba/wsresponses-handling-cookie-of-duplicate-set-cookie-headers
>I have a question about cookie handling by WSResponse when "Set-Cookie" header is duplicate. I'm not sure it is a bug.
>On receiving response with the following headers;
>    1. Set-Cookie:   THE_KEY=value1; expires=Wed, 28-Jan-2015 04:23:00 GMT; path=/
>    2. Set-Cookie:    THE_KEY=value2; expires=Wed, 28-Jan-2015 04:23:00 GMT; path=/
>
>Calling WSResponse's cookie("THE_KEY") method returns "value1". But according to RFC 6265, I guess it should return "value2", because old "*cookie with the same name, domain, and path* <http://tools.ietf.org/html/rfc6265#section-5.3>" should be removed. Is this behavior expected?

WSResponse class from WS client of playframework. I already ask playframework team, but they refering to your library because ws client use async-http-client.

**Comment by slandelle** [comment]
First, a response with duplicate Set-Cookie headers should be considered a bug and be fixed.

Then this section of RFC6265 relates to cookie storage, ie how a user-agent so implement a Cookie jar to store them and be able to send them back to the server in subsequent requests.

AsyncHttpClient doesn't have such component atm. AHC's Response only has a getCookies() method that returns a List of all the parsed cookies from all the Set-Cookie headers (so you would be able to implement a CookieJar).
This method that acts as a Map and takes a key (I guess the Cookie name) solely belongs to Play.
