### ISSUE TITLE
IllegalArgumentException: Synchronous ResponseHandler used in AsyncHttpClient

### ISSUE THREAD

**Issue by SolomonBier** [AsyncHttpClient/async-http-client#1087]
There is another ticket that mentions this, and I'm getting this with Android 6 marshmallow. 

I'm trying to run AsyncHttpClient every second via a ScheduledThreadPoolExecutor. This works fine when I run it on its own, but when I put it in the ScheduledThreadPoolExecutor it returns the following error:
`IllegalArgumentException: Synchronous ResponseHandler used in AsyncHttpClient`

I'm confused. Is the exception being thrown misnamed? Because I'm sending a `JsonHttpResponseHandler` as a response handler, which is async!

See exact same SO question:
http://stackoverflow.com/questions/34985255/scheduledthreadpoolexecutor-with-androidasynchttp

**Comment by slandelle** [comment]
https://github.com/loopj/android-async-http/issues/876

**Comment by SolomonBier** [comment]
@slandelle sorry :D
