### ISSUE TITLE
Exception creating WebSocket Connection from a Java Client behind a proxy

### ISSUE THREAD

**Issue by SudhanshuBhatt** [AsyncHttpClient/async-http-client#1088]
**UPDATE:**
**I tried the AHC 1.9.32 and 2.0.0-RC7, and was able to narrow it down to the following observations:**

**1. Both versions will work with Squid proxy server, if I do not enable authentication.**
**2. Both the versions fail if I make authentication mandatory.**

**Version 1.9.32: Results in the Invalid Status Code 400 error.**
**Version 2.0.0-RC7 : Results in a timeout after a default 6000ms.**

Library in use: AsyncHtpClient Library: 
Version : 1.9.32 and 2.0.0-RC7
Netty Version : 3.10.3.Final
Proxy: Squid Proxy
 
I am trying to create a websocket connection using AsyncHttpClient library. It works fine when using without the proxy. But when I start a proxy and pass in the Host, port, username and password , I am unable to create a websocket connection.
It get a stack trace which says Invalid Status Code 400:

I am setting the proxy configurations using Realm in AHC:

For 1.9.32:
```java
Realm realm = new Realm.RealmBuilder().setPrincipal("user_name").setPassword("password").setScheme(Realm.AuthScheme.BASIC).build();
ProxyServer ps1 = new ProxyServer("host_address", port_number);
ps1.setScheme(Realm.AuthScheme.BASIC);
AsyncHttpClientConfig config = new AsyncHttpClientConfig.Builder().setRealm(realm).setProxyServer(ps1).build();
final AsyncHttpClient c = new AsyncHttpClient(config);
```

For 2.0.0-RC7:
```java
Realm realm = new Realm.Builder("user_name", "password").setScheme(Realm.AuthScheme.BASIC).build();
ProxyServer.Builder proxyBuilder = new ProxyServer.Builder("host_address", port_number);
proxyBuilder.setRealm(realm);
ProxyServer proxyServer = proxyBuilder.build();
AsyncHttpClientConfig config = new DefaultAsyncHttpClientConfig.Builder().setProxyServer(proxyServer).build();
final AsyncHttpClient c = new DefaultAsyncHttpClient(config);
```

Am I not configuring the Proxy correctly?

**Comment by thjaeckle** [comment]
I am also experiencing similar problems with using Websockets behind a Proxy in Ning 1.9.31.
I am using a custom BasicAuth based authentication at the Websocket resource.

In that case it seems that the "realm" of the Request is some times the "realm" of the Proxy-Authentication and sometimes the "realm" of the BasicAuth.

In my case I don't get a Status Code 400 but a 401 as my BasicAuth resource did not receive the expected "Authorization" Header. The request to which I added the custom realm:
```
final ListenableFuture<WebSocket> execute = httpClient 
         .prepareGet(endpointURI.toString())
         .setRealm(realm)
         .execute(upgradeHandler);
```
does *not* include the "Authorization" Header at all:
```
Request DefaultHttpRequest(chunked: false)
GET / HTTP/1.1
Connection: keep-alive
Host: the.host.com
Proxy-Authorization: Basic secretsecretiwonttellyou=
Accept: */*
User-Agent: AHC/1.0
```

**Comment by slandelle** [comment]
Are you sure Squid now supports WebSockets?

Quote from [this thread on the Squid ML](http://squid-web-proxy-cache.1019090.n4.nabble.com/websocket-connection-fails-td4672654.html
) from August 2015:

> Squid simply does not support HTTP Upgrade yet.

Can you reproduce with AHC 2.0.0-RC8?
Can you share a way to reproduce, please? Like sending a private email with temporary credentials? I definitively don't have the cycles for setting up such an environment.

**Comment by thjaeckle** [comment]
Sorry, I don't know about Squid.
I am sitting behind a corporate proxy with authentication - even if I was willing to share my credentials that would be of no use to you as the corporate proxy has an intranet-only address.

I'll try to reproduce with 2.0.0-RC8

**Comment by thjaeckle** [comment]
Works with 2.0.0-RC8:
```
Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledUnsafeHeapByteBuf(freed))
CONNECT events-dev.apps.bosch-iot-cloud.com:443 HTTP/1.1
Host: the.host.com
Authorization: Basic blabla...
Proxy-Authorization: Basic foofoo...
Accept: */*
User-Agent: AHC/2.0
```

**Comment by slandelle** [comment]
OK, so I think this was a bug that got fixed in 2.0.0-RC7. AHC2 is a major rewrite, and such fix can't be simply backported in AHC1. And sadly, I really don't have the cycles to reimplement a new fix there.

**Comment by slandelle** [comment]
@SudhanshuBhatt Closing for now, as I really suspect your issue is simply that your proxy (Squid) doesn't support WebSocket. Feel free to reopen if you have more information stating otherwise.

**Comment by SudhanshuBhatt** [comment]
@slandelle I was able to create a WebSocket connection from behind a Squid proxy. The handling of HTTP Upgrade to WebSocket at the server endpoint had to be modified.
Thanks for all the help.

The 2.0.0-RC7 is however dependent of Java 8, is is possible that back portability be added for Java 7 ? :)

**Comment by slandelle** [comment]
> The 2.0.0-RC7 is however dependent of Java 8, is is possible that back portability be added for Java7?

Not a chance
