### ISSUE TITLE
Consume a WebSocket in Scala controller

### ISSUE THREAD

**Issue by vinitsharma87** [AsyncHttpClient/async-http-client#1093]
Hi!, I am implementing something like this, I have two different Play! projects out of which project-2 is having a `WebSocket` method inside its scala controller which was previously a normal `Action.async` method. This `WebSocket` method ignores any `JsValue` input given to it and returns a json. I need to connect/consume the json response of this `WebSocket` method of project-2 from within my project-1's scala controller ? I have tried implementation for connecting a `WebSocket` from scala controller using `AsyncHttpClient` and following is my code implementation:

```
val latch = new CountDownLatch(1)
val webSocketClient = c.prepareGet("ws://0.0.0.0:9000/demoSocket").execute(new WebSocketUpgradeHandler.Builder().addWebSocketListener(new WebSocketTextListener {

      override def onMessage(s: String): Unit = {
        println("onMessage response comes here =====================" + s)
      }

      override def onOpen(webSocket: websocket.WebSocket): Unit = {
        webSocket.sendTextMessage("Test bytes")
      }

      override def onFragment(s: String, b: Boolean): Unit = {}

      override def onError(throwable: Throwable): Unit = {}

      override def onClose(webSocket: websocket.WebSocket): Unit = {
        latch.countDown()
      }
    }).build()).get().sendTextMessage("test")

println("================================This thing shows whether WebSocket is open?" + webSocketClient.isOpen())
val result = webSocketClient.sendTextMessage("demo")
println("================================The json response is: " + result)
```

In the above code, first issue is that the `WebSocket` connection isn't being invoked. Also the result variable prints the string representation of a `WebSocket` object instead of the json response which the `WebSocket` connection should return. What thing I am implementing is wrong in the above code ? How can we consume the json response of a `WebSocket` connecting in scala ? Any help would be great!

**Comment by slandelle** [comment]
Please don't use the bugtracker for questions. We have a Google Group for that.

**Comment by vinitsharma87** [comment]
@slandelle Can you please provide me the Google group link where I can post my query ? Or some other link where I can post my question regarding AsyncHttpClient ? I have already posted my question on SO ([so question](http://stackoverflow.com/questions/35184280/implementing-a-websocketclient-in-scala-controller)) where @jroper told me to implement using AsyncHttpClient. But still I haven't achieved my required thing yet.

**Comment by vinitsharma87** [comment]
@slandelle , I need a little help from you. Do you have a small example for the `WebSocket`([this](https://github.com/AsyncHttpClient/async-http-client#websocket) code implementation ? I am really stuck since long. Kindly let me know for where I am going wrong ? Can you just tell me some site where the implementation is provided for same ? Thanks.

**Comment by slandelle** [comment]
Your problem is that you get WebSocket completely wrong. WebSocket is full duplex, it's not like HTTP/1.1 where you send a request and get a response. Outgoing and incoming messages can be completely non correlated, and don't have to be one for one. If you have a one for one association, that's purely application implementation specific and has nothing to do with the protocol.

Hence, `sendTextMessage` returns the `WebSocket` itself. If you want incoming messages, you have to use the listener.

Our Google Group address is in the README of this repository and can be easily [found on Google](http://bfy.tw/46V8).
