### ISSUE TITLE
gzip encoding

### ISSUE THREAD

**Issue by boxhead201** [AsyncHttpClient/async-http-client#1100]
Hi;

  I am in china, so I am unable to use Google Groups.  I am using 1.9.33/Netty and I can't seem to get compression working.  Er, I am unable to tell if I have compression working.  This is how I construct my client: 

```java
new AsyncHttpClient(new AsyncHttpClientConfig.Builder().setCompressionEnforced(true).build());
```
  And this is how I send my get request:

```
  asyncHttpClient
                .prepareGet(Constants.RADAR_IMAGE_BASE_URL + png)
                .addHeader("Accept-Encoding","gzip")
```
  But when I print the headers, I do not get an encoding header telling me gzip.  Does FluentCaseInsensitiveStringsMap include *all* the headers?  Or are some stripped out?

  FluentCaseInsensitiveStringsMap map = headers.getHeaders();

  Is there a way that I can tell that the server sent me gzip?

**Comment by slandelle** [comment]
> setCompressionEnforced(true) + addHeader("Accept-Encoding","gzip")

You don't need both: the goal of `setCompressionEnforced(true)` is to always set "Accept-Encoding" header if it's not defined.

> Does FluentCaseInsensitiveStringsMap include all the headers? Or are some stripped out?

Netty removes "Accept-Encoding" header from the response, as the entity is indeed no longer compressed.

AHC lets you change this behavior, see `config#keepEncodingHeader`.

Then, are you sure your server support gzip, and not only deflate? Why only enable gzip?

**Comment by slandelle** [comment]
Then, you'll honestly have to find a way to use the Google Group. This is a bug tracker.
