### ISSUE TITLE
Option for custom headers to proxy on CONNECT

### ISSUE THREAD

**Issue by dgllghr** [AsyncHttpClient/async-http-client#1101]
Similar to curl's `--proxy-header` option (https://curl.haxx.se/docs/manpage.html#--proxy-header), enable option to include headers in CONNECT requests to a proxy.

If I missed this feature somewhere, sorry for the trouble.

**Comment by slandelle** [comment]
Looks like something very non standard. What's your use case exactly? If you're looking for proxy auth, that's something that you set on the ProxyServer object.

**Comment by dgllghr** [comment]
In this case, a custom proxy is routing traffic to upstream proxies dynamically (can't be done with static tables), and we need to pass information to the custom proxy so it can route the requests appropriately. For HTTP requests, this can be done easily with headers. But with HTTPS requests, we are limited to using `Proxy-Authorization`.

This is certainly only a nice-to-have feature, but when I saw that curl had the option I thought it might be useful.

**Comment by slandelle** [comment]
Contribs welcome

**Comment by slandelle** [comment]
I guess contribution won't come.
