### ISSUE TITLE
Under High Stress, Large responses the Client performs worsen on Jdk 8

### ISSUE THREAD

**Issue by ttashi** [AsyncHttpClient/async-http-client#1103]
Hey Guys I am seeing a lot more gc activity with ning-async client 1.7.19 thats using netty 3.6.6.Final after upgrading to JDK 8 from 7. Do any of you guys have thought on this. It happens mostly on larger responses. The responses are not huge.. around 12KB.

**Comment by slandelle** [comment]
As answered on the Netty issue that you first wrote, please upgrade to latest AHC1: 1.9.33. There's no way I'd investigate on that old beast that was released almost 3 years ago.

Then, if you still experience issues, please report.

**Comment by ttashi** [comment]
I did tested 1.9.33 and Netty 4. Do you think the latest alpha version will help.

**Comment by slandelle** [comment]
1.9.33 doesn't support Netty 4, only AHC2 does. If you provided Netty 4 there instead of Netty 3, AHC1 probably silently picked the JDK provider, which is crap.

> Do you think the latest RC version will help.

Possible, yes. It depends on your use case.

**Comment by ttashi** [comment]
Alright I will try RC version, Correction here it was Netty 3.6.6.Final with Asycn 1.9.33.

**Comment by slandelle** [comment]
> Alright I will try RC version

Yes, please. I don't plan to invest on AHC1 as I'm migrating Gatling to AHC2.
If you have still an issue, the best way to have it investigated is to provide a sample to reproduce (AHC client + target sample application).

**Comment by ttashi** [comment]
I will update here, what ever the result. Thanks.

**Comment by ttashi** [comment]
Is the RC version available on Maven Central and any documentation on usages since the API seems to have changed a lot.

**Comment by slandelle** [comment]
GroupId has changed: http://search.maven.org/#artifactdetails%7Corg.asynchttpclient%7Casync-http-client%7C2.0.0-RC11%7Cjar

No, there's no migration guide yet, but you can probably figure out changes by yourself.

**Comment by ttashi** [comment]
Thanks!

**Comment by ttashi** [comment]
here are the result. Below with Async 1.7.19 and 3.6.6.Final, JDK 7 and 3.2.0-60-generic Ubuntu

<img width="1220" alt="screen shot 2016-03-02 at 9 27 59 pm" src="https://cloud.githubusercontent.com/assets/5086271/13484793/2214be34-e0be-11e5-9778-7bb4280bd8f6.png">

**Comment by ttashi** [comment]
here are the result. Below with Async 1.7.19 and 3.6.6.Final, JDK 8, the little dip in the CPU is when I turned off the async requests.
<img width="1219" alt="screen shot 2016-03-02 at 9 32 04 pm" src="https://cloud.githubusercontent.com/assets/5086271/13484801/3effab76-e0be-11e5-8fcf-462d2dd2fbf4.png">
 and 3.2.0-60-generic Ubuntu

**Comment by ttashi** [comment]
here are the result. Below with Async 2.0.0-RC11 and netty 4, JDK 8, the little dip in the CPU is when I turned off the async requests and later turned back on.

<img width="1222" alt="screen shot 2016-03-02 at 9 27 46 pm" src="https://cloud.githubusercontent.com/assets/5086271/13484817/8b26559a-e0be-11e5-89b4-f775d8ba7d94.png">

**Comment by slandelle** [comment]
What's your exact JDK8 version? What's your GC tuning?

Please provide a reproducer.

**Comment by ttashi** [comment]
I tried HotSPOT JDK 8, 8_51 and 8_74 and also tried ZULU. We can clearly see that Eden is getting filled up 3 times faster when we have the Async enabled on JDK 8 vs JDK 7. We tried to find a fix initially by tuning GC using both CMS and G1 with no significant improvement. Below is a memory allocation comparison when async is disabled vs enabled. I will work on isolating the problem in a smaller app to reproduce it.

![screen shot 2016-03-03 at 9 41 38 am](https://cloud.githubusercontent.com/assets/5086271/13501563/6c18719a-e124-11e5-9029-7ef55b7e3641.png)

**Comment by slandelle** [comment]
You don't test in isolation, so you have no way of pinting at AsyncHttpClient or Netty for sure.
There's:
* `backbird` which is probably your own code
* EhCache
* Guava

You have so figure out who allocates those `AbstractQueuedSynchronizer$Node.`s, where and why.

**Comment by ttashi** [comment]
When I say Isolate it will include all of our code using the client. We are looking into the AbstractQueuedSynchronizer$Node. The reason why we suspect Async is related to this is the way CPU usage and Garbage drops when that functionality is disabled, the drop pretty much brings it down to match JDK 7 profile, We don't see any such drop on JDK7 when the same function is disabled.

**Comment by ttashi** [comment]
Thanks guys for the help, it appears its the doozy apache camel that was causing the problem. I am going to close this.

**Comment by slandelle** [comment]
Cool
