### ISSUE TITLE
Handling of relative 30X Location headers could be friendlier

### ISSUE THREAD

**Issue by jeremyhaile** [AsyncHttpClient/async-http-client#1110]
When loading this URL "http://www.pollockdirect.com" with followRedirect enabled, you receive the following error: `Java::JavaUtilConcurrent::ExecutionException: java.net.UnknownHostException: www.pollockdirect.comstorefront: nodename nor servname provided, or not known`

The headers that come back from that URL are:
```
< HTTP/1.1 301 Moved Permanently
< Cache-Control: private
< Content-Length: 0
< Content-Type: text/html
< Location: storefront/home?idAffiliate=
```

The Location header is relative, which isn't technically correct based on the RFC. However, browsers handle this redirect just fine, and I think async-http-client should follow it the same way browsers do.

It appears that URI.create is appending "storefront/home" onto "http://www.pollockdirect.com" which results in "http://www.pollockdirect.comstorefront/home" which is obviously an invalid domain name. Instead it should follow it to "http://www.pollockdirect.com/storefront/home"

**Comment by slandelle** [comment]
Actually, relative Location headers are legit since [RC7231](https://tools.ietf.org/html/rfc7231#page-68) superseded RFC2616, and AHC does support them.

Here, it's simply a bug, where the target url is not properly computed. As a workaround, it would work it the context/original url is "http://www.pollockdirect.com/" (with a trailing slash).

**Comment by jeremyhaile** [comment]
@slandelle ah ok - thanks for the info. 

I definitely could append a trailing slash, although as I'm working on a crawler it's tough to know when it's  safe to append slashes. Perhaps if the URL does not already contain any slashes after the `https?://`then we could append one, but nervous about creating edge cases where that is not valid.
