### ISSUE TITLE
Race condition can cause Netty connection pool to close currently active connections

### ISSUE THREAD

**Issue by malaporte** [AsyncHttpClient/async-http-client#1113]
Under load we noticed that we sometimes get unexplainable read timeouts on connections on some connections for which we can confirm that a successful response was indeed returned by the server.

After a sizeable amount of investigation where we doubted everything ranging from our NATs to AWS ELBs, it turns out that sometimes `DefaultChannelPool` will close a connection that is in fact actively being used, causing and eventual read timeout in the code that waits for a result. This is because nothing prevents a channel that has been identified as expired from being handed out of the pool before it reaches the point where it is indeed closed. There is in fact a check there to prevent connections for which a Future is active from being closed, but this don't cover the case where the connection has been taken out of the pool but hasn't sent a request yet.

We get this problem in 1.9.33 but it also exists in the 2.0 version.

I have implemented a fix for this; I'll be submitting a PR shortly.

**Comment by slandelle** [comment]
Fixed on master w/ #1114

**Comment by slandelle** [comment]
Ping @wsargent @jroper 
Wasn't something similar reported on Play?

**Comment by wsargent** [comment]
Don't remember anything off the top of my head. There's https://github.com/AsyncHttpClient/async-http-client/issues/1027 but that's sort of the inverse of this, where threads stay open after they should be closed.

**Comment by wsargent** [comment]
There is https://github.com/AsyncHttpClient/async-http-client/issues/1027#issuecomment-175249025 though...

**Comment by slandelle** [comment]
Yes, that's the one I was looking for. Really seems to be the same, thanks!

**Comment by slandelle** [comment]
backported on 1.9 with 1d5b880e7e07b53942ded35bad82f39f65ba5761

**Comment by slandelle** [comment]
@malaporte just released 1.9.35
