### ISSUE TITLE
OAuthSignatureCalculator uses a weak RNG for nonce

### ISSUE THREAD

**Issue by wsargent** [AsyncHttpClient/async-http-client#1118]
OAuthSignatureCalculator uses a thread local random to generate a nonce:

```
    protected String generateNonce() {
        byte[] nonceBuffer = NONCE_BUFFER.get();
        ThreadLocalRandom.current().nextBytes(nonceBuffer);
        // let's use base64 encoding over hex, slightly more compact than hex or decimals
        return Base64.encode(nonceBuffer);
//      return String.valueOf(Math.abs(random.nextLong()));
    }
```

https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/oauth/OAuthSignatureCalculator.java#L225

The OAuth spec doesn't say anything about the standard of randomness, but given that this is authentication and it uses the term "nonce" and "random", I believe it's referring to a cryptographic nonce.  However, ThreadLocalRandom is not a cryptographically secure PRNG, so it should not be used for generating nonces.  If you have a SecureRandom class and call nextBytes on it repeatedly, it will call out to /dev/urandom on modern OS: https://tersesystems.com/2015/12/17/the-right-way-to-use-securerandom/

So the following should be fine:

```
SecureRandom random = new SecureRandom();
...
random.nextBytes(nonceBuffer);
```

**Comment by slandelle** [comment]
Does this really matter on the client side?

**Comment by wsargent** [comment]
...no, it doesn't.  False alarm.

Adding some links in case anyone is following up on this:

* http://hueniverse.com/2008/10/03/beginners-guide-to-oauth-part-iii-security-architecture/
* http://security.stackexchange.com/a/62737
* http://www.oauthsecurity.com/
* https://tools.ietf.org/html/rfc6819
* https://adayinthelifeof.nl/2010/12/16/oauth-timestamps-and-nonces/
* https://stackoverflow.com/questions/6865690/whats-the-point-of-a-timestamp-in-oauth-if-a-nonce-can-only-be-used-one-time

**Comment by slandelle** [comment]
Thanks for the links :)
