### ISSUE TITLE
Multipart/Form-Data: uploaded FilePart is corrupt/incomplete

### ISSUE THREAD

**Issue by domdorn** [AsyncHttpClient/async-http-client#1123]
I'm creating a kind of Proxy using the PlayFramework 2.5.1 and the bundled AsyncHttpClient 2.0-RC16. 

When uploading files over a certain size (not sure where's the limit), the transmitted Fileparts are incomplete and don't include a closing boundary. 

The requests look like this

browser -> playApp -> backend_server
[asynchttpclient_bug.zip](https://github.com/AsyncHttpClient/async-http-client/files/194538/asynchttpclient_bug.zip)

The files 
smallfile_browser_playapp.raw + smallfile_play_backendserver.raw + test.jpg 
show how the communication should be ( the fileparts end correct and include the closing boundary)

The files
conversation_browser_playapp.raw + conversation_play_backendserver.raw + 10003452_245377232464587_7349773111777690908_n.jpg
show how the communication is broken. the filepart in conversation_play_backendserver.raw suddendly stops and does not contain a closing boundary. 

it looks like this is a problem with some buffer having not enough space or something like that. 

Any help appreciated!

[asynchttpclient_bug.zip](https://github.com/AsyncHttpClient/async-http-client/files/194537/asynchttpclient_bug.zip)

**Comment by slandelle** [comment]
Thanks for reporting!

**Comment by slandelle** [comment]
Released in RC17

**Comment by domdorn** [comment]
fix works, thanks!
