### ISSUE TITLE
the connection is still established when the request future is timeout

### ISSUE THREAD

**Issue by wudikua** [AsyncHttpClient/async-http-client#1129]
When the async request future is timeout, I call the future.cancel(), but I use "netstat -an" to find the connection status is still ESTABLISH. I have configured the max connection and max connection per host. It seems not function.
I read the source code find that, the ChannelManager line 137, do not close the SocketChannel, but just realse the semaphore, should o be converted to SocketChannel and close it?

**Comment by slandelle** [comment]
Please:
* state the version you're using
* provide a reproducer

FYI, actual closing is performed here: https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L388

**Comment by wudikua** [comment]
this issues can easy reproduce, I call the future.get() with 1 nano second, and got a timeout exception, so
I call future.cancel(). when the connect is not establish, or the write is not send, even if user called future.cancel(), the connection will can't close.
I think this issues because of the NettyConnectListener line 75:
if (future.isDone()) {
      abortChannelPreemption();
      return;
}
the semaphore is realse, the channel is not close.

**Comment by slandelle** [comment]
This one is different from the one you originally described. I just fixed this edge case, see #1131.

Then, `Future.cancel` doesn't close the connection itself. It will be effectively closed on some other event, like read timeout or request timeout, or next read.

Feel free to ping if you can come up with a reproducer.

**Comment by slandelle** [comment]
Actually, I was wrong, Future#cancel indeeds close the connection if it's already open, see https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/NettyResponseFuture.java#L143-L146.
