### ISSUE TITLE
Diagnostics from AsyncHttpClient

### ISSUE THREAD

**Issue by stepancheg** [AsyncHttpClient/async-http-client#1130]
Requesting diagnostics API for `AsyncHttpClients`. E. g. methods like:

```
int getActiveRequestCount();
int getPooledConnectionCount();
int getHostCountWithPooledRequests();
List<String> getActiveRequests();
List<String> getPooledConnectionHosts();
```

and so on.

Currently I'm trying to find a leak in a program which looks like a leak in async-http-client to me (AsyncHttpClient reports I hit `maxConnections` limit while `netstat` reports much lower number of open connections). If async-http-client had such diagnostics API, I could verify my hypothesis. Currently I have no idea whether problem is in AsyncHttpClient or I use AsyncHttpClient API incorrectly.

Such API would be also very useful for monitoring (to plot e. g. active request count).

**Comment by slandelle** [comment]
Contribs welcome!

**Comment by stevenschlansker** [comment]
Thanks!
