### ISSUE TITLE
Allow to manually specify a Content-Length on setBody(Publisher<ByteBuffer>)

### ISSUE THREAD

**Issue by schmitch** [AsyncHttpClient/async-http-client#1136]
Actually when running something like that:

     new RequestBuilder().setUrl("http://localhost:9004").setMethod("POST").setBody(publisher).setContentLength(3)

while publisher is of type `Publisher<ByteBuffer>` the setContentLength will be ignored?! And a Header of type `Transfer-Encoding: chunked` will be added. However it would be great to set that manually on Streaming bodies so if a `Content-Length` is there it will be used else it's the old behavior. The use case is simple, stream data where the size is known or computed and the receiving client needs to know the `Content-Length`.

**Comment by schmitch** [comment]
@slandelle when do you create the next Milestone?

**Comment by slandelle** [comment]
Done: 2.0.0-RC21 (sic)
