### ISSUE TITLE
UnknownHostException exception

### ISSUE THREAD

**Issue by isYuriBoyka** [AsyncHttpClient/async-http-client#1140]
error:java.io.IOException: UnknownHostException exception: Unable to resolve host "no-data": No address associated with hostname

This is the file I want to download：
http://t-audiop.ubaby.cn/e8325558-9bb1-9524-2f7f-946747583d6d.lrc

Excuse me, what is the reason?

**Comment by slandelle** [comment]
Works for me. Which version are you using?

**Comment by isYuriBoyka** [comment]
1.4.9

**Comment by slandelle** [comment]
This is not the project you're looking for.
https://github.com/loopj/android-async-http/issues/876
