### ISSUE TITLE
Handshake did not complete within 10000ms 

### ISSUE THREAD

**Issue by charlesk40** [AsyncHttpClient/async-http-client#1141]
Hi there,
We are noticing that some clients connecting through our slow network are noticing this Handshake timeout.  We do not see the issue with faster network.  Not sure if increasing the timeout would help or fix the root cause but we would like to know if this timeout can be increased.  If so, what is the configuration setting that we can tweak?  Thanks.

**Comment by slandelle** [comment]
Don't use the bug tracker for questions, use the community mailing list.
Then, just look into the config class.
