### ISSUE TITLE
Release request for 1.9.39

### ISSUE THREAD

**Issue by elrodro83** [AsyncHttpClient/async-http-client#1142]
We are needing a released version that contains the commit https://github.com/AsyncHttpClient/async-http-client/commit/178ec0d668884be648f0a192666e1efcb228f857

**Comment by elrodro83** [comment]
Hi, @slandelle. Can this version be released? Thanks!

**Comment by slandelle** [comment]
I'm off for 10 days, I'll release when I'll be back. Then, it would be great that Alexey provides some feedback on your open PR.

**Comment by LucianoGandini** [comment]
Hi @slandelle, do you have an estimated release date?

Thanks!

**Comment by slandelle** [comment]
I'll release once #1134 and #1135 are closed/fix confirmed.

**Comment by slandelle** [comment]
Not an issue, use the Google Group.
