### ISSUE TITLE
Unhelpful error message while parsing Uri

### ISSUE THREAD

**Issue by jqno** [AsyncHttpClient/async-http-client#1149]
I'm not sure if this belongs here, or with the Play Framework. Please let me know if I should report it there instead of here!

Using the Play for Scala, we were trying to do an http request using Play's WSclient, and we got the following stack trace:

    java.lang.NullPointerException: scheme
       at com.ning.http.client.uri.Uri.<init>(Uri.java:56)
       at com.ning.http.client.uri.Uri.create(Uri.java:32)
       at com.ning.http.client.uri.Uri.create(Uri.java:25)
       at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:307)
       at com.ning.http.client.RequestBuilder.setUrl(RequestBuilder.java:165)
       at play.api.libs.ws.ning.NingWSRequest.buildRequest(NingWS.scala:218)
       at play.api.libs.ws.ning.NingWSRequest.execute(NingWS.scala:128)
       at play.api.libs.ws.WSRequest$class.get(WS.scala:408)
       at play.api.libs.ws.ning.NingWSRequest.get(NingWS.scala:81)

We were having some issues with dependency injection, so at first we figured it must have something to do with that. (How often do you see a NullPointerException in Scala, anyway? :smile: )

After much debugging, and looking at sources, we found out that we simply forgot to prepend our url with "http://"... :grimacing: 

It would have been helpful if the stacktrace was a bit clearer in what was going on, for example by wrapping the NPE in another exception that says something like "Invalid URI"?

**Comment by slandelle** [comment]
Check the NPE semantics:
```
Thrown when an application attempts to use null in a case where an object is required.
```

It's a common usage to use NPE for crashing when a mandator parameter is missing, Netty also does that heavily.

> How often do you see a NullPointerException in Scala, anyway? 

AHC is in Java :)

> It would have been helpful if the stacktrace was a bit clearer in what was going on

The stacktrace does mention that the missing parameter is `scheme`, which is exactly the mistake you made.

**Comment by jqno** [comment]
Thanks for the quick reply!

I'm not sure if I agree with you though, because I didn't supply any null values, and neither did Play. As you can see in the stack trace, I'm calling RequestBuilder.setUrl with a valid string that isn't null, and there's no Javadoc to indicate there that this can result in an NPE. The fact that something can be null, is an implementation detail of your code, so a user who's not familiar with your implementation (such as myself) will be surprised if an NPE pops up. It's extra surprising if you don't even use the RequestBuilder directly but through a 3rd party framework like Play.

But I'll take it up with them, and ask them to catch the NPE and wrap it in something more useful. While I'm here, are there any more exceptions that I should know about that AHC can throw?

**Comment by gmethvin** [comment]
I think it's okay for the `Uri` constructor to throw a NPE, but if you have a method that accepts a `String` it's not very useful to get a NPE several stack frames up from the actual method call.

It would be much more helpful if you threw an exception that would better explain to the user of the `String` API what is going on.

**Comment by wsargent** [comment]
Another work around is to use https://github.com/NET-A-PORTER/scala-uri to construct URIs and pass them into Play WS.   Getting pre-validated input before executing an operation is preferable, because exceptions and error handling are hard to handle after the fact.

**Comment by slandelle** [comment]
+1 for scala-uri.

Then, come on, we're talking about forgetting the scheme in the uri! Is it so hard to admit it was a very dumb user mistake (like we all do from time to time), whose cause was easy to figure out, and not blame the library here?

**Comment by gmethvin** [comment]
Technically, I think it would be more correct for `Uri.create(String)` to throw an `IllegalArgumentException` about the string, since that's what the end user is actually passing.

The simplest way to fix it in Play would be to write our own version of `Uri.create(String)` that just manually calls the `UriParser` class and checks to see if the parsed components are null before passing to the `Uri` constructor.

@slandelle Now that I look at it, it would be good if the AHC code documented which components can be null, perhaps using `@NotNull` annotations.

**Comment by MSMIgorRodriguez** [comment]
@slandelle, it might look like an easy to figure out mistake, but in fact I had to find this bug report to know what was the problem (I learnt today what an scheme is in HTTP, yes). I in fact think that it is a bug in the library as the first method called is `RequestBuilder.setUrl` that accepts it as correct and then it is the library itself the one that is passing a null value to the constructor of Uri. `RequestBuilder.setUrl` or `Uri.create` should throw an `IllegalArgumentException`.
