### ISSUE TITLE
Ssl parameters for specific connection

### ISSUE THREAD

**Issue by koen-serry** [AsyncHttpClient/async-http-client#1151]
Hi,

is there a way to pass a sslcontext to a specific requestbuilder instead of the whole httpclient? For instance if the certificate to a certain hosts is expired but you know it's being fixed you could temporarely allow it, while not lowering the security level of **all** requests being handled by that client. I know I could create a new httpclient, but that has quite some overhead in terms of threads (using the netty provider)

Koen

**Comment by slandelle** [comment]
No, it's not possible.

Then, please don't use the bugtracker for questions, use the community mailing lst.
