### ISSUE TITLE
proxy-authorization not working when using an http proxy while requesting a https url

### ISSUE THREAD

**Issue by gsfernandes** [AsyncHttpClient/async-http-client#1152]
Hi, I found that since this commit https://github.com/AsyncHttpClient/async-http-client/commit/68c9e7a20c96dff7a872c242496743bdbef08d3e the following scenario started to fail.

I have set a http proxy with basic authentication and I want to access a https url through the proxy. So, the authentication proxy header should be sent as part of the connect but it is not happening.

I'm using AHC 1.9.31 and Grizzly 2.3.21.

Before the referenced commit was added it was working and here was the sequence of messages:
>REQUEST: HttpRequestPacket (
   method=CONNECT
   url=httpbin.org:443
   headers=[
      Host=httpbin.org:443
      User-Agent=AHC/1.0
      Connection=keep-alive
      Proxy-Connection=keep-alive
      Proxy-Authorization=Basic am9obmRvZTpwYXNz]
)
RESPONSE: HttpResponsePacket (
  status=200
  reason=Connection established
)
REQUEST: HttpRequestPacket (
   method=GET
   url=/basic-auth/user/passwd
   protocol=HTTP/1.1
   headers=[
      Host=httpbin.org:443
      User-Agent=AHC/1.0
      Connection=keep-alive
      Accept=*/*
      Proxy-Connection=keep-alive
      Proxy-Authorization=Basic am9obmRvZTpwYXNz]
)
RESPONSE: HttpResponsePacket (
  status=401
  reason=UNAUTHORIZED
  protocol=HTTP/1.1
  committed=false
  headers=[
      server=nginx
      date=Tue, 10 May 2016 12:50:48 GMT
      content-length=0
      connection=keep-alive
      access-control-allow-origin=*
      www-authenticate=Basic realm="Fake Realm"
      access-control-allow-credentials=true]
)
REQUEST: HttpRequestPacket (
   method=GET
   url=/basic-auth/user/passwd
   protocol=HTTP/1.1
   headers=[
      Host=httpbin.org:443
      User-Agent=AHC/1.0
      Connection=keep-alive
      Accept=*/*
      Authorization=Basic dXNlcjpwYXNzd2Q=
      Proxy-Connection=keep-alive
      Proxy-Authorization=Basic am9obmRvZTpwYXNz]
)
...

Nowadays latest code from 1.9.x does not send the proxy-authorization with the correct data therefore I got the following messages sequence:

>REQUEST: HttpRequestPacket (
   method=CONNECT
   url=httpbin.org:443
   query=null
   protocol=HTTP/1.0
   content-length=-1
   headers=[
      Host=httpbin.org:443
      User-Agent=AHC/1.0
      Connection=keep-alive
      Proxy-Connection=keep-alive]
)
RESPONSE: HttpResponsePacket (
  status=407
  reason=Proxy Authentication Required
  protocol=HTTP/1.1
  content-length=3553
  committed=false
  headers=[
      server=squid/3.5.15
      mime-version=1.0
      date=Wed, 11 May 2016 17:40:32 GMT
      content-type=text/html;charset=utf-8
      content-length=3553
      x-squid-error=ERR_CACHE_ACCESS_DENIED 0
      vary=Accept-Language
      content-language=en
      proxy-authenticate=Basic realm="Squid proxy-caching web server"
      x-cache=MISS from localhost
      via=1.1 localhost (squid/3.5.15)
      connection=keep-alive]
)
...

After this point I got an error while parsing the http status code (I'm using squidman to test this, but this works with code before the mentioned commit):

>May 11, 2016 2:40:32 PM org.glassfish.grizzly.filterchain.DefaultFilterChain execute
WARNING: GRIZZLY0013: Exception during FilterChain execution
java.lang.NullPointerException
	at org.glassfish.grizzly.http.HttpClientFilter$ClientHttpResponseImpl.getProcessingState(HttpClientFilter.java:714)
	at com.ning.http.client.providers.grizzly.HttpTransactionContext.currentTransaction(HttpTransactionContext.java:122)
	at com.ning.http.client.providers.grizzly.AhcEventFilter.onHttpHeaderError(AhcEventFilter.java:254)
	at org.glassfish.grizzly.http.HttpCodecFilter.handleRead(HttpCodecFilter.java:563)
	at org.glassfish.grizzly.http.HttpClientFilter.handleRead(HttpClientFilter.java:175)

I looked at the code and I found that it is now checking for a connect flag and only if it is false it will add the proxy authentication header.

        com.ning.http.util.AuthenticatorUtils
        public static String perRequestProxyAuthorizationHeader(Request request,
            Realm realm, ProxyServer proxyServer, boolean connect) {

        String proxyAuthorization = null;

        if (!connect && proxyServer != null && proxyServer.getPrincipal() != null
                && proxyServer.getScheme() == Realm.AuthScheme.BASIC) {
            proxyAuthorization = computeBasicAuthentication(proxyServer);

        }

The previous version of the code was sending always the proxy-authorization without checking or not this flag.

I have made the change to do send the proxyAuthorization based on proxyServer data but I'm not able to get the test to complete the sequence or requests (it does the connect, get) due to an SSL issue that I'm not able to find out why it is failing. Let me know if you want me to share this code.

Thanks!

**Comment by gsfernandes** [comment]
Similar issue reported for Netty #996

**Comment by gsfernandes** [comment]
https://github.com/gsfernandes/async-http-client/commit/5f88a5ea5d61b96210e6aa64edef6e1cacbef8c5 link to the potential fix with the junit test (that as I mentioned has an issue with SSL that would need to be fixed)

**Comment by slandelle** [comment]
It looks to me that your change drops proxy auth over plain http.
I think the correct condition would actually be `plain http or connect`.

I'll try to get a Jetty based proxy working over HTTPS tomorrow for master branch. Then, you could try to backport it.

**Comment by gsfernandes** [comment]
Hi @slandelle,
I'm not sure if plain http should also be included in this case because whenever I tried the same scenario but accessing to plain http through a http proxy I saw that it works and it does the whole dialog with the server: GET->407 with the authenticate header->GET with proxy-authorization and finally the response from the remote server.
So, I don't know exactly if the same "dialog" should happen when a CONNECT is being made or either the proxy-authorization header should always. What would be the expected behaviour?

**Comment by gsfernandes** [comment]
Hi @slandelle,
Did you have a chance to look into this?
Thanks

**Comment by slandelle** [comment]
Barely.
I thing we really need integrated tests that really use a proxy, not just mimic one.
Jetty only has built-in support of plain HTTP proxy (see `org.eclipse.jetty.proxy.ProxyServlet`), but it seems possible to extend for supporting HTTPS, see http://stackoverflow.com/questions/9852056/jetty-proxyservlet-with-ssl-support#28226464.

I might be able to get a stab later this week, but I cannot guarantee it :(

**Comment by gsfernandes** [comment]
Hi, thank you! Meanwhile, if I have some time in the next days I'll try to use Jetty in my branch for testing the change.

**Comment by oleksiys** [comment]
@gsfernandes could you pls. share the testcase, so we can at least fix the NPE?

**Comment by IskanderMustafin** [comment]
I think there another (security) problem according to the logs provided by OP: 

after proxy established SSL tunnel between client and destination server, AHC still sends `Proxy-Authorization` header to the destination website (and proxy server can't remove this header while forwarding request because connection is encrypted)

**Comment by slandelle** [comment]
@IskanderMustafin I think that's something I fixed some time ago: 67f1cd669630cd4a9adca34704866b1f15a15033

Basically, we REALLY need those embedded integration tests.

**Comment by gsfernandes** [comment]
Hi, here is what I proposed to fix this issue https://github.com/gsfernandes/async-http-client/commit/5f88a5ea5d61b96210e6aa64edef6e1cacbef8c5
Still I would like to try what @slandelle proposed for testing it because the test that I wrote is having some issues with the ssl connection. Even more the change that @slandelle shared is almost the same that should be done for grizzly in order to fix this, send the proxy authorization header on connect or plain http.
I'm not aware of a NPE, at least from what we have found related to this issue but let me know if this works for you @oleksiys

**Comment by gsfernandes** [comment]
Hi,
I think that there was a misunderstanding about how the proxy should be set for this issue. It has to be just an HTTP proxy but the destination requested url should be an HTTPS. So there is no need to migrate to Jetty 9 in order to fix this issue and mostly when the code for these logic has been reimplemented in AHC 2.x
So, I have improved the tests (using a ConnectHandler to make it work the tunneling to the HTTPS server) and created a PR for this change in 1.9.x.
https://github.com/AsyncHttpClient/async-http-client/pull/1158
Thanks!

**Comment by slandelle** [comment]
@gsfernandes Awesome work, thanks a lot! Please address the few nits and I'll merge.

**Comment by slandelle** [comment]
FYI, I've ported the tests to Jetty 9 on the master branch: 48111becfa6b2cd19cbc2ead9f72ae976e340bd0.

My version really involve a proxy and target server pair for both plain HTTP and HTTPS.

**Comment by gsfernandes** [comment]
Awesome! I saw that the issue cannot be reproduced in master branch, that's also good because it was already fixed.

**Comment by pbostrom** [comment]
@gsfernandes this is great! thanks for fixing this

**Comment by oleksiys** [comment]
@gsfernandes thank you!

**Comment by gsfernandes** [comment]
You are welcome guys!

**Comment by afelisatti** [comment]
@slandelle when can we expect the 1.9.39 release including this fix?

**Comment by slandelle** [comment]
I can release in 2 weeks when I'm back to the office.

**Comment by afelisatti** [comment]
Thanks!

**Comment by afelisatti** [comment]
Thanks, @slandelle!
