### ISSUE TITLE
CompletableFuture exceptions are wrapped twice

### ISSUE THREAD

**Issue by etki** [AsyncHttpClient/async-http-client#1163]
Hi.
I'm a CompletableFuture-fan, so i work using this interface. I was expecting to get timeouts and stuff in the form of ExecutionException with original Exception as cause:

    ExecutionException:
      cause: TimeoutException

however, i see something more complicated:

    ExecutionException:
      cause: ExecutionException:
        cause: TimeoutException

I believe that it may be solved in a couple of lines in `ListenableFuture.CompletedFailure.toCompletableFuture`, however, i'm not familiar with project architecture and not sure that project maintainers will accept my vision, so i'm not sending any pull requests.
So, my proposition is: remove excessive ExecutionException wrapper in responses converted to CompletableFutures since it is not intuitive and most users will expect original cause wrapped in the exception thrown during `.get()` call.

**Comment by slandelle** [comment]
Completely agree. Fixed. Thanks for reporting.

**Comment by etki** [comment]
@slandelle that was blazingly fast, thank you! Waiting for release.
