### ISSUE TITLE
When connect fails, Grizzly provider doesn't notify with the proper exception (1.9 only)

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#1166]
See discussion and possible fix #1134.
Waiting for fix to be validated by @oleksiys.

**Comment by gsfernandes** [comment]
Hi @oleksiys, did you have a chance to look at this issue?
I would need this fixed along with #1152 in the new 1.9.x release of AHC. Let me know if I could help you somehow, I have tested the fix provided in #1134 and it does the fix for it.
Thank you!

**Comment by elrodro83** [comment]
Is there any ETA for this issue? @oleksiys

**Comment by afelisatti** [comment]
Any update on this, @oleksiys ? The 1.9.39 release seems to be blocked by this issue but there's a proposed fix available.
Thanks

**Comment by afelisatti** [comment]
Anyone else from the Grizzly team that could take a look at this? @rlubke

**Comment by rlubke** [comment]
Yep, will take a look.

**Comment by slandelle** [comment]
@rlubke Welcome back!

**Comment by rlubke** [comment]
@slandelle Thanks!
