### ISSUE TITLE
Allow customizing SslContext after default config is performed

### ISSUE THREAD

**Issue by marshallpierce** [AsyncHttpClient/async-http-client#1170]
I want to customize the trusted CA certs to only trust an internal CA (for service-to-service use). It seems like what I want is to use any of the `SslContextBuilder#trustManager()` methods when building the `SslContext`. However, I'd like to re-use the existing default setup that's done in `DefaultSslEngineFactory`. (Side note: When would `JsseSslEngineFactory` be used? It's not clear what it's for.) Right now my workaround is to copy-and-paste all the setup done in `DefaultSslEngineFactory` and `SslEngineFactoryBase` when creating my own `SslContext`, which isn't ideal.

One way to do this would be to allow customizing the `SslContextBuilder` created in `DefaultSslEngineFactory` right before `build()` is called, maybe by providing a `Function<SslContextBuilder,SslContextBuilder>` or `Consumer<SslContextBuilder>` in `AsyncHttpClientConfig`. This would allow for re-use of the existing config logic but also make it fairly easy to provide a hook that sets up the trust manager. However, it would mean that the config option would be meaningless if a custom SslEngineFactory is provided. I don't know how common that is in practice.

Anyway, I'm happy to provide a PR to get this fixed so I can delete my copy and pasted code...

**Comment by slandelle** [comment]
`JsseSslEngineFactory` takes a `javax.net.ssl.SSLContext` while `DefaultSslEngineFactory` is based on `io.netty.handler.ssl.SslContext`.

> One way to do this would be to allow customizing the SslContextBuilder created in DefaultSslEngineFactory right before build() is called, maybe by providing a Function<SslContextBuilder,SslContextBuilder> or Consumer<SslContextBuilder> in AsyncHttpClientConfig.

Better: have a protected method that you could override and that doesn't break API.

>  However, it would mean that the config option would be meaningless if a custom SslEngineFactory is provided. I don't know how common that is in practice.

I don't get you.

> Anyway, I'm happy to provide a PR to get this fixed so I can delete my copy and pasted code...

Sure, go ahead.

**Comment by marshallpierce** [comment]
- Jsse vs Default: makes sense, thanks.
- Protected method: will do, PR forthcoming.
- Config changes: I was referring to how only the Default factory impl would make use of the config option, which could be confusing to users. But, not an issue with the protected method route.

**Comment by slandelle** [comment]
> Config changes: I was referring to how only the Default factory impl would make use of the config option, which could be confusing to users. But, not an issue with the protected method route.

Oh, right, that's indeed a design issue! DefaultSslEngineFactory takes a `AsyncHttpClientConfig` but `SslEngineFactory` can be passed **from** the `AsyncHttpClientConfig`.

Let's change `DefaultSslEngineFactory` to lazy load (with double checked locking) the `SslContext` instance on `newSslEngine(AsyncHttpClientConfig config, String peerHost, int peerPort)`.

Want to tackle it too?

**Comment by marshallpierce** [comment]
> Let's change DefaultSslEngineFactory to lazy load (with double checked locking) the SslContext instance on newSslEngine(AsyncHttpClientConfig config, String peerHost, int peerPort).

Unfortunately `SslContextBuilder.build()` throws `SSLException`, which is not thrown by `newSslEngine()`. How would you like to handle that?

**Comment by slandelle** [comment]
Closed by #1171
