### ISSUE TITLE
DNS resolution does not use the timeouts

### ISSUE THREAD

**Issue by ElPicador** [AsyncHttpClient/async-http-client#1173]
Recently our DNS provider was DDoS. One of our application experienced timeouts (which make sense), but they were much higher than the one we set.

The DNS was accepting connections but was not answering anything. We managed to setup a server that does exactly that (see test below).

I have managed to reproduce the issue with a simple test, with the `2.0.4`, java `1.8`.
On MacOS, the following test runs in ~8s. But it should fail in ~100ms, as all timeouts are at 100ms, specially the `requestTimeout`.

Furthermore, it seems the timeout is OS specific (~20s on travis).
```
    AsyncHttpClientConfig cf = new DefaultAsyncHttpClientConfig
      .Builder()
      .setConnectTimeout(100)
      .setReadTimeout(100)
      .setRequestTimeout(100)
      .build();

    AsyncHttpClient asyncHttpClient = new DefaultAsyncHttpClient(cf);
    final long start = System.currentTimeMillis();
    Future<Integer> f = asyncHttpClient
      .prepareGet("http://java-" + System.currentTimeMillis() + ".algolia.biz/") //to be sure the dns resolution is not cached by the JVM
      .execute(new AsyncCompletionHandler<Integer>() {

        @Override
        public Integer onCompleted(Response response) throws Exception {
          return response.getStatusCode();
        }

        @Override
        public void onThrowable(Throwable t) {
        }
      });

    try {
      Assert.fail("fail here:" + f.get().toString());
    } catch(ExecutionException e) {
      long total = System.currentTimeMillis() - start;
      Assert.assertTrue("Timeout on DNS took " + total + " ms", total < 200);
    }
```

An exemple of output on MacOS:
```
java.lang.AssertionError: Timeout on DNS took 7349 ms
```

**Comment by slandelle** [comment]
The default name resolver (JDK) blocks the caller thread.
Such blocking calls don't fit well in AHC non-blocking model for sure. You can provide your own `NameResolver` (on the request), like a non blocking `DnsNameResolver` or a custom one that would wrap the `DefaultNameResolver` with a dedicated thread pool (in which case, you have to take care of possible thread starvation).

**Comment by ElPicador** [comment]
Thanks for the info.

For future use, I added this:
```
DnsNameResolver dnsNameResolver = new DnsNameResolverBuilder(group.next())
      .channelType(NioDatagramChannel.class)
      .queryTimeoutMillis(200)
      .build();


    Future<Integer> f = asyncHttpClient
      .prepareGet("http://java-" + System.currentTimeMillis() + ".algolia.biz/")
      .setNameResolver(dnsNameResolver)
...
```
