### ISSUE TITLE
Drop CleanupChannelGroup

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#1176]
I fail to see the value here. Plus ChannelGroup takes care of removing channel when it's closed.

**Comment by huntc** [comment]
Please be mindful of upstream dependencies when you remove public types i.e. please don't just bump up the patch release as you did here (2.0.4 to 2.0.5). This was a breaking change and perhaps deserved at least a 2.1.0.

FYI The problem caused a whole swag of problems upstream for Play and Lagom.

Thanks for your consideration.

**Comment by slandelle** [comment]
Hi @huntc 

Sorry, I didn't expected that anyone would be impacted with this change.

Then, that `CleanupChannelGroup` was public was definitively a mistake, as it was not even possible to pass one to AHC. So I'd be curious of how you were using it. Was it for hacking in AHC, or was it for other usage in Play's Netty layer? If the latter, it would have been better to fork it.

Honestly, I wish Java had proper visibility management like in Scala, so I could turn 90% of the classes here `private[asynchttpclient]`.

**Comment by huntc** [comment]
Thanks @slandelle - sounds like you need Scala re package scoping. :-)

Here was the line in Lagom (another framework of ours based on Play): https://github.com/lagom/lagom/search?utf8=%E2%9C%93&q=CleanupChannelGroup

...and here's our proposed fix: https://github.com/lagom/lagom/issues/313

Re. public types, deprecating them is also another option of course. Thanks.

**Comment by slandelle** [comment]
We have an unfortunate chain of events:
* original authors making this public, should have been package private. Even better: document what this class is about and how it improve things compared to standard implementation so that future maintainers would get a clue.
* me failing to realize this could ever break things downstream as there's no sane reason for someone else to be using it
* someone (no offense/blaming meant) mistakingly using it, all the more in a WebSocket client that's implemented on top of bare Netty and not on top of AHC

S**t happens

**Comment by huntc** [comment]
No worries - thanks for the explanations.

**Comment by jroper** [comment]
We shouldn't have been depending on it in Lagom - I have no idea why I added code that was.
