### ISSUE TITLE
WebSocketHandler, ping, pong frame don't need to have any readable bytes.

### ISSUE THREAD

**Issue by Yi-G** [AsyncHttpClient/async-http-client#1192]
Actually, it is a question, I don't find any chat or mailinglist to post my question.
Why the ping pong frame should have any readable bytes. According to the ws protocal, there is no need to have any bytes in the frame, but have a max limit.

Thanks! 

best regards
Yi

**Comment by slandelle** [comment]
The address of the mailing list is in the [README](https://github.com/AsyncHttpClient/async-http-client#user-group).

If you think you've found an issue, please provide the version you're using and a reproducer.
