### ISSUE TITLE
Unreliable behavior with custom Http based protocol

### ISSUE THREAD

**Issue by oakad** [AsyncHttpClient/async-http-client#1197]
I'm trying to use AHC (v2.0.6, java 8) to access a PHP backed server. The protocol is simple: client POSTs a binary coded message to the server, server replies with few basic headers and a binary coded reply. The server is reliable (prolonged commercial use at high volumes); Java's HttpUrlConnection, jetty-http, and, ironically, AHC v1.9.30 inter-operate with it flawlessly.

When attempting to use AHC (very simple test case: POST a single message, get a single reply) I'm encountering the following behavior (on different attempts):

1. All handler methods are called back, reply correctly received (~30% of attempts)
2. All handler methods are called back, bodyPart parameter to onBodyPartReceived callback is empty (no body bytes are delivered to client, despite being present on the wire)
3. No handler methods are called, application never terminates (future.get() is stuck waiting), despite server reply being present on the wire

I hope, somebody can point me to whatever configuration settings or other ways to resolve the above undesirable issues.

**Comment by slandelle** [comment]
Could be lots of things, from bad usage to your server being racy or not handling load. Please provide a reproducer.

**Comment by oakad** [comment]
As I mentioned, AHC 1.9.30 exhibits no such behavior (just like any other library I tried, apart from AHC 2). Unfortunately, I'm stuck with AHC 2 due to third party dependency.

How am I supposed to code a reproducer for this?

**Comment by slandelle** [comment]
Either trim your app and client down so I can install on my side, or grant a private access to your system.

**Comment by oakad** [comment]
Luckily, I have traced the problem to it's origin already. Sorry for the noise.

I was passing the body of the request via "setBody(InputStream)" method. The InputStream I was using had a faulty "int read()" method (as opposed to properly working "int read(byte[], int, int)" one). It appears, that newer version of AHC occasionally uses the former method to perform a "single byte" read, and upon receiving a negative char value expectedly truncates the request, causing problems down the line.

**Comment by slandelle** [comment]
> It appears, that newer version of AHC occasionally uses the former method to perform a "single byte" read

Absolutely: https://github.com/netty/netty/blob/4.0/handler/src/main/java/io/netty/handler/stream/ChunkedStream.java#L87-L89
