### ISSUE TITLE
Connecting to wrong machine when using IP

### ISSUE THREAD

**Issue by AliA74** [AsyncHttpClient/async-http-client#1210]
Hello,

We were having a really strange issue in our app . We were trying to connect to our server which doesn't have a domain thus we were reaching it by IP. But it was strange we were connecting to some wrong machine ! We could establish correct connection using a browser on the device but not with the library .

This is the address we were trying to reach (Which you can test it):
http://164.138.19.117/v1/version

if you get {"status":"failed","message":"Security Error"} then it means you have successfully reached the correct machine but if you get any other response (as we were getting 404 Not Found) it means you have reached wrong machine.

We switched to another library for this particular server and it's working correctly now.

I hope you will find this useful and can make a fix around this.

P.S. We were using version 1.4.9 , Not on all devices we had problem but most of them

**Comment by slandelle** [comment]
Huge huge huge SIGH...

You're not using AsyncHttpClient (this project), you're using Loopj's AndroidAsyncHttp.
See [here](https://github.com/loopj/android-async-http/issues/876) for my complain regarding this other project not being capable of properly routing its users.
