### ISSUE TITLE
[AHC 2] ByteBuffer Response wrong position 

### ISSUE THREAD

**Issue by marenzo** [AsyncHttpClient/async-http-client#1212]
Calling `Response#getResponseBodyAsByteBuffer` will return a new ByteBuffer but the current position will be the end of the buffer, rather than the start, causing to rewind manually the buffer.
The allocated byte buffer should have the position set to zero.

Problematic code is found at `NettyResponse#getResponseBodyAsByteBuffer`.

Just a side note: previous client returned the byte buffer with position zero.

**Comment by slandelle** [comment]
Closed by #1213
