### ISSUE TITLE
[AHC 2] AsyncHandler callback without content

### ISSUE THREAD

**Issue by marenzo** [AsyncHttpClient/async-http-client#1214]
In AHC 2.x, when I'm executing request providing my AsyncHandler implementation, after the last chunk being sent from the server, I receive another callback (to `onBodyPartReceived`) with empty payload, which can cause misleading of an actual chunk was sent.

This issue have not occurred with the previous client (1.9.x).

Extra details:
I have a test (https://github.com/outbrain/ob1k/blob/master/ob1k-http/src/test/java/com/outbrain/ob1k/http/ClientBasicFlowsTest.java#L99) that calls to chunked stream endpoint, that should return 3 chunks in total. In actual, with the new client, I receive 4 chunks, while the last one is just empty. The last chunk does not have any special identifier, except for the fact that the body part buffer is empty, but not sure I can account on it.

I haven't found the source of the bug (if it is) yet, but I'll update if I'll do

**Comment by slandelle** [comment]
> In AHC 2.x, when I'm executing request providing my AsyncHandler implementation, after the last chunk being sent from the server, I receive another callback (to onBodyPartReceived) with empty payload, which can cause misleading of an actual chunk was sent.

You're confusing TCP frames and chunks read from the wire. Those can be unrelated.

Netty 4 has this `LastHttpContent` that can contains some content or not, and can possibly contain trailing HTTP headers.

I guess I'll map more closely to their model in a next release.

In short, no, it's not a bug.

**Comment by marenzo** [comment]
Should I use `HttpResponseBodyPart#isLast`, and if it is, then consider the reading as done (and not trying do actually do something with the body)?

**Comment by slandelle** [comment]
Absolutely
