### ISSUE TITLE
Wrong OAuth 1.0 signature for some special characters in URL

### ISSUE THREAD

**Issue by SvenSchindler** [AsyncHttpClient/async-http-client#1216]
Hi there,

we're currently dealing with the following issue: we're trying to use the AsyncHttpClient to consume an OAuth 1.0 protected API. One of our request parameters may contain an asterisks value. This seems to lead to a wrong signature computation causing a 401 server response.

To reproduce the problem it is sufficient to generate an OAuth 1.0 signed request having an asterisk for one of its parameter values, e.g.: http://www.example.com/api?testvalue=* (using async-http-client version 2.0.10)

What we think what the problem is: behind the scenes, the client applies the OAuthSignatureCalculator class to compute the OAuth signature. The computation encodes form parameters separately and expects that all query parameters have been url encoded successfully. However, RFC 5849 defines to encode all parameters application/x-www-form-urlencoded for the signature generation (3.4.1.3.1.  Parameter Sources). Some characters, such as "*" or "~", do not need an URL encoding but a form encoding. The OAuthSignatureCalculator simply ignores these special cases.

A possible solution may be to re-encode all query parameters which require a special encoding to be application/x-www-form-urlencoded. For example, insert a special character check at the following code line:
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/oauth/OAuthSignatureCalculator.java#L149

Cheers,

Sven

**Comment by slandelle** [comment]
Thanks for reporting

**Comment by SvenSchindler** [comment]
Oh, that was quick :), thanks a lot!
