### ISSUE TITLE
Instantiate internal eventLoopGroup earlier or expose eventLoopGroup generator

### ISSUE THREAD

**Issue by mdedetrich** [AsyncHttpClient/async-http-client#1221]
I am currently experiencing an issue where I basically want to create a delegated `EventLoopGroup` from the default `EventLoopGroup` used internally by Async Http Client. The problem is that its not really possible to get a reference of how the default `EventLoopGroup` is constructed. If you use the `DefaultAsyncHttpClientConfigBuilder` to get the default `EventLoopGroup` you will get null, i.e.

```java
new DefaultAsyncHttpClientConfig.Builder().build().getEventLoopGroup; // is null
```

This is because the eventLoopGroup only gets instantiated later by the `ChannelManager` over here https://github.com/AsyncHttpClient/async-http-client/blob/e260b754f9cd0c7491b2551c83f556ecbfe6be4b/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L165-L188

Would it be possible to either instantiate the eventLoopGroup in the `build` method within the `Builder`, or expose how the default eventLoopGroup gets created by AsyncHttpClient so its possible to just get the default generated `EventLoopGroup`?

**Comment by slandelle** [comment]
Why don't you pass your own EventLoopGroup?

**Comment by mdedetrich** [comment]
> Why don't you pass your own EventLoopGroup?

I basically don't want to mess with possibly providing an incorrect (or underperforming) EventLoopGroup (I am using the assumption that the default EventLoopGroup that AsyncHttpClient creates is what is ideal).

**Comment by slandelle** [comment]
Ok, why not.
