### ISSUE TITLE
Unable to use v1.9.38 with android as it is giving me a NetworkOnMainThreadException

### ISSUE THREAD

**Issue by tirth1796** [AsyncHttpClient/async-http-client#1225]
It seems that it is running on the main thread itself. 
It is solved if I use StrictMode.enableDefaults(); 
But that is not a good way to go about it.

**Comment by slandelle** [comment]
Actually:
* AHC 1 has reached EOL
* AHC doesn't aim at supporting Android. AHC 1 was compiled with Java 7 and uses some methods that were not introduced in the pretending-to-be-but-actually-not-Java7-compatible Android SDK. AHC 2 is compiled against Java 8.
* You're probably using the JDK provider which was more of a toy than a production ready implementation. It was dropped in AHC 2.

You probably want to use OkHttp that's developed for Android.
