### ISSUE TITLE
Have a CookieJar

### ISSUE THREAD

**Issue by fangqiao** [AsyncHttpClient/async-http-client#1235]
Hi, 

I am using this lib for testing a custom REST server based on Netty 4.1. 4, the latest, using Scala.

I need to test that cookie has been set correctly at sever side and can be parsed correct on next request.

I used a single DefaultAsyncHttpClient object to submit the first round of request and it received server set cookies successfully.

```
val httpClient = new  DefaultAsyncHttpClient()

  val request : Request = (new RequestBuilder("POST")).
    setUrl("http://127.0.0.1:9090/login").
    setBody(json).
    build()

  val future : Future[Response] = httpClient.executeRequest(request)


  val response: Response = future.get()

  response.getStatusCode should equal (200)
  val cookies = response.getCookies 
```

The cookies from server were correctly returned.

Then I used the same DefaultAsyncHttpClient object to submit another request. I supposed the cookies be sent to server automatically. But the netty server was never able to get the cookies from the requests.

Then i tried in the next request by explicitly setting cookies.
      val request2: Request = (new RequestBuilder("GET")).
        setUrl("http://127.0.0.1:9090/developer").
        setCookies(cookies).
        build() 

This time the netty server can parse the cookies correctly.

I am wondering if it is by design that DefaultAsyncHttpClient will not send server side cookies in next round of request.

If so, I suggest to add the support to coming versions.

If not, what's the correct way to use this feature, which is very useful for my case.

Thanks

**Comment by slandelle** [comment]
> I am wondering if it is by design that DefaultAsyncHttpClient will not send server side cookies in next round of request.

No, AHC doesn't provide a cookie jar.

> If so, I suggest to add the support to coming versions.

Contribs welcome

> If not, what's the correct way to use this feature, which is very useful for my case.

You have the responses where you can fetch the Set-Cookie header, fetch those and use them to craft the next requests.

**Comment by fangqiao** [comment]
Thanks for the answers.

> You have the responses where you can fetch the Set-Cookie header, fetch those and use them to craft the next requests.

That is exactly what i am doing now. 

Maybe as interim solution, add a line to API doc or github homepage?

**Comment by slandelle** [comment]
No contrib so far. Closing for now.

**Comment by slandelle** [comment]
Note for potential contributor: you can have a look at https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/cookie/CookieJar.scala for an example. Main difference is AHC would need a thread safe implementation (most likely ConcurrentHashMap based).

**Comment by unoexperto** [comment]
@slandelle Could you please tell me what aspect exactly of implementation of CookieJar use provided above in https://github.com/Diagoras/async-http-client/commit/96747f9cb95725d86cf046fdb3510ebb41cfc2df you consider incorrect ?

**Comment by slandelle** [comment]
Sadly, all of it: it doesn't implement anything from the RFC6265 spec, such as domain and path matching.
