### ISSUE TITLE
Failed Compiling using asynchttpclient with android N java 8 v2.0.8

### ISSUE THREAD

**Issue by tirth1796** [AsyncHttpClient/async-http-client#1236]
This is the error stack I am receiving.

Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/INDEX.LIST
    File1: /Users/tirthshah/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-native-epoll/4.0.39.Final/9988e1c36df934a730b6f8654b45c29b44ac362f/netty-transport-native-epoll-4.0.39.Final-linux-x86_64.jar
     File2: /Users/tirthshah/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec/4.0.39.Final/f6af388f6d08e0163125e3dfa29edb22ca37b3b4/netty-codec-4.0.39.Final.jar
     File3: /Users/tirthshah/.gradle/caches/modules-2/files-2.1/io.netty/netty-codec-http/4.0.39.Final/92972d1c61506d07cea33c9d5fedd20d6893adbe/netty-codec-http-4.0.39.Final.jar
     File4: /Users/tirthshah/.gradle/caches/modules-2/files-2.1/io.netty/netty-handler/4.0.39.Final/daa94b949c65c2bf78e4fe7b869f0befdc063a36/netty-handler-4.0.39.Final.jar
     File5: /Users/tirthshah/.gradle/caches/modules-2/files-2.1/io.netty/netty-buffer/4.0.39.Final/a6442e529ef2e763d017a9d63ea88fc695bf8e72/netty-buffer-4.0.39.Final.jar
     File6: /Users/tirthshah/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport/4.0.39.Final/7bf6857ae0eea9217a62101cacea45834981ae60/netty-transport-4.0.39.Final.jar

**Comment by slandelle** [comment]
AHC is not compatible with Android.

**Comment by ricardojlrufino** [comment]
I am the [wasync](https://github.com/Atmosphere/wasync) library, that supports Android.
And I realized that it is based on the branche:
https://github.com/AsyncHttpClient/async-http-client/tree/1.9.x

Support for Android was dropped?

**Comment by slandelle** [comment]
Yes. More specifically, support for Java < 8 was dropped.
