### ISSUE TITLE
Use long instead of int for timeouts

### ISSUE THREAD

**Issue by igouss** [AsyncHttpClient/async-http-client#1243]
Typically time is specified stored in longs
for example: java.util.concurrent.TimeUnit.SECONDS.toMillis(5)

Please replace int with long in org.asynchttpclient.DefaultAsyncHttpClientConfig
    // timeouts
    private final int connectTimeout;
    private final int requestTimeout;
    private final int readTimeout;
    private final int shutdownQuietPeriod;
    private final int shutdownTimeout;
...
    // ssl
    private final int handshakeTimeout;

**Comment by slandelle** [comment]
Those are timeouts expressed in seconds, there's no way someone would be willing to configure a value larger than Integer.MAX_INT.

**Comment by igouss** [comment]
Ok, however I was expecting this to be in milliseconds.

**Comment by slandelle** [comment]
I meant milliseconds, typed from my phone.
Still, it doesn't change the fact that no one sane would try to use timeouts larger that Integer.MAX_INT, even in ms.

**Comment by igouss** [comment]
It's not about being sane (I agree it would be insane), it's about consistency with the java conventions.

**Comment by igouss** [comment]
Async request to Mars orbital observer can take a ~48 minutes and that can not be expressed in signed int. I'm not sending anything to Mars, but it shows that it is not unreasonable request. ;-)

**Comment by slandelle** [comment]
Sure, if some day Mars observer uses AsyncHttpClient and reports a bug, I'll gladly reconsider.
Until then, as no one has ever reported experiencing an issue with the current int values, there's no reason the break an existing API.
