### ISSUE TITLE
Is DefaultAsyncHttpClient ThreadSafe?

### ISSUE THREAD

**Issue by doom369** [AsyncHttpClient/async-http-client#1246]
From code look like not. Am I right?

**Comment by slandelle** [comment]
? Why?

**Comment by doom369** [comment]
My fail, didn't look carefully. I made review again, seems fine. What about adding threadSafe annotation or updating docs as I didn't find any explicit explanation?

**Comment by slandelle** [comment]
Are you talking about:
* [com.google.code.findbugs:jsr305](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.code.findbugs%22%20AND%20a%3A%22jsr305%22)
* or [net.sourceforge.findbugs:jsr305](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.sourceforge.findbugs%22%20AND%20a%3A%22jsr305%22)
* or [com.google.code.findbugs:annotations](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.code.findbugs%22%20AND%20a%3A%22annotations%22)
* or [net.sourceforge.findbugs:annotations](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.sourceforge.findbugs%22%20AND%20a%3A%22annotations%22)
* [findbugs:annotations](http://search.maven.org/#artifactdetails%7Cfindbugs%7Cannotations%7C1.0.0%7Cjar)
* [com.google.code.findbugs:findbugs-annotations](http://search.maven.org/#artifactdetails%7Ccom.google.code.findbugs%7Cfindbugs-annotations%7C3.0.1%7Cjar)

See my point: dealing with this is a mess, and I'm not convinced with the added value. What I not is that it will just add a messy dependency.

**Comment by doom369** [comment]
`See my point: dealing with this is a mess`

Agree. What about documentation? At least comments?

**Comment by slandelle** [comment]
The whole `AsyncHttpClient` javadoc would need a serious update :(
Contribs welcome :)
