### ISSUE TITLE
NoSuchMethodError (SSLContextError)

### ISSUE THREAD

**Issue by Ahmed-Saied** [AsyncHttpClient/async-http-client#1254]
I'm trying to use AsyncHttpClient but I got the following error 
java.lang.NoSuchMethodError: io.netty.handler.ssl.SslContext.newClientContextInternal(Lio/netty/handler/ssl/SslProvider;[Ljava/security/cert/X509Certificate;Ljavax/net/ssl/TrustManagerFactory;[Ljava/security/cert/X509Certificate;Ljava/security/PrivateKey;Ljava/lang/String;Ljavax/net/ssl/KeyManagerFactory;Ljava/lang/Iterable;Lio/netty/handler/ssl/CipherSuiteFilter;Lio/netty/handler/ssl/ApplicationProtocolConfig;JJ)Lio/netty/handler/ssl/SslContext;

**Comment by slandelle** [comment]
You're probably using a different Netty version. Problem is on your side and for you to figure out.

**Comment by Ahmed-Saied** [comment]
I'm using this dependency 
<dependency>
			<groupId>org.asynchttpclient</groupId>
			<artifactId>async-http-client</artifactId>
			<version>2.0.15</version>
		</dependency>

so should I explicitly use specific netty dependency or I should change the version of asynchttpclient

**Comment by Kyu** [comment]
(Came from google, this is the second result)

That method was last supported in `netty 4.1.0.Beta4`, as you can see in https://github.com/netty/netty/commit/06217aefb753904f431e9012cf65170e7eb07fa4.

The last stable version of netty before that was `4.0.56.Final`, and the last version of AsyncHttpClient that used that version was `2.0.25`, as you can see in https://github.com/AsyncHttpClient/async-http-client/commit/468b6f1f43d86fbb3cd7c8d34cf46b241606d335   

My use case is modding for an old Minecraft version(1.8.9), which strictly uses netty 4.0.23
