### ISSUE TITLE
Porting library to Netty 4.1

### ISSUE THREAD

**Issue by masterlittle** [AsyncHttpClient/async-http-client#1257]
Hi, I have a use-case wherein I wanted to route my traffic through a SOCKS proxy. As Netty 4.1 gives this functionality I tried porting this library to 4.1 and adding a Socks4ProxyHandler in the config. But after changing the version, I got a few errors and after fixing them I am getting this error on repeat. Please hep cause I am new to this and do not have much idea about resolving the error. I would be happy if you could even pint me in the right direction. Also if this is not possible immediately could there be any other way in which I could route my http requests through Tor? Maybe by tunnelling all traffic through the proxy?

**Comment by slandelle** [comment]
Please first check the bug tracker for existing related issues before creating duplicates, see #1161

Then, please use the mailing list for questions. AHC doesn't support SOCKS proxies atm. Feel free to contribute.
