### ISSUE TITLE
Expose ConnectionPool metrics for monitoring

### ISSUE THREAD

**Issue by ggarber** [AsyncHttpClient/async-http-client#1259]
It would be good to expose some metrics (connectionsInUse/Free) so that we can use that information for monitoring purposes.

**Comment by slandelle** [comment]
Duplicate of #1130 , wip in #1255

**Comment by skilledmonster** [comment]
Is this change ever merged to the master. I am using the latest version and I don't see the getClientStats in the AsyncHttpClient Interface. How do I collect client stats?

**Comment by joprice** [comment]
Could this be backported to 2.0.x?
