### ISSUE TITLE
Grizzly Provider HttpTransactionContext.getAsyncHandler() does not handle situation where future is null.

### ISSUE THREAD

**Issue by dfeist** [AsyncHttpClient/async-http-client#1261]
In various scenarios the future in HttpTransactionContext is null. While HttpTransactionContext exposes a getter for AsyncHandler, if does not handle the case where the future is null.

**Comment by dfeist** [comment]
@slandelle  Any chance this simple NPE can be merged in? Or will there be no further AHC1 releases now? /cc @rlubke

**Comment by slandelle** [comment]
@dfeist As I don't know anything about the old Grizzly provider, I can't safely assume that your proposed commit fixes anything as it doesn't ship any test demonstrating the issue. I'd rather have @rlubke or @oleksiys validate your PR.

Then, I can do a release of 1.9, but that will definitively be the final last one. AHC1 is EOL'ed.

**Comment by slandelle** [comment]
Closing, AHC1 is EOL'ed.

**Comment by rlubke** [comment]
@slandelle Hey Stephane, can you contact me offline to discuss further?  You should still have my gmail address.

**Comment by slandelle** [comment]
@rlubke Hey Ryan. Sorry, I've lost it, along with my "excylis.com" email address, for some complicated company reasons. You can reach me at slandelle at gatling dot io.
