### ISSUE TITLE
Keep-alive connection not kept on 301 w/ host change

### ISSUE THREAD

**Issue by MikeN123** [AsyncHttpClient/async-http-client#1268]
`Redirect30xInterceptor` tries to reuse a channel on a redirect if keep-alive is enabled, and tries to offer the channel to the pool if that is not possible due to a host change, see here: https://github.com/AsyncHttpClient/async-http-client/blob/300a6c3dab6076f7a427e0c869bee511ff6d3bbd/client/src/main/java/org/asynchttpclient/netty/handler/intercept/Redirect30xInterceptor.java#L152

Unfortunately, that does not work, as `NettyRequestSender.sendNextRequest()` immediately clears the `Channel` attribute, which was a fix for another issue (#1059): https://github.com/AsyncHttpClient/async-http-client/blob/300a6c3dab6076f7a427e0c869bee511ff6d3bbd/client/src/main/java/org/asynchttpclient/netty/request/NettyRequestSender.java#L473

Not sure about the correct fix, still trying to figure that out.

**Comment by slandelle** [comment]
Actually, your understanding is not correct. What's nulled out is the channel's attribute. The future's channel is still here.
Please provide a reproducer if you experience an issue.

**Comment by MikeN123** [comment]
Uhm, I don't think you get the issue. The problem is not the future's channel, the problem is the channel's attribute being nulled out.

I don't have a full reproduction available, but it is easily seen from the source. Working from `Redirect30xInterceptor`.

- The connection is redirected to a different host, hence `sameBase = false`
- `channelManager.drainChannelAndOffer()` is called, to drain the channel and send it to the pool (as expected, as the channel can still be used and is kept alive)
- `drainChannelAndOffer()` creates a new callback, using `newDrainCallback()`. This callback's task is simply to put the channel back in the pool when the remaining data has been received (i.e., when `LastContent` is received).
- This callback is set as the channel's attribute: https://github.com/AsyncHttpClient/async-http-client/blob/300a6c3dab6076f7a427e0c869bee511ff6d3bbd/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L484
- The `Redirect30xInterceptor` then continues, calls `NettyRequestSender.sendNextRequest()`, which immediately clears the attribute. Hence the drain callback is gone.
- Somewhere in the future, the `LastContent` is received, we end up in `AsyncHttpClientHandler. channelRead()`, which reads the attribute, finds `null`, and ends up with a message about an orphan channel, and the channel is closed: https://github.com/AsyncHttpClient/async-http-client/blob/300a6c3dab6076f7a427e0c869bee511ff6d3bbd/client/src/main/java/org/asynchttpclient/netty/handler/AsyncHttpClientHandler.java#L114

Hope that helps.

**Comment by slandelle** [comment]
Sorry, I didn't get your original "that does not work" :)
If think the buggy code is no longer necessary, I removed it.

Thanks for reporting!
