### ISSUE TITLE
Problem with Gson exception in response handler

### ISSUE THREAD

**Issue by Meowzz95** [AsyncHttpClient/async-http-client#1269]
If there's a `gson#fromJson()` in response handler and there;s some error during the json parsing(gson throws some exception, eg: parse a String into an int field), it will simply stuck there, no exception is thrown.

**Comment by slandelle** [comment]
Reproducer please.

**Comment by Meowzz95** [comment]
Sorry I just found out that the exception is thrown in 'onThrowable()' method.
