### ISSUE TITLE
Android Studio build error

### ISSUE THREAD

**Issue by luozheng1985** [AsyncHttpClient/async-http-client#1270]
when I use the lib in my project ,JDK8 it throws exception:
ERROR: AsyncHttpClientConfigHelper.java:65-66: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
ERROR: ChannelManager.java:338-339: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function
ERROR: ChannelManager.java:365-366: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are io.netty.util.concurrent.GenericFutureListener
ERROR: NettyReactiveStreamsBody.java:113-114: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.lang.Runnable
ERROR: NettyReactiveStreamsBody.java:113-114: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are io.netty.util.concurrent.GenericFutureListener
ERROR: DefaultChannelPool.java:257-258: Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function

when i use jdk 7:
Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
      at com.android.dx.command.dexer.Main.processClass(Main.java:775)
       at com.android.dx.command.dexer.Main.processFileBytes(Main.java:741)
   at com.android.dx.command.dexer.Main.access$1200(Main.java:88)

how to fix this problem?thank you!

**Comment by slandelle** [comment]
AHC doesn't support Android.
