### ISSUE TITLE
MultipartBody can enter into infinite loop when a part as empty byte[]

### ISSUE THREAD

**Issue by dfeist** [AsyncHttpClient/async-http-client#1273]
This affects 1.9.x, and given it's not grizzly specific code I assume it affects Netty provider also.  

I've yet to create a decent test case or put together a fix, but I'm seeing a condition that occurs when the second part is empty that causes an infinite loop [here](https://github.com/AsyncHttpClient/async-http-client/blob/async-http-client-1.9.27/src/main/java/com/ning/http/client/multipart/MultipartBody.java#L109)

**Comment by carryel** [comment]
@dfeist I think this issue already has been patched at https://github.com/AsyncHttpClient/async-http-client/issues/1089.
Could you test this at v1.9.33+?

**Comment by dfeist** [comment]
I'm seeing this with 1.9.24 so yes, I'm pretty sure this is the same issue.  Closing as duplicate of #1089
