### ISSUE TITLE
Spring AsyncRestTemplate support

### ISSUE THREAD

**Issue by rrva** [AsyncHttpClient/async-http-client#1277]
Looking for an adapter to use Spring [AsyncRestTemplate](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/AsyncRestTemplate.html) with AsyncHttpClient.

I found https://github.com/lukiano/future-async-java/tree/master/src/main/java/com/ning/http/client/spring but it's 3 years old and is based on when the package name included ning.

**Comment by slandelle** [comment]
Sorry, but that's not something that will live in this project.
There are already too many dependencies.
