### ISSUE TITLE
Release netty-bp as a jar to Central Sonatype repo

### ISSUE THREAD

**Issue by Spikhalskiy** [AsyncHttpClient/async-http-client#1284]
Hi,

I want to use netty-bp in my project (because I have to use netty 4.0 branch as async-http-client doesn't support 4.1). But it's released as a pom only to sonatype repo.
Is it intentionally? Could we release this dependency as a jar too?

**Comment by slandelle** [comment]
You're checking the wrong artifact (the parent one).

**Comment by Spikhalskiy** [comment]
@slandelle No, I', pretty sure there is no jars here https://repo1.maven.org/maven2/org/asynchttpclient/netty-bp/2.0.19/

**Comment by slandelle** [comment]
:)
