### ISSUE TITLE
Early termination of reactive streams subscriber should close connection

### ISSUE THREAD

**Issue by jroper** [AsyncHttpClient/async-http-client#1306]
If a reactive streams subscriber cancels mid response, currently, AHC will drain the response, and return the connection to the queue once done.  This is not what happens when `AsyncHandler.onBodyPartReceived` returns `ABORT`, for example, when that happens, the connection is closed (I think).  The problem we're seeing is that if you have an infinite stream (eg, a Twitter streamed search response), it's impossible to ever terminate it.  Reactive streams response handling should terminate the connection upon a reactive streams subscriber cancelling.

**Comment by slandelle** [comment]
Hey @jroper 
Could you please provide a reproducer, please?

**Comment by slandelle** [comment]
ping @jroper :)

**Comment by jroper** [comment]
I just reported this issue after a user reported the effect (basically it causes a connection leak), and then I had a look at the source code and saw the problem. I don't really have time to provide a reproducer - it would probably be easier for me to provide a fix - but @gmethvin may be able to help.

**Comment by slandelle** [comment]
I feel like we should always close the connection when the user explicitly says to ABORT, instead of draining the response and trying to offer to the connection pool...

**Comment by technocoreai** [comment]
Does the same memory leak apply to `responseFuture.abort()` as well? If yes, is there any chance of backporting the fix to the 2.0 branch, since 2.1 still doesn't have a release date?
