### ISSUE TITLE
ThrottleRequestFilter swallows interfaces

### ISSUE THREAD

**Issue by markus-s24** [AsyncHttpClient/async-http-client#1314]
The ThrottleRequestFilter wraps the AsyncHandler with an AsyncHandlerWrapper. This way all additional interfaces implemented by the originating AsyncHandler get lost. E.g. ProgressAsyncHandler, ResumableAsyncHandler or any custom interfaces.

Suggestion: Maybe use a dynamic proxy which implements all interfaces of the originating AsyncHandler instead of using AsyncHandlerWrapper.

**Comment by slandelle** [comment]
The `Filter` API comes from the original author of this library.
I have personally no use for it so far.

Contributions welcome

**Comment by markus-s24** [comment]
See https://github.com/AsyncHttpClient/async-http-client/pull/1315
