### ISSUE TITLE
Media is not supported when .addHeader("application/json; charset=utf-8")

### ISSUE THREAD

**Issue by danilomagrini** [AsyncHttpClient/async-http-client#1316]
My code is:
```java
http.preparePost(apiUrl + path)
                .addHeader("Accept", "application/json; charset=utf-8")
                .setQueryParams(params)
                .setHeader("Content-Type", "application/json; charset=utf-8").setBody(body);
```

When I call _response.getResponseBody()_ I receive: "Media is not supported"

If I remove _charset=utf-8_ on addHeader then works, but my post send wrong body charset.

How I configure charset UTF-8?

**Comment by slandelle** [comment]
Could you please provide the version of AHC you're using and a full working reproducer?

**Comment by slandelle** [comment]
"application/json; charset=utf-8" is not valid value for "Accept" header, "application/json" is.
The error message is your server complaining about that.

**Comment by danilomagrini** [comment]
With AHC of _com.ning.http.client_ I used:

```
http.preparePost(apiUrl + path)
				.addHeader("Accept", "application/json")
				.setQueryParameters(params)
				.setHeader("Content-Type", "application/json").setBody(body)
                                .setBodyEncoding("UTF-8");
```
AHC of _org.asynchttpclient_ doesnt have this method.

**Comment by slandelle** [comment]
AHC1 is EOL'ed (no longer maintained, won't be released again), please upgrade.
In AHC2, you can use `setCharset`.

Then, you're confusing "Accept" header and "Content-Type". Those don't have to have the same value. The former tells the server that you want a given response format, the latter that you're sending a request with a body in the given format. It's fine to mention the charset in the "Content-Type" header.

**Comment by danilomagrini** [comment]
@slandelle 

I already upgraded to AHC2

.setCharset() works. Thanks.

Using .setCharset() is the same that "Content-Type" header with "application/json; charset=utf-8" value?
