### ISSUE TITLE
Https timing out

### ISSUE THREAD

**Issue by MingweiSamuel** [AsyncHttpClient/async-http-client#1319]
Does this library support https? When I try to send requests it keeps timing out:

        AsyncHttpClient client = new DefaultAsyncHttpClient();
        Response r = client.prepareGet("https://www.google.com").execute().get();
        System.out.println(r.getResponseBody());

    java.util.concurrent.TimeoutException: Request timeout to www.google.com/74.125.192.103:443 after 60000 ms

**Comment by slandelle** [comment]
2.1.0-alpha1 was a very early WIP for the Play! people so they could start working on their own Netty 4.1 upgrade.
Current master should be way more stable. I intend to release 2.1.0-alpha2 soon after Netty 4.1.7 gets released.

**Comment by buremba** [comment]
I use 2.0.24 and have the same problem.
