### ISSUE TITLE
Single HttpResponseBodyPart contains only part of data, another is coming in second HttpResponseBodyPart 

### ISSUE THREAD

**Issue by vvsh** [AsyncHttpClient/async-http-client#1322]
Hi,

I recently switched from ning/async-http-client and see that data that is sent from the server over the long polling connection is not properly split by chunks.

Using ning all the chunks were coming correctly, but using async-http-client long parts are split.

Example: expected part size is 2599 bytes, but it comes in two parts, first part size is 502, second part size is 2097.

Is there any configuration that could be used to specify a max part size?

Thanks,
Uladzimir

**Comment by vvsh** [comment]
Also, I tried several times and see that first part size never greater than 1019 bytes.

**Comment by slandelle** [comment]
First, please use the mailing for questions, not the bug tracker.

Then, you don't and never had any control over how NIO buffers are read. You can't assume polling chunks that are send in the application layer on the server side get sent into one single TCP frame over the network, nor how they are read on the client side.
In short, ResponseBodyParts are NIO buffer chunks, and you can't assume any framework can reassemble them for you. You are the only one who have this logic.

**Comment by vvsh** [comment]
@slandelle, I got. But, why is it working well using the ning library with netty provider?
