### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lphgithub** [AsyncHttpClient/async-http-client#1326]
ystem.err: org.apache.http.client.HttpResponseException: Internal Server Error
01-17 11:59:57.943 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at com.loopj.android.http.AsyncHttpResponseHandler.sendResponseMessage(AsyncHttpResponseHandler.java:404)
01-17 11:59:57.943 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:161)
01-17 11:59:57.943 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:178)
01-17 11:59:57.943 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:109)
01-17 11:59:57.943 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-17 11:59:57.944 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-17 11:59:57.944 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-17 11:59:57.944 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-17 11:59:57.944 17931-17931/com.cairh.app.trust.zhongliang.test3 W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by slandelle** [comment]
https://github.com/loopj/android-async-http/issues/876
