### ISSUE TITLE
HttpResponseStatus does not need AsyncHttpClientConfig in constructor

### ISSUE THREAD

**Issue by wsargent** [AsyncHttpClient/async-http-client#1340]
Looking at the HttpResponseStatus, it's an abstract class that requires a config passed in the constructor:

https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/HttpResponseStatus.java#L29

However, the two implementing classes, Netty and HttpStatusWrapper do not make use of Config and it's not exposed in the API.  

```
        public HttpStatusWrapper(HttpResponseStatus wrapper, String statusText, int statusCode) {
            super(wrapper.getUri(), (AsyncHttpClientConfig)null);
            this.wrapped = wrapper;
            this.statusText = statusText;
            this.statusCode = statusCode;
        }
```

It'd be nice if the config was not required in the abstract class constructor. :-)

**Comment by slandelle** [comment]
Nice catch, thanks!

BTW, suggestions for breaking changes/clean for AHC 2.1 are gladly welcome :)
