### ISSUE TITLE
DefaultAsyncHttpClient does not exist

### ISSUE THREAD

**Issue by JamesTheHacker** [AsyncHttpClient/async-http-client#1351]
I think the Github docs are out of date.

They say to import `com.asynchttpclient.*` but that namespace does not exist. It's `com.ning`. When importing this namespace `DefaultAsyncHttpClient` does not exist.

I installed using the XML provided on MVN Repository: https://mvnrepository.com/artifact/com.ning/async-http-client/1.9.40

Am I doing something wrong? Do any up to date docs exist?

**Comment by slandelle** [comment]
Please have a bette look at the README, you're using the old AHC1. AHC2 has a different groupId and root package.

Then, please use the Google Group (see README) for questions, not the bugtracker.

**Comment by JamesTheHacker** [comment]
Where in the `README.md` does it mention the example code is for version 1? If the documentation is not up to date, or confusing, it's an issue. Hence why I filed one.
