### ISSUE TITLE
HTTPS Timeout

### ISSUE THREAD

**Issue by mahieddine** [AsyncHttpClient/async-http-client#1352]
Hi, 
First think for this wonderful library, i'm using it since a while now without any issue.
Right now, i'm migrating an old project and i'm using async http 2.0.28
The problem is that i couldn't make https requests (Timeout),
What i'm doing wrong ?
> AsyncHttpClient asyncHttpClient = new DefaultAsyncHttpClient();
> Future<Response> f = asyncHttpClient.prepareGet("https://www.google.com").execute();
> Response r = f.get();

Thank you !

**Comment by slandelle** [comment]
See Config object: https://github.com/AsyncHttpClient/async-http-client#configuration

Then, please use the mailing list for questions, not the bug tracker.

**Comment by mahieddine** [comment]
I've read that, but the issue is that with an HTTPS URL, i got timeout while with a HTTP URL it works correctly. i've posted my issue on the mailing list
