### ISSUE TITLE
Many active connections after updating from 1.9.31 to 2.0.28

### ISSUE THREAD

**Issue by maciej-kapusta** [AsyncHttpClient/async-http-client#1358]
Hello
Recently my team has been updating the async-http-client to a newer version, but we noticed some performance degradation after completing the process. Namely the p99 jumped by 25%, and mean by 10%. We also got more errors and timeouts.

We investigated further and we noticed that there are more active connections now on the box where we use the client. It seems that the connections are not pooled properly. There is either something wrong with our configuration, or with the new version of the client.

The trunkated output for `sar -n TCP,ETCP 1 3` on the machine with the old and the new version.

1.9.31:
Average:     active/s passive/s    iseg/s    oseg/s
Average:        **14,53**      1,38  17849,48  17934,60

 2.0.28:
Average:     active/s passive/s    iseg/s    oseg/s
Average:      **1292,23**      1,69  12656,08  12582,43

My configuration for the new client:

```
 DefaultAsyncHttpClientConfig.Builder configBuilder = new DefaultAsyncHttpClientConfig.Builder()
                .setConnectTimeout(1000)
                .setRequestTimeout(500)
                .setFollowRedirect(false)
                .setMaxRequestRetry(0)
                .setMaxConnectionsPerHost(200)
                .setMaxConnections(1000)
                .setConnectionTtl(300_000)
                .setPooledConnectionIdleTimeout(300_000)
                .setSoReuseAddress(true)
                .setKeepAlive(true)
                .setIoThreadsCount(ioThreads);
```

**Comment by slandelle** [comment]
Can you please provide a reproducer?

**Comment by maciej-kapusta** [comment]
You mean like a piece of code that would exactly reproduce the issue?

We only observed this in production, under load. At the time we saw that we were sending about 1500 requests per second calling about 20 different endpoints. I'll try to reproduce it with JMH and let you know how it went.

By the way, this was a quick response.

Thanks,

MK

**Comment by slandelle** [comment]
Not sure JMH is really suited, a simple loop would be better :)
But yeah, I would need a sample of both the client side, and the server one, so I can investigate the behavior you experience.

Thanks

**Comment by maciej-kapusta** [comment]
We managed to reproduce the issue. It seems that when talking to certain servers of our partners the connections are not reused. It only happens on the new client, not the old one. Unfortunately we do not know what causes it. Maybe we configured something wrong?

Also we cannot share the servers, as they are not ours.

**Comment by slandelle** [comment]
> Also we cannot share the servers, as they are not ours.

I'm sorry, but there's nothing I can do until I can reproduce.

You'll have to investigate yourself.

Another solution would be to contract with my company so I can work under NDA.

**Comment by maciej-kapusta** [comment]
It turns our that when we call `.setKeepAlive(true)` in DefaultAsyncHttpClientConfig.Builder the new client does not send the Connection: keep-alive header. It should be a quick fix.

**Comment by slandelle** [comment]
Nay, one shouldn't send a `Connection: keep-alive` request header when using HTTP/1.1 as it's the default/expected behavior. AHC would send it when using HTTP/1.0.

**Comment by maciej-kapusta** [comment]
I see your point, but it is a bit of a surprise.

**Comment by slandelle** [comment]
You can check what your browser does, it does exactly what I described.
Then, it seems that your server is broken and doesn't comply with HTTP/1.1 spec.

**Comment by maciej-kapusta** [comment]
I agree. Unfortunately we have no control over the servers.
