### ISSUE TITLE
ListenableFuture#addListener with null executor throws NPE

### ISSUE THREAD

**Issue by joedj** [AsyncHttpClient/async-http-client#1369]
ListenableFuture#addListener javadoc says:

    * Executor can be <code>null</code>, in that case executor will be executed
    * in the thread where completion happens.

However, this doesn't work with the `NettyResponseFuture` implementation:

    java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.screenExecutor(CompletableFuture.java:415)
	at java.util.concurrent.CompletableFuture.whenCompleteAsync(CompletableFuture.java:2142)
	at org.asynchttpclient.netty.NettyResponseFuture.addListener(NettyResponseFuture.java:257)

I'm happy to submit a pull request for this issue, if you can indicate how you want it fixed (i.e. update the documentation to reflect current behavour, or change behaviour to match documentation).

**Comment by slandelle** [comment]
Hi @joedj 

Thanks for reporting! I guess it would be better to try to implement what the doc says. But if it turns out to be difficult, let's update the doc.
And sure, PR welcome :)
