### ISSUE TITLE
Option to ignore authentication?

### ISSUE THREAD

**Issue by bahrmichael** [AsyncHttpClient/async-http-client#1383]
Is there an option to disable any authentication handling and plainly forward/return the request?

We currently use the AsyncHttpClient to create a proxy. The client and server, between which the proxy is placed, use digest authentication.

```
String newUrl; // new target URL
HttpServletRequest request; // the initial request

CompletableFuture<ResponseEntity> promise = client
                .prepareGet(newUrl)
                .setHeaders(getHeaders(request))
                .execute()
                .toCompletableFuture()
                .thenApply(resp -> createNewResponse(resp));
```

It appears that the AsyncHttpClient interferes with the digest authentication, preventing the client from receiving the expected result. With the synchronous ApacheHttpClient we do not have this issue: The request can be handed back to the client which the gets the expected result.

Here's the rundown of what we saw:

1. Client requests resource
2. Server returns 401 digest
3. Client submits digest
4. Server returns 401 digest
5. Loop: Client submits digest
6. Server returns 401 digest
7. ...

**Comment by slandelle** [comment]
If you don't configure a Realm, AHC should just return the plain response.
If it doesn't, please provide a reproducer.

**Comment by bahrmichael** [comment]
The client is `client = new DefaultAsyncHttpClient();`. Without any client- or realm-configuration. Will provide a reproducer later.

**Comment by bahrmichael** [comment]
I was not able to build the reproducer yet. Will look into it after the holidays. Thanks for reacting so quickly!

**Comment by slandelle** [comment]
Closing for now. Please ping if you can provide a reproducer.
Cheers.

**Comment by bahrmichael** [comment]
The issue was on our side. You can forget this :)
