### ISSUE TITLE
Question regard to request timeout and streaming

### ISSUE THREAD

**Issue by Noodle05** [AsyncHttpClient/async-http-client#1387]
I'm trying to stream a big file from a website and process it. So I use BodyDeferringAsyncHandler to create an InputStream to feed in to processor. The whole process take pretty long time (from 15 minutes to 30 minutes)

However I keep getting request timeout after 1 minute even I'm still reading data. Of cause I can set RequestTimeout value to a big number, but it doesn't make sense to timeout request while I'm still reading data.

Is this by design? or I mis-config AsyncHttpClient?

Thanks

**Comment by slandelle** [comment]
Request timeout is from request start to response end, so indeed, you have to increase it to match your upload time.

Please use the google group for questions, not the bug tracker.
