### ISSUE TITLE
Lost headers in debug logs

### ISSUE THREAD

**Issue by azhuchkov** [AsyncHttpClient/async-http-client#1390]
I use compression enforcement in the client configuration and it perfectly works. But debug headers dumps do not contain `Content-Encoding: gzip` response header when **tcpdump** shows that it actually was. 

By the way, is there a way to skip response decoding? For example, if i want to save gzip'ed content or just skip it in my performance test.

Thanks.

**Comment by slandelle** [comment]
> But debug headers dumps do not contain Content-Encoding: gzip response header

Of course, because it's removed once the entity body gets decompressed, otherwise you wouldn't get a valid HTTP entity (actual body content wouldn't be aligned with Content-Encoding header).

You can keep the original Content-Encoding header with the `keepEncodingHeader` config option.

> By the way, is there a way to skip response decoding?

No
