### ISSUE TITLE
Provide original exception in WebSocketHandler#handleException

### ISSUE THREAD

**Issue by makcon** [AsyncHttpClient/async-http-client#1392]
It is impossible to recognize top level exception in case of an internal error after - 
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/handler/WebSocketHandler.java#L145

**Comment by slandelle** [comment]
What's you're problem exactly? Could you provide a reproducer demonstrating your use case, please?

**Comment by makcon** [comment]
Recently we tried to send big content using web sockets. And we got null param in `WebSocketListener.onError(Throwable t)` After deep debugging we found we exceeded default  `maxFramePayloadLength` ("Max frame length of " + this.maxFramePayloadLength + " has been exceeded.") We spent couple of hours to realized it. If you would provide original exception instead of `e.getCause()` we see the message in log.

**Comment by slandelle** [comment]
Makes sense. Thanks!
