### ISSUE TITLE
Support WebSocket compression

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#1394]

**Comment by NullP0inter** [comment]
I am attempting to get permessage-deflate working with AsyncHttpClient and Netty by manually adding in certain handlers to the channel pipeline but have run into various issues and not sure if it can even work with the current AHC code.  I just noticed this enhancement and wasn't sure when the ETA would be or if you had any short term workarounds for getting this to work for me?

**Comment by slandelle** [comment]
@NullP0inter No, it's not implemented yet. Contributions welcome!

**Comment by slandelle** [comment]
@NullP0inter Note that the feature described here is to support Compression Extensions, as described in RFC7692).

**Comment by NullP0inter** [comment]
I found my issues out and figured I would share as a workaround until there is a AHC configuration that does this for us.  I simply had added my channels in the wrong order

Using AHC 2.1.0 and Netty 4.1.19.Final you can enable web socket permessage-deflate extension by something like the following into your AsyncHttpClientConfig

```Java
DefaultAsyncHttpClientConfig.Builder builder = new DefaultAsyncHttpClientConfig.Builder();

Consumer<Channel> compressionConfigurer = new Consumer<Channel>() {
	@Override
	public void accept(Channel ch) {
		// Need to overwrite built in decoder to enable extentions - second parameter == true
		ch.pipeline().addBefore(AHC_WS_HANDLER, WS_DECODER_HANDLER + "-with-extentions", new WebSocket08FrameDecoder(false, true, 2147483647));
		ch.pipeline().addAfter(WS_DECODER_HANDLER + "-with-extentions", "per-message-deflate-handler", WebSocketClientCompressionHandler.INSTANCE);
	}
};

AsyncHttpClientConfig config = builder.setWsAdditionalChannelInitializer(compressionConfigurer).build();
```

**Comment by slandelle** [comment]
Yeah, it would be pretty simple to have built-in support. Most of the work would actually be to write the server-side of the test :)

Then, as it would require a minor AHCConfig change to enable this feature, I would rather wait a few weeks before releasing AHC 2.2 as I've just released 2.1.0.

**Comment by slandelle** [comment]
Would be great!

I need to update the README and require that the commit message matches Netty's template: https://netty.io/wiki/writing-a-commit-message.html.

The test suite mostly uses Jetty for server peer. I don't know if it supports WebSocket compression, but there's a chance it does. Ckeck `ByteMessageTest`.

Cheers!

**Comment by NullP0inter** [comment]
Jetty should be good depending on the version.  I am actually using Jetty 9.2 for my server setup at work that we are using our application with AHC to connect to.
