### ISSUE TITLE
Wire logging misses multiple headers

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#1400]
Troubleshooting of a proxy related issue revealed that the logging of a response misses multiple headers. In this case the proxy was sending two "Proxy-Authenticate": "Negotiate" and "NTLM", but only the first was seen. Here's the comparison between the logs and a TCP dump:
DEBUG 2017-04-10 14:03:09,284 [[prototype_lexis_wsdl].http.requester.HTTP_Request_Configuration.worker(4)] com.ning.http.client.providers.grizzly.AhcEventFilter: RESPONSE: HttpResponsePacket (
  status=407
  reason=Proxy Authentication Required
  protocol=HTTP/1.1
  content-length=1215
  committed=false
  headers=[
      proxy-authenticate=NEGOTIATE
      cache-control=no-cache
      pragma=no-cache
      content-type=text/html; charset=utf-8
      proxy-connection=close
      connection=close
      content-length=1215]
)

Reassembled TCP (1467 bytes):
0000  48 54 54 50 2f 31 2e 31 20 34 30 37 20 50 72 6f   HTTP/1.1 407 Pro
0010  78 79 20 41 75 74 68 65 6e 74 69 63 61 74 69 6f   xy Authenticatio
0020  6e 20 52 65 71 75 69 72 65 64 0d 0a 50 72 6f 78   n Required..Prox
0030  79 2d 41 75 74 68 65 6e 74 69 63 61 74 65 3a 20   y-Authenticate: 
0040  4e 45 47 4f 54 49 41 54 45 0d 0a 50 72 6f 78 79   NEGOTIATE..Proxy
0050  2d 41 75 74 68 65 6e 74 69 63 61 74 65 3a 20 4e   -Authenticate: N
0060  54 4c 4d 0d 0a 43 61 63 68 65 2d 43 6f 6e 74 72   TLM..Cache-Contr
0070  6f 6c 3a 20 6e 6f 2d 63 61 63 68 65 0d 0a 50 72   ol: no-cache..Pr
0080  61 67 6d 61 3a 20 6e 6f 2d 63 61 63 68 65 0d 0a   agma: no-cache..
0090  43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 65   Content-Type: te
00a0  78 74 2f 68 74 6d 6c 3b 20 63 68 61 72 73 65 74   xt/html; charset
00b0  3d 75 74 66 2d 38 0d 0a 50 72 6f 78 79 2d 43 6f   =utf-8..Proxy-Co
00c0  6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d   nnection: close.
00d0  0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f   .Connection: clo
00e0  73 65 0d 0a 43 6f 6e 74 65 6e 74 2d 4c 65 6e 67   se..Content-Leng
00f0  74 68 3a 20 31 32 31 35 0d 0a 0d 0a 3c 48 54 4d   th: 1215....

**Comment by slandelle** [comment]
@afelisatti Please, pretty please! AHC1 and its Grizzly provider have reached end of life, period.
There will never ever be any bug fixes, new features or new release for those from this repository.
If you Mulesoft people really don't want to migrate to AHC2, or move to another library, please consider forking, maintaining yourself and eventually publishing in your own groupId.

**Comment by afelisatti** [comment]
Hey, @slandelle, we have our own logging solution without this defect, I just thought you might appreciate this pointed out as it may affect AHC2 as well. I'm sorry for not making that clear enough, we just appreciate ourselves when our community helps out but we will reconsider opening this sort of issues if it's a problem to you. Thanks.

**Comment by slandelle** [comment]
> I just thought you might appreciate this pointed out as it may affect AHC2 as well

Thanks then. But actually, the Netty and the Grizzly providers in AHC1 almost didn't share any code, just the API layer. That really was the core issue with AHC1: 2 very different underlying libraries, with different features, different issues and different maintainers trying to fit in a common API and schedule. Worst nightmare ever.
So there's no way to tell beforehand if a Grizzly provider issue could hit AHC2.
AHC2 does have [wire logging when trace level is enabled](https://github.com/AsyncHttpClient/async-http-client/blob/98bef40637212fc1c64ec47b1b11bb1a15144704/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L230-L232).
Regards
