### ISSUE TITLE
Support MDC/ThreadLocal variable propagation across async contexts

### ISSUE THREAD

**Issue by Diagoras** [AsyncHttpClient/async-http-client#1408]
As far as I can tell, in the current version of AsyncHttpClient there's no way to propagate the ThreadLocal context that [MDC](https://logback.qos.ch/manual/mdc.html) depends on. I'm forced to block on operations in order to keep MDC data accessible, which defeats the purpose of this client. Ideally, there'd be a user-configurable or automatic way to pass the ThreadLocal variables from each thread to the next - [something like how it can be propagated by a properly configured ExecutionContext in Scala](http://code.hootsuite.com/logging-contextual-info-in-an-asynchronous-scala-application/?_sm_au_=iVVkq5MM5S1sr6vR).

Let me know if you need any more detail.

**Comment by slandelle** [comment]
AHC already has tons of AsyncHandler implementations with tons of hooks, so I don't have to add such hack all over the place in AHC code.

But you can implement the same technique in your own AsyncHandler implementation: just store your MDC in the constructor, and set it back when you calling onCompleted and clean it afterward.

**Comment by Diagoras** [comment]
@slandelle Hmm, alright. I'll give that a shot and let you know how it goes.

**Comment by Diagoras** [comment]
@slandelle You're right, that does do it. Unfortunately, the MDC context isn't propagated into the AsyncHttpClient/Netty thread pool that logs the request/response, but I can live without that. Thanks for the help.
