### ISSUE TITLE
Inactive channel causes Future never completes

### ISSUE THREAD

**Issue by XiaochunLU** [AsyncHttpClient/async-http-client#1417]
We're using AHC 2.0.32.  When the following logs appear, calling request Future#get() will be blocked forever, even if we set connectTimeotu/requestTimeout/readTimeout on AsyncHttpClientConfig.

```
[DEBUG] [2017-05-22 10:41:43,990] [AsyncHttpClient-2-2] [org.asynchttpclient.netty.handler.HttpHandler] - Channel Closed: [id: 0xf70f44a0, L:/10.1.2.135:57118 ! R:proxy.abuyun.com/139.129.199.35:9010] with attribute INSTANCE
[DEBUG] [2017-05-22 10:41:43,992] [AsyncHttpClient-2-1] [org.asynchttpclient.netty.handler.HttpHandler] - Channel Closed: [id: 0x482f1d3b, L:/10.1.2.135:57117 ! R:proxy.abuyun.com/139.129.199.35:9010] with attribute INSTANCE
[DEBUG] [2017-05-22 10:41:43,993] [AsyncHttpClient-2-4] [org.asynchttpclient.netty.handler.HttpHandler] - Channel Closed: [id: 0xca791b36, L:/10.1.2.135:57120 ! R:proxy.abuyun.com/139.129.199.35:9010] with attribute INSTANCE
```

It this log normal?  We're working on a crawler so all requests are sent through proxies.  The proxy server seems unstable that it will occasionally close all connections.

I've tried to debug into the code where the log prints in AsyncHttpClientHandler#channelInactive().  This line is suspicious:
```
Object attribute = Channels.getAttribute(channel);
```
It seems the attribute is just a plain String of value "INSTANCE", and thus by passed all later logic.

**Comment by XiaochunLU** [comment]
Now we're using Future#get(long, TimeUnit) to work around this problem.  We set timeout to 60 seconds. 
When the timeout occurs, the request completes successfully with the correct response. This is very strange...

**Comment by slandelle** [comment]
Can you please provide a reproducer?

**Comment by XiaochunLU** [comment]
I don't know how to reproduce it programmatically...

This problem occurs in our test environment frequently **only when proxy is used and the proxy server is unstable** (the proxy server is a thirt-party product and it will close connections when there are too many concurrent requests).  We've never encountered such problem when requst directly to a site or when the proxy server is stable (when less people are using it).

**Comment by slandelle** [comment]
> I don't know how to reproduce it programmatically...

Not much I can do without a way to reproduce your problem.

Just one thing: where are you calling `Future.get()`? You definitively don't want to perform blocking calls in the IO threads (eg in the AsyncHandler) or you might end up in a dead lock similar to what you describe. AHC is primarily non blocking. What don't you use listeners/callbacks instead?

**Comment by XiaochunLU** [comment]
We don't use AsyncHandler.  We utilize `CompletableFuture` to make blocking calls and make requests retryable.  The code like below:

```
public /*abstract*/ class AbstractRetriableTask {
    protected final AsyncHttpClient httpClient = HttpClientFactory.get();

    protected final String url;
    protected final HttpOption option;
    protected final AsyncCompletionHandler handler;

    protected int maxCycleRetry;
    protected int cycleRetryCount = 0;

    **protected CompletableFuture<Response> future = new CompletableFuture<>();**

    public AbstractRetriableTask(String url, HttpOption option, AsyncCompletionHandler handler) {
        this.url = url;
        this.option = option;
        this.handler = handler;

        maxCycleRetry = option != null ? option.getMaxCycleRetry() : HttpOption.NOTSET;
        if (maxCycleRetry < 0) {
            maxCycleRetry = DEFAULT_MAX_CYCLE_RETRY;
        }
    }

    public /*abstract*/ ListenableFuture<Response> execute() {
        // setup request
        Request request = ...
        executeRequest(request);
        return new GuavaListenableFuture<>(future);
    }

    private void executeRequest(Request request) {
        httpClient.executeRequest(request, new AsyncCompletionHandlerBase())
            .toCompletableFuture()
            .whenCompleteAsync((response, t) -> {
                if (t != null) {
                    if (++cycleRetryCount < maxCycleRetry) {
                        // retry
                        BoundRequestBuilder builder = new BoundRequestBuilder(httpClient, request);
                        // do something on bulder...
                        executeRequest(builder.build());
                    } else {
                        if (handler != null) {
                            handler.onThrowable(t);
                        }
                        future.completeExceptionally(t);
                    }
                } else {
                    if (handler != null) {
                        handler.onResult(response);
                    }
                    future.complete(response);
                }
            });
    }

    ...
```

We're migrating the crawler from apache http-client to AHC. In order to speed up crawling, we optimize some of the code to use `AsyncCompletionHandler` to parallel requests for some URLs, and then using guava `Futures.successfulAsList(futures).get()` to wait for all to complete.

For CompletableFuture#whenCompleteAsync callback, as I know it is invoked on ForkJoinPool, which should not interfere with the Netty IO thread.  Is it correct?

**Comment by slandelle** [comment]
> For CompletableFuture#whenCompleteAsync callback, as I know it is invoked on ForkJoinPool, which should not interfere with the Netty IO thread. Is it correct?

Correct

Sorry, but I'm afraid you'll have to try and build a more simple reproducer so I can investigate.

**Comment by XiaochunLU** [comment]
Still proxy is the root culprit, I'll make some more investigation to see if it is possible to setup a sandbox to reproduce it.  Thanks!

**Comment by slandelle** [comment]
Closing for now. Please feel free to reopen if you can provide more information.
