### ISSUE TITLE
Implement a getter for the AsyncHttpClientConfig on AsyncHttpClient

### ISSUE THREAD

**Issue by atehrani** [AsyncHttpClient/async-http-client#1420]
The DefaultAsyncHttpClient overloaded constructor can take in a AsyncHttpClientConfig as an argument. However the interface, nor the implementation exposes a way to get the AsyncHttpClientConfig from that instance. This becomes an issue if one wants to re-create a new instance with the same config. Without the getter, this becomes difficult.

We would like to be able to do something like this

```
if (asyncHttpClient.isClosed())
{
      newAsyncHttpClient = new DefaultAsyncHttpClient(asyncHttpClient.getConfig()); // The getConfig() is the missing method that makes this not possible.
}
```

**Comment by slandelle** [comment]
Contributions welcome :)
