### ISSUE TITLE
Connections not being released after timeout

### ISSUE THREAD

**Issue by pghilardi** [AsyncHttpClient/async-http-client#1426]
Hi,

I am using the version 2.1.0-alpha1 of this library and I am facing some problems when my requests expires with timeout. The problem is that these connections are not released in the pool of connections to be reused. So I am using a max of 800 connections per host, and when 800 of my requests receive a timeout, the library will always throw the exception: Too Many Connections: 800 in all the next requests.

I think that when this library handle timeout with the exception "java.util.concurrent.TimeoutException: Request timeout to not-connected after 60000 ms" the channel is not being removed from the open channels.

See this code in the ChannelManager constructor:

```
        if (maxTotalConnectionsEnabled || maxConnectionsPerHostEnabled) {
            openChannels = new DefaultChannelGroup("asyncHttpClient", GlobalEventExecutor.INSTANCE) {
                @Override
                public boolean remove(Object o) {
                    boolean removed = super.remove(o);
                    if (removed) {
                        if (maxTotalConnectionsEnabled)
                            freeChannels.release();
                        if (maxConnectionsPerHostEnabled) {
                            Object partitionKey = channelId2PartitionKey.remove(Channel.class.cast(o));
                            if (partitionKey != null) {
                                Semaphore hostFreeChannels = freeChannelsPerHost.get(partitionKey);
                                if (hostFreeChannels != null)
                                    hostFreeChannels.release();
                            }
                        }
                    }
                    return removed;
                }
            };
            freeChannels = new Semaphore(config.getMaxConnections());
        } else {
            openChannels = new DefaultChannelGroup("asyncHttpClient", GlobalEventExecutor.INSTANCE);
            freeChannels = null;
        }
```

The method remove() from openChannels is not being called in the method closeChannel().

```
public void closeChannel(Channel channel) {

        LOGGER.debug("Closing Channel {} ", channel);
        Channels.setDiscard(channel);
        removeAll(channel);
        Channels.silentlyCloseChannel(channel);
    }
```

I am thinking if the correct code wouldn't be to change the closeChannel() implementation to:

```
public void closeChannel(Channel channel) {

        LOGGER.debug("Closing Channel {} ", channel);
        Channels.setDiscard(channel);
        removeAll(channel);
        openChannels.remove(channel);
        Channels.silentlyCloseChannel(channel);
    }
```

Summarizing, I think that the code **openChannels.remove(channel);** is missing in the closeChannel() method.

Thanks!

**Comment by slandelle** [comment]
> I am using the version 2.1.0-alpha1

Before investigating, could you please upgrade to latest 2.1.0-alpha20? There's been tons of fixes since since alpha1.

**Comment by pghilardi** [comment]
Thanks for the support!

I checked the code of version 2.1.0-alpha1 of method NettyResponseFuture.terminateAndExit() againt the same method in the version 2.1.0-alpha20 (the latest one) and I you are right, the bug is fixed in the latest version! :D

Method in 2.1.0-alpha1

```
    private boolean terminateAndExit() {
        cancelTimeouts();
        this.channel = null;
        this.reuseChannel = false;
        return isDone.getAndSet(true) || isCancelled.get();
    }
```

Method in 2.1.0-alpha20

```
private boolean terminateAndExit() {
        releasePartitionKeyLock();
        cancelTimeouts();
        this.channel = null;
        this.reuseChannel = false;
        return isDoneField.getAndSet(this, 1) != 0 || isCancelled != 0;
    }
```

The missing line releasePartitionKeyLock() is not present in the 2.1.0-alpha1 and this line releases the semaphore, so... that's it!

I will update to the latest version.

Thanks man!
