### ISSUE TITLE
Extras - Registry is getting incorrect constructor

### ISSUE THREAD

**Issue by nitinsurana** [AsyncHttpClient/async-http-client#1428]
```
Constructor<AsyncHttpClient> constructor = asyncHttpClientImplClass.getConstructor(DefaultAsyncHttpClientConfig.class);
 ```
Should be 
`.getConstructor(AsyncHttpClientConfig.class);`

Otherwise, all custom AsyncHttpClient implementations are tightly coupled to DefaultAsyncHttpClient and testing becomes difficult.

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by nitinsurana** [comment]
If you agree, I can of course submit a pull request.

**Comment by slandelle** [comment]
Thanks!
