### ISSUE TITLE
Null response when onStatus returns ABORT (2.0 only)

### ISSUE THREAD

**Issue by yuppie-flu** [AsyncHttpClient/async-http-client#1430]
# Description:
When async-http-client is used to send requests asynchronously, sometimes **onCompleted** method of **AsyncCompletionHandler** receives null responses for some unknown reason. I debugged the behavior but did not find any clues, may you can help me with that. 

# Reproducer repository:
https://github.com/yuppie-flu/async-http-client-npe

The issue is reproduced not every run, please try several times.

# Affected version
2.0.32

**Comment by slandelle** [comment]
Thanks for reporting!

Not sure when I'll be able to investigate, I'm pretty swamped atm :(
Note that 2.1.0-alpha20 seems to work fine with your sample.

**Comment by slandelle** [comment]
Seems to be related to #1350 that changed behavior for ABORT in AHC 2.1.

**Comment by slandelle** [comment]
@yuppie-flu fixed! thanks again for reporting!

**Comment by yuppie-flu** [comment]
@slandelle Thank you for the fix, when are you going to release **2.0.33**?

**Comment by slandelle** [comment]
@yuppie-flu released
