### ISSUE TITLE
asyncHandler is not unwrapped before instanceof tests

### ISSUE THREAD

**Issue by jozsefilles** [AsyncHttpClient/async-http-client#1432]
When using _ThrottleRequestFilter,_ my custom _TransferCompletionHandler_ is getting wrapped into an _AsyncHandlerWrapper._

This later fails the type check in _WriteListener_'s constructor so that _onHeadersWritten()_ is never called:
`this.progressAsyncHandler = future.getAsyncHandler() instanceof ProgressAsyncHandler ? (ProgressAsyncHandler<?>) future.getAsyncHandler() : null;`

The same might apply to the _NettyRequestSender_'s _writeRequest_ method for testing against the types _TransferCompletionHandler_ and _AsyncHandlerExtensions_.

**Comment by slandelle** [comment]
Dup of #1314, fixed in 2.1 branch (won't be in 2.0 one)

**Comment by jozsefilles** [comment]
Thanks for pointing into the right direction!
