### ISSUE TITLE
How to reset http client properties?

### ISSUE THREAD

**Issue by skilledmonster** [AsyncHttpClient/async-http-client#1441]
Is there a way to reset http client connection properties - for example - increase max connections, increase request timeout etc. 

I guess, ideally, I am looking for a way to check if there are any in flight connections, wait for all inflight connections to return, close the client, and re-init. 

Please advice.

**Comment by slandelle** [comment]
Have a look at the registry module.

Then, please use the mailing list for questions, not the bug tracker.
