### ISSUE TITLE
HttpUtils method urlEncodeFormParams Charset

### ISSUE THREAD

**Issue by keyhunter** [AsyncHttpClient/async-http-client#1444]
When the charset is not utf-8 , this code ([org.asynchttpclient.util.HttpUtils](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/util/HttpUtils.java)) will produce the wrong result

`public static ByteBuffer urlEncodeFormParams(List<Param> params, Charset charset) {
        return StringUtils.charSequence2ByteBuffer(urlEncodeFormParams0(params), charset);
    }`

This Code specifies the utf-8 encoding， and can't change, this will result in errors under other encodings(GBK etc).

**Comment by slandelle** [comment]
@keyhunter Could you provide a failing test case please?

**Comment by keyhunter** [comment]
Of course.
`
       String beEncodeValue = "中文";

        List<Param> params = new ArrayList<>();

        params.add(new Param("language", beEncodeValue));

        ByteBuffer result1 = HttpUtils.urlEncodeFormParams(params, Charset.forName("GBK"));

        ByteBuffer result2 = HttpUtils.urlEncodeFormParams(params, Charset.forName("UTF-8"));`
They all use the method urlEncodeFormParams0, so produced the same result.

But the real result is:
`
URLEncoder.encode(beEncodeValue, "GBK");// should be "%D6%D0%CE%C4";
URLEncoder.encode(beEncodeValue, "UTF-8");//should be "%E4%B8%AD%E6%96%87"
`
They are different.

**Comment by slandelle** [comment]
@keyhunter Should be fixed (even though there's room for perf improvement). Could you please check on your side?

**Comment by keyhunter** [comment]
OK, thanks.
👍
