### ISSUE TITLE
Improve Origin header handing for WebSockets

### ISSUE THREAD

**Issue by AchimKlotz** [AsyncHttpClient/async-http-client#1448]
In the NettyRequestFactory the origin header is calculated this way:
` .set(ORIGIN, "http://" + uri.getHost() + ":" + uri.getExplicitPort())//`

this is wrong for secure wss websocket request, if you for example have an request to
`wss://yourdomain.com` the origin header will be  `http://yourdomain.com:443`

The correct header should be calculated like this:
`String origin = (uri.getScheme().equals("wss") ? "https" : "http" ) +"://"+uri.getHost() +(uri.getExplicitPort() != 80 && uri.getExplicitPort() != 443 ? uri.getExplicitPort() : "");`

**Comment by slandelle** [comment]
I've just check with Chrome on `http://websocket.org/` and `Origin` header is really `http://websocket.org` when connection over `wss`.

<img width="1023" alt="capture d ecran 2017-08-03 a 13 44 51" src="https://user-images.githubusercontent.com/849197/28920625-e0c077d8-7852-11e7-8067-5051bf315674.png">

**Comment by AchimKlotz** [comment]
but not if you call **https**://websocket.org/echo.html
then the origin header is **https**://websocket.org. 
I've got the problem that a server is only reachable by https and wss and the websocket connection is rejected if the origin header is not set correctly. With Chrome this is working fine on that server
Please see also a related netty issue which has been fixed about a year ago: https://github.com/netty/netty/issues/5402
![selection_157](https://user-images.githubusercontent.com/30689030/28928441-7496256a-786d-11e7-9a80-94cae12fcb2c.png)

**Comment by slandelle** [comment]
Oh my, you're right.
So browsers use the web page for Origin o_0.

But then, as you can see, your suggestion doesn't work either: you jump can't build the Origin header from the ws(s) url as it could be a different domain (here, WebSocket domain is "echo.websocket.org" while Origin header targets "websocket.org").

The best solution would be to honor existing "Origin" header.
Then, if it's undefined, it might indeed be a good idea to use https for wss.

WDYT?

**Comment by AchimKlotz** [comment]
I think that's a sensible solution: If the "Origin" header is passed use that one, otherwise construct it like in my suggested solution. 
According to the specification https://tools.ietf.org/html/rfc6454#section-6.1 the port should be omitted if it is the standard port for the protocol:
`5.  If the port part of the origin triple is different from the
       default port for the protocol given by the scheme part of the
       origin triple:`

**Comment by slandelle** [comment]
> According to the specification https://tools.ietf.org/html/rfc6454#section-6.1 the port should be omitted if it is the standard port for the protocol

Yes, I noticed that too but didn't have time yesterday for logging the issue. This is a separate issue.

Would you mind updating your PR, please?

**Comment by AchimKlotz** [comment]
`String origin =request.getHeaders().get(ORIGIN) != null ?
                             request.getHeaders().get(ORIGIN) :
        		   (uri.isSecured() ? "https" : "http" ) +"://"+uri.getHost() +
                           ((uri.getExplicitPort() != 80 && !uri.isSecured()) || (uri.getExplicitPort() != 443 && uri.isSecured()) ? 
                    uri.getExplicitPort() : "");
        `
also attached as git diff to version 2.0.33

[header.txt](https://github.com/AsyncHttpClient/async-http-client/files/1199877/header.txt)

**Comment by slandelle** [comment]
Never used Git, huh? ;-)
