### ISSUE TITLE
Infinite stream causes OOM

### ISSUE THREAD

**Issue by czietsman** [AsyncHttpClient/async-http-client#1450]
I wanted to test the speed at which a large file can be sent so I created a little test server which consumes all data it receives and this test app which tries to send as much data as possible until it is killed.

    public static void main(String[] args) throws Exception {
        final String url = "http://" + args[0] + ":" + args[1];
        final AsyncHttpClient asyncHttpClient = new AsyncHttpClient();
        final ListenableFuture<Response> future = asyncHttpClient
                .preparePut(url)
                .setBody(new InfiniteInputStream())
                .execute();
        future.get(60, TimeUnit.SECONDS);
    }

    private static class InfiniteInputStream extends InputStream {
        @Override
        public int read() throws IOException {
            throw new IllegalStateException();
        }

        @Override
        public int read(byte[] b) throws IOException {
            return b.length;
        }
    }

PayloadGenFactory.StreamDataPayloadGenerator has the following loop which tries to fit everything into memory and fails spectacularly:

            while ((read = in.read(b)) != -1) {
                if (read > buffer.remaining()) {
                    buffer = mm.reallocate(buffer, buffer.capacity() + 512);
                }
                buffer.put(b, 0, read);
            }

Is there a better way to achieve the same functionality or is Grizzly just not suited for sending large payloads?

**Comment by slandelle** [comment]
Grizzly? It seems you're using AHC1, which is reached on of life.
Please upgrade if possible (as AHC2 no longer support Grizzly but only Netty).
