### ISSUE TITLE
Use a custom DNS Name resolver

### ISSUE THREAD

**Issue by fistons** [AsyncHttpClient/async-http-client#1463]
I'm using AsyncHttpClient in my project, along side with other Http client and I would like to use a custom DNS Resolver (something like google's 8.8.8.8) **only for** AsyncHttpClient.

Is there a way to do that easily?

**Comment by slandelle** [comment]
Yes, you can pass a Netty DNS name resolver in the AHC config. Check Netty for the API.
Also, please use the mailing list for questions, not the bug tracker.
