### ISSUE TITLE
AsyncHttpClient - 2.0.35 - Requests getting randomly timed out

### ISSUE THREAD

**Issue by kushal-tracxn** [AsyncHttpClient/async-http-client#1464]
I am using async http client to download some bunch of websites. Following is the skeleton of my code.On downloading around 20k websites, about 100-150 random websites, gets wrongly timed out every time [Also cross checked with wget]. 
Observed that "Request timeout after x seconds" are correct responses but "Connection timed out" responses are false sometimes.  I have tried this with multiple size of thread pool/time outs.
This is very unreliable for my application. Any idea why this is happening?

```
AsyncHttpClientConfig cf = new DefaultAsyncHttpClientConfig.Builder().setMaxRequestRetry(5).setKeepAlive(true).build()
final AsyncHttpClient asyncHttpClient = new DefaultAsyncHttpClient(cf);
ExecutorService pool = Executors.newFixedThreadPool(threadPool)
for (message in messageList) {
        final String urlString = message;
        pool.execute(new Runnable() {
            @Override
            void run() {
                BoundRequestBuilder request = asyncHttpClient.prepareGet(urlString);
                request.setHeader("User-Agent", "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0");
                request.setHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
                request.setHeader("Accept-Language", "en-US,en;q=0.5");
                request.setHeader("Accept-Encoding", "utf-8");
                request.setRequestTimeout(60000)

                @Override
                public String onCompleted(Response response) throws Exception {
                    String.valueOf(response.getStatusCode());
                }

                @Override
                public void onThrowable(Throwable t)

            }
        }
    })
}
```

**Comment by slandelle** [comment]
This is not an AHC bug, more likely a network issue. Check your network (avoid poor networks such as low quality WiFi) and any software that might mess up with it, such as antivirus.

If you have to live with those connectivity issues, implement some retry.

Now, please use the Google Group for questions, not the bug tracker.

**Comment by kushal-tracxn** [comment]
This code is being run from an large aws instance with enough cpu/network/memory bandwidth. Have tried the similar exercise for 10k - 500k domains with multiple iterations for the same batch size as well. 
This was done with monitoring all network and machine resources so as to keep a check on the resource being consumed. And since for a specific batch size the website being timed out are different on each iteration, it looks like a bug to me. I have manually verified all the timed out websites and most of them send successful responses on every call.

Yes some retry logic can be tried out, but it still unclear why the timeouts are happening in the first place.Posted on the google group as well but did not get any response, hence opted for the bug tracker.
