### ISSUE TITLE
async-http-client conflicts with librarys that use netty

### ISSUE THREAD

**Issue by hope4555** [AsyncHttpClient/async-http-client#1465]
Since DefaultChannelId.java and ChannelId.java were copied from an older build of netty, 
projects that use netty with newer versions are breaking

https://github.com/AsyncHttpClient/async-http-client/tree/2.0/client/src/main/java/io/netty/channel

Example: using "async-http-client" with "org.apache.qpid" (that also is dependant on netty) is broken

**Comment by slandelle** [comment]
* AHC 2.0 -> Netty 4.0
* AHC 2.1 -> Netty 4.1

**Comment by zvozin** [comment]
Is there a good reason Async HTTP Client includes io.netty classes? It has rippling compatibility repercussions all across the ecosphere?

**Comment by slandelle** [comment]
@zvozin See [here](https://github.com/gatling/gatling/issues/3369#issuecomment-338896594) for details. Don't mess up with dependency versions, period.

**Comment by zvozin** [comment]
Your backport is broken - it’s missing method(s) - which is causing a problem with some Netty 4.1-using libraries.

The more apt process would have been to port the functionality into org.async. There’s no good reason for async client to include an io.netty class.

**Comment by slandelle** [comment]
@zvozin I have no idea how to make you understand that AHC 2.0 is not compatible with Netty 4.0 as intended and that if you want Netty 4.1 you must upgrade to AHC 2.1.

Freezing this thread to put an end to this pointless discussion.
