### ISSUE TITLE
PerRequestRelative302Test fails, since microsoft.com now uses HTTPS

### ISSUE THREAD

**Issue by gerdriesselmann** [AsyncHttpClient/async-http-client#1470]
Microsoft.com has been switched to HTTPS lately, so any redirect goes to 

```
https://www.microsoft.com:443
```

not 

```
http://www.microsoft.com:80
```

PerRequestRelative302Test therefore fails.

**Comment by gerdriesselmann** [comment]
There is a pull request fixing this: #1471

**Comment by slandelle** [comment]
Thanks for contributing, but AHC 1 has reached end of life one year ago and no further work will ever happen there.
This issue has already been fixed on both 2.0 and master branch.

Regards
