### ISSUE TITLE
Unable to download multiple urls in parallel

### ISSUE THREAD

**Issue by engineerkushal** [AsyncHttpClient/async-http-client#1473]
I am trying to download multiple urls in parallel using the ahc client. The problem I am facing is that only 8-10 requests get submitted and response starts coming in. Hence I am not able to leverage the total network bandwidth and speed. Is this normal ahc behaviour. If no which parameter should be tuned so that all requests get submitted in parallel. 
Average size of my url list is 5000.

Following is the current sample response for my code. Instead of this  I want the code and to submit all requests in parallel togetherl, so that my primary executing thread is not blocked when the responses come in.

[Current Behaviour]
Preparing and sending request : url1
Preparing and sending request : url2
Preparing and sending request : url3
Preparing and sending request : url4
Preparing and sending request : url5
Preparing and sending request : url6
Preparing and sending request : url7
SUCCESS
SUCCESS
SUCCESS
Preparing and sending request : url8
Preparing and sending request : url9
Preparing and sending request : url10
Preparing and sending request : url11
Preparing and sending request : url12
FAILURE
SUCCESS
SUCCESS
Preparing and sending request : url13
Preparing and sending request : url14

[Expected Behaviour]
Preparing and sending request : url1
Preparing and sending request : url2
Preparing and sending request : url3
Preparing and sending request : url4
Preparing and sending request : url5
Preparing and sending request : url6
Preparing and sending request : url7
Preparing and sending request : url8
Preparing and sending request : url9
Preparing and sending request : url10
Preparing and sending request : url11
Preparing and sending request : url12
Preparing and sending request : url13
Preparing and sending request : url14
'
'
Preparing and sending request : url5000
[SUCCESS]
[SUCCESS]
[SUCCESS]
[SUCCESS]
[SUCCESS]
[FAILURE]
[FAILURE]
[SUCCESS]
[SUCCESS]

```
for(url in urlList){
  AsyncCompletionHandler asyncCompletionHandler = new AsyncCompletionHandler<Void>() {
    onCompleted(Response response){
    logger.debug("[SUCCESS] response.getUri().toString()")
    }

    onThrowable(Throwable t){
    logger.error("[ERROR] t.getMessage()")
    }
  }

  logger.debug("Preparing and sending request : " + url)
  BoundRequestBuilder request = asyncHttpClient.prepareGet(url)
  request.setHeader("User-Agent", userAgent)
  request.setHeader(CrawlerConfigUtil.REQUEST_URL, url)
  request.setHeader(property, value);
  request.setRequestTimeout(requestTimeout)
  final ListenableFuture<Void> future = request.execute(asyncCompletionHandler)
}
```

**Comment by slandelle** [comment]
Please use the mailing list for questions. The bug tracker is only for issues.
