### ISSUE TITLE
Streaming Large files / Use as Proxy

### ISSUE THREAD

**Issue by dblevins** [AsyncHttpClient/async-http-client#1474]
We are using this client library to implement a proxy.  (note, not talking to a proxy, we are the proxy).

Ideally when reading large files or gigabytes long streams we'd like to not have much buffered in memory and simply write it to the caller when new bytes are available.  I.e. make the request using the AsyncHttpClient, read the headers, do our part, send our transformed response headers to our caller, then "get out of the way" and have some code that takes response body bytes from AsyncHttpClient as they come in and we write them our caller.

Do you have any pointers on if this is possible or where we might make a contribution?

**Comment by slandelle** [comment]
Looks like plain old `AsyncHandler` to me. Am I missing something?

Then, please use the mailing list for questions, not the bug tracker which is for... bugs.

**Comment by slandelle** [comment]
Idle, closing for now
