### ISSUE TITLE
ver 1.9.29 not support TLS v1.2?

### ISSUE THREAD

**Issue by kazushima** [AsyncHttpClient/async-http-client#1475]
I 'm using async-http-client ver1.9.29 for http-request.
When I requested to a server , The following error occurred.
`
java.security.cert.CertificateException: No subject alternative DNS name matching <hostname> found.
`

Next, I changed jar-file to 2.0.24, and requested. This request was success.
After that,  I got the information.
The target server can be connected with only TLS 1.2.

If you know, please tell me that supported TLS version of asyc-http-clinet ver1.9.29.

Best Regard.

**Comment by slandelle** [comment]
Sorry, but AHC 1 has reached end of life more than one year ago. It's no longer maintain, and I don't want to even try remembering how things work and didn't work back then.
Please upgrade to AHC 2.

Then, next time, please use the mailing list for questions. The bug tracker is only for bugs and feature requests.

**Comment by kazushima** [comment]
Thanks for your comment.
Sorry.It was inappropriate.

**Comment by slandelle** [comment]
No problem :)
