### ISSUE TITLE
Is there a way to have a synchronous client?

### ISSUE THREAD

**Issue by ramswaroop** [AsyncHttpClient/async-http-client#1478]
Something like:
```
AsyncHttpClient asyncHttpClient = new DefaultSyncHttpClient();
```
would be great or if this doesn't look good, we can set the property in Config Builder.

**Comment by slandelle** [comment]
It doesn't make sense. AHC is non blocking at its core, so it doesn't need to decorate a blocking client with an async layer that delegates to an ExecutorService. `execute` returns a `Future` that you can wait for in a blocking way with `get`.
