### ISSUE TITLE
Consider upgrade netty to 4.1

### ISSUE THREAD

**Issue by mrniko** [AsyncHttpClient/async-http-client#1480]
According to issue below netty 4.0 reach EOL in 2018. Please consider update to 4.1 version

https://github.com/netty/netty/issues/7439

**Comment by slandelle** [comment]
Please check the mailing list for current discussion.

**Comment by slandelle** [comment]
And AHC 2.1 is already available in beta (as I answered in the Netty thread you mentionned). feedback welcome.
