### ISSUE TITLE
High CPU usage and file descriptors leak after load

### ISSUE THREAD

**Issue by Kshekhovtsova** [AsyncHttpClient/async-http-client#1481]
After some load (~800 rps for 6 minutes) on http(s) stub through AsyncHttpClient java process still consumes CPU and file descriptors. This bug is not reproducing every time (e.g. once for 5 times) and it could reproduce on less rps but on more long-term load. 
AsyncHttpClient version is 2.0.37
JVM version:
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```
OS version:
```
$ cat /proc/version
Linux version 2.6.32-504.1.3.el6.x86_64 (mockbuild@c6b9.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #1 SMP Tue Nov 11 17:57:25 UTC 2014
```
Amount of file descriptors of java process after load (were not decreased):
```
$ lsof -p 61649 | wc -l
11292
```
CPU usage after load:
```
top - 12:16:37 up 79 days, 34 min,  2 users,  load average: 1.99, 1.95, 1.93
Tasks: 121 total,   1 running, 120 sleeping,   0 stopped,   0 zombie
Cpu(s): 50.4%us,  0.1%sy,  0.0%ni, 49.5%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   8053548k total,  4987844k used,  3065704k free,   147548k buffers
Swap:   524284k total,        0k used,   524284k free,  1544732k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
61649 user      20   0 5781m 1.3g  13m S 201.6 17.1 183:50.26 java
```
I attached load test sources and Java Flight Recording for 1 min after load too.
[ahc-load.zip](https://github.com/AsyncHttpClient/async-http-client/files/1538799/ahc-load.zip)
[flight_recording_192168141893666_1.zip](https://github.com/AsyncHttpClient/async-http-client/files/1538801/flight_recording_192168141893666_1.zip)

**Comment by slandelle** [comment]
Could you please upgrade to AHC 2.1.0-RC1 and report if you can still reproduce?

**Comment by Kshekhovtsova** [comment]
Okay, I'll try.

**Comment by slandelle** [comment]
Also, you must close your AHC instance when your test is done, otherwise you'll leak threads and connections.

**Comment by Kshekhovtsova** [comment]
In test - yes, I must. But what should I do in my http server (netty too) which is doing http requests through AHC? I can't close AHC at the middle of the load on my server. I enabled conn. pooling but it seemed not helped much with amount of connections.

**Comment by Kshekhovtsova** [comment]
Thanks for response about release candidate version. I tried it and I think it got better.

**Comment by slandelle** [comment]
> In test - yes, I must. But what should I do in my http server (netty too) which is doing http requests through AHC? I can't close AHC at the middle of the load on my server. I enabled conn. pooling but it seemed not helped much with amount of connections.

Indeed, but if the lsof value you reported was with the client you provided, it would explain such large amount.

> Thanks for response about release candidate version. I tried it and I think it got better with connections. But now I got some memory issues.

Please provide a full reproducer: client + server. And no Kotlin please. I'm willing to help but don't have the cycles to lose time with a language I don't use.

**Comment by Kshekhovtsova** [comment]
> Please provide a full reproducer: client + server. And no Kotlin please.
Okay, I wanted to rewrite it on Java too, but hadn't much time for that. I'll add Java sources some time later.

**Comment by slandelle** [comment]
> But now I got some memory issues.

You're probably writing too fast. Instead of sleeping for some nanoseconds after sending a request, you'd be better with a queue and scheduling next request in whenComplete.

**Comment by slandelle** [comment]
@Kshekhovtsova gentle ping

**Comment by slandelle** [comment]
closing for now
feel free to ping if you happen to have more information
