### ISSUE TITLE
Contents of HttpResponseBodyPart truncated to 8K

### ISSUE THREAD

**Issue by rudivk** [AsyncHttpClient/async-http-client#1482]
I am using the AsyncHttpClient to subscribe to events published by a remote service. The remote service is sending a lot of data under certain circumstances. The event is a properly formatted JSON object that I subsequently attempt to parse.
I noticed that parse errors were occurring during the handling of the events and found that the event data, i.e. the bytes that I get from the HttpResponseBodyPart object is 8192bytes in size and stops somewhere in the middle of the JSON object. This obviously explains the parse errors. The number of bytes that I get align pretty well a power of 2 (exactly 8K), which leads me to believe that the data is being truncated by a buffer that is exactly 8K in size.
I don't have all the source code available but I did find that EagerResponseBodyPart is using org.asynchttpclient.netty.util.ByteBufUtils#byteBuf2Bytes to copy the 8192 bytes into a byte[] that I subsequently convert to a String to parse as JSON.

The code of byteBuf2Bytes seems reasonable so I may be barking up the wrong tree here and look at io.netty.buffer classes or maybe I have completely misunderstood the onBodyPartReceived method and large events are sent in multiple, successive calls to onBodyPartyReceived and I need to figure out a way to know that one bodyPart is the completion of a previous one?

**Comment by slandelle** [comment]
> I noticed that parse errors were occurring during the handling of the events and found that the event data, i.e. the bytes that I get from the HttpResponseBodyPart object is 8192bytes in size and stops somewhere in the middle of the JSON object.

You're getting it wrong. HttpResponseBodyPart contains the bytes that could be read from one single iteration of the event loop. Its size is maxed by the read buffer size from Netty.
`onBodyPart` will be called multiple times and you can't assume you have a full payload/frame.
Depending on your use case, you might need to buffer the bytes until onComplete is called.

Then, please use the mailing list for questions, not the bug tracker.
