### ISSUE TITLE
FileMultipartPart is never "Done" with empty file or channel close exception

### ISSUE THREAD

**Issue by yangye1947** [AsyncHttpClient/async-http-client#1485]
Hi, I'm using ahc 2.0.31.  Observed hanging AHC thread in two scenarios: 1. upload an empty file. 2. netty channel closed. At first, I thought these two cases were unrelated. But going through the code, found they seem caused by the same reason.

I used the default unpooled buffer allocator with UnpooledUnsafeDireByteBuf. In the code, on channel closed or file is empty, it will return -1, which makes sense.
```
public int setBytes(int index, ScatteringByteChannel in, int length) throws IOException {
        this.ensureAccessible();
        ByteBuffer tmpBuf = this.internalNioBuffer();
        tmpBuf.clear().position(index).limit(index + length);

        try {
            return in.read(tmpBuf);
        } catch (ClosedChannelException var6) {
            return -1;
        }
    }
```

But when file multipart part received -1, it decreased the position by -1. Then it compared the position with the length to see if the position reaches the end. With decrease by -1 every time, the position will never reach the end. And causing the thread looping forever...
```
    protected long transferContentTo(ByteBuf target) throws IOException {
        int transferred = target.writeBytes(this.channel, target.writableBytes());
        this.position += (long)transferred;
        if (this.position == this.length) {
            this.state = MultipartState.POST_CONTENT;
            this.channel.close();
        }

        return (long)transferred;
    }
```

This is easy to reproduce. You can simply upload with empty file. Let me know if I mis-understand anything. Thx!

**Comment by slandelle** [comment]
I've added a test in `MultipartUploadTest` sending an empty file and wasn't able to reproduce.

```java
@Test(groups = "standalone")
public void sendEmptyFile() throws Exception {
    File file = getClasspathFile("empty.txt");
    try (AsyncHttpClient c = asyncHttpClient(config())) {
        Request r = post("http://localhost" + ":" + port1 + "/upload/bob")
                .addBodyPart(new FilePart("file", file, "text/plain", UTF_8))
                .build();

        Response res = c.executeRequest(r).get();
        assertEquals(res.getStatusCode(), 200);
    }
}
```

So yes, it would be great if you could provide a unit test to reproduce, please.

**Comment by slandelle** [comment]
> I've added a test in MultipartUploadTest sending an empty file and wasn't able to reproduce.

OK, got it, the code you mention is only used on the non-zero-copy path.
Fixing

**Comment by yangye1947** [comment]
I tried your test code, cannot reproduce. Then I notice in my code, the connection is mutual authenticated with ssl context. When I start to use "https", the issue reproduced.
```
    @Test
    public void sendEmptyFile() throws Exception {
        File file = new File("/<path-to-empty-file>");
        
        // We used the client side ssl certificate
        AsyncHttpClient c = new DefaultAsyncHttpClient(new DefaultAsyncHttpClientConfig.Builder()
                    .setSslContext(sslContext)
                    .setUseOpenSsl(true)
                    .build());
        
        BoundRequestBuilder builder  = c.preparePost("https://<url-to-post>");
        builder.addBodyPart(new FilePart("file", file, "application/gzip"))
                .setHeader("content-type", "multipart/form-data");
        Request r = builder.build();
        Response res = c.executeRequest(r).get();
```

I traced the code path in your test code using "http", in the FileMultipartPart, it uses the method "protected long transferContentTo(WritableByteChannel target) throws IOException". 
When I switched to use "https", it uses the method "protected long transferContentTo(ByteBuf target) throws IOException".

These two methods have different impl.

**Comment by yangye1947** [comment]
Also, the thread got hanging when there's closedChannalException. Will your fix also fix that exception?

**Comment by slandelle** [comment]
I suspect you didn't properly test with my change.
The 2 different paths depend on zero-copy being enabled. Zero copy is of course not available on https.  I test both cases: https://github.com/AsyncHttpClient/async-http-client/commit/6184e9a650dae813c76af41793d6c886d37eaf59#diff-883478bf0f63161a0a9f363ad001c93cR145

**Comment by yangye1947** [comment]
IC, we do want the zero-copy enabled to save memory usage.

**Comment by slandelle** [comment]
zero copy is not possible over https: you need to read bytes in user space to perform encryption

**Comment by yangye1947** [comment]
Thx for fixing the issue. One more follow up question regarding the memory usage.

My app is tightly restricted to the memory usage (128MB). The app is simple though. Just read file and send requests and plus encrypt the requests with ssl. So I try to preserve the memory to avoid OOM. Even though I use the PooledBufferAllocator, there's still byte buffer that constant eat memory and trigger lots of GC.

Are those caused by the encryption on my user space?
