### ISSUE TITLE
New Connect for every request going via Proxy(Squid3)

### ISSUE THREAD

**Issue by pradeepitm12** [AsyncHttpClient/async-http-client#1486]
Hi, I am using async-http-client version 1.9.40.
My end point is https and I am trying to send multiple requests via Squid3 proxy. I need a persistent connection between client and proxy.
But I can clearly see in proxy logs that for every request new CONNECT is sent.Also with netstat for every request new ESTABLISHED is seen.
I tried to do tunneling but in this case also new connections are made. Can someone please help me to make a tunnel between client, proxy, and endpoint

Below are proxy logs
1512990924.739 134 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990925.740 122 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990926.738 103 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990927.841 187 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990928.840 174 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990929.839 162 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990930.839 150 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990931.840 139 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990932.841 130 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990933.838 111 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990934.938 190 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -
1512990935.939 179 127.0.0.1 TCP_MISS/200 0 CONNECT 52.221.109.35:443 - HIER_DIRECT/52.221.109.35 -

**Comment by slandelle** [comment]
AHC 1 is **DEAD**. Please upgrade to AHC 2.

**Comment by pradeepitm12** [comment]
Thanks for the information, Can you please help me more.

My client is making a new connection (client and proxy) for every new
request, I want to reuse the connection.

If tunnel is solution for this then how to achieve tunneling with AHC 2

On Mon, Dec 11, 2017 at 5:19 PM, Stephane Landelle <notifications@github.com

**Comment by pradeepitm12** [comment]
Can you please share with me some sample code doing tunneling with AHC 2.
