### ISSUE TITLE
how to build and maintain  a tunnel for a requests through proxy for ssl endpoint

### ISSUE THREAD

**Issue by pradeepitm12** [AsyncHttpClient/async-http-client#1489]
We have a setup with Java async-http-client ->proxy-> ssl endpoint (https://abc.com/getData)
We are trying to build a tunnel (like mentioned here https://docs.oracle.com/cd/E19575-01/821-0053/adyef/index.html) from client to ssl endpoint, so that only one CONNECT request should be sent to proxy before sending requests.
We want to maintain the connection which was created with CONNECT for other upcoming requests.
Below is my code 
	asyncHttpClient = asyncHttpClient(config()
				.setProxyServer(proxyServer("127.0.0.1", 3128))
				.setKeepAlive(true)
				.setConnectionTtl(3000)
			    .setMaxConnectionsPerHost(3)
			    .setPooledConnectionIdleTimeout(1000)
			    .setConnectionTtl(5000)
	);
		Request request = asyncHttpClient.preparePost("https://abcxyz.net/getData")
					.setVirtualHost("abcxyz.net")
					.setHeader("Connection", "keep-alive")
					.setHeader("Content-Type", "application/json")
					.setBody(indata)
					.build();

			Future<Response> whenResponse =   asyncHttpClient.executeRequest(request);

But I can clearly see in Proxy log that for each request I am getting **CONNECT**.

1513157788.695    325 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 -HIER_DIRECT/35.190.1.8 -
1513158144.605   1905 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158183.766    101 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158210.699   3707 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158211.957    229 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158213.261    285 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158217.393   3114 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158219.266    855 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158220.392    101 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158221.469     57 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158222.864    366 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158224.990   1105 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158229.048   3037 127.0.0.1 TCP_MISS/200 5239 **CONNECT** 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158230.237    169 127.0.0.1 TCP_MISS/200 5239 CONNECT 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158231.357     95 127.0.0.1 TCP_MISS/200 5239 CONNECT 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -
1513158232.424     50 127.0.0.1 TCP_MISS/200 5239 CONNECT 35.190.1.8:443 - HIER_DIRECT/35.190.1.8 -

**Comment by slandelle** [comment]
Please provide debug logs. Most likely your remote peer (your proxy or your remote host) closes connections.

**Comment by pradeepitm12** [comment]
Below are the logs which contain some exception, These exceptions where not there when I was using AHC1.9.x

Dec 13, 2017 10:04:25 PM sdk.SS2 getIp
INFO: ipaddress from existing file is 35.190.1.8
Dec 13, 2017 10:04:25 PM sdk.SS2 async_sendReq2SS
SEVERE: Error in asynchttpclient:java.lang.ClassCastException: org.asynchttpclient.netty.NettyResponseFuture cannot be cast to io.netty.util.concurrent.Future
Dec 13, 2017 10:04:25 PM sdk.SS2 shieldsquare_ValidateRequest
INFO: {"pid":"28552df6-9162-1965-3095-29ee6f4a78f7","responsecode":"-1","reason":"java.lang.ClassCastException: org.asynchttpclient.netty.NettyResponseFuture cannot be cast to io.netty.util.concurrent.Future\n\tat sdk.SS2.async_sendReq2SS(SS2.java:1129)\n\tat sdk.SS2.shieldsquare_ValidateRequest(SS2.java:425)\n\tat org.apache.jsp.index_jsp._jspService(index_jsp.java:83)\n\tat org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:728)\n\tat org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)\n\tat org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)\n\tat org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:728)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)\n\tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)\n\tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)\n\tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)\n\tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)\n\tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)\n\tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)\n\tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)\n\tat org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)\n\tat org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)\n\tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)\n\tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)\n\tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)\n\tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)\n\tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n","url":"","dynamic_JS":"var __uzdbm_c = 2+2"}
data

**Comment by slandelle** [comment]
```
java.lang.ClassCastException: org.asynchttpclient.netty.NettyResponseFuture cannot be cast to io.netty.util.concurrent.Future
    at sdk.SS2.async_sendReq2SS(SS2.java:1129)
```

Your code is broken. AHC's future implements `java.util.concurrent.Future` and has nothing to do with `io.netty.util.concurrent.Future`.

**Comment by pradeepitm12** [comment]
But that is the same case if **https://twitter.com** or **Google.com** as my endpoint.

**Comment by pradeepitm12** [comment]
But that is the same case if https://twitter.com
<https://www.google.com/url?q=https%3A%2F%2Ftwitter.com&sa=D&sntz=1&usg=AFQjCNEZGwleuQsrvxfZCoc4UYgd5HAytw>
or Google.com as my end point.
