### ISSUE TITLE
onThrowable doesn't called

### ISSUE THREAD

**Issue by Djaler** [AsyncHttpClient/async-http-client#1492]
When I call get() method of future (instead of async logic using listeners), onThrowable method of my AsyncHandler doesn't called.

**Comment by slandelle** [comment]
Sorry, I don't get you. Please provide a reproducer and the version of AHC you're using.

**Comment by Djaler** [comment]
I use 2.0.37

For example:
Handler:
`@Log4j2
public abstract class AbstractAsyncHandler<T> extends AsyncCompletionHandler<T> {

    @Override
    public void onThrowable(Throwable t) {
        super.onThrowable(t);

        //SOME MY LOGIC
    }

    @Override
    public final T onCompleted(Response response) throws Exception {
        //SOME MY LOGIC

        return onSuccessResponse(response);
    }

    abstract protected T onSuccessResponse(Response build) throws Exception;
}`

Next - 
`Result result = asyncHttpClient.prepareGet(url).execute(new SomeAsyncHandlerInheritor()).get();`
And when I get some exception, for example TimeoutException, onThrowable method doesn't called.

But if I use this
`asyncHttpClient.prepareGet(url).execute(new SomeAsyncHandlerInheritor()).toCompletableFuture().thenAccept(result -> doSomething(result));` - onThrowable called

**Comment by slandelle** [comment]
> I use 2.0.37

Can you reproduce with 2.1.0-RC3? Can you please provide a full actionable reproducer, not just the concept?

**Comment by Djaler** [comment]
With 2.1.0-RC3 it works good, thank you

**Comment by slandelle** [comment]
Great, thanks for your feedback!
