### ISSUE TITLE
URLEncoding with %2F leads to request issues

### ISSUE THREAD

**Issue by Sese-Schneider** [AsyncHttpClient/async-http-client#1493]
If you request an URL e.g. `http://example.com/thumbnails/testfolder%2Fimage.png` AsyncHttpClient converts this to: `http://example.com/thumbnails/testfolder/image.png` and requests this url instead (which it defently shouldn't)!

> `%2F` is the URLEncoded char `/`

Quick workaround is: `asyncHttpClient.setURLEncodingEnabled(false)` (use with caution)

**Comment by slandelle** [comment]
I suspect you're using an old version and this issue has already been fixed for a long time.

With AHC 2.1.0-RC3:

```java
try (AsyncHttpClient client = asyncHttpClient()) {
    client.prepareGet("http://example.com/thumbnails/testfolder%2Fimage.png").execute().get();
}
```

```
Request DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
GET /thumbnails/testfolder%2Fimage.png HTTP/1.1
host: example.com
accept: */*
user-agent: AHC/2.1

Response DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Date: Tue, 09 Jan 2018 12:26:31 GMT
Expires: Tue, 16 Jan 2018 12:26:31 GMT
Last-Modified: Tue, 09 Jan 2018 12:24:17 GMT
Server: ECS (oxr/83AE)
Vary: Accept-Encoding
X-Cache: 404-HIT
Content-Length: 1270
```

**Comment by Sese-Schneider** [comment]
Compile version: `compile 'com.loopj.android:android-async-http:1.4.9'`

**Comment by slandelle** [comment]
@Sese-Schneider Turns out you were complaining to the wrong project and realized it.

Again, I really hate this lame loopj that picked a confusing name (years after this project) and that refuses to properly route its users to their own repo so they stop creating invalid issues here that I waste time having a look at.
