### ISSUE TITLE
AsyncHttpClient causes timeout when connecting via proxy

### ISSUE THREAD

**Issue by greenGitUser** [AsyncHttpClient/async-http-client#1496]
When using AHC for sending out an asynchronous request to an endpoint via a proxy it fails due to timeout.

**"java.util.concurrent.TimeoutException: Request timed out to localhost/127.0.0.1:20003 of 60000 ms"** where the localhost and the port is the proxy host and port. The 60000 ms is the default timeout set.

Most of the configuration related check was done by setting ample timeout for ConnectTimeout, WebSocketTimeout, ReadTimeout, RequestTimeout. Different AsyncHttpProvider was also tested where the JDKAsyncHttpProvider gave a different error **"java.util.concurrent.TimeoutException: No response received after 60000 ms"**. Here the actual request is going through the proxy. The proxy receives the 200 OK but it is not reaching the AHC.

Is this an issue because of the proxy? The issue occurs only when we send a asynchronous request via proxy. All other request are working fine. The asynchronous request without proxy, synchronous request with/without proxy also works.

**Comment by slandelle** [comment]
Generally speaking, when reporting an issue against a library, you're supposed to follow those obvious steps:
* check that you're not using an old version and that upgrading fixes your problem
* if not, provide the version your using and a way to reproduce your problem

As you mention `JDKAsyncHttpProvider`, you're using AHC 1, which has reached end of life for a very long time. AHC 2.1.0 was released yesterday. Please upgrade.

**Comment by greenGitUser** [comment]
Hi Slandelle, I understand your points. We are checking if we can upgrade. But I'm not sure we can provide a test client which can be used for reproducing the issue.

Thank you for the update.

**Comment by greenGitUser** [comment]
@slandelle - We recently found that the issue happens only with a particular endpoint (mendelson AS2). When we send a connection header with close as value, the mendelson responds with only the following:

HTTP/1.1 200 OK
Connection: close
Server: Jetty(9.2.9.v20150224)

Other server responds with:
HTTP/1.1 200 OK
connection: close
server: Apache
content-length: 0

The content-length is missing. We face the issue only when content-length is missing.
What is the recommended way to handle this particular scenario?

**Comment by slandelle** [comment]
Please provide a reproducer
