### ISSUE TITLE
Seeing too many RemotelyClosedException 

### ISSUE THREAD

**Issue by benishak** [AsyncHttpClient/async-http-client#1497]
In the logs I see the following exception without stack trace

```
org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
```

here is how my client is built

```
AsyncHttpClientConfig asyncHttpClientConfig = new DefaultAsyncHttpClientConfig.Builder()
          .setChannelPool(new DefaultChannelPool(2000, 10000, DefaultChannelPool.PoolLeaseStrategy.LIFO,
            new HashedWheelTimer(15, TimeUnit.MILLISECONDS), 500))
          .setThreadPoolName("async-client-aproxy")
          .setKeepAlive(true)
          .setConnectionTtl(10000)
          .setConnectTimeout(250)
          .setReadTimeout(5000)
          .setMaxRequestRetry(0)
          .setMaxConnectionsPerHost(1000)
          .build();
```

I tried increasing the `ConnectionTtl, cleanerPeriod ` but I saw no decreased number of exception of RemotelyClosedException

**Comment by slandelle** [comment]
"Remotely closed" means your server abruptly closed the connection while AHC was trying to write, and it kept on doing so enough though AHC performed some retry (4 by default).

You probably want to investigate your server and why it closes connections this way.

If you really think this is an AHC issue and your server doesn't close connections, please:
* upgrade to latest AHC (2.1.0)
* provide a full actionable reproducer (a standalone test I can run on my side and that exhibits your issue)

**Comment by slandelle** [comment]
Closing for now. Please ping if you can provide requested elements.
