### ISSUE TITLE
Setter for connectionPoolCleanerPeriod

### ISSUE THREAD

**Issue by agapic** [AsyncHttpClient/async-http-client#1503]
Is there a particular reason that connectionPoolCleanerPeriod has no setter? If there's no reason, I can submit a PR for this, as I'd like to personally use it.

Currently, it's being set as 
`private int connectionPoolCleanerPeriod = defaultConnectionPoolCleanerPeriod();`

**Comment by slandelle** [comment]
> If there's no reason, I can submit a PR for this, as I'd like to personally use it.

That's a mistake. Yes, please do.

**Comment by agapic** [comment]
Sure. I'll do it.

**Comment by slandelle** [comment]
Closed by #1506
