### ISSUE TITLE
Provide a way to disable insecure cipher suites filtering

### ISSUE THREAD

**Issue by fistons** [AsyncHttpClient/async-http-client#1510]
We have some SSL handshake failure with some website, using async-http-client 2.2.1:

Reproducer:
```
import org.asynchttpclient.AsyncHttpClient;

import static org.asynchttpclient.Dsl.*;

public class Main {

  public static void main(String[] args) throws Exception {
    try (AsyncHttpClient c = asyncHttpClient()) {
      c.prepareGet("https://www.gretalr.com").execute().get();
    }
  }
}
```

This website is just an example and works fine with firefox/chrome and Apache Http Client 4.3.5

**Comment by slandelle** [comment]
Frankly, the [grade of this website on SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=www.gretalr.com) is absolutely horrible.
But then, I agree AHC/Netty just work (preferably out of the box) as browsers do.

I suspect the handshake failure is related to the cipher suite filtering Netty does to enforce security. I've opened an issue there: https://github.com/netty/netty/issues/7655.

Thanks for reporting!

**Comment by fistons** [comment]
> Frankly, the grade of this website on SSLLabs is absolutely horrible.

We are absolutely agree, especially for a French institution web site ;)

Thanks!

**Comment by slandelle** [comment]
I would love that Netty would provide a way to disable security as a workaround for such case.

Then, the core problem is that the only ciphers that this website supports and that are not flagged as INSECURE or WEAK on SSLLabs (and are most likely to be forcefully disabled in Netty) are not supported in JDK8 (didn't check JDK9). Things work in browers as they support more cipher suites than Java. Things work with Apache HttpComponents as it doesn't enforce security.

As a workaround, you can bypass Netty SSL components:

```java
SSLContext sslcontext = SSLContext.getInstance("TLS");
sslcontext.init(null, null, null);
try (AsyncHttpClient c = asyncHttpClient(config().setSslEngineFactory(new JsseSslEngineFactory(sslcontext)))) {
  c.prepareGet("https://www.gretalr.com").execute().get();
}
```

**Comment by slandelle** [comment]
> We are absolutely agree, especially for a French institution web site ;)

If those people are your clients, I really recommend you get in touch with them so they fix their mess.

**Comment by fistons** [comment]
Your workaround works fine, but it seems to be problematic when trying to fetch website with SSL certificate with an incomplete issuer chain:

 * https://www.ssllabs.com/ssltest/analyze.html?d=www.midland.edu
 * https://www.ssllabs.com/ssltest/analyze.html?d=www.mangahome.com
 * https://www.ssllabs.com/ssltest/analyze.html?d=m.mangahere.co

Here is a reproducer:

```
import static org.asynchttpclient.Dsl.asyncHttpClient;
import static org.asynchttpclient.Dsl.config;

import org.asynchttpclient.AsyncHttpClient;
import org.asynchttpclient.Response;
import org.asynchttpclient.netty.ssl.JsseSslEngineFactory;

import javax.net.ssl.SSLContext;

public class Main {

  public static void main(String[] args) throws Exception {
    SSLContext sslcontext = SSLContext.getInstance("TLS");
    sslcontext.init(null, null, null);
    try (AsyncHttpClient c = asyncHttpClient(config()
      .setSslEngineFactory(new JsseSslEngineFactory(sslcontext))
            .setDisableHttpsEndpointIdentificationAlgorithm(true)
            .setUseInsecureTrustManager(true)
      )) {
      Response res = c.prepareGet("https://www.mangahome.com").execute().get();
      System.out.println(res.getResponseBody());
    }
  }
}

and the output:

```

**Comment by slandelle** [comment]
@fistons This has nothing to do with the original issue, and is something no one but Oracle can "fix": Comodo is currently not a trusted CA in the JDK, you need to [install](https://blogs.oracle.com/jtc/installing-trusted-certificates-into-a-java-keystore) it yourself.

**Comment by slandelle** [comment]
Actually, it seems Comodo was added in the trusted root CA in Java 9: http://openjdk.java.net/jeps/319

**Comment by fistons** [comment]
Ok thanks for your answer.

So I guess my only hope to fetch all kind of https website, even the shittier one, is to wait for your pull request (mentioned [here](https://github.com/netty/netty/issues/7655#issuecomment-361877074)) to be accepted by netty.

Thanks for you help!

**Comment by slandelle** [comment]
No, you got it wrong. You need to build a store and import the missing root CAs.
