### ISSUE TITLE
Requests with virtual host sent to wrong destination when keep-alive is enabled

### ISSUE THREAD

**Issue by yifanmai** [AsyncHttpClient/async-http-client#1519]
Scenario:

1.  The client sends a request to `10.0.0.1` with virtual host `virtualhost.example` with keep-alive enabled.
2. Shortly after the first request is complete and before the connection is closed, the client sends a request to `10.0.0.2` with virtual host `virtualhost.example` with keep-alive enabled.

Expected behavior: Request 1 is sent to `10.0.0.1` and request 2 is sent to `10.0.0.2`.

Actual behavior: Both requests are sent to `10.0.0.1`.

This bug occurs because the client uses the virtual host alone as the channel pool partition key when a virtual host is set for a request. This causes the client to incorrectly reuse connections with the same virtual host even if the physical destination address differs. This can be fixed by changing channel pool partition key to a (base URL, virtual host) tuple.

**Comment by yifanmai** [comment]
This is the incorrect channel pool partition key logic:
https://github.com/AsyncHttpClient/async-http-client/blob/9a64a2e2326c3ed1dcfe3318e1824b119dd5e85b/client/src/main/java/org/asynchttpclient/channel/ChannelPoolPartitioning.java#L28-L38

**Comment by slandelle** [comment]
So I think key should account for both host and virtualHost, right?

**Comment by slandelle** [comment]
@yifanmai Willing to contribute a PR? ;-)

**Comment by yifanmai** [comment]
Sure!
