### ISSUE TITLE
ByteArrayBodyGenerator construcor not visible

### ISSUE THREAD

**Issue by maltalex** [AsyncHttpClient/async-http-client#1526]
In 8daebe0b00b7e1a16ee29f71b371c23310b82065, The `ByteArrayBodyGenerator` constructor suddenly stopped being `public` unlike every other `BodyGenerator`. This isn't detected by tests since `ByteArrayBodyGeneratorTest` is in the same package - `org.asynchttpclient.request.body.generator`.

Was this intentional? All versions past this commit (2.1.1 and newer) cannot `POST` byte arrays without resorting to reflection.

**Comment by slandelle** [comment]
Thanks for reporting.

> All versions past this commit (2.1.1 and newer) cannot POST byte arrays without resorting to reflection.

What about `RequestBuilderBase#setBody(byte[])`? https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/RequestBuilderBase.java#L374

`ByteArrayBodyGenerator` will probably go away in a future version.

**Comment by maltalex** [comment]
Thanks.

> What about `RequestBuilderBase#setBody(byte[])`?

No idea. We're using `ByteArrayBodyGenerator` in our code. Frankly, I'm not sure why. It was probably something we copied off an example at some point. I wrongly assumed that any alternative way of using a byte array to fill the body would call `ByteArrayBodyGenerator`'s constructor, and my IDE didn't find such calls. Anyway, if it's being deprecated, we'll switch to `setBody()`.
