### ISSUE TITLE
Body truncation with Content-Type Header in AHC 2.1+

### ISSUE THREAD

**Issue by PatrickBuTaxdoo** [AsyncHttpClient/async-http-client#1530]
I just tried to use the newer versions of AHC. 
I use AHC to call my own API with JSON payload.
The following code works in 2.0.37 and 2.0.39, but not in 2.1.2, 2.3.0 and 2.4.2 (tested only these versions).

My code:
```java
DefaultAsyncHttpClientConfig config = new DefaultAsyncHttpClientConfig.Builder()
		.setRequestTimeout((int) timeout.toMillis())
		.setReadTimeout((int) timeout.toMillis())
		.setConnectionTtl(1000 * 60 * 5)
		.setUserAgent("Taxdoo")
		.setKeepAlive(true)
		.build();

DefaultAsyncHttpClient httpClient = new DefaultAsyncHttpClient(config);

RequestBuilder builder = new RequestBuilder()
	.setUrl("https://api...")
	.setMethod("POST");
// body is a String containing JSON
builder.setBody(body);
builder.setCharset(StandardCharsets.UTF_8);

builder.setHeader("Content-Type", "application/json");
// with AsyncHttpClient version 2.1+ this header leads to a truncation of the body
builder.setHeader("Content-Length", String.valueOf(body.length()));
httpClient.executeRequest(builder).toCompletableFuture()
```
When i remove the Content-Length header while using AHC 2.1+, the body is not truncated.

**Comment by slandelle** [comment]
The difference is AHC 2.0 was ignoring your broken header while AHC 2.1 is honoring it.
Content-Length is the length of the encoded body in **BYTES**, not the number of chars in UTF-8.
If you payload contains non US-ASCII chars, those numbers are different.
Just let AHC compute Content-Length for you instead of forcing it.
