### ISSUE TITLE
Retrofit module. Content-Type header is not passed

### ISSUE THREAD

**Issue by zeldigas** [AsyncHttpClient/async-http-client#1531]
Configuration:
```xml
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.asynchttpclient</groupId>
            <artifactId>async-http-client</artifactId>
            <version>2.4.3</version>
        </dependency>
        <dependency>
            <groupId>org.asynchttpclient</groupId>
            <artifactId>async-http-client-extras-retrofit2</artifactId>
            <version>2.4.3</version>
        </dependency>
```
I found that content type header is not passed properly to AHC's request. The problem is that content-type is contained in Body object (retrofit object), not in headers list, but this field is ignored in `createRequest` method of org.asynchttpclient.extras.retrofit.AsyncHttpClientCall

**Comment by slandelle** [comment]
@zeldigas Would you mind providing a PR? Extra modules are maintained by the community and I'm not a Retrofit user myself.

**Comment by zeldigas** [comment]
Sure, I'll do it this week.

**Comment by slandelle** [comment]
Cool, thanks!

**Comment by zeldigas** [comment]
PR created, please check and let me know if I need improve it somehow
