### ISSUE TITLE
java.net.ConnectException: handshake alert: unrecognized_name

### ISSUE THREAD

**Issue by coud** [AsyncHttpClient/async-http-client#1535]
I posted this issue in stackoverflow and wanted to reach more people regarding this issue. This might be not an issue with AHC but I wanted to know a solution to this specific for AHC.  

https://stackoverflow.com/questions/49399908/java-net-connectexception-handshake-alert-unrecognized-name

I am using the library org.asynchttpclient:async-http-client:2.4.0 to scrape multiple urls of different hosts at the same time. I'm having this issue with the website https://www.westcommunitycu.org/index.shtml where the library fails to get a response. The error is java.net.ConnectException: handshake alert:  unrecognized_name

I already read that disabling sni in java (setting -Djsse.enableSNIExtension=false) will fix the issue and it really fixes it. But another site https://www.cityftmyers.com is having an error java.net.ConnectException: https://www.cityftmyers.com:443 when SNI is disabled.

I need to support both instances not the global disable sni property.

**Comment by slandelle** [comment]
There's nothing that can be done about it. That's a server issue whose TLS implementation is broken. Use 2 different client instances, and try falling back when TLS isn't properly implemented.

**Comment by coud** [comment]
That will work for me but how will I configure the other client to bypass SNI? I already digged in to the AHC settings but couldn't find a related setting.

**Comment by coud** [comment]
Thank you very much!! That patch works.
