### ISSUE TITLE
Question about read and request timeout

### ISSUE THREAD

**Issue by hariso** [AsyncHttpClient/async-http-client#1537]
First of all, thanks for such a great project!

In a project, I'm using AHC 1.9.15. I hope that we will be able to upgrade soon, but we are experiencing an issue which cannot wait for the upgrade.

The issue is about a POST request which is expected to take quite some time. On that request's level, we set a request timeout which is one hour. The `AsyncHttpClient` instance has read timeout and request timeout set to 1 minute.

The mention POST request is failing, because of the read timeout. AHC's source code for `NettyRequestSender` shows this:
```java
int readTimeoutValue = config.getReadTimeout();
if (readTimeoutValue != -1 && readTimeoutValue < requestTimeoutInMs) {
    // no need for a readTimeout that's less than the requestTimeout
    Timeout readTimeout = newTimeout(new ReadTimeoutTimerTask(nettyResponseFuture, this, timeoutsHolder,
            requestTimeoutInMs, readTimeoutValue), readTimeoutValue);
    timeoutsHolder.readTimeout = readTimeout;
}
```

Based on the above, I have following questions:
1. What exactly is the difference between read and request timeout?
2. Is there a possibility to set the read timeout on request level?
3. Based on the comment "no need for a readTimeout that's less than the requestTimeout" shouldn't the condition be `readTimeoutValue > requestTimeoutInMs`? I might be way off here because I don't really understand the difference between read and request timeout here.

Thanks in advance!

**Comment by slandelle** [comment]
Hi,

Please use the mailing list for questions, not the bugtracker.

> In a project, I'm using AHC 1.9.15. I hope that we will be able to upgrade soon, but we are experiencing an issue which cannot wait for the upgrade.

AHC 1 has reached EOL many years ago. 

> What exactly is the difference between read and request timeout?

* readTimeout: happens because time receiving consecutive response chunks is too long
* requestTimeout: happens because overall time for receiving full response is too long

> Is there a possibility to set the read timeout on request level?

Yes, on AHC 2: https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/RequestBuilderBase.java#L507

> Based on the comment "no need for a readTimeout that's less than the requestTimeout" shouldn't the condition be readTimeoutValue > requestTimeoutInMs? I might be way off here because I don't really understand the difference between read and request timeout here.

I won't even spend time on an dead old version. Please upgrade and report if you have any issue with latest version.

**Comment by hariso** [comment]
@slandelle Thanks a lot for the answer! I'll use the mailing list next time!
