### ISSUE TITLE
Trust all SSL?

### ISSUE THREAD

**Issue by bootstraponline** [AsyncHttpClient/async-http-client#154]
How do I trust all SSL with async-http-client? Here's [how it's done for Apache HttpComponents](http://stackoverflow.com/a/11951889). This is an essential feature for a proxy that wants to process all connections.

**Comment by chambas** [comment]
Can someone give one example, please? The links form previous posts doesn't work.

**Comment by slandelle** [comment]
@chambas Please use the Google Group for questions, not the bugtracker.
