### ISSUE TITLE
Need only the stream for response

### ISSUE THREAD

**Issue by noviceamateur** [AsyncHttpClient/async-http-client#1543]
I am using Apache Async Http Client to download huge files from Azure Storage.

This is the sample code I am using ->

     CloseableHttpAsyncClient httpclient = HttpAsyncClients.createDefault();
      httpclient.execute(request, new FutureCallback<org.apache.http.HttpResponse>() {
         @Override
         public void completed(final org.apache.http.HttpResponse httpResponse) {
         }

         @Override
         public void failed(final Exception e) {
            future.completeExceptionally(e);
         }

         @Override
         public void cancelled() {
            future.completeExceptionally(new Exception("Request cancelled"));
         }
      });

But this is storing the file in a local buffer before invoking completed callback .

I tried using AsyncByteConsumer ->

      AsyncByteConsumer<org.apache.http.HttpResponse>
              consumer = new AsyncByteConsumer<org.apache.http.HttpResponse>() {
         @Override
         protected void onByteReceived(ByteBuffer buf, IOControl ioctrl) throws IOException {

         }

         @Override
         protected void onResponseReceived(org.apache.http.HttpResponse response) throws HttpException, IOException {
         }

         @Override
         protected org.apache.http.HttpResponse buildResult(HttpContext context) throws Exception {
            return null;
         }
      };

This also did not work for me.
I am getting the following error ->
java.lang.IllegalStateException: Content has not been provided

All I want is to get the stream for the response which I will pass on to my clients so that they can download the file directly using the stream.

**Comment by slandelle** [comment]
Wrong project, this is not Apache HttpComponents here.
