### ISSUE TITLE
Custom properties being ignored

### ISSUE THREAD

**Issue by dparmar** [AsyncHttpClient/async-http-client#1546]
Custom ahc.properties present on the classpath gets ignored, probably due to side effect of the fix for issue #1536.

**Steps to reproduce**:
- Create /async-http-client/src/main/resources/ahc.properties with following entry.
`org.asynchttpclient.userAgent=Custom`

- Add corresponding test to AsyncHttpClientDefaultsTest.java
```
  public void testCustomProperty() {
    Assert.assertNotEquals(AsyncHttpClientConfigDefaults.defaultUserAgent(), "AHC/2.1", "Custom property ignored");
  }
```
**Probable fix**:
Use getClass().getClassLoader().getResourceAsStream(file) for loading custom AHC properties.

**Comment by slandelle** [comment]
Nah. As of #1538 (titled "Use package relative resources"), custom `ahc.properties` must be in `org.asynchttpclient.config` package, not at classpath root.
