### ISSUE TITLE
Limit body size

### ISSUE THREAD

**Issue by jeremyhaile** [AsyncHttpClient/async-http-client#1551]
Is there a way to limit the body size loaded into memory when calling `getResponseBody()`?

We're running into an "out of memory" issue that we suspect is from a large body being loaded. We are checking the content length in the onHeadersReceived callback and aborting if it is too large, but would like to also make sure that we don't load too large of a body into memory if the headers are incorrect.

Please let me know if there is a way to do this today, or if not it would be good if there was a way to limit this.

**Comment by slandelle** [comment]
Implement your own AsyncHandler to keep track of chunk size.
Now, please use the mailing list for questions, not the bug tracker.
