### ISSUE TITLE
Timeout expiring when sending a request outside of unit tests.

### ISSUE THREAD

**Issue by JamieSinn** [AsyncHttpClient/async-http-client#1554]
I've got an extremely weird bug. AHC works perfectly within the unit tests I've written for the project, but as soon as it goes into production it doesn't work and times out after 60s.
The server logs show that there is never a request being received, which leads me to believe it's on the side of the library.
(https://i.imgur.com/Tyg64qa.png)

The exact same request succeeds when submitted during the unit test.
https://i.imgur.com/9EPTPX0.png

This is confusing me to no end, as there's no difference between the two.  What could cause this?

**Comment by slandelle** [comment]
Could be a bug, either in your application or AHC. Is your AHC version up to date?

**Comment by JamieSinn** [comment]
Using the LATEST maven keyword, so it should be. Going to try a build with the snapshot number forced.

**Comment by slandelle** [comment]
You’re still using maven 2?!

**Comment by JamieSinn** [comment]
Maven 3.3.9

**Comment by slandelle** [comment]
AFAIK, LATEST metaversion was dropped in maven 3.

**Comment by JamieSinn** [comment]
Update: 
Shading ALL libraries are required. Cannot just shade AHC. resolved the issue.
