### ISSUE TITLE
Serializing request body for SignatureCalculator

### ISSUE THREAD

**Issue by dzieciou** [AsyncHttpClient/async-http-client#1556]
Our authentication algorithm calculates HTTP request signature based on its body, defined as an array of bytes. I have started to implement [`SignatureCalculator`][1], but found that AHC defines many different forms of request body: `Request#getByteData`, `Request#getCompositeByteData`, `Request#getStringData`, `Request#getFile`.

I can try to re-implement serialization on my own, but I would like to avoid re-inveting the wheel. Is there any `serializeRequestBody(Request) : byte[]` method in AHC that does it?

I have looked into existing `SignatureCalculator` implementations in AHC codebase, but all of them consider only one type of requests body: `Request#getFormParams`:

* [OAuthSignatureCalculator.java][2]
* [StaticOAuthSignatureCalculator][3]

My implementation so far:

```java
private byte[] serializeRequestBody(Request request) {

    if (request.getByteData() != null) {
      return request.getByteData();
    } else if (request.getCompositeByteData() != null) {
      List<Byte> buff = new ArrayList<>();
      for (byte[] bytes : request.getCompositeByteData()) {
        buff.addAll(Bytes.asList(bytes)); 
      }
      return Bytes.toArray(buff);
    } else if (request.getStringData() != null) {
      throw new UnsupportedOperationException("Serializing StringData in request body is not supported");
    } else if (request.getByteBufferData() != null) {
      throw new UnsupportedOperationException("Serializing ByteBufferData in request body is not supported");
    } else if (request.getStreamData() != null) {
      throw new UnsupportedOperationException("Serializing StreamData in request body is not supported");
    } else if (isNonEmpty(request.getFormParams())) {
      throw new UnsupportedOperationException("Serializing FormParams in request body is not supported");
    } else if (isNonEmpty(request.getBodyParts())) {
      throw new UnsupportedOperationException("Serializing BodyParts in request body is not supported");
    } else if (request.getFile() != null) {
      throw new UnsupportedOperationException("Serializing File in request body is not supported");
    } else if (request.getBodyGenerator() instanceof FileBodyGenerator) {
      throw new UnsupportedOperationException("Serializing FileBodyGenerator in request body is not supported");
    } else if (request.getBodyGenerator() instanceof InputStreamBodyGenerator) {
      throw new UnsupportedOperationException("Serializing InputStreamBodyGenerator in request body is not supported");
    } else if (request.getBodyGenerator() instanceof ReactiveStreamsBodyGenerator) {
      throw new UnsupportedOperationException("Serializing ReactiveStreamsBodyGenerator in request body is not supported");
    } else if (request.getBodyGenerator() != null) {
      throw new UnsupportedOperationException("Serializing generic BodyGenerator in request body is not supported");
    } else {
      return new byte[]{};
    }
  }
```  

 [1]: https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/SignatureCalculator.java
 [2]: https://github.com/AsyncHttpClient/async-http-client/blob/f5663546db0a69d316b2b13995ee4f103efef00c/client/src/main/java/org/asynchttpclient/oauth/OAuthSignatureCalculator.java
 [3]: https://github.com/AsyncHttpClient/async-http-client/blob/f5663546db0a69d316b2b13995ee4f103efef00c/client/src/test/java/org/asynchttpclient/oauth/StaticOAuthSignatureCalculator.java

**Comment by dzieciou** [comment]
Anyone here?

**Comment by slandelle** [comment]
I think for now the best way would be to introduce a static helper that would support the different body types.

Note that it seems you're actually requesting this for Gatling, but Gatling is moving away from AHC in Gatling 3 and the API will be very different.

**Comment by dzieciou** [comment]
@slandelle Thanks for explanation. 

What HTTP client will Gatling 3 be using?

**Comment by slandelle** [comment]
Own internal one.
