### ISSUE TITLE
publish 2.5.x versions to maven central

### ISSUE THREAD

**Issue by lev112** [AsyncHttpClient/async-http-client#1561]
the latest version in maven central is 2.4.9:
https://mvnrepository.com/artifact/org.asynchttpclient/async-http-client

**Comment by slandelle** [comment]
No, 2.5.1 is already visible and 2.5.2 is on its way: http://search.maven.org/#search%7Cga%7C1%7Casync-http-client

<img width="1014" alt="central" src="https://user-images.githubusercontent.com/849197/42622702-4eb5965c-85c1-11e8-9f80-56aacb634639.png">

search.maven.org is the official maven dashboard.
mvnrepository.com isn't, and seems to be lagging behind.

PS: please use the mailing list for such demands, not the bug tracker

**Comment by lev112** [comment]
yes, you are correct
thank you
