### ISSUE TITLE
Can not find any option to ignore SSL 

### ISSUE THREAD

**Issue by tenstriker** [AsyncHttpClient/async-http-client#1564]
I am trying to use Stand alone Ahc http client as my application is not a web app.

What is the way to accept any ssl certificate? 

It's very confusing with 3 different versions of ahc-http libraries. AsyncHttpClient, Standalone version and Shaded version.

I tried seemengly simpler approach but I got compile error as shaded and regular client doesn't seem to compatible with each other apis.

```
  val config = new DefaultAsyncHttpClientConfig.Builder().setAcceptAnyCertificate(true).build
  val wsClient2 = AhcWSClient(config) //type mismatch; found : play.shaded.ahc.org.asynchttpclient.DefaultAsyncHttpClientConfig required: play.api.libs.ws.ahc.AhcWSClientConfig
```

I tried different approaches documented at https://www.playframework.com/documentation/2.6.x/ScalaWS

This one seemed simple:

```
implicit val system = ActorSystem()
    implicit val materializer = ActorMaterializer()
    val wsClient = AhcWSClient()
```
But I can't find a way to accept any certificate with above default AhcWSClient.

Then I tried following:

```
import com.typesafe.config.ConfigFactory
import play.api._
import play.api.libs.ws._
import play.api.libs.ws.ahc._

val configuration = Configuration.reference ++ Configuration(ConfigFactory.parseString(
  """
    |ws.followRedirects = true
    |play.ws.ssl.loose.acceptAnyCertificate=true
  """.stripMargin))

// If running in Play, environment should be injected
val environment = Environment(new File("."), this.getClass.getClassLoader, Mode.Prod)
val wsConfig = AhcWSClientConfigFactory.forConfig(configuration.underlying, environment.classLoader)
val wsClient: WSClient = AhcWSClient(wsConfig)
```

THis works. but is there an easier version of this like 1st one?

**Comment by slandelle** [comment]
There’s some confusion here.

Here is AsyncHttpClient.
The two others are built on top of this one by Lightbend and Play! project.

You’ll have to ask them on their respective support channels.
