### ISSUE TITLE
Allow multiple auth schemes

### ISSUE THREAD

**Issue by nddipiazza** [AsyncHttpClient/async-http-client#1569]
The apache commons HTTP client allows you to specify a list of Auth schemes.

In particular NTLM and Kerberos. If the kerberos fails fall back to NTLM. If NTLM fails fall back to basic.

Since we only have one scheme in async http client, doesn't this mean we can only specify one form of auth scheme? Thanks!

**Comment by slandelle** [comment]
Yes, only one. How come one wouldn’t know the exact scheme used by its server?!
Please use the mailing list for questions.

**Comment by nddipiazza** [comment]
I think you might have closed this without understanding the issue. Here is the use-case which is definitely a valid one:

You are writing a generic web component. It takes any random variety of auth methods to access a variety of different web servers. 

Might be basic auth
Might be forms auth
Might be NTLM
Might be SSO
Might be Kerberos

You want the http client to handle whatever might be thrown at it generically.

**Comment by slandelle** [comment]
> I think you might have closed this without understanding the issue.

No, I didn't.

I'm not convinced that this auth scheme fallback strategy you'd like is very useful, at least for most users:

* People know which exact auth scheme is supported by the remote they're sending requests to
* For people using auth schemes, most of them use a single one. For the rest of them, an easy workaround is to use one HTTP client instance per scheme.

What's for sure is that I don't have any use for such feature so I'll never implement it myself.
Then, contributions are welcome!
