### ISSUE TITLE
`hasResponseBody` behaviour seems to be incosistent with the docs

### ISSUE THREAD

**Issue by silmeth** [AsyncHttpClient/async-http-client#1570]
The [`Response` interface’s `hasResponseBody` documentation ](https://static.javadoc.io/org.asynchttpclient/async-http-client/2.5.2/org/asynchttpclient/Response.html#hasResponseBody--) claims:

> Return true if the response's body has been computed by an AsyncHandler. It will return false if the either AsyncHandler.onStatusReceived(HttpResponseStatus) or AsyncHandler.onHeadersReceived(HttpHeaders) returned AsyncHandler.State.ABORT

which I understand as `true` always if the `AsyncHandler` did not return `ABORT` from the `onStatusReceived` or `onHeadersReceived` (even if the body itself is empty, in such case I would expect to get empty byte array as the accumulated body).

And yet, if one uses the default `AsyncCompletionHandler`, which always returns `CONTINUE` from those two methods, if one gets a response with empty body (`Content-Length: 0`), then `hasResponseBody()` on the response returns `false`.

That is the case, because the `NettyResponse`, which is created by the `AsyncCompletionHandler`, implements it as:

```java
  @Override
  public boolean hasResponseBody() {
    return isNonEmpty(bodyParts);
  }
```

I find this confusing, and believe this might be a bug.

**Comment by slandelle** [comment]
I agree that the actual behavior doesn't match the javadoc.

IMHO, the current javadoc has nothing to do with the current method name `hasResponseBody`. Such method should be named something like `isAborted` and sadly it's complicated to fix it until next major release.

So I'd rather fix the javadoc to mach current behavior.

**Comment by slandelle** [comment]
Thanks for reporting
