### ISSUE TITLE
KQueueEventLoopGroup is ignored

### ISSUE THREAD

**Issue by jamel** [AsyncHttpClient/async-http-client#1575]
Here it is
https://github.com/AsyncHttpClient/async-http-client/blob/a6d1cd2cd6cd027d9c183b023caeb77864f28691/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L138-L142

I just want to use native EventLoopGroup on MacOS.

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by elventear** [comment]
I am experiencing the same the same issue. I would be willing to contribute a fix, but I am wondering what would be an acceptable approach. The current approach seems to be too constrained to specific implementations. 

I am thinking along the lines of providing a `ChannelFactory` within `AsyncHttpClientConfig` when the `EventLoopGroup` is provided within the configuration.

**Comment by slandelle** [comment]
@elventear If your use case is only to support using a `KQueueEventLoopGroup`, please do the same as getEpollSocketChannelFactory but test the underlying OS with `io.netty.util.internal.PlatformDependent`. Just make sure that things with even with `netty-transport-native-kqueue` in the classpath.
