### ISSUE TITLE
Hash fragments are dropped in Netty Request

### ISSUE THREAD

**Issue by paambaati** [AsyncHttpClient/async-http-client#1576]
AHC drops the hash fragments when building a new request in `newNettyRequest`. `uri.toUrl()` might need to be replaced with `uri.toFullUrl()`.

https://github.com/AsyncHttpClient/async-http-client/blob/365c1e6a582499f8aaec30d56a398e694033e999/client/src/main/java/org/asynchttpclient/netty/request/NettyRequestFactory.java#L228

Additionally, `toRelativeUri()` also needs to be modified to include hash fragments - https://github.com/AsyncHttpClient/async-http-client/blob/365c1e6a582499f8aaec30d56a398e694033e999/client/src/main/java/org/asynchttpclient/uri/Uri.java#L167-L177

Can I send a PR to fix this?

**Comment by slandelle** [comment]
No. Fragments must not be sent to the server.

**Comment by paambaati** [comment]
@slandelle Our use case is this - were building a thin HTTP client wrapper that can also proxy requests.

We've seen occasional websites that actually do pagination with `#` fragments, and we'd have to preserve those to get to the content.

**Comment by slandelle** [comment]
AFAIK, Those requests violate with the HTTP specs and I’m adamant against supporting broken implementations.
If you can get in touch with the developers of those apps/websites, you should ask them to fix.

**Comment by paambaati** [comment]
@slandelle I'm afraid I can't do that. If you would consider including this behind a configuration, I can send a PR.

**Comment by ftomassetti** [comment]
Getting access to fragments would be useful also in my use case. I am basically creating a proxy for OAuth2 authentication with google and google return the access token as a fragment
