### ISSUE TITLE
CookieStore slows down with increasing number of cookies

### ISSUE THREAD

**Issue by joshovi** [AsyncHttpClient/async-http-client#1580]
In https://github.com/AsyncHttpClient/async-http-client/blob/365c1e6a582499f8aaec30d56a398e694033e999/client/src/main/java/org/asynchttpclient/cookie/ThreadSafeCookieStore.java#L160 the look up over cookies traverses all entries in the map. The side effect to clean all expired cookies traverses the list again. The cost for algorithm scales with the number of cookies.

In our project we had to disable the cookie store, i.e.
`new DefaultAsyncHttpClientConfig.Builder()
.setCookieStore(null)
...
.build()`  

Maybe you could rewrite the function using another data structure that facilitates the look up for candidate cookies and then make a lazy removal of the expired candidates, or remove expired cookies asynchronously and periodically.

**Comment by sivaalli** [comment]
@slandelle Can I work on a fix for this?

**Comment by slandelle** [comment]
@sivaalli sure, contributions welcome
