### ISSUE TITLE
gzip/deflate response through Proxy is not getting decompressed before consumed.

### ISSUE THREAD

**Issue by mallik-soupati** [AsyncHttpClient/async-http-client#1583]
I have a situation where : 
Browser ----> (proxy app:AsyncHttpClient) ----> Proxy ----> Origin Server( web site)
Ex: URL: https://example.com/startPage

While I can view the web pages correctly when accessed without Proxy; the browser shows (junk) gzip data when accessed the same pages through Proxy.

My proxy configuration doesn't unpack the gzip/deflate response received from Origin. I think the AsyncHttpClient should decompress it, before the response is consumed downstream.

Could you please look into it, or suggest any workaround. Please let me know if you need more information.

thanks,

**Comment by slandelle** [comment]
Fixed, thanks for reporting!

**Comment by mallik-soupati** [comment]
Greatly appreciate your quickly addressing this issue. Is it possible to release this fix ? 2.5.4?

Apologies for commenting on the closed ticket.

**Comment by slandelle** [comment]
Trying to, but Sonatype is broken (again)...

**Comment by mallik-soupati** [comment]
Thanks, I will check back.
