### ISSUE TITLE
Some way not to rely on this maven library com.sun.activation?

### ISSUE THREAD

**Issue by nddipiazza** [AsyncHttpClient/async-http-client#1589]
When i migrated from 2.4.7 to 2.5.4 I noticed that the transitive dependency pulls in`com.sun.activation`.

This is not desirable as this causes errors with many libraries until you add an exclusion on `com.sun.activation`.

Can we shade this dependency?

**Comment by slandelle** [comment]
I'm afraid that's neither possible nor desirable, see https://stackoverflow.com/questions/46493613/what-is-the-replacement-for-javax-activation-package-in-java-9.

> This is not desirable as this causes errors with many libraries

What happens exactly? Have you reached out maintainers of those other libraries? Are they even maintained?

**Comment by nddipiazza** [comment]
ahhh i see now. thanks for that link it educated me.

**Comment by slandelle** [comment]
You're welcome :)

Long story short: javax.activation packake shipped in JDK is going away and pulling `com.sun.activation:javax.activation:1.2.0` is the proper long term way.
