### ISSUE TITLE
How to define thread pool, or at least number of threads ?

### ISSUE THREAD

**Issue by maciejbak85** [AsyncHttpClient/async-http-client#1590]
Currently what I see is that maximum 16 threads is being created by an asyncHttpClient, how can I configure it ?

**Comment by slandelle** [comment]
Please use the mailing list and not the bug tracker for questions.
AHC uses 2*core threads for IO. It doesn't make sense to use more, you can't have more threads executing at a given time than you have cores.

**Comment by maciejbak85** [comment]
thank you for you answer. I understand correctly relation cores to max threads, but I want to minimize this number :)

**Comment by maciejbak85** [comment]
https://groups.google.com/forum/#!topic/asynchttpclient/qG49fdC4YUM
