### ISSUE TITLE
RequestBuilder.addQueryParam does not conform to the HTTP standard when it is a POST request

### ISSUE THREAD

**Issue by liuziangexit** [AsyncHttpClient/async-http-client#1598]
HTTP rules says, the key-value pairs should be placed in HTTP body if this request is a POST request.

Which means this is wrong(this is produced by async-http-client 2.0.7):
```
POST /post/chat?data=zzz&chat_time=zzzz HTTP/1.1 
Host: zzz.zzz.zzz
Accept: */* 
User-Agent: AHC/2.0 
 

```

A correct POST request should be like this: 
```
POST /post/chat HTTP/1.1 
Host: zzz.zzz.zzz
Accept: */* 
User-Agent: AHC/2.0 
 
data=zzz&chat_time=zzzz

```

My code is:
```
AsyncHttpClient httpclient = asyncHttpClient();
BoundRequestBuilder builder = httpclient.preparePost(aUrl.toExternalForm())
		                   .addQueryParam("uid", player.getAccountid())
                                   .addQueryParam("packageId", agent);
ListenableFuture<Response> future = builder.execute();

```

It is looks like a bug, or maybe i use async-http-client in a wrong way?

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
[2] https://tools.ietf.org/html/rfc7231#section-4.3.3

**Comment by slandelle** [comment]
You’re confusing POST and www-form-urlencoded encoding.
