### ISSUE TITLE
The request.getLocalAddress always return null

### ISSUE THREAD

**Issue by wuguangkuo** [AsyncHttpClient/async-http-client#1599]
Hi, when I trace the request/response object in the callback function，the request.getLocalAddress always return null，while the response.getLocalAddress return the local IP and Port info.

By the way，when the request execution throw some exception, would there be a possibility to get a response/request object with it's localAddress? I'm diagnosing the network exception，and I want to get localAddress when encounter this exception：
org.asynchttpclient.exception.RemotelyClosedException: Remotely closed

**Comment by wuguangkuo** [comment]
The version I'm using is 2.6.0

**Comment by slandelle** [comment]
There's some misunderstanding. `Request#getLocalAddress` is not populated by AHC, it's an option YOU can populate to force the local address.
