### ISSUE TITLE
addFormParams got wrong charset

### ISSUE THREAD

**Issue by jilen** [AsyncHttpClient/async-http-client#1602]
```scala
val builder = ahc
  .preparePost("xxx")
  .addFormParam("account", weixinId)
  .addFormParam("openid", req.openid)
  .addFormParam("remark", req.remark)
```
The server receive `???` if I input Chinese.

I had to urlencode it like 
```scala
val builder = ahc
    .preparePost("xxx")
    .setHeader("Content-Type", "application/x-www-form-urlencoded")
    .setBody(s"account=${weixinId}&openid=${req.openid}&remark=${enc(req.remark)}")
```

**Comment by jilen** [comment]
@slandelle https://travis-ci.org/jilen/ahc-cn/builds/470795478#L644 https://github.com/jilen/ahc-cn/blob/master/src/main/scala/Server.scala

**Comment by slandelle** [comment]
@jilen 

https://github.com/jilen/ahc-cn/blob/master/build.sbt#L6

You're running a very old version. Please use latest (2.6.0).

**Comment by jilen** [comment]
@slandelle Does 2.6.0 binary compatible with 2.0.x ?

**Comment by slandelle** [comment]
@jilen No. All the more as 2.1+ runs on top of Netty 4.1. Both AHC 2.0 and your old play version run on Netty 4.0 which is no longer maintained either.
In short, your whole stack is no longer maintained.
