### ISSUE TITLE
AsyncHandler  propagate netty channel for backpressure 

### ISSUE THREAD

**Issue by Zeymo** [AsyncHttpClient/async-http-client#1606]
Maybe inject netty channel in on `onBodyPartReceived` for slow client consumer in order to do channel.setAutoRead() operation ?

**Comment by slandelle** [comment]
Have you tried the reactive streams module?

**Comment by Zeymo** [comment]
reactive streams module just buffer body in queue，it not avoid OOM when client consumer slow. It's better to invoke netty origin channel.config().setAutoread(false) than buffer in the queue

**Comment by namiles** [comment]
I also am interested in having a backpressure mechanism

**Comment by namiles** [comment]
@Zeymo On using the reactive streams stuff that already exists in the library, it looks like AHC is properly handling backpressure. I am able to very slowly stream thousands of multi-gigabyte files concurrently with minimal heap usage and no issues. It sounds like you've got an issue with the rest of your code not propagating backpressure properly.

@slandelle I recommend closing this issue.

**Comment by slandelle** [comment]
@namiles Thanks for your feedback! closing
