### ISSUE TITLE
does this version support sending gzipped requests? 

### ISSUE THREAD

**Issue by ormalca1** [AsyncHttpClient/async-http-client#1607]
I read a lot but still didn't manage to understand if this version  support sending gzipped requests? 

second question - i understand that adding the accept-encoding header (by either setCompressionEnforced or setCompressionEnabled in com.ning.http.client 1.8.3) but does it also decompress the responses we get? i believe it does but i would like to verify that is also works in the older version (1.8.3)

thank you!

**Comment by slandelle** [comment]
Please use the mailing list, this is a bug tracker.
