### ISSUE TITLE
How to disable hostname verification in AsyncHttpClient

### ISSUE THREAD

**Issue by rdhabalia** [AsyncHttpClient/async-http-client#1611]
### Issue
We would like to use secure tls connection over HTTPS but we just want to disable hostname verification for the server certs. 
I can see that #197 PR introduced a way to disable hostname verification but later this option has been removed. Now, I don't see a way to specifically disable hostname-verification. 
I can see two options to [allowInsecureConnection](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/AsyncHttpClientConfig.java#L233) and [isDisableHttpsEndpointIdentificationAlgorithm](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/AsyncHttpClientConfig.java#L233) but that can disable other things including hostname-verification which we want to avoid.

### Question
So, can anyone suggest right way to disable Hostname verification in http-client.

**Comment by rdhabalia** [comment]
@slandelle not sure but could you be able to provide your suggestion for this issue?

**Comment by rdhabalia** [comment]
@slandelle ??

**Comment by cxzhang2** [comment]
any updates on this?

**Comment by slandelle** [comment]
https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/AsyncHttpClientConfig.java#L238
