### ISSUE TITLE
version of jdk6 ？

### ISSUE THREAD

**Issue by zhongzunfa** [AsyncHttpClient/async-http-client#1619]
I want to know which version of jdk6 is compiled.
Where can I see？

**Comment by slandelle** [comment]
Please use the mailing list for questions, not the bugtracker.

JDK6 was dropped a long time ago and is definitively not a target here, neither is Android if that's what you're arming for. If so, I advice you use a different library.

**Comment by zhongzunfa** [comment]
I feel very sorry commit issue, the question is my code complied jdk 1.6 so maven package having error错误的类文件： org/asynchttpclient/AsyncHttpClient.class(org/asynchttpclient:AsyncHttpClient.class)
[ERROR] 类文件具有错误的版本 52.0，应为 50.0
