### ISSUE TITLE
ESTABLISHED question about asyncHttpClient

### ISSUE THREAD

**Issue by losye** [AsyncHttpClient/async-http-client#1624]
i found two AsyncHttpClient object will effect each other.
when i use one of AsyncHttpClient to execute request with 300qps(172.11.22.33:80) , it handle about 40 "ESTABLISHED" connection.
meanwhile,   i use another AsyncHttpClient to execute request with 1000qps(differenct ip + port)
then,  i found   it handle about 300+ "ESTABLISHED" connection(172.11.22.33:80 )

why?  it be related to os system  ?

**Comment by slandelle** [comment]
Please use the community mailing list for questions, not the bug tracker.

No idea why you use 2 different AHC instances.
The number of concurrent connections depends on how many concurrent requests you have in peak.
If you have a 1s response time, you need 1000 connections to perform 1000rps (with HTTP/1.1)
