### ISSUE TITLE
High QPS requests case timeout task backlog in taskqueue

### ISSUE THREAD

**Issue by hadyang** [AsyncHttpClient/async-http-client#1625]
After run some hours, the old generation is full, memory dump result below:

![image](https://user-images.githubusercontent.com/19161326/54476115-6dd9cb80-4834-11e9-98e3-e3f922a79930.png)

Looks like becase of task too many, worker can't consume these. Is any way to fix it ?

**Comment by slandelle** [comment]
You’re sending requests way too fast for your OS/network/peer.
You have to introduce some sort of back pressure mechanism.
