### ISSUE TITLE
Unable to use SignatureCalculator or RequestCustomizer in Retrofit extras

### ISSUE THREAD

**Issue by aefimov** [AsyncHttpClient/async-http-client#1629]
The class `org.asynchttpclient.extras.retrofit.AsyncHttpClientCall` is package visible. You cannot use builder from it to use `callCustomizer`.
Also the sample from https://github.com/AsyncHttpClient/async-http-client/tree/master/extras/retrofit2 is wrong, that code is not compilable.

Invocation of setSignatureCalculator on httpClient before using in call factory is also does not work, cos request builder used in Retrofit simple ignored it.

So, for today on version `2.8.1` it is unable to intercept requests and modify it if Retrofit used.

**Comment by namiles** [comment]
Not sure what you mean about the code not being compilable. Compiles fine for me. Can you be more specific?

**Comment by aefimov** [comment]
```

**Comment by slandelle** [comment]
I personally don’t use Retrofit. Would you be interested in contributing a fix?

**Comment by aefimov** [comment]
Ok, let me try

**Comment by slandelle** [comment]
@aefimov ping
