### ISSUE TITLE
Getting java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by sunny1974** [AsyncHttpClient/async-http-client#1631]
Im using Async http client to send messages to twitter server. But randomly im getting connection reset by peer issue after some everything works fine. Can somebody tell me why im getting this issue.

I'm using below jar files:
httpasyncclient-4.1.3.jar
httpclient-4.5.3.jar
httpcore-4.4.6.jar
httpcore-nio-4.4.6.jar
httpmime-4.5.3.jar

**Comment by slandelle** [comment]
Wrong library, here is not apache http client.
