### ISSUE TITLE
Broken file while writing from LazyResponseBodyPart to AsynchronousFileChannel

### ISSUE THREAD

**Issue by Birthright50** [AsyncHttpClient/async-http-client#1634]
For download file from remote host and save to file I used default `ResponseBodyPartFactory.EAGER` and  `AsynchronousFileChannel` so as not to block the netty thread as data arrives. But as my measurements showed, in comparison with `LAZY` the memory consumption in the Java heap increases many times over.

So I decided to go straight to `LAZY`, but did not consider the consequences for the files.

This code will help to reproduce the problem.:
   ```java
 public static class AsyncChannelWriter {
        private final CompletableFuture<Integer> startPosition;
        private final AsynchronousFileChannel channel;

        public AsyncChannelWriter(AsynchronousFileChannel channel) throws IOException {
            this.channel = channel;
            this.startPosition = CompletableFuture.completedFuture((int) channel.size());
        }

        public CompletableFuture<Integer> getStartPosition() {
            return startPosition;
        }

        public CompletableFuture<Integer> write(ByteBuffer byteBuffer, CompletableFuture<Integer> currentPosition) {
            return currentPosition.thenCompose(position -> {
                CompletableFuture<Integer> writenBytes = new CompletableFuture<>();
                channel.write(byteBuffer, position, null, new CompletionHandler<Integer, ByteBuffer>() {
                    @Override
                    public void completed(Integer result, ByteBuffer attachment) {
                        writenBytes.complete(result);
                    }

                    @Override
                    public void failed(Throwable exc, ByteBuffer attachment) {
                        writenBytes.completeExceptionally(exc);
                    }
                });
                return writenBytes.thenApply(writenBytesLength -> writenBytesLength + position);
            });
        }

        public void close(CompletableFuture<Integer> currentPosition) {
            currentPosition.whenComplete((position, throwable) -> IOUtils.closeQuietly(channel));
        }
    }

    public static void main(String[] args) throws IOException {
        final String filepath = "/media/veracrypt4/files/1.jpg";
        final String downloadUrl = "https://m0.cl/t/butterfly-3000.jpg";

        final AsyncHttpClient client = Dsl.asyncHttpClient(Dsl.config().setFollowRedirect(true)
                .setResponseBodyPartFactory(AsyncHttpClientConfig.ResponseBodyPartFactory.LAZY));
        final AsynchronousFileChannel channel = AsynchronousFileChannel.open(Paths.get(filepath), StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        final AsyncChannelWriter asyncChannelWriter = new AsyncChannelWriter(channel);
        final AtomicReference<CompletableFuture<Integer>> atomicReferencePosition = new AtomicReference<>(asyncChannelWriter.getStartPosition());
        client.prepareGet(downloadUrl)
                .execute(new AsyncCompletionHandler<Response>() {

                    @Override
                    public State onBodyPartReceived(HttpResponseBodyPart content) throws Exception {
                        final CompletableFuture<Integer> currentPosition = atomicReferencePosition.get();
                        final CompletableFuture<Integer> newPosition = asyncChannelWriter.write(content.getBodyByteBuffer(), currentPosition);
                        atomicReferencePosition.set(newPosition);
                        return State.CONTINUE;
                    }

                    @Override
                    public Response onCompleted(Response response) {
                        asyncChannelWriter.close(atomicReferencePosition.get());
                        return response;
                    }
                });
```

in this case, the picture is broken. But if i use `FileChannel` instead of `AsynchronousFileChannel`, in both cases, the files come out normal. Can there be any nuances when working with `DirectByteBuffer` (in case with`LazyResponseBodyPart.getBodyByteBuffer()`) and `AsynchronousFileChannel`? Or is this some kind of bug?

**Comment by slandelle** [comment]
Your problem is not related to AHC but to your own code. You should probably try asking on stackoverflow.

My2cents: your logic is broken. `startPosition` is computed once and is the initial file size.

**Comment by Birthright50** [comment]
My code tracks the file position perfectly. If this were not the case, `EAGER` would not work either.
However, I decided to do another test with `LAZY` without tracking the position in the file. Just copy-paste.
```java
        final String filepath = "1.jpg";
        final String downloadUrl = "https://m0.cl/t/butterfly-3000.jpg";
        
        AsyncHttpClient client = Dsl.asyncHttpClient(Dsl.config().setFollowRedirect(true)
                .setResponseBodyPartFactory(AsyncHttpClientConfig.ResponseBodyPartFactory.LAZY));

        client.prepareGet(downloadUrl)
                .execute(new AsyncCompletionHandlerBase())
                .toCompletableFuture()
                .whenComplete((response, throwable) -> {
                    try {
                        final FileChannel open = FileChannel.open(Paths.get(filepath), StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
                        open.write(response.getResponseBodyAsByteBuffer());
                        open.close();
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                });
```
In this case, the file also turns out to be broken. Why is that? As I looked in the debug mode, NettyResponse contains an array of 511 `HttpResponseBodyPart`'s which contain identical objects`PooledSlicedByteBuf`. If i call `getBodyPartBytes` method, accordingly i get 511 identical data arrays.

Returning to the original problem, `PooledSlicedByteBuf` cannot be shared in another thread for appending buffer data to file, so the data should be immediately utilize in the `onBodyPartRecieved` method (as does `EAGER`, which copies data to `HeapByteBuffer`, and this `HeapByteBuffer` can pass to another thread), otherwise the netty thread changes it, and thus a broken file is obtained.

Is this a `LazyResponseBodyPart` class design issue? Or was it originally conceived?

**Comment by slandelle** [comment]
LAZY strategy was a kind of "internal" I implemented for Gatling. It's not intended for using with `getResponseBodyAsByteBuffer`. It's intended for using in an `AsyncHandler` where you would cast parts into `LazyResponseBodyPart` so you can directly read from `io.netty.buffer.ByteBuf` without involving extra copies.

**Comment by slandelle** [comment]
example:

```java
final String filepath = "1.jpg";
final String downloadUrl = "https://m0.cl/t/butterfly-3000.jpg";

try (AsyncHttpClient client = Dsl.asyncHttpClient(
  Dsl.config().setResponseBodyPartFactory(AsyncHttpClientConfig.ResponseBodyPartFactory.LAZY))) {
  client.prepareGet(downloadUrl)
    .execute(new AsyncHandler<Void>() {

      private FileChannel open;

      @Override
      public State onStatusReceived(HttpResponseStatus responseStatus) throws Exception {
        if (responseStatus.getStatusCode() != 200) {
          return State.ABORT;
        }

        open = FileChannel.open(Paths.get(filepath), StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
        return State.CONTINUE;
      }

      @Override
      public State onHeadersReceived(HttpHeaders headers) {
        return State.CONTINUE;
      }

      @Override
      public State onBodyPartReceived(HttpResponseBodyPart bodyPart) throws Exception {
        LazyResponseBodyPart lazyPart = (LazyResponseBodyPart) bodyPart;
        open.write(lazyPart.getBodyByteBuffer());
        return State.CONTINUE;
      }

      @Override
      public Void onCompleted() throws Exception {
        if (open != null) {
          open.close();
        }
        return null;
      }

      @Override
      public void onThrowable(Throwable t) {
        try {
          onCompleted();
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    }).get();
}
```

**Comment by Birthright50** [comment]
> example:
> 
> ```java
> final String filepath = "1.jpg";
> final String downloadUrl = "https://m0.cl/t/butterfly-3000.jpg";
> 
> try (AsyncHttpClient client = Dsl.asyncHttpClient(
>   Dsl.config().setResponseBodyPartFactory(AsyncHttpClientConfig.ResponseBodyPartFactory.LAZY))) {
>   client.prepareGet(downloadUrl)
>     .execute(new AsyncHandler<Void>() {
> 
>       private FileChannel open;
> 
>       @Override
>       public State onStatusReceived(HttpResponseStatus responseStatus) throws Exception {
>         if (responseStatus.getStatusCode() != 200) {
>           return State.ABORT;
>         }
> 
>         open = FileChannel.open(Paths.get(filepath), StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE);
>         return State.CONTINUE;
>       }
> 
>       @Override
>       public State onHeadersReceived(HttpHeaders headers) {
>         return State.CONTINUE;
>       }
> 
>       @Override
>       public State onBodyPartReceived(HttpResponseBodyPart bodyPart) throws Exception {
>         LazyResponseBodyPart lazyPart = (LazyResponseBodyPart) bodyPart;
>         open.write(lazyPart.getBodyByteBuffer());
>         return State.CONTINUE;
>       }
> 
>       @Override
>       public Void onCompleted() throws Exception {
>         if (open != null) {
>           open.close();
>         }
>         return null;
>       }
> 
>       @Override
>       public void onThrowable(Throwable t) {
>         try {
>           onCompleted();
>         } catch (Exception e) {
>           e.printStackTrace();
>         }
>       }
>     }).get();
> }
> ```
In fact, it was the first option that I tried. It works. But there is one nuance. the write operation blocks the netty processing thread, so I decided to use `AsynchronousFileChannel` to free the netty thread.

But as I understand it, this client does not store all incoming data in `PooledSliceByteBuf`, but overwrites it when this data arrives (so as not to run out of memory in direct buffer), so I cannot transfer it to another thread, because at this time it can be changed. It turns out there is only one way out. In the `onBodyPartRecieved` method, do copy this direct buffer to another? Is it possible and more effective than blocking disk write operation?

**Comment by slandelle** [comment]
There are several things you must take care of:

* ByteBuf and ByteBuffer can share content and ByteBufs are **pooled**. So you can't simply pass the ByteBuffer to a different thread. You would either need to copy or learn how to work with ByteBuf (retain it so it's not offered back to the pool right away and release it properly once written so you don't suffer from memory leaks)
* properly compute position. I'm pretty sure your solution is racy because you assume read -> finish write -> read sequence.
* properly wait for all the chunks to be saved on disk

**Comment by Birthright50** [comment]
Thank you for such an answer. Finally, this code I was able to earn.
Example without tracking with `ComplatableFuture`.
But still there is an incomprehensible point, in this case it is not clear what the difference between `copy`, `retain`, `retainedDuplicate` methods? Is there a difference in terms of efficiency?
If it doesn't bother you, could you answer this question, which I also asked on [stackoverflow](https://stackoverflow.com/questions/56397766/java-asynchttpclient-broken-file-while-writing-from-lazyresponsebodypart-to-asy)? Many people are interested in this recording feature without using java heap byte buffer.
```java
    public static void main(String[] args) throws IOException {
        final String filepath = "1.jpg";
        final String downloadUrl = "https://m0.cl/t/butterfly-3000.jpg";
        final AsyncHttpClient client = Dsl.asyncHttpClient(Dsl.config().setFollowRedirect(true)
                .setResponseBodyPartFactory(AsyncHttpClientConfig.ResponseBodyPartFactory.LAZY));
        final ExecutorService executorService = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors() * 2);
        final AsynchronousFileChannel channel = AsynchronousFileChannel.open(Paths.get(filepath), new HashSet<>(Arrays.asList(StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE)), executorService);
        final AtomicLong filePosition = new AtomicLong(channel.size());
        client.prepareGet(downloadUrl)
                .execute(new AsyncCompletionHandler<Response>() {
                    @Override
                    public State onBodyPartReceived(HttpResponseBodyPart content) {
                        final ByteBuf byteBuf = ((LazyResponseBodyPart) content).getBuf().copy();
                        final boolean isLast = content.isLast();
                        channel.write(byteBuf.nioBuffer(), filePosition.getAndAdd(byteBuf.readableBytes()), byteBuf, new CompletionHandler<Integer, ByteBuf>() {
                            @Override
                            public void completed(Integer result, ByteBuf attachment) {
                                attachment.release();
                                if(isLast){
                                    IOUtils.closeQuietly(channel);
                                }
                            }
                            @Override
                            public void failed(Throwable exc, ByteBuf attachment) {
                                attachment.release();
                                exc.printStackTrace();
                            }
                        });
                        return State.CONTINUE;
                    }

                    @Override
                    public Response onCompleted(Response response) {
                        return response;
                    }
                });
    }
```

**Comment by slandelle** [comment]
> final AtomicLong filePosition = new AtomicLong(channel.size());

You don't need this. A given AsyncHandler is always execute by the same Netty thread.

> final ByteBuf byteBuf = ((LazyResponseBodyPart) content).getBuf().copy();

Just retain the byteBuf so it's not offered to the pool until you release in CompletionHandler. You don't need to copy.

> If it doesn't bother you, could you answer this question, which I also asked on stackoverflow?

I'm done with being bullied by the modos there.
