### ISSUE TITLE
A typo in the README file

### ISSUE THREAD

**Issue by maseev** [AsyncHttpClient/async-http-client#1640]
From the [README.md](https://github.com/AsyncHttpClient/async-http-client#basics-1) file:

> AHC provides 2 APIs for defining requests: bound and unbound. AsyncHttpClient and **Dls**` provide methods for standard HTTP methods (POST, PUT, etc) but you can also pass a custom one.

I'm not sure, but it looks like it should be ```Dsl``` and not ```Dls```.

**Comment by slandelle** [comment]
Thanks for reporting
