### ISSUE TITLE
Android Compatibility

### ISSUE THREAD

**Issue by BerkerD** [AsyncHttpClient/async-http-client#1642]
Does AHC support android?

**Comment by slandelle** [comment]
Please ask questions on our mailing list, not on our bugtracker.

**Comment by prayagupd** [comment]
figured AHC is not for android yet - https://github.com/AsyncHttpClient/async-http-client/issues/1681#issuecomment-562987155

android related questions - https://github.com/AsyncHttpClient/async-http-client/issues?q=is%3Aissue+android+is%3Aclosed
