### ISSUE TITLE
Multi-part Request body is not kept after 307 Redirects

### ISSUE THREAD

**Issue by prabhash1785** [AsyncHttpClient/async-http-client#1643]
In my current usage of async-http-client, I notice that multi-part request body is not kept after server sends a 307 redirect for HTTP Post. It does keep request body for non-multi part data though.

We are using Async Http Client lib Version: 2.2.0

Multi Part Request data is:
Part 1: jsonpart string
Part 2: byte array of mime data

Multi-part data is set as follows:
```
Request request = new RequestBuilder(Methods.POST)
                       .addBodyPart(jsonPart)
                       .addBodyPart(mimePart)
```

Looking at this code, I don't see 307Interceptor is setting MultiPart data. I am hoping I am looking at the right place.
https://github.com/AsyncHttpClient/async-http-client/blob/6e4c1a6eb8a33964aa181721aa96b80f69c3b7bf/client/src/main/java/org/asynchttpclient/netty/handler/intercept/Redirect30xInterceptor.java#L102-L114

**Comment by slandelle** [comment]
Thanks for reporting
