### ISSUE TITLE
javax.net.ssl.SSLException: SSLEngine closed already

### ISSUE THREAD

**Issue by unoexperto** [AsyncHttpClient/async-http-client#1645]
Hi @slandelle. I've been haunted by this exception for couple years at least and after preliminary investigation I have feeling that AHC uses single `SSLEngine` for all instances of `DefaultAsyncHttpClient` class. Which means as soon as some bad domain botches it http clients of entire app stop working.

Exception is thrown in `io.netty.handler.ssl.SslHandler.wrap(ChannelHandlerContext ctx, boolean inUnwrap)` in line

```
if (result.getStatus() == Status.CLOSED) {
    buf.release();
    buf = null;
    promise.tryFailure(SSLENGINE_CLOSED);
    promise = null;
    // SSLEngine has been closed already.
    // Any further write attempts should be denied.
    pendingUnencryptedWrites.releaseAndFailAll(ctx, SSLENGINE_CLOSED);
    return;
}
```

And the moment it happens it's pretty much game over for the client. All subsequent attempts to send request simply hang.

Could you please clarify how it works currently and what to do?

**Comment by slandelle** [comment]
> I have feeling that AHC uses single SSLEngine for all instances of DefaultAsyncHttpClient class.

No, it creates a new SSLEngine [for each connection](https://github.com/AsyncHttpClient/async-http-client/blob/4803ab464b620f7b14c56d6d2cda4bc99d518485/client/src/main/java/org/asynchttpclient/netty/channel/ChannelManager.java#L330).

> Could you please clarify how it works currently and what to do?

1. Upgrade to latest JDK in case of a JDK nug
2. Upgrade to latest AHC is case it's a Netty bug
3. Switch to netty-tcnative, eg with BoringSSL static
4. Provide a way to reproduce

**Comment by unoexperto** [comment]
> Switch to netty-tcnative, eg with BoringSSL static

Just tried. Same outcome.

> Provide a way to reproduce

I'll try to create isolated example tomorrow. But I'm pretty sure it will occur quickly if you call https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=pubmed&id=30789216&cmd=neighbor_score&retmode=json couple thousand times. That's pretty much what my project does.

In the mean time could you please suggest workaround ? Why SSLEngine never recovers ? Can I forcibly initialize it right after I catch the exception?

**Comment by slandelle** [comment]
I suspect the problem has something to do with request retry.
It looks like your server frequently crashes connections (set max request retry to 0 and loop on the provided url with a 10ms pause and you’ll quickly see it).

**Comment by slandelle** [comment]
I'm afraid you'll have to provide a reproducer. I can't hammer your url because of your rate limiter.

**Comment by unoexperto** [comment]
> I'm afraid you'll have to provide a reproducer. I can't hammer your url because of your rate limiter.

@slandelle Here we go
https://github.com/unoexperto/bug-ahc-ssl-exception

It includes private API key (it's not my API btw) so rate limit is 10 calls / second.

I guess how quickly it reproduces is pretty random. First time it took me only couple minutes to get the exception. Now it's been running for 7 and is still going.

In my production it takes ~30-50 mins to get to faulty state.

**Comment by slandelle** [comment]
@unoexperto I think I've fixed it. Is there any chance you can build from sources and try on your side?

**Comment by unoexperto** [comment]
@slandelle One test fail so I can't build it.

```
Tests run: 871, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 168.491 sec <<< FAILURE! - in TestSuite
testGetCompleteServicePrincipalName(org.asynchttpclient.spnego.SpnegoEngineTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.asynchttpclient.spnego.SpnegoEngineTest.testGetCompleteServicePrincipalName(SpnegoEngineTest.java:138)
```

Is there maven command besides `package` I can use to build jars ?

**Comment by slandelle** [comment]
mvn package -Dmaven.test.skip

**Comment by unoexperto** [comment]
7 days of running in production - no issues. Thanks!

**Comment by slandelle** [comment]
Great news, thanks for your feedback!
