### ISSUE TITLE
Set ChannelManager.AHC_WS_HANDLER to run in another EventExecutorGroup

### ISSUE THREAD

**Issue by bahui80** [AsyncHttpClient/async-http-client#1647]
Hi, 

We are using AsyncHttpClient library for WebSocket transport. We were having an issue and we needed the `ChannelManager.AHC_WS_HANDLER` to run in another thread since we had some of the incoming requests taking too long. 
We still wanted to be able to send outgoing requests via the WebSocket even if the incoming pipeline was busy. 

One solution we found to this was the following:
```
EventExecutorGroup inboundExecutor = new DefaultEventExecutorGroup(50, runnable -> new Thread(runnable, "InboundExecutor"));

AsyncHttpClient client = new DefaultAsyncHttpClient(new DefaultAsyncHttpClientConfig.Builder()
.setWsAdditionalChannelInitializer(channel -> {
                        ChannelPipeline pipeline = channel.pipeline();
                        ChannelHandler channelHandler = pipeline.get(ChannelManager.AHC_WS_HANDLER);

                        pipeline.remove(ChannelManager.AHC_WS_HANDLER);
                        pipeline.addLast(inboundExecutor, ChannelManager.AHC_WS_HANDLER, channelHandler );
                    })
.build());
```

I don't like that much the idea of removing the pipeline and adding it back with a new executor.

So I was thinking of sending a PR changing the class `ChannelManager` to be able to add a custom executor via configuration on the builder (a map or something like that) when adding the pipelines to the ChannelPipeline:

```
wsBootstrap.handler(new ChannelInitializer<Channel>() {
      @Override
      protected void initChannel(Channel ch) {
        ChannelPipeline pipeline = ch.pipeline()
                .addLast(HTTP_CLIENT_CODEC, newHttpClientCodec())
                .addLast(AHC_WS_HANDLER, wsHandler);
```

Thanks in advance

**Comment by slandelle** [comment]
> since we had some of the incoming requests taking too long

I don't get it. Do you mean you perform blocking operations in the WebSocket handler? If so, your issue is here and you should delegate such operation to another thread pool.

**Comment by bahui80** [comment]
Yes, we have a blocking operation and we can't change that. We are depending on some business logic that works like this.

Anyways, reading some questions about Netty on Internet, some people recommend using a different `EventExecutorGroup` for inbound and outbound Channels.

Since the `ChannelManager.AHC_WS_HANDLER` is initialized in the ChannelManager class, I would like to be initialized with a different EventExecutorGroup

**Comment by slandelle** [comment]
> Yes, we have a blocking operation and we can't change that. We are depending on some business logic that works like this.

You must then offload this blocking operation to a dedicated threadpool instead of performing it directly in the handler.
