### ISSUE TITLE
Program hangs when prepareGet.execute.toCompletableFuture is used inside thenCompose call

### ISSUE THREAD

**Issue by nikita-mospan** [AsyncHttpClient/async-http-client#1651]
Hi.

Could you please explain whether the following behavior is expected: if I try to compose some CompletableFuture (in the code it is called start) with asynchronous http request that is wrapped into CompletableFuture via toCompletableFuture() API then the program hangs and I didn't manage to find the root cause. Example code is below:
```
package mospan;

import java.io.IOException;
import java.util.concurrent.*;

import org.asynchttpclient.*;

public class HttpClientExample {

    public static void main(String[] args) throws IOException {

        final String url = "https://www.google.com/";

        try (AsyncHttpClient client = Dsl.asyncHttpClient()) {
            CompletableFuture<Void> start = new CompletableFuture<>();
            final CompletableFuture<Void> future =
                    start.thenCompose(nil -> client.prepareGet(url)
//                    client.prepareGet(url)
                            .execute()
                            .toCompletableFuture()
                    )
                            .thenAccept(response -> {
                                final String body = response.getResponseBody();
                                System.out.println("body = " + body.length() + " [" + Thread.currentThread().getName() + "]");
                            })
                            .thenRun(() -> System.out.println("Done!"));

            future.join();
        }

    }

}
```

If I do not use composition of futures, i.e. comment line 17, uncomment line 18 and comment line 21 then everything works as expected. May be the problem is in interaction between Common Fork Join Pool and thread pool used by AsyncHttpClient, but I didn't mange to figure out firm explanation on that.

Thank you for help.

**Comment by slandelle** [comment]
Your example is broken. You never complete `start` so `thenCompose` is never called and `join` blocks forever.
You have to call `start.complete(null);` just before `future.join();`.

**Comment by nikita-mospan** [comment]
Yes, my bad, sorry.

Thank you for paying attention.
