### ISSUE TITLE
Problems with ° character JSON upload

### ISSUE THREAD

**Issue by paulfemiak** [AsyncHttpClient/async-http-client#1654]
One of the text fields inside of my JSON upload payload contains a ° character. This triggers 500 error response scenario.

**Comment by slandelle** [comment]
I see you're into mobile apps, so I'm pretty sure you're not using this project that doesn't support Android but this one: https://loopj.com/android-async-http/. If I'm correct, please close this issue and report to the proper project.
Otherwise, please provide a sample to reproduce

**Comment by paulfemiak** [comment]
Sorry about that and thank you for pointing me in the right direction @slandelle.
