### ISSUE TITLE
Basic Auth doesn't work

### ISSUE THREAD

**Issue by GautamaBuddha** [AsyncHttpClient/async-http-client#1655]
DefaultHeaders class calculates same index for `Authorization` and `accept` headers. 
NettyRequestFactory on the first step adds `Authorization` header after that is set `accept` to the same position in `entries` array. 

![image](https://user-images.githubusercontent.com/1217820/62040348-1c8a1180-b202-11e9-9e17-2fc8e3d9c524.png)
![image](https://user-images.githubusercontent.com/1217820/62040391-39264980-b202-11e9-838f-407d9f9b8c4f.png)

after `accept` is set we don't have `Authorization` header:
![image](https://user-images.githubusercontent.com/1217820/62040537-7db1e500-b202-11e9-8a77-4f6ee137bb0d.png)

**Comment by slandelle** [comment]
This class is from netty.
If you think you’ve found a bug, please report there, and provide a test case to reproduce and the version of netty you’re using.
