### ISSUE TITLE
Granular request timeout exception detail (I need the full path of the url)

### ISSUE THREAD

**Issue by cosmir17** [AsyncHttpClient/async-http-client#1661]
I use Akka actor. I fire http requests to different endpoints (using your framework).

When a request times out, it just shows, www.domain.com
it doens't show the full path so that I don't know which request got timed out.

Is there way to make request timeout exception more granular to include the full path? (java.util.concurrent.TimeoutException).

P.S. I also want 'java.net.ConnectException' to have detailed paths too, but the timeout is much more important.

**Comment by slandelle** [comment]
Please use the community mailing list (see README) for questions, not the bug tracker.

**Comment by cosmir17** [comment]
@slandelle Hi, this can be a new feature(setting option) if it's not already threre.
Anyway, did you mean the Google group when you said 'the community mailing list'?
