### ISSUE TITLE
How can i disable the log default?

### ISSUE THREAD

**Issue by M1178475702** [AsyncHttpClient/async-http-client#1668]
When i make a request, there are always a lot of logs and even a request message printed when the request is complete.
I want to disable those logs, are there any methods? Any help will be appreciate!

**Comment by M1178475702** [comment]
I want to disable the log as the following:
![0Q}~01IIL}BU88C_ Y )MNR](https://user-images.githubusercontent.com/42426867/66705570-0e588580-ed5b-11e9-8cad-54c0b10dd536.png)
![XW(KE`(WX _W83`}L$}TIOP](https://user-images.githubusercontent.com/42426867/66705571-0ef11c00-ed5b-11e9-9fc4-4cfd0646e7d8.png)

**Comment by slandelle** [comment]
You have to provide a slf4j backend such as logback in the classpath and configure it properly.

**Comment by slandelle** [comment]
Next time, please use the Google Group for questions, this is a bug tracker.
