### ISSUE TITLE
Client re-building a request prevents usage of custom requests

### ISSUE THREAD

**Issue by kringol** [AsyncHttpClient/async-http-client#1672]
Currently the client is creating a new RequestBuilder(prototype) on some cases like
- When there are cookies on the storage for that uri
- When the range offset is not 0

Problem is we are using some custom filters that rely on us using an extended implementation of Request.java which adds some extra settings which the filter consumes. Normally it works fine, and the filter checks if the request instance is of our type and extracts those. But due to the mentioned behavior we are loosing our custom implementation on the way when there are cookies for example. 

We can contribute with some changes to overcome if you are open to it.
Proposed solution: 
Instead of having a RequestBuilder(prototype) on the client, have something like request.builder(), which will do the same but we can override on our request implementation to use a builder that will take our extra settings into account.

**Comment by slandelle** [comment]
Sure, please do send a PR.

**Comment by kringol** [comment]
> Sure, please do send a PR.

Thanks @slandelle, I've submitted a PR and left some comments for you there as well
