### ISSUE TITLE
builder setLocalAddress does not work in a multiple network interfaces environment

### ISSUE THREAD

**Issue by vlad4800** [AsyncHttpClient/async-http-client#1674]
I have a device with two network interfaces: eth0 and wlan0. The interfaces receive an IP via DHCP from different pools. Thus the eth0 interface has something like: 10.0.x.x and wlan0 has 192.168.x.x

I want to bind all HTTP requests fromAHC to go via the wlan0 interface so I used:

```
DefaultAsyncHttpClientConfig.Builder builder = new DefaultAsyncHttpClientConfig.Builder()
builder.setLocalAddress(interfaceIp);
```
`interfaceIp` is the wlan0 InetAddress.

The problem is that all requests fail(connect timeout).

There is a similar issue with `curl` where if you don't specify _both_ the interface and ip address your packets will bind to that ip, but will route via eth0 if eth has a lower metric defined on that device.

So `curl -4v --interface 192.168.x.x http://google.com` doesn't work, but `curl -4v --interface wlan0 192.168.x.x http://google.com` works.

Is there a way to be able to specify the interface name instead of the IP? Or both?

P.S. If both eth0 and wlan0 have IPs from the same DHCP pool then all seems to work!

**Comment by slandelle** [comment]
`setLocalAddress(InetAddress)` boils down to calling `java.nio.channels.SocketChannel#bind(SocketAddress)`.

So I'm sorry, but if you really have a bug, it's in the JRE.
Closing as there's really nothing we can do here.
