### ISSUE TITLE
Tuning params not affecting performance

### ISSUE THREAD

**Issue by tomerz90** [AsyncHttpClient/async-http-client#1676]
I have a use case where Im downloading 21GB in about 1400 files.
I have 40 IO threads (tried with 16 also with same results) and Im downloading 60 files simultaneously.
Im running on 16 CPUs and its on 100% the entire download.
I tried playing around with all kinds of params, probably everything you can set in the config and it seemed to have no effect on performance, good or bad.
Is there a config I can use to save up on CPU and by that improve the performance in terms for download speed?
Can it be that this client is just not built for max performance and so there was so "wasteful" areas?
If so, and any specific areas come to mind, would appreciate letting me know so I can maybe fork a version of my own, or maybe you can add a flag to turn these off, stuff like validations that take up CPUs and they may not be needed if raw performance is the target.

Thanks!

**Comment by slandelle** [comment]
No idea what you do.
This client was used in [Gatling](https://gatling.io/) until version 3, so it's really intended for performance.
