### ISSUE TITLE
Trying to use OpenSSL throws NoClassDefFoundError

### ISSUE THREAD

**Issue by tomerz90** [AsyncHttpClient/async-http-client#1677]
I set `useOpenSsl` to true in the config and when trying to run I get:
```Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLPrivateKeyMethod
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more
```
I tried adding the `netty-tcnative` dependency but there seems to be a version mismatch since I get a different error and I dont know which version would work

**Comment by slandelle** [comment]
`netty-tcnative` is only a parent jar.

Import `netty-tcnative-boringssl-static` instead.

**Comment by tomerz90** [comment]
Why boringssl? Is there no option to use OpenSSL? (I know boringssl is a branch of OpenSSL)

**Comment by slandelle** [comment]
Please read Netty's documentation for the different options: https://netty.io/wiki/forked-tomcat-native.html
