### ISSUE TITLE
setMaxConnections don not work

### ISSUE THREAD

**Issue by hengyuan** [AsyncHttpClient/async-http-client#1678]
my config is like this:
DefaultAsyncHttpClientConfig config = Dsl.config()
				.setRequestTimeout(60000)
				.setConnectTimeout(60000)
				.setMaxRequestRetry(3)
				.setMaxConnections(2)
				.setMaxConnectionsPerHost(5)
the "AsyncHttpClient" Thread count growth to a bigger number
how to control threads count

**Comment by slandelle** [comment]
No idea what you do, but number of connections and number of threads are unrelated. Number of threads in AHC is 2 * cores for IO + 1 for scheduling.
