### ISSUE TITLE
Can this project used in an android project?

### ISSUE THREAD

**Issue by M1178475702** [AsyncHttpClient/async-http-client#1681]
If can, please look the bug following:
when i use this project in my android project, it throw the exception like this:
![image](https://user-images.githubusercontent.com/42426867/70393110-e9625500-1a21-11ea-9653-ff0682c32c2b.png)
![image](https://user-images.githubusercontent.com/42426867/70393122-026b0600-1a22-11ea-9beb-0a1972f66697.png)
When i use it in a plain java project, it is normal work.
I have install its dependencies all by gradle.It also contain the slf4j, so i can't understand this exception.
![image](https://user-images.githubusercontent.com/42426867/70393159-4e1daf80-1a22-11ea-8613-e26e7340a022.png)
Any help will be appreciate!

**Comment by slandelle** [comment]
Sorry, but this library doesn't aim at supporting Android:
* it's not tested on Android
* no contributor has ever helped with this
* Google choose to not port the whole Java API. For example, try looking for https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String) in the Android SDK...
