### ISSUE TITLE
websocket - gzip/deflate TextWebSocketFrame  through Proxy is not getting decompressed before consumed

### ISSUE THREAD

**Issue by zhp0260** [AsyncHttpClient/async-http-client#1689]
I have a situation :
Websocket ----> (proxy app:AsyncHttpClient) ----> Proxy ----> Origin Server( web site)
Ex: URL: wss://pshudws.365pushodds.com/zap/?uid=1234567890

While I can get the websocket message correctly when accessed without Proxy; the app shows (junk) gzip data when accessed the same pages through Proxy.

My proxy configuration doesn't unpack the gzip/deflate TextWebSocketFrame received from Origin. I think the AsyncHttpClient should decompress it, before the response is consumed downstream.

I read the source, I find websocket connect without proxy, use wsBootstrap object to handle it, when use proxy, use the httpBootstrap object to handle it. 

Could you please look into it, or suggest any workaround. Please let me know if you need more information.

thanks,
![1578360160(1)](https://user-images.githubusercontent.com/713002/71860881-5b1be480-312f-11ea-9c57-dc4174740092.png)

**Comment by slandelle** [comment]
Thanks for reporting
