### ISSUE TITLE
I'm probably misconfiguring, but... seeing curious behavior with max conns per host

### ISSUE THREAD

**Issue by marshallpierce** [AsyncHttpClient/async-http-client#1690]
Here's how I'm building the client:

```
        int timeout = 1000;
        var client = Dsl.asyncHttpClient(Dsl.config()
                .setConnectTimeout(timeout)
                .setReadTimeout(timeout)
                .setRequestTimeout(timeout * 2)
                .setUserAgent("foo")
                .setMaxConnectionsPerHost(50));
```

The workload has about 10-20 req/s per JVM. The 99%ile response time of the service it hits is 50ms. 50 connections per host seems like way overkill per Little's law (20 * .05 = 1, so hypothetically one connection would work), and yet I'm seeing this be thrown fairly often. Even if every request took the request timeout of 2s, that would be (20 * 2 = 40) connections. Any thoughts on where I should look? Thanks!

**Comment by slandelle** [comment]
Can't say without being able to reproduce. Could be that:
* you have sudden response time burst. How do you measure your response times? What's your max? Do you have 1s accuracy?
* you have a sudden burst in throughput. How do you measure it?
* there's a bug in AHC. Which version do you use?

**Comment by marshallpierce** [comment]
Understood. This service has an "interesting" setup for response time measurements (legacy, etc), and it could well be masking some short-time-window behavior. We're on 2.10.4. At this point I'm happy to blame system behavior that isn't measured well, so as long as there isn't some obvious thing I should be configuring but am not, I think I'll designate this not your problem. :) Thanks for the quick reply.

**Comment by slandelle** [comment]
Thanks for your feedback.
