### ISSUE TITLE
Getting null as Response in OnCompleted callback

### ISSUE THREAD

**Issue by tomerz90** [AsyncHttpClient/async-http-client#1691]
I created a handler that extends `AsyncCompletionHandler`, I tried following the code but got lost.
Im downloading a number of files and creating one handler per file.
I have also added a re-try mechanism that downloads this file again with the same handler:

```
@Override
  public State onStatusReceived(HttpResponseStatus status) throws Exception {
    if (!HttpStatusCodes.isSuccess(status.getStatusCode())) {
      retryOrFail(new FailedToDownloadException(status));
      return State.ABORT;
    }

    return super.onStatusReceived(status);
  }

  @Override
  public void onThrowable(Throwable t) {
    retryOrFail(t);
  }
```

`retryOrFail` create a new get request and calls `execute` with the handler used for the download that failed.
Im guessing Im just not supposed to re-use handlers for some reason, but would love to get your input about what exactly is going wrong.

**Comment by slandelle** [comment]
No idea what you do exactly without you providing a [SSCCE](http://sscce.org/).

Then, please use the community mailing list for such questions, not the bug tracker.

Regards
