### ISSUE TITLE
Transitive dependencies on different versions of `netty-handler`

### ISSUE THREAD

**Issue by ljwagerfield** [AsyncHttpClient/async-http-client#1696]
The `async-http-client:2.10.4` library introduces transitive dependencies on two different versions of `netty-handler`.

It seems AHC's direct dependencies on `netty-reactive-streams` and `netty-codec-http` introduce the problem: the former requires an older version of `netty-handler`.

**This adds compile-time warnings to SBT projects.**

I'm using SBT `1.3.6`.

Please see dependency graph below:

![image](https://user-images.githubusercontent.com/3638917/74087120-4d84b200-4a81-11ea-9a3f-71fb858a59dd.png)

**Comment by slandelle** [comment]
There’s no issue and the version indeed pulled is the most modern one.

**Comment by ljwagerfield** [comment]
> There’s no issue and the version indeed pulled is the most modern one.

I'm not sure how you can say this?

Are you saying this because: a) you consider SBT warnings to be ignorable, or b) you believe there's a bug in SBT's handling of transitive dependencies, such that it's throwing a false negative in this particular occasion? I'm unaware of such a bug in the latter instance -- please do enlighten me!

**/build.sbt**
```scala
libraryDependencies += "org.asynchttpclient" % "async-http-client" % "2.10.4"
```

**project/build.properties**
```scala
sbt.version = 1.3.6
```

**run this:**
```bash
sbt update
```

See the **compiler warning**.

**Comment by slandelle** [comment]
a) I’m familiar with Netty, Netty ia pretty strick with semver and you’re looking at differences in fix versions.

Generally speaking, those sbt warnings are quite often just noise, in particular when the differences are about fix versions, not even minor...

**Comment by ljwagerfield** [comment]
Thanks for the clarification 👍
