### ISSUE TITLE
App crashing with NullPointerException while using aynschttpclient as a shaded library.

### ISSUE THREAD

**Issue by harinirajendran** [AsyncHttpClient/async-http-client#1700]
When we start the app it crashes with the following stack trace when we use asynchttpclient as shaded library.
[2020-02-19 20:58:58,692] ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
java.lang.NumberFormatException: null
        at java.base/java.lang.Integer.parseInt(Integer.java:614)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at io.confluent.shaded.org.asynchttpclient.config.AsyncHttpClientConfigHelper$Config.getInt(AsyncHttpClientConfigHelper.java:85)
        at io.confluent.shaded.org.asynchttpclient.config.AsyncHttpClientConfigDefaults.defaultMaxRedirects(AsyncHttpClientConfigDefaults.java:134)
        at io.confluent.shaded.org.asynchttpclient.DefaultAsyncHttpClientConfig$Builder.<init>(DefaultAsyncHttpClientConfig.java:670)
        at io.confluent.shaded.org.asynchttpclient.Dsl.config(Dsl.java:83)

On further investigation, we found out that in AsyncHttpClientConfigDefaults.java, the following constant is defined.
public static final String ASYNC_CLIENT_CONFIG_ROOT = "org.asynchttpclient.";

When we compile the jar as fat jar with asynchttpclient as shaded jar, any occurrence of "org.asynchttpclient." gets replaced to "io.confluent.shaded.org.asynchttpclient." which is the shaded path for this library in our repo. As a result, value of ASYNC_CLIENT_CONFIG_ROOT gets changed to "io.confluent.shaded.org.asynchttpclient." causing null pointer exception as there is no config parameter starting with io.confluent.shaded.org.asynchttpclient. is present in ahc-defaults.properties.

Since shading the library is a common use case, I think we should handle that in asynchttpclient rather than having client create a separate ahc.properties file.

**Comment by slandelle** [comment]
> When we compile the jar as fat jar with asynchttpclient as shaded jar, any occurrence of "org.asynchttpclient." gets replaced to "io.confluent.shaded.org.asynchttpclient."

That's an issue with your shaded process. This String constant has nothing to do with the root package, it's just the prefix of the properties in the config file.

Play framework has been shading AHC and translating package for a long time without issue. In particular, config file location is resolved [in the same package of the helper class](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/config/AsyncHttpClientConfigHelper.java#L46) so it works fine when both are translated.

**Comment by sirianni** [comment]
True.  Translation of String constants does appear to be an issue, however, with both of the major shading tools for gradle and maven:
* https://github.com/johnrengelman/shadow/issues/338
* https://issues.apache.org/jira/browse/MSHADE-156

**Comment by slandelle** [comment]
Then you should not only translate the strings in the Java code but in the properties file too.
