### ISSUE TITLE
Asynchronous/non-blocking filter

### ISSUE THREAD

**Issue by avillev** [AsyncHttpClient/async-http-client#1703]
I have been using the Request filter for some time now and am running into an issue with rate-limiting (as shown here: https://jfarcand.wordpress.com/2010/12/21/going-asynchronous-using-asynchttpclient-the-basic/).

My API is fully reactive and the filter is using the caller's thread. Using a normal rate limiter will literally block the thread and potentially cause issues to the API.

I considered using some kind of non-blocking rate limiter but then I noticed that, even if AHC is non-blocking, its filters are. It does not seem possible to do something before the http call in a non-blocking/reactive manner into RequestFilter.

Am I missing something? Or could we consider making the change?

**Comment by slandelle** [comment]
In a reactive app, you should be using the reactive streams API.
