### ISSUE TITLE
Support realm/authentication from Uri

### ISSUE THREAD

**Issue by dontgitit** [AsyncHttpClient/async-http-client#1707]
Hi,

I was curious if there are plans to support user:password authentication automatically from the request url. For instance, browsers and curl support something like `https://user:password@domain.com` - they seem to automatically translate that into basic user:password auth. Are there any plans to do that with AsyncHttpClient? It seems that if no `realm` is set explicitly, then maybe `RequestBuilderBase.build` can create one from `uri.userInfo` if it's present? Something along the lines of,

```java
private Realm computeRealm(Uri finalUri) {
  if (finalUri.getUserInfo() == null) { return null; }
  String[] parts = finalUri.getUserInfo().split(":", 2);
  if (parts.length == 2) {
    return new Realm.Builder(parts[0], parts[1]).setScheme(Realm.AuthScheme.Basic).build();
  } else {
    return null;
  }
}
```

and then inside `RequestBuilderBase.build`,

```java
Realm realm = rb.realm == null ? computeRealm(finalUri) : rb.realm;
return new DefaultRequest(..., realm, ...);
```

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by dontgitit** [comment]
Happy to contribute, but I just wanted to know if it's desired behavior or not. Even though curl and web browsers seem to support it, I think it might be deprecated/discouraged: 

https://tools.ietf.org/html/rfc3986#section-3.2.1
> Use of the format "user:password" in the userinfo field is deprecated. 

https://tools.ietf.org/html/rfc3986#section-7.5
> A password appearing within the userinfo component is deprecated and should be considered an error (or simply ignored)

Seems like it's insecure (if it's under `https` scheme), and is also potentially an attack vector - users might see a URL like http://www.google.com:search@example.com/, which is actually on the host example.com not google.com

**Comment by n-miles** [comment]
I don't think the client should be doing anything that the RFC says should be considered an error or ignored.

**Comment by dontgitit** [comment]
Yeah... for a moment I thought it might be nice to support since curl as well as browsers support it, but on further thought it's probably not a great idea.

**Comment by slandelle** [comment]
Sorry for the long delay (things are "complicated" on my side atm, just like lots of people I guess...).

Yeah, I think you're right, let's drop this.
