### ISSUE TITLE
Allow disabling cookie jar

### ISSUE THREAD

**Issue by ngbinh** [AsyncHttpClient/async-http-client#1714]
since https://github.com/AsyncHttpClient/async-http-client/commit/d4f1e5835b81a5e813033ba2a64a07b020c70007 ,I cannot disable CookieStore by ` new DefaultAsyncHttpClientConfig.Builder() .setCookieStore(null) ... .build()`. There are many usecases where we do not want ahc to handle Cookies. 

I am wondering if there should be a more official way of disabling cookie or at least adding a `null` check here https://github.com/AsyncHttpClient/async-http-client/blob/45b456129daa7136e6b32bb323f8d35232997a57/client/src/main/java/org/asynchttpclient/DefaultAsyncHttpClient.java#L96

**Comment by slandelle** [comment]
A regression indeed, thanks for reporting.

**Comment by ngbinh** [comment]
Thanks!
