### ISSUE TITLE
TooManyConnectionsPerHost Exception

### ISSUE THREAD

**Issue by aneeshkapur1** [AsyncHttpClient/async-http-client#1716]
I am upgrading from AHC 1.8.15 to AHC 2.9.0 while it works fine in all the cases, have successfully ported the code but there is a peculiar issue with the timeout scenarios. Whenever a certain request is timed out multiple times, it throws a TooManyConnectionsPerHostException. It could be a connection leak or can be something which was not properly ported by me. 

My Config for async client is

 DefaultAsyncHttpClientConfig.Builder builder = new DefaultAsyncHttpClientConfig.Builder();
        JsseSslEngineFactory sslEngineFactory = new JsseSslEngineFactory(sslContext);
        builder.setKeepAlive(true)
                .setSslEngineFactory(sslEngineFactory)
                .setAcquireFreeChannelTimeout(m_httpTimeout)
                .setCompressionEnforced(true)
                .setProxyServer(createProxy())
                .setMaxConnectionsPerHos(2)
                .setMaxConnections(m_maxConnections > 0 ? (int) (m_maxConnections * 1.5) : m_maxConnections)
                .setConnectTimeout(m_httpTimeout);
                 .setReadTimeout(2000);

I am using multiple callable threads and a booleanlistenablefuture to dispatch request to various URL's. I may need some guidance for this

**Comment by slandelle** [comment]
Please don't spam the mailing list and the bug tracker.

Connections limits are securities. They don't buffer requests when the limit is reached but reject the requests. It was always supposed to work this way but feature was broken in AHC 1 and requests could keep on opening new connections and bypass the limit.
