### ISSUE TITLE
Epoll/Kqueue optional

### ISSUE THREAD

**Issue by swimmesberger** [AsyncHttpClient/async-http-client#1717]
When using async-http-client in an OSGi environment and we do not want to use the native transport we have to ship with the io.netty:netty-transport-native-epoll, io.netty:netty-transport-native-kqueue and io.netty:netty-transport-native-unix-common dependencies even though they are not necessary.

We would prefer to use async-http-client with the default transport without the native dependencies. One way to fix this would be to markt these dependencies (and packages) in the maven-bundle-plugin as optional imports. (https://github.com/AsyncHttpClient/async-http-client/blob/master/pom.xml#L194)
Currently every dependency is imported as required the '*' symbol. It's possible to mark some of these packages as optional with following instructions:
`
io.netty.channel.kqueue;resolution:=optional,io.netty.channel.epoll;resolution:=optional
`

**Comment by slandelle** [comment]
Contributions welcome

**Comment by swimmesberger** [comment]
Made PR #1718

**Comment by slandelle** [comment]
Thx
