### ISSUE TITLE
InputStream lost on 308 redirect, ByteArray not

### ISSUE THREAD

**Issue by christiangroth** [AsyncHttpClient/async-http-client#1720]
Hi everybody,

I'm currently fiddling around with AHC and multipart requests. So far so good and everything is fine. However there is a special case were a PUT request gets a HTTP 308 response and in this case the second request does not send the body anymore. I've seen that this should work according to https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/netty/handler/intercept/Redirect30xInterceptor.java

I'm using the following code to create the Request:

    BoundRequestBuilder requestBuilder = client.preparePut(url);
    requestBuilder
        .addBodyPart(new StringPart("properties", properties, "application/json"))
        .addBodyPart(new InputStreamPart("xxx", data, "xxx"));

If I do not provide the data as InputStream but read all bytes into memory everything works fine, also following the HTTP 308 redirect.

    BoundRequestBuilder requestBuilder = client.preparePut(url);
    try {
        byte[] dataBytes = new byte[data.available()];
        data.read(dataBytes);
        requestBuilder
            .addBodyPart(new StringPart("properties", properties, "application/json"))
            .addBodyPart(new ByteArrayPart("xxx", dataBytes, null, StandardCharsets.UTF_8, "xxx"));
        } catch (IOException e) {
            Logging.logError("Unable to read data for media to be published to " + url + "!", e, getClass());
    }

So my question is: Are redirects not supported when streaming the media content using an InputStream or am I doing something wrong or is this a bug?

Bets regards
  Chris

**Comment by slandelle** [comment]
Yes, you are doing something wrong.

The network is not instantaneous.
If your server choses to respond early without waiting for having received the full request, including its body, there's a very good chance the user-agent has already started writing the request body on its side of the socket.
If your request body is/contains an InputStream, it has already been consumed and can't be regenerated.

There's no way to handle this gracefully. Period.

Protecting against the possibility of the server performing an early response is exactly what [Expect-Continue](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100) is for.

**Comment by christiangroth** [comment]
Hi, 

one last question / suggestion on this: Would it be possible to implement a InputStreamProviderPart instead of an InputStreamPart? The InputStreamProviderPart would use a Lamba to create a fresh InputStream every time it's needed. 

I could implement the class InputStreamProviderPart myself, but as fas as I see in the code this won't work because there is an if-else construct in org.asynchttpclient.request.body.multipart.MultipartUtils#generateMultipartParts creating the XYZMultiPart instances. Is there a possibility that I can extend this myself, or is this not intended at all?

Imho this would be a good solution to allow streaming based multipart requests completely independent if the server uses redirects or not. Me as a client developer does not want to think about if the server may use redirects so that I have to adapt my client code accordingly.

Best regards
  Chris

**Comment by slandelle** [comment]
Nice idea.
Is this something you'd be willing to contribute?

**Comment by christiangroth** [comment]
I'd be happy to try. Unfortunately, I can't say when exactly I will be able to do this, because we are currently having to prioritize what we can implement and when through short-time work in the projects.

**Comment by christiangroth** [comment]
We have workarounded the missing API like this, so we will go with that for now.

    public static class InputStreamSupplierPart extends InputStreamPart {

        private final Supplier<InputStream> inputStreamSupplier;

        public InputStreamSupplierPart(String name, Supplier<InputStream> inputStreamSupplier, String fileName) throws IOException {
            super(name, inputStreamSupplier.get(), fileName);
            this.inputStreamSupplier = assertNotNull(inputStreamSupplier, "inputStreamSupplier");
        }

        @Override
        public InputStream getInputStream() {
            try {
                return inputStreamSupplier.get();
            } catch (IOException e) {
                Logging.logError("Unable to get fresh InputStream!", e, getClass());
                return null;
            }
        }
    }

**Comment by christiangroth** [comment]
We are expecting resource leakage with our workaround. I guess it's because InputStreamPart.getInputStream() is called per chunk to be sent? Not sure. However, I may come up with a PR soon, so that an InputStreamSupplierPart will be part of AHC.

**Comment by pejobo** [comment]
@slandelle Hi Stephen, shouldn't this issue be re-opened until #1726 is merged?
