### ISSUE TITLE
Netty version update

### ISSUE THREAD

**Issue by asurovenko** [AsyncHttpClient/async-http-client#1727]
Hello,
already present 4.1.50.Final netty version, do you have any plans to update it in the near future?
Thanks.

**Comment by TomGranot** [comment]
@asurovenko Not sure if you noticed, but Netty's been upgraded to 4.1.51 earlier this month:

https://github.com/AsyncHttpClient/async-http-client/commit/383d543b3b9382c496057caa4e8fa48f4c8ef0a2#diff-600376dffeb79835ede4a0b285078036R469

**Comment by TomGranot** [comment]
@asurovenko Since no response, closing.
