### ISSUE TITLE
Absence of detailed walk through other than readme and non-functional guidelinks

### ISSUE THREAD

**Issue by mayank-mundhra-2012** [AsyncHttpClient/async-http-client#1741]
Please help. New user here

There is no detailed walkthrough beyond the readme

The below guidelinks are non-functional.

    https://jfarcand.wordpress.com/2010/12/21/going-asynchronous-using-asynchttpclient-the-basic/
    https://jfarcand.wordpress.com/2011/01/04/going-asynchronous-using-asynchttpclient-the-complex/
    https://jfarcand.wordpress.com/2011/12/21/writing-websocket-clients-using-asynchttpclient/

**Comment by TomGranot** [comment]
@mayank-mundhra-2012 I've opened a PR to remedy this:

https://github.com/AsyncHttpClient/async-http-client/pull/1738

It has archived links to these resources:

* http://web.archive.org/web/20111224171448/http://jfarcand.wordpress.com/2011/01/12/going-asynchronous-using-asynchttpclient-for-dummies/
* http://web.archive.org/web/20111224171241/http://jfarcand.wordpress.com/2010/12/21/going-asynchronous-using-asynchttpclient-the-basic/
* http://web.archive.org/web/20111224162752/http://jfarcand.wordpress.com/2011/01/04/going-asynchronous-using-asynchttpclient-the-complex/
* http://web.archive.org/web/20120218183108/http://jfarcand.wordpress.com/2011/12/21/writing-websocket-clients-using-asynchttpclient/

I applied for maintainership of the repo (waiting for @slandelle, who's head over heels releasing the very awesome [Gatling Academy](https://academy.gatling.io/)), and one of the first points I want to address is a proper guide of exactly what's going on in the repo, as well as a few other niceties that a repo as useful as this should have.

**Comment by mayank-mundhra-2012** [comment]
A product oriented walkthrough would be great,

Thank you in advance.

**Comment by TomGranot** [comment]
@mayank-mundhra-2012 Just to update, the current (immediae) roadmap for the repo is as follows:

1. Migrate CI from Travis --> GitHub Actions, since Travis is phasing out open source credits
2. Clean up all issues & PRs 
3. Docs - I think the first thing I intend to write is this exact walkthrough.

**Comment by mayank-mundhra-2012** [comment]
Thank you :)

**Comment by TomGranot** [comment]
@mayank-mundhra-2012 Can confirm I finished a (very rough) first draft here:
https://github.com/AsyncHttpClient/async-http-client/pull/1768

Please note that there are still _a lot_ of TODOs left. It's a start:)
