### ISSUE TITLE
Is Java 7 compatible?

### ISSUE THREAD

**Issue by wangpuye** [AsyncHttpClient/async-http-client#1747]
We still use java 7 in some projects. But it looks `2.12.1` cannot run on Java 7.

**Comment by TomGranot** [comment]
@kyriegence I'm a new maintainer, still going through the library. The official answer is its supported from Java 8 onwards, but I have not personally verified it either way yet.

**Comment by hyperxpro** [comment]
v2 needs Java 8 and v3 needs Java 11 minimum.
