### ISSUE TITLE
Response body transformation

### ISSUE THREAD

**Issue by oripwk** [AsyncHttpClient/async-http-client#1759]
Hi,

How can I instruct AsyncHttpClient to transform the response body?

I can do it after receiving the response inside the user code, but I'm looking for a cleaner way, that will handle this automatically on every call, something like registering response transformers.

I'm trying to avoid doing this on every request:

```scala
val http = new DefaultAsyncHttpClient()

val resp = http
  .prepareGet("https://httpbin.org/brotli")
  .execute()
  .get()

val bytes =
  if (resp.getHeader("content-encoding") == "br") {
    val br = new BrotliCompressorInputStream(resp.getResponseBodyAsStream)
    val bytes = IOUtils.toByteArray(br)
    br.close()
    bytes
  } else resp.getResponseBodyAsBytes
```

**Comment by TomGranot** [comment]
@oripwk Thanks for opening the issue and providing great details!

## Continuations / `CompleteableFuture`
First and foremost, the easiest way to get where you want - a _cleaner_ way to do this - is by using `CompleteableFuture` to perform a callback once the full response body has arrived. The computation performed by the callback can be whatever you want it to be, and so (converted to Java) what you're asking for could be something like this:

```java
public class BrotliBodyTransformer {
    public static byte[] brotliTransformer(Response resp) {
        byte[] bytes = new byte[0];
        System.out.println(resp.getHeader("Content-Encoding"));
        try {
            if (resp.getHeader("Content-Encoding").equals("br")) {
                BrotliCompressorInputStream br = new BrotliCompressorInputStream(resp.getResponseBodyAsStream());
                bytes = IOUtils.toByteArray(br);
                System.out.println("Here be Brotli bytes");
            } else {
                bytes = resp.getResponseBodyAsBytes();
                System.out.println("Here be non-Brotli bytes");
            }
        } catch (Exception e) {
            System.err.println("Exception thrown while transforming body:" + e);
        }
        return bytes;
    }

    public static void main(String[] args) {
        AsyncHttpClient http = new DefaultAsyncHttpClient();
        byte[] responseBytes;
        try {
            responseBytes = http.prepareGet("https://httpbin.org/brotli")
                    .execute()
                    .toCompletableFuture()
                    .thenApply(BrotliBodyTransformer::brotliTransformer)
                    .join();
            System.out.println(Arrays.toString(responseBytes));
        } catch (Exception e) {
            System.err.println("Exception thrown while running request:" + e);
        }
    }
}
```

This _seems_ to do the trick. 

## `ListenableFuture`

In a similar way, you can define an actual callback. See [here](https://github.com/AsyncHttpClient/async-http-client#setting-callbacks-on-the-listenablefuture) for a bit more details, the example there is pretty self-explanatory. I'd be happy to elaborate if this still does not help.

However... the "correct" way to do it might be to use `AsyncHandler`.

## `AsyncHandler`

A [handler](https://github.com/AsyncHttpClient/async-http-client/blob/f61f88e694850818950195379c5ba7efd1cd82ee/client/src/main/java/org/asynchttpclient/AsyncHandler.java), in this context, is a built-in construct inside AHC that has callbacks. These are invoked as soon as some part of the data is available during the asynchronous response. Think headers, body, trailing headers, etc. The interesting bit from your perspective is [`onCompleted`](https://github.com/AsyncHttpClient/async-http-client/blob/f61f88e694850818950195379c5ba7efd1cd82ee/client/src/main/java/org/asynchttpclient/AsyncHandler.java#L117), which is invoked once the processing of the response is done.

While this might be the "proper" way to do it, it might be too granular for your use case. Please take a look at the other two options first, and if you'd like to get a bit more info hit me up.

## Comment on Brotli support in AHC

I'm a new maintainer on the repo, and as such there are many things I still do not know.

Therefore, I must note that there are [two](https://github.com/AsyncHttpClient/async-http-client/blob/bf1738b863c90e8c37e9d092cb3aad4648117b77/client/src/main/java/org/asynchttpclient/netty/request/NettyRequestFactory.java#L154-L155) [places](https://github.com/AsyncHttpClient/async-http-client/blob/bf1738b863c90e8c37e9d092cb3aad4648117b77/client/src/main/java/org/asynchttpclient/util/HttpUtils.java#L174-L181) in which it's clearly mentioned that AHC does not currently support Brotli. I have not yet explored why or what's the history here exactly, but just FYI. 

@slandelle if you have a moment to chime in here that would be awesome 💯

**Comment by oripwk** [comment]
@TomGranot Thank you for your detailed answer.

I started to write a reply why I cannot write an `AsyncHandler`. But in the midst, I had an idea. So, this is my solution (sorry, it's in Scala):

```scala
class MyHandler extends AsyncCompletionHandlerBase {
  private var status: HttpResponseStatus = _

  override def onStatusReceived(status: HttpResponseStatus): State = {
    this.status = status
    super.onStatusReceived(status)
  }

  override def onCompleted(response: Response): Response = {
    val bytes =
      if (response.getHeader("content-encoding") == "br") {
        val br = new BrotliCompressorInputStream(response.getResponseBodyAsStream)
        val bytes = IOUtils.toByteArray(br)
        br.close()
        bytes
      } else response.getResponseBodyAsBytes
    val parts = List[HttpResponseBodyPart](
      new EagerResponseBodyPart(Unpooled.copiedBuffer(bytes), true)
    )
    new NettyResponse(status, response.getHeaders, parts.asJava)
  }
}
```

This was my original message:

>I indeed looked into the `AsyncHandler` option very thoroughly.
>
>I used `AsyncCompletionHandlerBase` and tried implementing the `onCompleted(…)` method. However, this attempt failed when I realized I cannot build a `Response` object myself in a proper way since the first argument to the `NettyResponse` constructor is a `HttpResponseStatus` object and you need to have a `Channel` object to build it, and there's no `Channel` in this scope.
>
>I can use the `CompleteableFuture` but I kind of wanted AsyncHttpClient to do this behind the scenes.

**Comment by TomGranot** [comment]
@oripwk From a first look this feels like a perfectly reasonable solution to me. There's really no reason to go overboard here if you're doing what looks like a rather simple transformation. That handler can be re-used as much as you'd like, of course.

If you ever end up having code that can be contributed back to the repo (even in an example form), feel free to open a PR. There's a lot of value in this repo, and I'd be really happy to see it being brought to the surface.

Ping me if you need directions, and have a great day!
