### ISSUE TITLE
Too many thread waiting,low send speed,and oom .  Need help,thanks!

### ISSUE THREAD

**Issue by Christian-health** [AsyncHttpClient/async-http-client#1778]
**Problem Suspect 1**

188 instances of "io.netty.channel.nio.NioEventLoopGroup", loaded by "java.net.URLClassLoader @ 0x9707a360" occupy 931.71 MB (58.73%) bytes. 

Keywords
io.netty.channel.nio.NioEventLoopGroup
java.net.URLClassLoader @ 0x9707a360

Details »

  **Problem Suspect 2**

20 instances of "io.netty.buffer.PoolArena$HeapArena", loaded by "java.net.URLClassLoader @ 0x9707a360" occupy 304.36 MB (19.19%) bytes.

Biggest instances:

io.netty.buffer.PoolArena$HeapArena @ 0x847a2d88 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x847b2710 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x86a409a8 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x86a41530 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x890257a0 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x8a059980 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x8b06e308 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x8c09d4a8 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x8d0c83f0 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x8e0f3d40 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97b56ec8 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97c8a0f0 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97e1fc28 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97e55458 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97e861d0 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97e86d00 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97e87888 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97ea8500 - 16.02 MB (1.01%) bytes.
io.netty.buffer.PoolArena$HeapArena @ 0x97ec1f38 - 16.02 MB (1.01%) bytes.
These instances are referenced from one instance of "io.netty.buffer.PoolArena[]", loaded by "java.net.URLClassLoader @ 0x9707a360"

 AsyncHttpClient-5355-48
"AsyncHttpClient-5073-62" prio=5 tid=195418 WAITING
"AsyncHttpClient-4989-18" prio=5 tid=192121 WAITING
"AsyncHttpClient-5043-31" prio=5 tid=194190 WAITING
"AsyncHttpClient-5027-27" prio=5 tid=193689 WAITING
"AsyncHttpClient-5051-19" prio=5 tid=194387 WAITING
"AsyncHttpClient-4983-28" prio=5 tid=191981 WAITING
"AsyncHttpClient-5000-37" prio=5 tid=192948 WAITING
"AsyncHttpClient-5071-27" prio=5 tid=195437 WAITING
"AsyncHttpClient-4987-58" prio=5 tid=192407 WAITING
"AsyncHttpClient-4967-3" prio=5 tid=191162 WAITING
"AsyncHttpClient-4979-54" prio=5 tid=192016 WAITING
"AsyncHttpClient-5357-9" prio=5 tid=206213 RUNNABLE
"AsyncHttpClient-5003-45" prio=5 tid=193099 WAITING
"AsyncHttpClient-5005-12" prio=5 tid=192707 WAITING
"AsyncHttpClient-4965-29" prio=5 tid=191263 WAITING
"AsyncHttpClient-5033-55" prio=5 tid=194072 WAITING
"AsyncHttpClient-5001-54" prio=5 tid=193041 WAITING
"AsyncHttpClient-5016-32" prio=5 tid=192893 WAITING
"AsyncHttpClient-5049-10" prio=5 tid=194327 WAITING
"AsyncHttpClient-4967-70" prio=5 tid=191918 WAITING
"AsyncHttpClient-5021-11" prio=5 tid=193149 WAITING
"AsyncHttpClient-4989-41" prio=5 tid=192159 WAITING
"AsyncHttpClient-4967-16" prio=5 tid=191266 WAITING
"AsyncHttpClient-5353-11" prio=5 tid=206289 RUNNABLE
"AsyncHttpClient-4969-49" prio=5 tid=191477 WAITING
"AsyncHttpClient-5131-52" prio=5 tid=197793 WAITING
"AsyncHttpClient-4957-64" prio=5 tid=191551 WAITING
"AsyncHttpClient-5037-48" prio=5 tid=194512 WAITING
"AsyncHttpClient-5357-57" prio=5 tid=206344 RUNNABLE
"AsyncHttpClient-4993-54" prio=5 tid=192579 WAITING
"AsyncHttpClient-5347-71" prio=5 tid=206173 WAITING
"AsyncHttpClient-5013-42" prio=5 tid=193410 WAITING
"AsyncHttpClient-5121-44" prio=5 tid=197084 WAITING
"AsyncHttpClient-4973-28" prio=5 tid=191792 WAITING
"AsyncHttpClient-5053-58" prio=5 tid=195048 WAITING
"AsyncHttpClient-4981-45" prio=5 tid=192046 WAITING
"AsyncHttpClient-4979-14" prio=5 tid=191741 WAITING
"AsyncHttpClient-5018-55" prio=5 tid=193494 WAITING
"AsyncHttpClient-4987-4" prio=5 tid=191860 WAITING
"AsyncHttpClient-4963-69" prio=5 tid=191714 WAITING
"AsyncHttpClient-5023-5" prio=5 tid=193201 WAITING
"AsyncHttpClient-5039-42" prio=5 tid=194457 WAITING
"AsyncHttpClient-5020-68" prio=5 tid=193774 WAITING
"AsyncHttpClient-5011-76" prio=5 tid=192860 WAITING
"AsyncHttpClient-5011-12" prio=5 tid=192796 WAITING
"AsyncHttpClient-5355-52" prio=5 tid=206316 RUNNABLE
"AsyncHttpClient-4997-34" prio=5 tid=192594 WAITING
"AsyncHttpClient-5064-5" prio=5 tid=194920 WAITING
"AsyncHttpClient-5009-27" prio=5 tid=193029 WAITING
"AsyncHttpClient-5023-64" prio=5 tid=193603 WAITING
"AsyncHttpClient-5011-44" prio=5 tid=192828 WAITING
"AsyncHttpClient-1845-6" prio=5 tid=70723 RUNNABLE
"AsyncHttpClient-5127-72" prio=5 tid=197824 WAITING
"AsyncHttpClient-4972-50" prio=5 tid=191751 WAITING
"AsyncHttpClient-5353-18" prio=5 tid=206328 RUNNABLE
"AsyncHttpClient-4986-61" prio=5 tid=192290 WAITING
"AsyncHttpClient-5037-1" prio=5 tid=193718 WAITING
"AsyncHttpClient-5020-65" prio=5 tid=193754 WAITING
"AsyncHttpClient-5059-8" prio=5 tid=194811 WAITING
"AsyncHttpClient-4979-8" prio=5 tid=191716 WAITING
"AsyncHttpClient-4975-51" prio=5 tid=191441 WAITING
"AsyncHttpClient-4953-66" prio=5 tid=191110 WAITING
"AsyncHttpClient-5043-33" prio=5 tid=194192 WAITING
"AsyncHttpClient-5031-20" prio=5 tid=193757 WAITING
"AsyncHttpClient-4979-43" prio=5 tid=191933 WAITING
"AsyncHttpClient-5350-7" prio=5 tid=205902 WAITING
"AsyncHttpClient-4959-59" prio=5 tid=191576 WAITING
"AsyncHttpClient-5037-3" prio=5 tid=193868 WAITING
"AsyncHttpClient-4955-37" prio=5 tid=190961 WAITING
"AsyncHttpClient-4987-62" prio=5 tid=192426 WAITING
"AsyncHttpClient-4986-70" prio=5 tid=192331 WAITING
"AsyncHttpClient-4975-62" prio=5 tid=191452 WAITING
"AsyncHttpClient-5351-33" prio=5 tid=206332 RUNNABLE
"AsyncHttpClient-5021-69" prio=5 tid=193736 WAITING
"AsyncHttpClient-5016-55" prio=5 tid=192916 WAITING
"AsyncHttpClient-4989-5" prio=5 tid=191983 WAITING
"AsyncHttpClient-5007-46" prio=5 tid=193330 WAITING
"AsyncHttpClient-5011-36" prio=5 tid=192820 WAITING
"AsyncHttpClient-5039-41" prio=5 tid=194452 WAITING
"AsyncHttpClient-5053-30" prio=5 tid=194780 WAITING
"AsyncHttpClient-4986-11" prio=5 tid=191932 WAITING
"AsyncHttpClient-4979-69" prio=5 tid=192172 WAITING
"AsyncHttpClient-5217-60" prio=5 tid=201173 WAITING
"AsyncHttpClient-4991-8" prio=5 tid=192194 WAITING
"AsyncHttpClient-5059-35" prio=5 tid=194983 WAITING
"AsyncHttpClient-5009-55" prio=5 tid=193171 WAITING
"AsyncHttpClient-4979-48" prio=5 tid=191979 WAITING
"AsyncHttpClient-5241-62" prio=5 tid=202631 WAITING
"AsyncHttpClient-4967-35" prio=5 tid=191549 WAITING
"AsyncHttpClient-4969-21" prio=5 tid=191265 WAITING
"AsyncHttpClient-4995-38" prio=5 tid=192619 WAITING
"AsyncHttpClient-5000-68" prio=5 tid=192979 WAITING
"AsyncHttpClient-4983-55" prio=5 tid=192197 WAITING
"AsyncHttpClient-5039-5" prio=5 tid=193967 WAITING
"AsyncHttpClient-5047-68" prio=5 tid=195154 WAITING
"AsyncHttpClient-4987-35" prio=5 tid=192297 WAITING
"AsyncHttpClient-5031-35" prio=5 tid=193952 WAITING
"AsyncHttpClient-5020-71" prio=5 tid=193796 WAITING
"AsyncHttpClient-4967-29" prio=5 tid=191408 WAITING
"AsyncHttpClient-4995-37" prio=5 tid=192610 WAITING
"AsyncHttpClient-5042-11" prio=5 tid=194035 WAITING
"AsyncHttpClient-5011-35" prio=5 tid=192819 WAITING
"AsyncHttpClient-4975-67" prio=5 tid=191457 WAITING
"AsyncHttpClient-5011-34" prio=5 tid=192818 WAITING
"AsyncHttpClient-4995-65" prio=5 tid=192743 WAITING
"AsyncHttpClient-4983-26" prio=5 tid=191969 WAITING
"AsyncHttpClient-5241-61" prio=5 tid=202630 WAITING
"AsyncHttpClient-4977-71" prio=5 tid=192187 WAITING
"AsyncHttpClient-4967-22" prio=5 tid=191301 WAITING
"AsyncHttpClient-4969-47" prio=5 tid=191475 WAITING
"AsyncHttpClient-4977-60" prio=5 tid=192068 WAITING
"AsyncHttpClient-5018-54" prio=5 tid=193493 WAITING
"AsyncHttpClient-5057-76" prio=5 tid=194994 WAITING
"AsyncHttpClient-4979-24" prio=5 tid=191788 WAITING
"AsyncHttpClient-5071-21" prio=5 tid=195321 WAITING
"AsyncHttpClient-4965-71" prio=5 tid=191684 WAITING
"AsyncHttpClient-4989-56" prio=5 tid=192338 WAITING
"AsyncHttpClient-4983-1" prio=5 tid=191700 WAITING
"AsyncHttpClient-5049-59" prio=5 tid=194771 WAITING
"AsyncHttpClient-5033-68" prio=5 tid=194085 WAITING
"AsyncHttpClient-5036-65" prio=5 tid=194342 WAITING
"AsyncHttpClient-4991-48" prio=5 tid=192431 WAITING
"AsyncHttpClient-5003-63" prio=5 tid=193377 WAITING
"AsyncHttpClient-5033-54" prio=5 tid=194071 WAITING
"AsyncHttpClient-5001-52" prio=5 tid=193026 WAITING
"AsyncHttpClient-4997-14" prio=5 tid=192460 WAITING
"AsyncHttpClient-5339-66" prio=5 tid=206296 RUNNABLE
"AsyncHttpClient-5003-40" prio=5 tid=193072 WAITING
"AsyncHttpClient-5037-18" prio=5 tid=194045 WAITING
"AsyncHttpClient-5013-51" prio=5 tid=193482 WAITING
"AsyncHttpClient-5020-30" prio=5 tid=193325 WAITING
"AsyncHttpClient-4983-60" prio=5 tid=192226 WAITING
"AsyncHttpClient-5253-46" prio=5 tid=202494 WAITING
"AsyncHttpClient-4967-2" prio=5 tid=191152 WAITING
"AsyncHttpClient-5025-27" prio=5 tid=193544 WAITING
"AsyncHttpClient-5007-15" prio=5 tid=193042 WAITING
"AsyncHttpClient-5043-45" prio=5 tid=194204 WAITING
"AsyncHttpClient-5025-17" prio=5 tid=193455 WAITING
"AsyncHttpClient-4955-67" prio=5 tid=191141 WAITING
"AsyncHttpClient-4983-25" prio=5 tid=191957 WAITING
"AsyncHttpClient-4991-11" prio=5 tid=192203 WAITING
"AsyncHttpClient-5055-65" prio=5 tid=194884 WAITING
"AsyncHttpClient-4997-6" prio=5 tid=192368 WAITING
"AsyncHttpClient-4991-29" prio=5 tid=192350 WAITING
"AsyncHttpClient-5030-17" prio=5 tid=193737 WAITING
"AsyncHttpClient-5020-28" prio=5 tid=193294 WAITING
"AsyncHttpClient-4997-57" prio=5 tid=193023 WAITING
"AsyncHttpClient-4991-75" prio=5 tid=192638 WAITING
"AsyncHttpClient-4965-5" prio=5 tid=191105 WAITING
"AsyncHttpClient-5071-11" prio=5 tid=195237 WAITING
"AsyncHttpClient-5071-49" prio=5 tid=195459 WAITING
"AsyncHttpClient-5020-14" prio=5 tid=193156 WAITING
"AsyncHttpClient-5016-63" prio=5 tid=192924 WAITING
"AsyncHttpClient-5033-11" prio=5 tid=193829 WAITING
"AsyncHttpClient-5329-2" prio=5 tid=205120 WAITING
"AsyncHttpClient-5357-58" prio=5 tid=206345 RUNNABLE
"AsyncHttpClient-5023-15" prio=5 tid=193290 WAITING
"AsyncHttpClient-5007-55" prio=5 tid=193423 WAITING
"AsyncHttpClient-5355-53" prio=5 tid=206317 RUNNABLE
"AsyncHttpClient-5023-49" prio=5 tid=193568 WAITING
"AsyncHttpClient-5007-42" prio=5 tid=193310 WAITING
"AsyncHttpClient-5043-55" prio=5 tid=194214 WAITING
"AsyncHttpClient-5055-28" prio=5 tid=194643 WAITING
"AsyncHttpClient-5042-7" prio=5 tid=194012 WAITING
"AsyncHttpClient-5013-43" prio=5 tid=193419 WAITING
"AsyncHttpClient-5125-75" prio=5 tid=197787 WAITING
"AsyncHttpClient-5000-59" prio=5 tid=192970 WAITING
"AsyncHttpClient-4969-40" prio=5 tid=191425 WAITING
"AsyncHttpClient-4961-34" prio=5 tid=191149 WAITING
"AsyncHttpClient-5005-10" prio=5 tid=192690 WAITING
"AsyncHttpClient-4979-10" prio=5 tid=191729 WAITING
"AsyncHttpClient-5007-66" prio=5 tid=193530 WAITING
"AsyncHttpClient-4975-37" prio=5 tid=191393 WAITING
"AsyncHttpClient-4981-18" prio=5 tid=191831 WAITING
"AsyncHttpClient-4953-49" prio=5 tid=190974 WAITING
"AsyncHttpClient-4955-29" prio=5 tid=190929 WAITING
"AsyncHttpClient-5000-51" prio=5 tid=192962 WAITING
"AsyncHttpClient-5049-70" prio=5 tid=194830 WAITING
"AsyncHttpClient-5007-25" prio=5 tid=193172 WAITING
"AsyncHttpClient-4983-50" prio=5 tid=192104 WAITING
"AsyncHttpClient-4969-36" prio=5 tid=191391 WAITING
"AsyncHttpClient-5073-69" prio=5 tid=195425 WAITING
"AsyncHttpClient-5047-48" prio=5 tid=194879 WAITING
"AsyncHttpClient-5009-19" prio=5 tid=192773 WAITING
"AsyncHttpClient-5057-67" prio=5 tid=194948 WAITING
"AsyncHttpClient-5057-66" prio=5 tid=194947 WAITING
"AsyncHttpClient-5011-43" prio=5 tid=192827 WAITING
"AsyncHttpClient-5016-65" prio=5 tid=192926 WAITING
"AsyncHttpClient-5359-1" prio=5 tid=206251 RUNNABLE
"AsyncHttpClient-5043-57" prio=5 tid=194216 WAITING
"AsyncHttpClient-4961-28" prio=5 tid=191130 WAITING
"AsyncHttpClient-5071-10" prio=5 tid=195226 WAITING
"AsyncHttpClient-5036-64" prio=5 tid=194331 WAITI

**Comment by hyperxpro** [comment]
Fixed after upgrading to the latest Netty version.
