### ISSUE TITLE
To all who had issues and PRs in the last while

### ISSUE THREAD

**Issue by TomGranot** [AsyncHttpClient/async-http-client#1780]
Hey all,

Apologies for being away - work came calling and I lost track of things in the last ~1.5 months.

Expect issues answered (albeit not necessarily resolved) and PRs reviewed (albeit not necessarily merged) in the upcoming weeks (most likely will get to some of them this weekend).

Having said that - I still feel that the priority should be on finishing the CI (https://github.com/AsyncHttpClient/async-http-client/pull/1758) and the contributor technical overview (https://github.com/AsyncHttpClient/async-http-client/pull/1768).

This is a rather popular library, and if someone has a few hours (shouldn't take more than that, including ramping up once the technical overview is done) I'd appreciate a hand with an issue or a PR review. 

Doing this alone - in the long run - is difficult, especially with no commercial backing. Even a bit of time from an experienced programmer can make a real dent. It's the infra we're all running on, after all, isn't it? :)

My Twitter handle is the same as my handle here, and if you'd like to take it 1-1 to see if and how you can come on board - DM me there. It would be awesome to hear from you, and my e-mail inbox is open as well (not hard to find it). 

cc @doom369 @christian-health @jsanders67 @andres-de-biase-wcar @rgupt102 @ZhezherP @taymindis @rachidbm @aqingsao @sms0070 @yazgoo @neket985

**Comment by doom369** [comment]
Hello. Sorry, but I don't understand how discussions and CI could have more priority over the reported issues (https://github.com/AsyncHttpClient/async-http-client/issues/1779 and https://github.com/AsyncHttpClient/async-http-client/issues/1769) when it was encountered by multiple different teams. Especially when the PR with the fix is provided, the fix is super simple and the test is provided. All you have to do is to merge. That's above my understanding.

I'm not ready to spend time for discussions like many others and I'm not here to convenience you what to do, so I just did a fork, applied the patch, and deployed it to the production. Without talks.

**Comment by TomGranot** [comment]
@doom369 You are right and wrong, IMHO.

First - regarding the PR in question - I did not pay enough attention to it, it is indeed very simple and was merged now.

On the other hand, this is an open-source project. This means that the number one resource we are missing is developer time.

I can't rightfully ask someone to contribute their time (without payment) to build the _infrastructure_ for the repo. Heck, I can't even rightfully ask someone to contribute _to the actual repo_ since, as I mentioned, it's free and open source.

I can, however, ease the way into helping out with the repo. I can make it so it takes an experienced developer 10 minutes instead of an hour to figure out how a specific part works. 

I think this is worth the effort, and so I am going to proceed in this way.

Closing for now, but feel free to comment if you wish.

**Comment by doom369** [comment]
I'm not saying automation and docs are not important. They are. And you're doing the right job here. Yes, it's open-source and you don't have to fix, review, or even merge the PRs. However, if you're willing to maintain this repo you just can't ignore the bugs that are actually there if you're a maintainer now.

**Comment by TomGranot** [comment]
That is not my intention - it was a specific oversight on my end. 

I feel you - it's hard out there when relying on open source stuff. 

I think we understand each other, though;)
