### ISSUE TITLE
Does AHC support decompressing body by gzip or deflate automatically?

### ISSUE THREAD

**Issue by asyougo** [AsyncHttpClient/async-http-client#1791]
When the response has a header named Content-Encoding, does AHC support decompressing body by gzip or deflate automatically? If not, how can I implement the function of decompresssing the body after receiving response?

**Comment by jilen** [comment]
It is done automatically, you could test it against   https://httpbin.org/#/Response_formats/get_gzip

**Comment by asyougo** [comment]
> It is done automatically, you could test it against https://httpbin.org/#/Response_formats/get_gzip

It's useful.Thank you very much!
