### ISSUE TITLE
Denial of Service (DoS) vulnerability in 4.1.60.Final

### ISSUE THREAD

**Issue by ronanwatkins** [AsyncHttpClient/async-http-client#1802]
Recommend upgrading `netty.version` to `4.1.68.Final` in the pom.
It's causing snyk to report high vulnerabilities from projects using this dependency.

More details: https://app.snyk.io/vuln/SNYK-JAVA-IONETTY-1584063

**Comment by dari0g** [comment]
Is there an update on this issue?

**Comment by ronanwatkins** [comment]
Unfortunately, it seems like this project isn't getting much attention anymore. The last commit was 7 months ago and the previous maintainer tweeted that he doesn't have time to maintain this project anymore.

**Comment by hyperxpro** [comment]
Will be fixed in the v3.0.0 release.
