### ISSUE TITLE
DefaultChannelPool finding memory leak

### ISSUE THREAD

**Issue by hujunzhong** [AsyncHttpClient/async-http-client#1808]
当请求很多不同的地址，而且地址经常变化，DefaultChannelPool只回收了IdleChannel，但partitions的key,和ConcurrentLinkedQueue都是没有回收的。以下截图是我用老的ning http的内存状态，最新的DefaultChannelPool也存在同样的问题

**Comment by hujunzhong** [comment]
![image](https://user-images.githubusercontent.com/3366485/145531361-dcc4c86b-2f85-4e19-b86e-2b35df06dfa6.png)

**Comment by hyperxpro** [comment]
Please give v3 a try and open a fresh issue if the issue still persists. And please use English.

**Comment by 232311xiaoping** [comment]
> 当请求很多不同的地址，而且地址经常变化，DefaultChannelPool只回收了IdleChannel，但partitions的key,和ConcurrentLinkedQueue都是没有回收的。以下截图是我用老的ning http的内存状态，最新的DefaultChannelPool也存在同样的问题

这个问题解决了吗？

**Comment by hyperxpro** [comment]
English

**Comment by hujunzhong** [comment]
解决了，done,thanks!



***@***.***
 
From: 232311xiaoping
Date: 2023-05-15 14:00
To: AsyncHttpClient/async-http-client
CC: hujunzhong; Author
Subject: Re: [AsyncHttpClient/async-http-client] DefaultChannelPool finding memory leak (Issue #1808)
当请求很多不同的地址，而且地址经常变化，DefaultChannelPool只回收了IdleChannel，但partitions的key,和ConcurrentLinkedQueue都是没有回收的。以下截图是我用老的ning http的内存状态，最新的DefaultChannelPool也存在同样的问题
这个问题解决了吗？

**Comment by 232311xiaoping** [comment]
> English

okk

**Comment by 232311xiaoping** [comment]
> 解决了，done,thanks! ***@***.*** From: 232311xiaoping Date: 2023-05-15 14:00 To: AsyncHttpClient/async-http-client CC: hujunzhong; Author Subject: Re: [AsyncHttpClient/async-http-client] DefaultChannelPool finding memory leak (Issue #1808) 当请求很多不同的地址，而且地址经常变化，DefaultChannelPool只回收了IdleChannel，但partitions的key,和ConcurrentLinkedQueue都是没有回收的。以下截图是我用老的ning http的内存状态，最新的DefaultChannelPool也存在同样的问题 这个问题解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

How to solve this problem? Can you share the solution，thanks
