### ISSUE TITLE
Binary file upload fails to the target system 

### ISSUE THREAD

**Issue by deepaktaker** [AsyncHttpClient/async-http-client#1811]
Binary file upload fails to the target system because the target system doesn't understand Transfer-Encoding: chunked header which is sent by default by netty is bundled by camel-ahc.
The target system expects the Content-Length header but there is no way to disable camel-ahc from sending data in chunks for binary content.
I think this is a big issue. at least there should be a property to enable or disable camel-ahc from sending chunked data to the target.

**Comment by andresetevejob** [comment]
can you show your code

**Comment by deepaktaker** [comment]
The issue was i camel code which is now fixed https://issues.apache.org/jira/browse/CAMEL-17470
