### ISSUE TITLE
Request times out after being sent in AHC

### ISSUE THREAD

**Issue by saurabh782** [AsyncHttpClient/async-http-client#1826]
Hi everyone,
I am using the org.asynchttpclient library version(2.12.3).I am using a service which makes a lot of downstream api calls to different services.Earlier I was using a single AHC object instance for all the downstream service calls with (maxConnectionPool=1000) and (maxConnectionsPerHost=500) with keep-alive=true. What happened was the requests were being sent from my client service to the target services but many of them timed out with the message "Request timeout to <target-service> after <request-timeout>ms". What I observed is the response from the services was within the timeout duration but for some reason the request timed out.
As an experiment I increased the number of AHC instances and used a separate instance for each of the downstream service with the config remaining the same.I observed that the timeouts decreased significantly and the overall response time observed from the downstream calls improved.But still there are false timeouts which are seen.
Also have seen this issue happening when using an open channel.When using a new channel this never seems to happen.
I guess this is due to blocking of thread due to some reason that it is not able to process the new responses arriving in the channel.Is this some known bug or there may be some issue with my implementation,can someone throw some light on it?

**Comment by hyperxpro** [comment]
I'm investigating this.

**Comment by solvip** [comment]
This is also an issue with 2.10.4.

**Comment by saurabh782** [comment]
@hyperxpro any update regarding the investigation?

**Comment by hyperxpro** [comment]
This will be fixed in v3 release.
