### ISSUE TITLE
v3.0.0 timeline

### ISSUE THREAD

**Issue by saomyatangri** [AsyncHttpClient/async-http-client#1846]
Following up in regards to #1810, when is v3.0.0 expected to be deployed? The CVE issue is impacting our shared libraries so wondering when we can expect a fix for this.

**Comment by hyperxpro** [comment]
By end of this weekend, expect beta release.

**Comment by manolo** [comment]
After the beta, how long it will take final ?

**Comment by hyperxpro** [comment]
That really depends on feedbacks and API stability but I target to release final by end of Q1 2023.

**Comment by hyperxpro** [comment]
Beta 1 releasing today.

**Comment by saurabh782** [comment]
@hyperxpro I am not able to find the 3.0.0-SNAPSHOT in the maven central.

**Comment by hyperxpro** [comment]
3.0.0.Beta1now available on Maven Central.
