### ISSUE TITLE
[Question] Using java.time.Duration for timeouts and ttls

### ISSUE THREAD

**Issue by Asapin** [AsyncHttpClient/async-http-client#1861]
Would maintainers be interested in changing various timeouts and TTLs to use `java.time.Duration` instead of `int`?

I think this will make configuration more obvious and easier to understand. 
And since the library is changing its version to 3.x.x, now is probably the perfect time for such breaking changes.

If maintainers are interested, I can prepare a PR for this

**Comment by hyperxpro** [comment]
Closed by  #1862
