### ISSUE TITLE
Is hostname certifcate validation enabled by default?

### ISSUE THREAD

**Issue by matheussbernardo** [AsyncHttpClient/async-http-client#1895]
Hello. I am trying to be sure that when using DefaultAsyncHttpClientConfig.Builder() the hostname certificate validation is enabled by default.

**Comment by hyperxpro** [comment]
Yes, it is.

See: https://github.com/AsyncHttpClient/async-http-client/blob/498930feaa1bd717eb6dcbefb50e483de70caf8b/client/src/main/resources/org/asynchttpclient/config/ahc-default.properties#L31C21-L31C64
