### ISSUE TITLE
2.12.4 release with updated Netty dependencies

### ISSUE THREAD

**Issue by rogierslag** [AsyncHttpClient/async-http-client#1957]
Thanks for an awesome library! While we are waiting for version 3 to arrive, would it be possible to release a version `2.12.4` to maven central which has the `pom.xml` property `netty.version` set to `4.1.109`? The current version `4.1.60` pulls in a netty versions with some open cves.

**Comment by hyperxpro** [comment]
v3.0.0 stable has been released
