### ISSUE TITLE
Cookie explicitly set on the request is getting discarded in favor of the one from the cookie jar

### ISSUE THREAD

**Issue by Spikhalskiy** [AsyncHttpClient/async-http-client#1964]
# Expected Behavior

A cookie explicitly specified on a RequestBuilder should take precedence over a cookie stored in cookie jar.

# Actual Behavior

```
cookieStore = httpClient.getCookieStore();
cookieStore.add("some_url", new DefaultCookie("name", "value1"));
BoundRequestBuilder requestBuilder = httpClient.prepareGet("some_url");
requestBuilder.addCookie(new DefaultCookie("name", "value2"));
httpClient.executeRequest(requestBuilder.build())
```

This code leads to a request being performed with cookie "name":"value1", which is not what is expected by a user when a user explicitly sets a cookie on a `RequestBuilder`.

# Root cause

Cookies from cookie jar [are overriding cookies coming from the RequestBuilder here](https://github.com/AsyncHttpClient/async-http-client/blob/2200b2477c84d2517fcbdf5d42f71d459c09066f/client/src/main/java/org/asynchttpclient/DefaultAsyncHttpClient.java#L238)

# Affected version

2.12.3, 3.0 pre-releases

**Comment by pickypg** [comment]
The supplied link puts the commit hash in the wrong place, but the root cause is that it blindly overrides Cookies by using `addOrReplace(cookie)` from the `CookieStore`.

https://github.com/AsyncHttpClient/async-http-client/blob/661ec72/client/src/main/java/org/asynchttpclient/DefaultAsyncHttpClient.java#L238

**Comment by pickypg** [comment]
I've added a PR that only uses `Cookie`s from the `CookieStore` if they're unset.

https://github.com/AsyncHttpClient/async-http-client/pull/2033

**Comment by pickypg** [comment]
As a note, you can workaround this issue -- if you don't actually want the `CookieStore` -- by disabling it upon client creation:

```java
DefaultAsyncHttpClientConfig.Builder clientBuilder = Dsl.config()
    .setCookieStore(null)
```
