### ISSUE TITLE
units for timeout configs

### ISSUE THREAD

**Issue by ukarim** [AsyncHttpClient/async-http-client#1968]
Hi!

It would be great to specify units for timeout values in the documentation

```
Dsl.config()
        .setReadTimeout(xxx)
        .setConnectTimeout(xxx)
        .setRequestTimeout(xxx)
```

**Comment by hyperxpro** [comment]
Would you like to do a PR?

**Comment by ukarim** [comment]
@hyperxpro  It looks like this issue will be automatically resolved with next stable release. 3.x.x version uses java.time.Duration as method argument.
Thanks!
