### ISSUE TITLE
addShutdownHook in ResumableAsyncHandler causes class loader leak

### ISSUE THREAD

**Issue by syvalta** [AsyncHttpClient/async-http-client#291]
com.ning.http.client.resumable.ResumableAsyncHandler.ResumableIndexThread adds a shutdown hook at initialization. When ning is used inside a web application it will result in a classloader leak when the application is undeployed (reference from system class --> ResumableIndexThread instance --> ResumableIndexThread class --> web app classloader). This results in all the web app classes to be kept in perm gen.

**Comment by slandelle** [comment]
No proposed fix for 2 years, adding a javadoc warning and closing.

**Comment by slandelle** [comment]
No proposed fix for 2 years, adding a javadoc warning and closing.
