### ISSUE TITLE
[release] 2.0.0-beta1

### ISSUE THREAD

**Issue by jfarcand** [AsyncHttpClient/async-http-client#334]
@rlubke @slandelle Any objection? What is missing is a small documentation update to describe how to hook up the new artifact.

**Comment by wsargent** [comment]
Is the SPDY impl related to https://github.com/AsyncHttpClient/async-http-client/issues/50 ?

**Comment by slandelle** [comment]
@wsargent AHC2 will only support Netty 3 and 4. I'm considering releasing some alpha versions.

**Comment by slandelle** [comment]
Closing, we're already releasing alpha versions.
