### ISSUE TITLE
Support for Java 8 CompletableFuture<T> as suppliment to Future+CompletionHandler

### ISSUE THREAD

**Issue by tnn** [AsyncHttpClient/async-http-client#399]
JDK 8 introduces a composable standard Future called CompletableFuture[1]. Even through it will be a pain to support this while retaining backwards compatibility, adding support for this standard future is very important when designing complete async systems. It enables the same returned Future to be reused, composed[2] and simplifies the usage of AsyncHttpClient.

Example usage:
```
asyncHttpClient.prepareGet(url)
    .exceuteJava8Style()
    .thenApply(res -> doStuff(res))
    .exceptionally(e -> log.error("Got exception", e));
```

[1] http://download.java.net/jdk8/docs/api/java/util/concurrent/CompletableFuture.html 
[2] http://nurkiewicz.blogspot.dk/2013/05/java-8-completablefuture-in-action.html

**Comment by alinpopa** [comment]
What about using a `CompletableFuture` as a `Promise`, something like this:
```
public <T> CompletableFuture<T> get(String url, Function<Response, T> supplier){
        final CompletableFuture<T> toBeCompleted = new CompletableFuture<>();
        asyncHttpClient.prepareGet(url).execute(new AsyncCompletionHandler<Response>() {
            @Override
            public Response onCompleted(Response response) throws Exception {
                toBeCompleted.complete(supplier.apply(response));
                return response;
            }

            @Override
            public void onThrowable(Throwable t){
                toBeCompleted.completeExceptionally(t);
            }
        });
        return toBeCompleted;
}

final Function<Response, String> responseProducer = (response) -> {
    try {
        return response.getResponseBody();
    } catch (Exception e) {
        return e.getMessage();
    }
};

final CompletableFuture<String> f =
    get("http://127.0.0.1:8080/bla1", responseProducer)
        .thenCompose(response -> get("http://127.0.0.1:8080/" + response, responseProducer);
```

That's the alternative that I found ... not sure if it's the best, what do you think?

**Comment by slandelle** [comment]
Yep, that's the way to do it until we target JDK8 (which won't sadly happen in a near future).

**Comment by JesseBlackman** [comment]
`CompletableFuture<Response> future = httpClient
              .executeRequest(requestBuilder).toCompletableFuture();`
In case someone found this issue
