### ISSUE TITLE
WS library blocking on DNS lookup timeout

### ISSUE THREAD

**Issue by oalper** [AsyncHttpClient/async-http-client#414]
We are trying to do a basic web service call, and realized that even though it returns a Future, it blocks on DNS lookup, so the whole thing will end up blocking the caller thread if there is a DNS issue. 

I traced the issue all the way down to NettyAsyncHttpProvider.doConnect, basically this method is trying to create a InetSocketAddress object within the main thread, and that blocks the main thread if you have any DNS issues.

BTW, we are using version: 1.7.21 with Play Framework 2.2.1 on scala

**Comment by wsargent** [comment]
Netty 4.0 has async DNS now, so this is an option :-)

**Comment by slandelle** [comment]
No, Netty 4.1 has a DNS codec, not 4.0. And it's unstable.
Non blocking DNS resolution is something we could consider in a future version (after 2.1 which is drawing near).

**Comment by slandelle** [comment]
Actually, you can already pass a optional `NameResolver` [when building a request](https://github.com/AsyncHttpClient/async-http-client/blob/master/client/src/main/java/org/asynchttpclient/RequestBuilderBase.java#L510).

**Comment by wsargent** [comment]
Okay, that's good to know -- so then AHC uses https://netty.io/4.1/api/io/netty/resolver/DefaultNameResolver.html out of the box, which is blocking, but you can swap that out for a https://netty.io/4.1/api/io/netty/resolver/dns/DnsNameResolver.html in the builder.  Okay.

**Comment by slandelle** [comment]
Yep.
FYI, I backported Netty DNS modules in AHC 2.0 so they could run on Netty 4.0, but at some point it became really painful.
