### ISSUE TITLE
Add support for SPDY protocol

### ISSUE THREAD

**Issue by jfarcand** [AsyncHttpClient/async-http-client#50]
Netty 3.3.x has support (donated by Twitter). We should investigate how that could be supported by AHC as well via the Upgrade interface

**Comment by wsargent** [comment]
+1

**Comment by slandelle** [comment]
Does it still make sense to put any effort into SPDY as HTTP/2.0 is finalized?

**Comment by wsargent** [comment]
Good point, I'm still getting to grips with the new territory.  Here's a post from HC as well:

https://mail-archives.apache.org/mod_mbox/hc-dev/201503.mbox/%3CCAFmYSVn2Ugscp3SdSTmmq2qOL-HVcX3-ZMMgVujWmJTQhH5M7g@mail.gmail.com%3E

**Comment by jfarcand** [comment]
Closing, HTTP2 makes more sence and available in Netty 2.

**Comment by slandelle** [comment]
@jfarcand Does it mean you're willing to tackle HTTP2 support?

**Comment by jfarcand** [comment]
@slandelle No :-) But can help in a couple of month...maybe :-)
