### ISSUE TITLE
Provide a RedirectStrategy API

### ISSUE THREAD

**Issue by jluehe** [AsyncHttpClient/async-http-client#535]
Apologies if this has been asked already ...

Does Ning provide a feature similar to Apache's org.apache.http.client.RedirectStrategy, which gives developers an opportunity to intercept a redirect that is automatically handled by the client library, and allows them to implement some custom logic?

Thanks,

Jan

**Comment by slandelle** [comment]
Closing, as ResponseFilter provides the feature.
