### ISSUE TITLE
Add connection timeout as a per request setting

### ISSUE THREAD

**Issue by joshgord** [AsyncHttpClient/async-http-client#54]
Currently connection timeout is only settable on the pool through AsyncHttpClientConfig.  Can connection timeout be added to PerRequestConfig so this value can be controlled at the request level?

**Comment by pavelliu** [comment]
It seems this is finally merged on 07/04/2014, 06/03 AM PST time
Drop PerRequestConfig, close #591
feeb5042899adbcb4475205eefbb5dc4fe9fad90

so if we'd like to get the "official" version built, the closes one is async-http-client-1.9.0-BETA1 (tagged on 07/10/2014)
