### ISSUE TITLE
Backpressure in AsyncHandler

### ISSUE THREAD

**Issue by jroper** [AsyncHttpClient/async-http-client#544]
AsyncHandler provides no mechanism to send back pressure on receiving the body parts.

Imagine you have a server that stores large files on Amazon S3, and streams them out to clients, using async http client to connect to S3.  Now imagine you have a very slow client, that connects and downloads a file.  The slow client pushes back on the server via TCP.  However, async http client will keep on calling onBodyPartReceived as fast as S3 provides it with data.  The AsyncHandler implementation will have three choices:

1. Block. Then it's blocking a worker thread, preventing other concurrent operations from happening.  This is not an option.
2. Buffer. Eventually this will cause an OutOfMemoryError.  This is not an option.
3. Drop. Then the client gets a corrupted file.  This is not an option.

AsyncHandler therefore needs a mechanism to propagate back pressure when handling body parts.  One possibility here is to provide a method to say whether you are interested in receiving more data or not.  This would correspond to a Channel.setReadable(true/false) in the netty provider, which will push back via TCP flow control.  This could either be provided by injecting some sort of "channel" object into the AsyncHandler, or, since HttpResponseBodyPart already provides mechanisms for talking back to the channel (eg closeUnderlyingConnection()), it could be provided there.

**Comment by jroper** [comment]
An update here - I've implemented reactive streams support for Netty 4.0 here:

https://github.com/typesafehub/netty-reactive-streams

So, as far as how we'd actually implement support for reactive streams in this, there's two things to consider, request bodies and response bodies.  We also need to consider that not every provider is going to provide a reactive streams implementation at the same time, so it needs to be an opt in thing.

Starting with response bodies, I propose that we provide a new sub interface of `AsyncHandler` called `StreamedAsyncHandler`, which introduces a new method, `onStream(org.reactivestreams.Publisher<HttpResponseBodyPart>)`.  A provider can, if it chooses to, check if the supplied async handler is an instance of `StreamedAsyncHandler`, and if it is, cast and invoke `onStatusReceived`, `onHeadersReceived`, and then `onStream`.  If it invokes `onStream`, it will never invoke `onBodyPartReceived`, but will eventually invoke either `onThrowable` or `onCompleted` once the body has been consumed (in addition to invoking the `onComplete` or `onError` methods on the subscriber).  A provider does not have to invoke `onStream`, even if it supports reactive streams, for example, if the request has no body, or if the request body is small and it has buffered it in memory, it may invoke `onBodyPartReceived` instead.  A provider that does support reactive streams however should invoke `onStream` when the body is of a size that should not be buffered into memory.

For request bodies, this can be supported by creating a new sub class of `BodyGenerator` for bodies generated by a reactive streams Publisher.  This will have a method to get the publisher that a reactive streams supporting provider will use.  The `getBody` method will return an implementation of `Body` that uses a crude blocking queue based reactive streams subscriber to implement the `read` method for those providers that don't support reactive streams.

How does that sound?

**Comment by jfarcand** [comment]
Non binding (Stephane is the chef), but I like your proposal +1 !

**Comment by slandelle** [comment]
@jroper So sorry for the late reply, just so many things to do before leaving on vacations!

Your suggestion looks great. I just have one question: is it OK to no deal with the other evens that AHC automatically handles (redirects, authentication, retry)?

Please let me know if you need some changes in AHC.

Thanks!

**Comment by jroper** [comment]
@slandelle I'm not sure I understand the question - from my understanding, if implemented as described, redirects, authentication, retry etc will all be handled normally - the AsyncHandler isn't invoked until filters/redircts/auth etc are handled.

**Comment by slandelle** [comment]
@jroper I was asking if it was ok for you to not have full control over the requests being sent.

**Comment by jroper** [comment]
Yeah, no problem. If we wanted full control, we'd use Netty directly :)

**Comment by slandelle** [comment]
Right :)
Please let me know if you need anything. On vacation arm, but will do my best to answer.

**Comment by jroper** [comment]
Here's an initial attempt at the `StreamedAsyncHandler`:

https://github.com/jroper/async-http-client/commit/1da72d579996d9529b9abdb3da4bc5530ca9cf45

Most of the code there is actually test code, I had to implement my own reactive streams subscriber for the tests.  This could be removed if we pull a reactive streams implementation in for the tests, for example, Akka streams or RxJava.

Note that when reactive streams is being used, this pushes some processing into the `Processor`, primarily converting `HttpContent` into `HttpResponseBodyPart`.  This is necessary in order to make use of the `netty-reactive-streams` implementation, since it gets plugged into the pipeline where it can handle more than just `onChannelRead` events, it also handles `onChannelReadComplete` events and makes `read` calls back up the pipeline.

**Comment by slandelle** [comment]
Wow, that was surprisingly short?! I'm impressed!

> Note that when reactive streams is being used, this pushes some processing into the Processor, primarily converting HttpContent into HttpResponseBodyPart.

Note that there's 2 ways of doing this conversion: one safe (default) way that eagerly copy the bytes from the ByteBuf, and one that let you handle the ByteBuf directly. I did that because I expect most users to shoot themselves in the foot if they have to deal with ByteBufs.

**Comment by jroper** [comment]
In the reactive streams implementation, the lazy one won't work, since elements may (or may not) be dispatched asynchronously to the consumer, and if they are dispatched asynchronously, the `ByteBuf` may already have been released by the time it's read, which will cause an exception to be thrown.  So we should probably either make the reactive streams impl always eager, or we need to require the consumer to release the `ByteBuf` themselves if the lazy impl is being used.

**Comment by slandelle** [comment]
Exactly.

**Comment by jfarcand** [comment]
Quick question, we don't seems to cover websocket with this patch, or I'm mistaken? I think we should extends the concept up to the `WebSocketUpgradeHandler` by either extending the interface or add a new `WebSocketUpgradeStreamingHandler`.

**Comment by jroper** [comment]
No, we haven't made any attempt to cover websockets yet.  It shouldn't be hard though to implement.
