### ISSUE TITLE
Have an option for using OpenSslEngine

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#569]
http://netty.io/wiki/forked-tomcat-native.html#wiki-h2-1

**Comment by tomfitzhenry** [comment]
Looks like the OpenSSL SslProvider now supports client side: https://github.com/netty/netty/blob/9498d1a9b30e13df75a8af20ed3382967375554f/handler/src/main/java/io/netty/handler/ssl/SslContext.java#L745

**Comment by tomfitzhenry** [comment]
Oh, and it's since become supported in AsyncHttpClient: https://github.com/AsyncHttpClient/async-http-client/blob/e418d627107e1e797ea4d03e6b93e2a356ee995e/client/src/main/java/org/asynchttpclient/netty/ssl/DefaultSslEngineFactory.java#L40

Woo.
