### ISSUE TITLE
Listen to WebSocket write failures

### ISSUE THREAD

**Issue by johnoliver** [AsyncHttpClient/async-http-client#613]
As discussed on the Google Group, there is currently no way of detecting if a write to a WebSocket fails or not. Both Grizzly and Netty return Futures from their write operations that could be exposed in the API to allow the client code to listen for failed writes.

**Comment by slandelle** [comment]
Renaming as the issue is not specific to WebSockets.

**Comment by dguggemos** [comment]
Any news on this issue? Is it planned to be implemented? This would not only be useful to react on failures but also to get some feedback if the web socket accepts more messages. Currently messages are queued until we run out of memory when publishing at high rate and we have no chance to know if a message is really on the wire.

**Comment by slandelle** [comment]
No, nothing planned atm. Contribs welcome.
