### ISSUE TITLE
Better Continuous Integration 

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#648]
There's a BuildHive account: https://buildhive.cloudbees.com/job/AsyncHttpClient/job/async-http-client/ but it's no longer used.

Let's switch to Travis and let's deploy snapshots on Sonatype.

**Comment by slandelle** [comment]
The main issue is with the tests that rely on external websites, whose behavior is different depending on the client IP location. Typically, google.com redirects to google.fr when calling from France.

There's a plan for stopping using external websites in our integration tests suite, see discussion in #1069.
If we fail to do so, we can still isolate those tests into a dedicated maven profile that wouldn't run on Travis.

**Comment by slandelle** [comment]
@dotta ping

**Comment by dotta** [comment]
:fireworks:
