### ISSUE TITLE
How can I get progress rate when uploading big file? Get it when uploading not completed!

### ISSUE THREAD

**Issue by yizhl** [AsyncHttpClient/async-http-client#728]
I am trying to implement async file upload with progress ,get progress rate when I uploading a big file in order to show it to user..

I tried the method suggested in the docs. Using transfer listener. http://sonatype.github.com/async-http-client/transfer-listener.html

I implemented onBytesSent of TransferListener interface (just as test):

``` java
public void onBytesSent(ByteBuffer byteBuffer) {

     System.out.println("Total bytes sent - ");
     System.out.println(byteBuffer.capacity());
}
```

Then in another thread(because I don't want to block the app) I tried to do the following:

``` java
TransferCompletionHandler tl = new TransferCompletionHandler();
tl.addTransferListener(listener);

asyncHttpClient.preparePut(getFullUrl(fileWithPath))
      .setBody(new BodyGenerator() {
           public Body createBody() throws IOException {
                return new FileBodyWithOffset(file, offset);
           }
       })
       .addHeader(CONTENT_RANGE, new ContentRange(offset, localSize).toString())
       .execute(handler).get();
```

Everything is fine. File is uploaded correctly and very fast. <b>But the issue is - I am getting messages from onBytesSent in TransferListener only AFTER the upload is finished.<b> For exmaple the upload is completed in 10 minutes. And during that 10 minutes I get nothing. And only after that everything is printed on the console.

I can't figure out what is wrong with this code. I just tried to follow the docs.

I tried to execute the above code in the main thread and it didn't work either.

Maybe it is a wrong way to implement upload progress listener using this client?

**Comment by odiszapc** [comment]
@slandelle 
Hi there, it looks like `org.asynchttpclient.netty.request.body.BodyChunkedInput` does not touch it's `progress` member at all. Are you ok with a one-line PR?:

    @Override
    public ByteBuf readChunk(ByteBufAllocator alloc) throws Exception {

        if (endOfInput)
            return null;

        ByteBuf buffer = alloc.buffer(chunkSize);
        Body.BodyState state = body.transferTo(buffer);
        progress += buffer.writerIndex();        // <<<<<< Increase progress
        switch (state) {
        case STOP:
            endOfInput = true;
            return buffer;
        case SUSPEND:
            // this will suspend the stream in ChunkedWriteHandler
            buffer.release();
            return null;
        case CONTINUE:
            return buffer;
        default:
            throw new IllegalStateException("Unknown state: " + state);
        }
    }

After that correct values are passed to `onByteSent`. I think its normal that sometimes `org.asynchttpclient.handler.TransferListener#onBytesSent` receives amount = 0, we can just ignore such situations, the rest things looks good, `current` value grows monotonically:

    onBytesSent, amount = 8192, current = 8192, total = 1000000
    onBytesSent, amount = 8192, current = 16384, total = 1000000
    onBytesSent, amount = 8192, current = 24576, total = 1000000
    onBytesSent, amount = 73728, current = 98304, total = 1000000
    onBytesSent, amount = 0, current = 98304, total = 1000000
    onBytesSent, amount = 0, current = 98304, total = 1000000
    onBytesSent, amount = 0, current = 98304, total = 1000000
    onBytesSent, amount = 0, current = 98304, total = 1000000
    onBytesSent, amount = 0, current = 98304, total = 1000000
    onBytesSent, amount = 49152, current = 147456, total = 1000000
    onBytesSent, amount = 0, current = 147456, total = 1000000
    onBytesSent, amount = 0, current = 147456, total = 1000000
    onBytesSent, amount = 0, current = 147456, total = 1000000
    onBytesSent, amount = 0, current = 147456, total = 1000000
    onBytesSent, amount = 0, current = 147456, total = 1000000
    onBytesSent, amount = 49152, current = 196608, total = 1000000
    onBytesSent, amount = 0, current = 196608, total = 1000000
    onBytesSent, amount = 0, current = 196608, total = 1000000
    onBytesSent, amount = 0, current = 196608, total = 1000000
    onBytesSent, amount = 0, current = 196608, total = 1000000
    onBytesSent, amount = 0, current = 196608, total = 1000000
    onBytesSent, amount = 49152, current = 245760, total = 1000000
    onBytesSent, amount = 0, current = 245760, total = 1000000
    onBytesSent, amount = 0, current = 245760, total = 1000000

In my expirience the number of onByteSent call is always = `total` / `8192` (which is the default buffer size hardcoded in `BodyChunkedInput` static variable). You can see that a coupe of calls merged. Not famirlar with Netty, maybe merging happens due to non-blocking nature of network writes.

Any thoughts?

**Comment by odiszapc** [comment]
Fixed zeroes in `org.asynchttpclient.netty.request.WriteProgressListener`:

    49        if (progress != lastLastProgress) {
    50            progressAsyncHandler.onContentWriteProgress(progress - lastLastProgress, progress, total);
    51        }

Result:

    onBytesSent, amount = 8192, current = 8192, total = 1000000
    onBytesSent, amount = 73728, current = 81920, total = 1000000
    onBytesSent, amount = 49152, current = 131072, total = 1000000
    onBytesSent, amount = 49152, current = 180224, total = 1000000
    onBytesSent, amount = 49152, current = 229376, total = 1000000
    onBytesSent, amount = 49152, current = 278528, total = 1000000
    onBytesSent, amount = 49152, current = 327680, total = 1000000
    onBytesSent, amount = 49152, current = 376832, total = 1000000
    onBytesSent, amount = 49152, current = 425984, total = 1000000
    onBytesSent, amount = 49152, current = 475136, total = 1000000
    onBytesSent, amount = 49152, current = 524288, total = 1000000
    onBytesSent, amount = 49152, current = 573440, total = 1000000
    onBytesSent, amount = 49152, current = 622592, total = 1000000
    onBytesSent, amount = 49152, current = 671744, total = 1000000
    onBytesSent, amount = 49152, current = 720896, total = 1000000
    onBytesSent, amount = 49152, current = 770048, total = 1000000
    onBytesSent, amount = 49152, current = 819200, total = 1000000
    onBytesSent, amount = 49152, current = 868352, total = 1000000
    onBytesSent, amount = 49152, current = 917504, total = 1000000
    onBytesSent, amount = 49152, current = 966656, total = 1000000
    onBytesSent, amount = 33344, current = 1000000, total = 1000000


So, are you ok with that? Can I perform a PR?

**Comment by slandelle** [comment]
doh!

Yes, please go with a PR. Thanks a bunch!

**Comment by odiszapc** [comment]
Done: https://github.com/AsyncHttpClient/async-http-client/pull/1354

**Comment by odiszapc** [comment]
@slandelle excuse me, when can I expect this fix to be landed on Maven Central?

**Comment by slandelle** [comment]
I'd say next week, I'm traveling this week.

**Comment by slandelle** [comment]
@odiszapc 2.0.29 and 2.1.0-alpha5 are up on central.
