### ISSUE TITLE
Add config option to eject channels from connection pool after 5xx error response

### ISSUE THREAD

**Issue by kstokoz** [AsyncHttpClient/async-http-client#733]
## Background  ##
In AWS standard service architecture have ELB with several backend nodes. In case of globally load balanced service you will have same in several regions. In case one of the regions has problems in AWS there is an option to fail-over. During fail-over IPs from problematic regions no longer distributed to clients in DNS lookup.

Unfortunately if you are using AHC with connection pooling in case of fail-over requests will continue to be routed to region which has a problem. All request will have 5xx error codes.

## Issue ##
To be able to recover with AHC from such situation is would be great to have a config option not to add such problematic channels back to the pool. So that when new connection required DNS lookup will get healthy region.    

For 1.8.x i was able to to do it easily as NettyResponseFuture had a httpResponse object inside
    
	protected final boolean getKeepAlive() {
        boolean is5xxError = (httpResponse != null && httpResponse.getStatus().getCode() >= 500);
        return keepAlive && !is5xxError;
    } 

in 1.9.x there was a major change in this area and it is no longer easy to do this change.

**Comment by slandelle** [comment]
Implemented in #753, but implementation being reconsidered in #982.

**Comment by VenkataKotra** [comment]
> A partial solution would indeed to have the ELB replies 503 + Connection: close header, but then, only the connection for this request wouldn't be offered back to the pool. What about all the other ones? You'd still get 503 for quite some time, until all connections to the crashed region have been used and removed.

@kstokoz, @slandelle - I'm wondering if there is a complete solution to this problem. I see a bunch of 503s from the partial solution, until all connections are used and removed.

**Comment by slandelle** [comment]
Implement your own retry on 503.
Or better, report a bug against AWS.
