### ISSUE TITLE
Connections in CLOSE_WAIT state forever when server resets/closes the connection - Netty provider

### ISSUE THREAD

**Issue by rugoyal** [AsyncHttpClient/async-http-client#776]
We are using AHC with Netty provider. If the server resets or closes the connection, it is not getting closed by AHC in our app (client side).
All the Connections are in CLOSE_WAIT state and SOCKET leakage is happening. We are observing this under high load after integrating AHC in our project.
AHC Version : 1.8.13
JDK : 7
No ssl communication
Connection pooling and keep-alive set to true.

**Comment by slandelle** [comment]
@rugoyal Have you been able to give recent AHC versions a try?

**Comment by slandelle** [comment]
Closing for now. @rugoyal If you have any new element to provide, feel free to ping and I'll reopen.

**Comment by rilush** [comment]
Hello, any chance I can run into this problem with async-client 1.8.16 and netty-3.9.2 running on top of play 1.2.5? I experience FD leakage with "can't identify protocol' message after switching to the libraries above.
Thanks,
  Ilya.

**Comment by slandelle** [comment]
@rilush AHC 1.8 is no longer maintained. Please get in touch with the Play 1 maintainer so they upgrade from 1.8 to 1.9.
