### ISSUE TITLE
DefaultHostnameVerifier crash on Android because sun.security.util.HostnameChecker is missing

### ISSUE THREAD

**Issue by AmauryEsparza** [AsyncHttpClient/async-http-client#783]
there is part of the problem, please help!

java.lang.IllegalStateException: java.lang.ClassNotFoundException: sun.security.util.HostnameChecker

**Comment by slandelle** [comment]
Inspiration: https://code.google.com/p/kolab-android/source/browse/trunk/javamail/com/sun/mail/util/SocketFetcher.java#559

**Comment by slandelle** [comment]
Closed by #810
