### ISSUE TITLE
randomize cnonce calculation to support concurrency

### ISSUE THREAD

**Issue by chrisrhut** [AsyncHttpClient/async-http-client#787]
`Realm.newCnonce()` currently gets its MD5 source bytes via the system time: `byte[] b = md.digest(String.valueOf(System.currentTimeMillis()).getBytes(ISO_8859_1));`

Meaning that concurrent requests with the same nonce could send the same cnonce, which some servers may not like. An improvement would be to randomize this per invocation:

```java
        private static final Random random = new Random();
        private void newCnonce() {
            try {
                MessageDigest md = MessageDigest.getInstance("MD5");
                byte[] b = new byte[8];
                random.nextBytes(b);
                cnonce = toHexString(b);
            } catch (Exception e) {
                throw new SecurityException(e);
            }
        }
```

(this is actually quite a bit faster too - 100 million invocations takes 12000ms the string conversion way, and only 2800ms using the random byte array.)

**Comment by slandelle** [comment]
> but there's also MessageDigest.getInstance() in newResponse() - I figured if we were going to convert one then should do both?

Right. The MessageDigest should only be fetched once per build call: fetch it in build body, then pass it to newOnce and newResponse. This would also clean up the `UnsupportedEncodingException` handling.

> something about locking or synchronization maybe?

Yeah, Random is synchronized, so you lose CPU cycles (when the thread gets its share of time slicing but can't acquire the lock), hence ThreadLocalRandom.
Then, regarding `MessageDigest`, you save allocations if you cache it in the thread and recycle.

**Comment by slandelle** [comment]
Thanks.

Then, I wonder if there was really a need to randomize. Maybe using an AtomicInteger that we would increment and then complete with left zeros. WDYT?

I have to read the DIGEST auth spec again.

**Comment by chrisrhut** [comment]
it probably would technically work, but I don't think that would be being a "good citizen". The whole idea of the cnonce is to help prevent replay attacks, but still enable re-using the same server nonce for performance reasons. Thus, I don't think we would want such a generally sequential algorithm for cnonce generation.

**Comment by slandelle** [comment]
You're probably right, thanks!
