### ISSUE TITLE
We want to use  async-http-client  for Digest Access Authentication on proxy, does it support the  function  ?

### ISSUE THREAD

**Issue by weiliangwei** [AsyncHttpClient/async-http-client#790]
Hi,
   We are using nginx  as  proxy, and  use  nginx-http-auth-digest   as Digest authentication. We  set  the   nginx 's IP  and port   on IE browser ,and  we could access the website with username and password  normally as we expect . But  how to  use  async-http-client  access the website  by proxy  like  IE browser ,? We  use digest access authenication on proxy ,if  authenication success ,will access the target website ,others  return http's  401 code (authenication fail).
 Does the  async-http-client support the function ? We try many times   ,and all fail.  If it support ,could you give me an example? We use  Digest authentication  not  Basic authentication  on  Nginx proxy.
   Thanks very much!

**Comment by slandelle** [comment]
Which version do you use and with which provider?

**Comment by weiliangwei** [comment]
I use version  1.8  and  not  use provider   for  testing .  My code fllowing :  
  AsyncHttpClient client = new AsyncHttpClient();
       ProxyServer  p=new ProxyServer("192.168.20.189", 80, "userTest", "123456");
 
    ListenableFuture<Response>  a=   client.prepareGet("http://www.baidu.com").setProxyServer(p).execute();
       System.out.println(a.get().getResponseBody().toString());

I  want  to  access  "http://www.baidu.com"  by  the nginx  proxy , And  the  nginx proxy  has  own the digest    authentication  because I  installed the "nginx-http-auth-digest " .  We  set  the nginx proxy  in the browser ,and  the funtion  no  problem  . But  I  use  the  code above ,the  function  is not  right ,and  return code  401  (Authentication  Required).  

 By the way , I  use nginx  for  two function :  proxy  and digest authentication .If  authentication success, the  proxy  the request .Others  return  401 code. The website "http://www.baidu.com"  does not  need digest authentication. The nginx  proxy  need  digest  authentication .  Could you help me ? Thanks very much again !

**Comment by slandelle** [comment]
First, please upgrade to latest 1.9. Then, provide latest Netty 3 in the classpath. Otherwise, AHC will use a JDK based implementation which is just a toy.

**Comment by weiliangwei** [comment]
Hi ,
  I'm sorry .  Is  My  code  right?  Do I need change my code ? Or  Could  you give me an example  ?

**Comment by slandelle** [comment]
#790 duplicate
