### ISSUE TITLE
Grizzly: GrizzlyMaxConnectionsInThreadsTest fails

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#794]
@oleksiys ping :)

**Comment by slandelle** [comment]
@oleksiys I confirm: this test still fails on my side. Probably a race condition.

**Comment by oleksiys** [comment]
ok, will take a look.
Didn't fail for me last time I tested, but may be it was disabled.

On Fri, Jan 30, 2015 at 3:31 PM, Stephane Landelle <notifications@github.com

**Comment by slandelle** [comment]
The test is currently disabled, yes. It fails for me every time I run from maven with the whole test suite. But it succeeds if I run it separately.

**Comment by oleksiys** [comment]
Looking at the test, not sure it's 100% correct, we always check the failed
rank and expect it to be 1, but not sure in threaded scenario we can always
guarantee that.
WDYT?

**Comment by slandelle** [comment]
If I'm not mistaking, the server latency is 2 sec (see DEFAULT_TIMEOUT), so I think it's pretty safe to assume the 2 requests should try to fly at the same time and hit the concurrent connections limit.

**Comment by oleksiys** [comment]
Right, but AFAIU the test still fails if the 1st request (rank 0) hit the
limit.

Alexey.

On Tue, Feb 3, 2015 at 12:45 AM, Stephane Landelle <notifications@github.com

**Comment by slandelle** [comment]
I refactored at it seems to be fine. Thanks for your help!
