### ISSUE TITLE
Javadoc from readme is for 1.8.0-SNAPSHOT

### ISSUE THREAD

**Issue by borisaka** [AsyncHttpClient/async-http-client#798]
https://github.com/AsyncHttpClient/async-http-client
In readme link to javadoc for  1.8.0-SNAPSHOT version.

**Comment by belak** [comment]
What's the status on this? It would be nice to have javadocs available somewhere public.

**Comment by longcao** [comment]
I've been crossing my figures for this one for awhile and serendipitously came across these hosted docs for every version: http://www.javadoc.io/doc/com.ning/async-http-client/

I'll send in a quick PR for the README.md since this seems to be what everyone's looking for.

**Comment by slandelle** [comment]
@longcao Please do. That's one neat service!
