### ISSUE TITLE
Allow setting closeOnSSLException flag for netty provider

### ISSUE THREAD

**Issue by SpookyCookie** [AsyncHttpClient/async-http-client#807]
Netty's SSLHandler has closeOnSSLException flag which is used to close connection in case of exceptions thrown during ssl communication. In netty 3.9 the flag is set to false by default due to compatibility issues, even though documentation recommends it to be true.

There is no way to set it to true when using AsyncHttpClient. Having this flag to false can lead to leaking https connections. Please provide the ability to specify the value for this flag when using NettyAsyncHttpProvider.

**Comment by slandelle** [comment]
Are those leaks something you observed in AHC?

**Comment by SpookyCookie** [comment]
Yes. We are doing many HTTPS request from our application. Occasionally those requests may fail during ssl communication. We noticed that in this case we end up with hung up established connection. The number of such connections will grow up gradually. The connections are closed when the application is shutdown. We are using ahc-1.8.4.

We fixed the issue by branching out ahc-1.8.4 locally and setting closeOnSSLException to true when creating SSLHandler in NettyAsyncHttpProvider.

**Comment by slandelle** [comment]
Then, why just make it confugurable? Wouldn't it be better to simply force it?

**Comment by SpookyCookie** [comment]
Yes, I agree. I'm not sure if having this as false will ever be desirable when using AHC. I think forcing it would be good. It is recommended value anyways: http://netty.io/3.9/api/org/jboss/netty/handler/ssl/SslHandler.html#setCloseOnSSLException%28boolean%29. Also as far as I understand this shouldn't be a problem with Netty 4.0.

**Comment by slandelle** [comment]
Done, thanks for reporting!
