### ISSUE TITLE
Netty: Use standard JDK7 way of enabling certificate validation over HTTPS

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#810]
@wsargent described the problem here: http://tersesystems.com/2014/03/23/fixing-hostname-verification/

For a few months, we've been using a custom HostnameVerifier that also performs hostname matching. We use a private "com.sun" class that's not available on Android, see #783.

Since we now target JDK7, and the Netty provider properly create the SSLEngine with the target hostname and port, we could use JDK7's `SSLParameters` instead of this HostnameVerifier.

**Comment by slandelle** [comment]
@oleksiys I don't find where this would be done in the Grizzly provider.

**Comment by wsargent** [comment]
If you're targeting JDK 1.7, yes.  You can use setEndpointIdentificationAlgorithm and it should work fine.

```
val engine = sslContext.createSSLEngine(peerHost, peerPort)
val sslParams = sslContext.getEnabledParameters()
sslParams.setEndpointIdentificationAlgorithm("HTTPS") 
engine.setSSLParameters(sslParams)
engine.setUseClientMode(true)
```

I would run dnschef to stage a MiTM attack to make sure this works: http://tersesystems.com/2014/03/31/testing-hostname-verification/

**Comment by wsargent** [comment]
The patch doesn't call setSSLParameters.  Added a note: https://github.com/AsyncHttpClient/async-http-client/commit/bd0fc7451f19149045dda742d785380bc606385d#commitcomment-9526572

**Comment by slandelle** [comment]
Fixed. Checking this was on my todo list. Thanks!

**Comment by oleksiys** [comment]
Is there a test, which fails on Grizzly because of this issue?

**Comment by slandelle** [comment]
Maybe `GrizzlyBasicHttpsTest` would fail under J9, but I'm not sure.

It's just an implementation matter. We currently have a HostnameVerifier that actually also perform hostname matching. The plan is to drop it, as JDK7 now provides the trigger the HTTPS hostname verifying on SSLEngine.

**Comment by slandelle** [comment]
Actually, I added a new test `BasicHttpsTest.failInstantlyIfNotAllowedSelfSignedCertificate` and it fails with Grizzly: it throws a EOF instead of a SSLHandshakeException.
