### ISSUE TITLE
urlconnection.disconnect() missing in JDK provider

### ISSUE THREAD

**Issue by jenskordowski** [AsyncHttpClient/async-http-client#813]
JDKAsyncHttpProvider does not close the connection in a few cases (e.g. redirect). AsyncHttpUrlConnection has a member "terminate" that is not reset in the beginning of the call() method. The issue exists on both 1.8.x and 1.9.x branches.
The ApacheAsyncHttpProvider resets it.

**Comment by slandelle** [comment]
Pull Requests welcome :)

**Comment by jenskordowski** [comment]
Pull request filed, see https://github.com/AsyncHttpClient/async-http-client/pull/814

**Comment by jenskordowski** [comment]
I changed it only in 1.9.x. I assume, you will cherry pick this to 1.8.x if everything is fine.

**Comment by slandelle** [comment]
Closed by #814

**Comment by slandelle** [comment]
Thanks.
