### ISSUE TITLE
Allow setting user in SpnegoEngine

### ISSUE THREAD

**Issue by fabienbancharel** [AsyncHttpClient/async-http-client#83]
Hello,
Using Gatling to load test a CAS / SPNEGO server, it appears that in SpnegoEngine, it is not possible to use other credentials than the connected user.
For a load test, it would be better to use different credentials (to avoid locking an account for example).
I think it is possible, in a JUnit we use this piece of code :

```java
kinitArgs[0] = user;
kinitArgs[1] = password;
sun.security.krb5.internal.tools.Kinit.main(kinitArgs);
gssUserName = manager.createName(kinitArgs[0].substring(0, kinitArgs[0].indexOf("@")),
							GSSName.NT_USER_NAME, krb5MechOid);

GSSCredential clientGssCreds = manager.createCredential(
						gssUserName != null ? gssUserName.canonicalize(krb5MechOid) : null,
						GSSCredential.INDEFINITE_LIFETIME, krb5MechOid, GSSCredential.INITIATE_ONLY);

clientGssCreds.add(gssUserName, GSSCredential.INDEFINITE_LIFETIME, GSSCredential.INDEFINITE_LIFETIME,
						spnegoMechOid, GSSCredential.INITIATE_ONLY);

// create target server SPN
GSSName gssServerName = manager.createName(spn, GSSName.NT_USER_NAME);

GSSContext clientContext = manager.createContext(gssServerName.canonicalize(spnegoMechOid),
						spnegoMechOid, clientGssCreds, GSSContext.DEFAULT_LIFETIME);

// optional enable GSS credential delegation
clientContext.requestCredDeleg(true);

spnegoToken = new byte[0];

// create a SPNEGO token for the target server
spnegoToken = clientContext.initSecContext(spnegoToken, 0, spnegoToken.length);
```

Do you think it would be possible to "improve" SpnegoEngine to allow setting the user  ?
Thanks,
Fabien.

**Comment by slandelle** [comment]
Gatling requests can take a `authRealm` or `ntlmAuth` with per user specific data.

**Comment by dmak** [comment]
I have the same challenge as described in initial post by @fabienbancharel. Currently `org.asynchttpclient.spnego.SpnegoEngine` uses the credentials of the user who is logged into the system (or who has issued `kinit -f`). Apparently I would like to use another user which is configured via [`login.config`](http://docs.oracle.com/javase/7/docs/technotes/guides/security/jgss/tutorials/LoginConfigFile.html). More over, the granted ticket could get expired e.g. during the Gatling run, however there is no ability to refresh it. This brings me to idea that there should be a away to replace `SpnegoEngine` implementation with some custom one. For example, `SpnegoEngine#instance()` method could use `java.util.ServiceLoader` helper to locate such custom implementation (this approach needs introduction of some interface with only method `String generateToken(String server)`).

**Comment by slandelle** [comment]
The core issue with Spnego and other enterprisey auth schemes is that I have neither knowledge, needs, nor such environment at hand for testing :( So I'm afraid I won't be able to investigate and help on such topics.

**Comment by dmak** [comment]
I don't expect `SpnegoEngine` to implement all corner cases. I would like somehow to inject my implementation of token provider. That is possible by lookup using `java.util.ServiceLoader`, or having public setter `SpnegoEngine#setInstance(...)`.

**Comment by slandelle** [comment]
@dmak Then, if you know what you're doing, please send a PR :)

**Comment by dmak** [comment]
I agree, thanks for your comment. If I get some time to prepare PR, I'll certainly do it.

**Comment by slandelle** [comment]
Would be great!
