### ISSUE TITLE
freeChannels isn't being released (Netty)

### ISSUE THREAD

**Issue by marenzo** [AsyncHttpClient/async-http-client#831]
For some reason, the following code:

```java
    AsyncHttpClientConfig config = new AsyncHttpClientConfig.Builder().setMaxConnections(200).setMaxConnectionsPerHost(100).build();
    AsyncHttpClient asyncHttpClient = new AsyncHttpClient(config);
    for (int i = 0; i < 140; i++) {
      asyncHttpClient.prepareGet("http://localhost/page.html").execute(new AsyncCompletionHandler<Response>(){

        @Override
        public Response onCompleted(Response response) throws Exception{
          System.out.println("Completed");
          return response;
        }

        @Override
        public void onThrowable(Throwable t){
          System.out.println(t.getMessage());
        }
      }).get();
    }
```
Will throw the following exception: `java.io.IOException: Too many connections per host 100`

As its seems, `abortChannelPreemption` (in `NettyConnectListener`) is never being called because the condition `if (future.isDone())` is always false, thus `freeChannels` (`ChannelManager`) never being released.

Happens on AHC 1.9.10, Java version "1.7.0_65".

**Comment by slandelle** [comment]
Please upgrade to 1.9.11: #820

**Comment by marenzo** [comment]
Thanks for the fast reply!

**Comment by srirama-rayaprolu** [comment]
Hi 

Here the code inside the for loop is blocked.(as get() is called on the future). While executing this piece of code, if checked for the netstat , it would show  only one connection. 

If for loop is executed in asynchronous way the problem of IO exception is coming. How to control this.

Pl. correct me if I am wrong.

Thanks in advance.

**Comment by slandelle** [comment]
@srirama-rayaprolu AHC maxConnection mechanism is a security, it doesn't come with a queue for buffering the excessive requests. If you want one, you have to write one. Contributions welcome.
