### ISSUE TITLE
WebSocketUpgradeHandler.onCompleted should throw Exception when status != 101

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#836]
... instead of returning a null WebSocket, see https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/ws/WebSocketUpgradeHandler.java#L80

Suggested by @oleksiys on the mailing list.

I vote :+1: 

@jfarcand WDYT?

**Comment by jfarcand** [comment]
If @oleksiys say that, I have no choice and say the same :-) :+1:

**Comment by oleksiys** [comment]
thank you guys :)

**Comment by slandelle** [comment]
@oleksiys done!

**Comment by oleksiys** [comment]
@slandelle  great, thank you!
