### ISSUE TITLE
Make SSLSessionContext cache configurable

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#837]
See https://github.com/netty/netty/issues/832

I think I have a user that have this exact issue on Gatling.

What kind of defaults should be going with? 1 cache and 60s timeout?

@jfarcand @oleksiys Thoughts?

**Comment by oleksiys** [comment]
May be it's just me, but I'd leave whatever JDK has as a default and make possible to configure.
Restrict it to 1 cache and 60s may not be that bad for a client side, but may increase load significantly on the server side, which processes many of such a clients and will have to do full handshake much more often.

**Comment by slandelle** [comment]
I agree, I realize those values are stupid. Let's leave the default timeout, if I get it right, the session will be invalidated by the server.

But I really think we should have a non zero default cache max size, as it seems to be the only way to evacuate invalidated sessions from `SSLSessionContextImpl.sessionCache` that weren't explicitly removed. Except from a full GC that would drop the SoftReferences.

I have a user who ended up with 1,5M instances in this cache. When CMS collection is triggered, it has a very hard time with them (it seems GC are bad with References, hence the `ParallelRefProcEnabled ` option), resulting in long GC pauses.

Why not go with a 50,000 max cache size? Doesn't such a high value seem realistic for a max number of concurrent alive SSLSessions?

**Comment by oleksiys** [comment]
@slandelle do you have a testcase for this issue? I can show it to some folks here and may be get some advice from them.

**Comment by slandelle** [comment]
@oleksiys Sadly no. That's a Gatling user load testing one of his company's applications.

**Comment by slandelle** [comment]
@oleksiys I finally went with not overriding defaults as people might be already using the System prop.

**Comment by oleksiys** [comment]
@slandelle +1, IMO it's the best we can do.
