### ISSUE TITLE
Possible javadoc error?

### ISSUE THREAD

**Issue by bibhas2** [AsyncHttpClient/async-http-client#842]
http://asynchttpclient.github.io/async-http-client/apidocs/com/ning/http/client/AsyncCompletionHandler.html

The Javadoc gives the idea that if an exception is thrown from ``onCompleted(Response r)`` then ``onThrowable(Throwable t)`` will not be called. ``onCompleted`` is stated as ``always invoked as last callback method``.

This does not seem to reflect what happens in reality. An exception thrown in ``onCompleted`` does indeed call ``onThrowable(Throwable t)``. This distinction is crucial for anyone counting down a ``CountdownLatch`` from both of these callbacks. If  ``onCompleted()`` throws an exception you run the danger of counting down the latch twice.

**Comment by slandelle** [comment]
Yes, that's an error. I will fix it.

**Comment by slandelle** [comment]
closed by adc0354274c075c42947da2701bca028ae9020ea
