### ISSUE TITLE
Grizzly provider doesn't support NTLM

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#846]
Using NTLM will result in a "java.util.concurrent.ExecutionException", either "java.lang.IllegalStateException: 401 response received, but no WWW-Authenticate header was present" or "java.lang.IllegalStateException: Unsupported authorization method: NTLM", depending on whether the auth is set to preemptive or not.

**Comment by slandelle** [comment]
Hi @oleksiys,

Do you think you'll ever be able to do something about it?

**Comment by oleksiys** [comment]
Hi,

yes, I'll take a look, is it 1.9.x?
Do we have NTLM tests I can enable for Grizzly to test?

Thank you.

WBR,
Alexey.

**Comment by slandelle** [comment]
> yes, I'll take a look, is it 1.9.x?

Yep

> Do we have NTLM tests I can enable for Grizzly to test?

Yep too: NTLMTest (you could have found out by yourself ;-) ).

Good luck with that. I had to implement blindly, without a NTLM system at hand, with a user remotely testing for me...

**Comment by jfarcand** [comment]
Still having nightmare with NTLM ;-)

**Comment by slandelle** [comment]
It seems to be working on the Netty side, I cross fingers I don't have to touch it ever again...

**Comment by oleksiys** [comment]
All that sounds very optimistic :))

On Tue, Mar 31, 2015 at 3:36 PM, Stephane Landelle <notifications@github.com

**Comment by slandelle** [comment]
Closed by 0cf82663953ebc2201b2b3e2df219e7def6ba5a4 and 980308663f01ff7f0baca48f91d1ef2bf3f99026
