### ISSUE TITLE
Netty: Cancel timeouts asap

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#848]
without waiting for the channel to drain

This is a better understanding of #844

**Comment by slandelle** [comment]
ping @maxpower-artvandelay I think this was your exact issue, but the fix was invalid.

**Comment by maxpower-artvandelay** [comment]
Hey, I believe so, I'll attempt to reproduce the read timeout I saw with the new client.

**Comment by slandelle** [comment]
Thanks!
