### ISSUE TITLE
Exception Ljava/lang/NoClassDefFoundError; thrown while initializing Lcom/ning/http/util/AsyncHttpProviderUtils;

### ISSUE THREAD

**Issue by idchlife** [AsyncHttpClient/async-http-client#849]
Having this problem for over week. Anyone experienced this?

    04-02 17:50:38.955  21138-21227/eu.application.androidapplication W/dalvikvm﹕ Exception Ljava/lang/NoClassDefFoundError; thrown while initializing     Lcom/ning/http/util/AsyncHttpProviderUtils;
    04-02 17:50:38.955  21138-21227/eu.application.androidapplication W/System.err﹕ java.lang.ExceptionInInitializerError
    04-02 17:50:38.955  21138-21227/eu.application.androidapplication W/System.err﹕ at com.ning.http.client.RequestBuilderBase.computeFinalUri(    RequestBuilderBase.java:599)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at com.ning.http.client.RequestBuilderBase.build(RequestBuilderBase.    java:607)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.build(    AsyncHttpClient.java:263)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(    AsyncHttpClient.java:225)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at eu.application.androidapplication.applicationphone.tasks.    ConnectToChatSocketTask.doInBackground(ConnectToChatSocketTask.java:29)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at eu.application.androidapplication.applicationphone.tasks.    ConnectToChatSocketTask.doInBackground(ConnectToChatSocketTask.java:18)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
    04-02 17:50:38.958  21138-21227/eu.application.androidapplication W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
    04-02 17:50:38.961  21138-21227/eu.application.androidapplication W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.    java:1080)
    04-02 17:50:38.961  21138-21227/eu.application.androidapplication W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.    java:573)
    04-02 17:50:38.965  21138-21227/eu.application.androidapplication W/System.err﹕ at java.lang.Thread.run(Thread.java:856)
    04-02 17:50:38.968  21138-21227/eu.application.androidapplication W/System.err﹕ Caused by: java.lang.NoClassDefFoundError: java.nio.charset.    StandardCharsets
    04-02 17:50:38.968  21138-21227/eu.application.androidapplication W/System.err﹕ at com.ning.http.util.AsyncHttpProviderUtils.<clinit>(    AsyncHttpProviderUtils.java:46)
    04-02 17:50:38.968  21138-21227/eu.application.androidapplication W/System.err﹕ ... 12 more

**Comment by slandelle** [comment]
Either you're using an old version. Then, please update.
Or your Dalvik is not compatible with JDK7.

**Comment by idchlife** [comment]
@slandelle I'm using version 1.9.17 right know.
About Dalvik is not compatible, how can it be? Error is present only when starting on device huawei p6-u06. You mean this phone has Dalvik VM with JDK <7?

**Comment by slandelle** [comment]
Exactly.

From [huawei p6-u06's spec](http://consumer.huawei.com/en/mobile-phones/tech-specs/p6-u06-en.htm), it ships with Android 4.2.2.
Android only supports JDK7 since KitKat (4.4).

**Comment by idchlife** [comment]
@slandelle thank you!
