### ISSUE TITLE
Inconsistent behavior in redirect after dropping setRemoveQueryParamsOnRedirect

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#852]
That feature was dropped from 1.9.x in https://github.com/AsyncHttpClient/async-http-client/commit/e1233ac3249f11e827a599ea5b0c3f0d3672af4b but as you can see there on Netty's side  the false flag survived while on Grizzly's it was the true flag, so Grizzly removes query parameters on redirects.

**Comment by slandelle** [comment]
For the record, @jfarcand had no idea why he introduced that and made true the default in the first place. So I removed it, as I couldn't find any information about such a behavior in the RFC.

I kept Grizzly provider's behavior the same so I didn't break anything on a side that's no mine.

**Comment by afelisatti** [comment]
The problem I am seeing is that when the location header contains query parameters, say "/redirect?param1=value1&param2=value2" then the location used for the redirect is "/redirect". Setting the removeQueryParamsOnRedirect flag to false solved the issue in 1.8.14 but now this is not possible.

**Comment by slandelle** [comment]
IMHO, Grizzly should behave like Netty. @alexei, that's your call.

**Comment by oleksiys** [comment]
As usual stupid question, do we have a test for it? :)
If not, Ana, can you pls. send me a testcase?

Thank you.

**Comment by afelisatti** [comment]
Couldn't find an existing test case for that. I'll add one to the PR
submitted.

**Comment by afelisatti** [comment]
This was fixed with the PR merge.
