### ISSUE TITLE
Improve Documentation to highlight need to close each AsyncHttpClient or only have one

### ISSUE THREAD

**Issue by jtruelove** [AsyncHttpClient/async-http-client#856]
I ran in to an issue using your library and following your simple example. I wasn't closing the http connections after use, I assumed that when the object went out of scope it would get reclaimed or that you did whatever pooling of connections you needed underneath this is how many Http libs I've used work. 

I moved to having only one instance for the entire server and everything resolved itself. I would just call out in the main Readme that connections MUST be closed and encourage people to only create one instance and just make sure your callback handlers are thread safe.

This seems like a common misuse of your library. As seen here:
http://stackoverflow.com/questions/12903761/threads-running-amuck-with-asynchttpclient-and-quartz-job

If you can find a way to auto clean up the connections or alert the user of the lib that this was going on that would also probably be a good area of improvement.

**Comment by slandelle** [comment]
Contribution welcome.

**Comment by slandelle** [comment]
AHC implements `Closeable`, so it's pretty obvious that it's supposed to be closed, typically in a `try-with-resources` block that's available since JDK7.
