### ISSUE TITLE
AsyncCompletionHandlerBase logger should be static

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#861]
Following #749, that logger should also be static to improve performance.

**Comment by afelisatti** [comment]
Just submitted a PR on branch master, but this should be back ported to 1.9.x as well.

**Comment by slandelle** [comment]
Cleaner. But don't expect a huge performance gain: logger instances are cached in the factory :)

**Comment by slandelle** [comment]
Thanks

**Comment by afelisatti** [comment]
You're welcome!
