### ISSUE TITLE
NTLM auth fails on redirect

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#866]
Testing NTLM auth in 1.9.x I found that it fails when the server response to the request containing the type 3 message is a redirect. The issue is that the connection is already authenticated but the redirect request has the "Authorization" header in it (with the type 3 message). This happens for Netty and Grizzly. With Grizzly, in addition,  the connection is not reused.

**Comment by slandelle** [comment]
Could you provide a reproducer, please?

**Comment by afelisatti** [comment]
Unfortunately the testing was against private instances of SharePoint and MS Dynamics. I'll see if I can get access to another server. 
I guess NTLMTest could be modified to show this behavior by returning a 307 instead of a 200 status code though.

**Comment by oleksiys** [comment]
Just to make sure, type 3 message sends a local redirect to a different
path, not a different host?
In Grizzly, as I understand, we just take a new connection from pool to
serve the redirect, not sure how it works in Netty, but with NTLM it kind
of make sense to check if it's local redirect and reuse the existing
connection. Is that right?

WBR,
Alexey.

**Comment by slandelle** [comment]
@afelisatti  Type 3 message? You mean type 2, right? Type 3 is from client to server.

@oleksiys In Netty, current connection is reused when redirecting on the same (scheme, host, port).

**Comment by afelisatti** [comment]
The server response to the type 3 message is a 307 redirect to a different path. So when the redirect is done the authentication header is sent again and the request is rejected.

**Comment by slandelle** [comment]
Get it, fixed for Netty.

**Comment by afelisatti** [comment]
Thanks. I'll test it again tomorrow.
@oleksiys, that sounds like the right thing for NTLM. I tested it forcing Grizzly to reuse the connection and it worked except for the  auth header being sent again.

**Comment by oleksiys** [comment]
I'll fix it tomorrow.
Thank you!

WBR,
Alexey.

**Comment by slandelle** [comment]
@afelisatti Did you get a chance to check if the Netty provider now works as expected, please?

**Comment by afelisatti** [comment]
@slandelle yes, it does work now. Although the logs showed that the auth process was done again. Just checked with wireshark and the connection was not reused for the redirect. I guess it's not an issue though since that new connection is reused for the following requests.

**Comment by slandelle** [comment]
Is the redirect done to the same (scheme, host, port) triplet?

**Comment by afelisatti** [comment]
Yes. In fact, the only change in the Location header is a slash at the end of the URL. Only difference I see is that I included the port in the initial URL (like ww.example.com:80) . I see the connection being reused after removing that port.

**Comment by slandelle** [comment]
Fixed, see #870. Thanks a lot for reporting!

**Comment by oleksiys** [comment]
Should be fixed for Grizzly provider as well.
Can you pls. double check?

Thank you!

**Comment by afelisatti** [comment]
Just checked for both Grizzly and Netty. Working fine now. Thanks for the quick fixes!
