### ISSUE TITLE
NTLM auth using bad credentials results in a 400 with Grizzly

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#869]
When bad credentials are used, the server sends a 401 after the client type 3 message. It seems Grizzly then tries to start the auth process again which ends up in a 400 response from the server. I uploaded the simplified exchange observed here http://pastebin.com/WYbAaJbJ

**Comment by slandelle** [comment]
What about the Netty provider?

**Comment by afelisatti** [comment]
I checked, the Netty provider works well and returns the 401.

**Comment by slandelle** [comment]
Thanks for the info.

**Comment by afelisatti** [comment]
Just tested again with changes for #866 in Grizzly provider (commit 6bfe61d951b0056fd16d27c6ea69f684f524fadb) and this is now working as expected, meaning the response to the request with bad credentials is a 401.

**Comment by slandelle** [comment]
Thanks, closing.
