### ISSUE TITLE
Detecting WS not supported by server-side

### ISSUE THREAD

**Issue by dimzon** [AsyncHttpClient/async-http-client#871]
this code run forever (ya.ru is not WebSocket) and I have no idea
1) why it doesn't breaks
2) how to detect server (or firewall) doesn't support websocket

```java
AsyncHttpClient c = new AsyncHttpClient();
try {
    WebSocket websocket = c.prepareGet("http://ya.ru/")
            .execute(new WebSocketUpgradeHandler.Builder().addWebSocketListener(
                    new WebSocketListener() {
                        @Override
                        public void onOpen(WebSocket websocket) {
                        }

                        @Override
                        public void onClose(WebSocket websocket) {
                        }

                        @Override
                        public void onError(Throwable t) {
                          t.printStackTrace();
                        }
                    }).build()).get();
    System.out.println(websocket);
} catch (InterruptedException e) {
    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
} catch (ExecutionException e) {
    e.printStackTrace();  //To change body of catch statement use File | Settings | File Templates.
}
```

I'm trying to write IP-over-HTTP tunneling proxy (to bypass firewalls). WebSockets is perfect but some ugly firewalls doesn't allow them. So main idea is to check ability to connect to websocket first and fallback to http-pooling...

**Comment by slandelle** [comment]
Please mention your AHC version and the provider you use.
I just tested with AHC 1.9.20 and Netty and I got the expected `IllegalStateException: Invalid Status Code 200` as `http://ya.ru/` is not a ws url.

Could you please provide all the information plus a working example?

Then, it looks like what you're trying to achieve is what [Atmosphere](https://github.com/Atmosphere/atmosphere) is about.

**Comment by slandelle** [comment]
@dimzon Note that your above sample doesn't terminate because you forgot to close the client.
I also improved the way websockets are validated, your test should fail fast as scheme is neither `ws` nor `wss`.

Closing as the issue in your sample is broken. Feel free to open a new one if you can provide a proper sample demonstrating an issue.
