### ISSUE TITLE
java.io.IOException: Remotely closed

### ISSUE THREAD

**Issue by rjbhewei** [AsyncHttpClient/async-http-client#872]
builder.setMaxRequestRetry(0);
builder.setRequestTimeout(60 * 1000);
builder.setConnectTimeout(60 * 1000);
use this config,client send async request to the server,but client have "java.io.IOException: Remotely closed"  exception，small probability。

**Comment by slandelle** [comment]
Because that's exactly that: some remote component (server, proxy, etc) closed the socket while the client was trying to write. That's what retry is for.

**Comment by rjbhewei** [comment]
i use netty5 as server ，not close the client unless the request data deal ok

 public void start() throws InterruptedException {
        bossGroup = new NioEventLoopGroup(1);
        workerGroup = new NioEventLoopGroup();
        ServerBootstrap bootstrap = new ServerBootstrap();
        bootstrap.option(ChannelOption.SO_BACKLOG, 1024);
        bootstrap.option(ChannelOption.SO_REUSEADDR, true);
        bootstrap.option(ChannelOption.TCP_NODELAY, true);
        bootstrap.option(ChannelOption.SO_KEEPALIVE, true);
        bootstrap.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class).handler(new LoggingHandler(LogLevel.INFO)).childHandler(new ChannelInitializer<SocketChannel>() {

            @Override
            protected void initChannel(SocketChannel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();

                pipeline.addLast("serverCodec",new HttpServerCodec());

                pipeline.addLast("aggregator", new HttpObjectAggregator(Integer.MAX_VALUE));

                pipeline.addLast(e1, "handler", new KernHttpServerHandler_netty5());

            }
        });

**Comment by slandelle** [comment]
Which version of AHC do you use?

**Comment by slandelle** [comment]
Answering my own question: 1.9.17.
This is definitively a duplicate of #848 that was fixed in 1.9.18.

Of the importance of checking upgrades and release notes before reporting an issue...

**Comment by rjbhewei** [comment]
1.9.17
