### ISSUE TITLE
NettyCloseCodeReasonMsgTest.wrongProtocolCode test failing

### ISSUE THREAD

**Issue by ipsq** [AsyncHttpClient/async-http-client#879]
http://pastebin.com/j6ptvM8y

**Comment by ipsq** [comment]
org.asynchttpclient.providers.netty3.ws

**Comment by ipsq** [comment]
Do you use some sort of CI solution? I run these tests on my own TeamCity setup, just to test it.

**Comment by slandelle** [comment]
I'd gladly use Travis, but some of the tests I inherited for the previous land owner work or fail depending on your timezone... I set them to mine (Europe) while the free CI like Travis and Cloudbees use US.

The proper thing to do first would be to fix those tests.

**Comment by ipsq** [comment]
Also, what are you planning to do with Grizzly? You have some tests for it but currently the provider is not in the repo's master branch.

**Comment by slandelle** [comment]
Grizzly is going away in 2.0
