### ISSUE TITLE
ECCN for async-http-client

### ISSUE THREAD

**Issue by beurer** [AsyncHttpClient/async-http-client#881]
Hello,
We use async-http-client in our commercial product and therefore need to know the ECCN for it.
The ECCN is an international Export control and compliance number that is necessary for EVERY Export. Most of the european countries specify their goods according to the european commerce control list (EG dual-use list : http://ec.europa.eu/trade/index_en.htm).
So for export of a commercial Software using async-http-client  ( or any other open source or OEM Software), we need to document the libs, on one side to comply with license obligations and on the other side the ECCNs for Export restrictions. Please note, as the US regulations also care about re-export of US items ( any stuff that contains US Content above a certain Limit), we need to specify both; the EU-ECCN and the US-ECCN and hopefully the US license exception that applies (e.g. TSU for open source).

So please specify the ECCN for async-http-client  or answer the following questions:
- Country of origin ( where is async-http-client  Software mainly developed)
- is there US Content in there? ( e.g. other open source libs)
- Is the SW designed or modified to use cryptography performing any cryptographic function other than authentication or digital signature? (y/n) 
–if yes,
-- key length symetric
-- Bit length asymmetric

Thanks and kind regards
Maria Beurer

**Comment by slandelle** [comment]
Hello Maria,

I have to investigate this and talk with the project's founder, @jfarcand.

AHC doesn't currently have an ECCN.

* Country of origin: currently, mainly France, but in this project long history, it's been developped in Canada and the US.
* is there US Content in there: yes, at least all the Grizzly support has been developed by Oracle employees in the US. Then, you'll have to check Netty or Grizzly depending on which one you use.
* Is the SW designed or modified to use cryptography performing any cryptographic function other than authentication or digital signature? HTTPS support, currently with the JDK factories, but might support OpenSSL someday.

Hope it helps.

**Comment by jfarcand** [comment]
The initial version `1.0` of the project as been developped in the US and founded `Ning.com` company. That was from November 2009 to June 2010. From July 2010 to July 2011 it was developped under the `Sonatype.com` company. From July 2011 until now it has been fully developped by company like `HelloReverb.com`, 'Oracle',  and  `Excilys`. `Excilys` (France) is the main contributor.
