### ISSUE TITLE
Grizzly: Connection: keep-alive header is sent even if keep-alive is disabled

### ISSUE THREAD

**Issue by andresgregoire** [AsyncHttpClient/async-http-client#885]
GrizzlyAsyncHttpProvider always adds the "Connection: keep-alive" header to the request. If allowPoolingConnections is set to false in the AsyncHttpClientConfig, then the header "Connection: close" should be added, as the client will not reuse the connection.

**Comment by oleksiys** [comment]
makes sense, I'll take a look.
Thank you.

**Comment by slandelle** [comment]
Note: the Netty provider has this right.

@oleksiys see `AsyncHttpProviderUtils.keepAliveHeaderValue`

**Comment by oleksiys** [comment]
@slandelle hmm, what about config.isAllowPoolingSslConnections()? Also for redirects Grizzly can use standalone (not pooled) connections (not sure if Netty does the same).

**Comment by oleksiys** [comment]
marking the issue as closed.

**Comment by slandelle** [comment]
@oleksiys I don't get your question. Regarding redirects, Netty reuse the same connection if the redirect is the same host and scheme.

**Comment by oleksiys** [comment]
@slandelle sorry, if I wasn't clear. The AsyncHttpProviderUtils.keepAliveHeaderValue, you referred, checks config.isAllowPoolingConnections() only, but AFAIU when we decide if we want to pool connection or not we also consider config.isAllowPoolingSslConnections() (for SSL connections)...
So the AsyncHttpProviderUtils.keepAliveHeaderValue may set "Connection: keep-alive" header for SSL connection, even though config.isAllowPoolingSslConnections() is false.
