### ISSUE TITLE
Send Image from android to Node js

### ISSUE THREAD

**Issue by StigmaKim** [AsyncHttpClient/async-http-client#895]
I need your help. Please help me.

I'd like to send image from android app to Nodejs server to save into mongoDB on server side.

My code is like this.

Android ->
File file = new File(imgpath);
RequestParams param = new RequestParams();
param.put("email", email);
param.put("image", file, "image/jpg");

HttpClient.post("uploadImg_Profile/", param, new AsyncHttpResponseHandler() {
....

Node.js->
exports.uploadImg_Profile= function(req, res){
    var User = new user({ 
        img : req.body.image
    });
    //
    console.log("img: "+ User.img);
}
But console.log result is undefined. I respect that this is seen "jhgdsfejdi734634jdhfdf" like this bson type result.

1. How can I get img data?

2. There is a way to get file's type from File object dynamically?

**Comment by slandelle** [comment]
Not an issue but a question. Please use the Google Group.

**Comment by slandelle** [comment]
Not even the right project, you're looking for loopj.

**Comment by StigmaKim** [comment]
sorry, and thanks.
