### ISSUE TITLE
Netty: Client preserves form params when POST returns with 302 redirect

### ISSUE THREAD

**Issue by yatindra** [AsyncHttpClient/async-http-client#898]
Hi,

When the server returns a 302 redirect for a POST request, the client preserves the POST body from the original request, in my case the form params.

This generally is not an issue, but when proxying through Squid, I get `411 Length Required` which actually is because the request is a `GET` with a body and Content-Length header.
Confirmed this by

1. setting strict302Handling to true on client config, in which case the new request remains a POST.
1. modifying the `com.ning.http.client.providers.netty.handler.Protocol` class as below.

If this is not considered an AHC issue, then would like a way to configure the resetting of the body in the client config.

I am using AHC version 1.9.6 with Netty provider. Also tested the same with latest 1.9.25.
The issue appears to be in `com.ning.http.client.providers.netty.handler.Protocol`
where:
```java
// if we are to strictly handle 302, we should keep the original method (which browsers don't)
// 303 must force GET
if ((statusCode == FOUND.getCode() && !config.isStrict302Handling()) || statusCode == SEE_OTHER.getCode())
    requestBuilder.setMethod("GET");
```
should be:
```java
// if we are to strictly handle 302, we should keep the original method (which browsers don't)
// 303 must force GET
if ((statusCode == FOUND.getCode() && !config.isStrict302Handling()) || statusCode == SEE_OTHER.getCode()) {
    requestBuilder.setMethod("GET");
    requestBuilder.resetFormParams();
    requestBuilder.resetNonMultipartData();
    requestBuilder.resetMultipartData();
}
```

Thanks

**Comment by slandelle** [comment]
Expected behavior is very empirical here: the RFCs are very vague.
Will fix.

**Comment by yatindra** [comment]
Thanks.
