### ISSUE TITLE
Netty: Workaround for IIS server when Host header value contains port as well

### ISSUE THREAD

**Issue by yatindra** [AsyncHttpClient/async-http-client#899]
Hi,

So, this is actually not an issue, but I would like to know a workaround for this.
When the Host header in request contains the port as well `Host: www.example.com:443`
which is the default behaviour and which is also as per RFC, servers like IIS fail to parse it properly and return a 404 for a valid URL.
This may not be the case always, only when IIS is not configured properly.
For direct cases where I know the end URL, I usually set the Host header manually and AHC does not overwrite the value I provide.
But in cases where a redirection happens AHC will generate a new request and there I don't have control over the value. I don't have control over the original URL input as well, so updating to the correct URL is also not possible.
Example URL: https://www.chamberofcommerce.com/short-hills-nj/11218079-massage-envy-spa-short-hills-llc

Is there a workaround for this?

**Comment by slandelle** [comment]
A proper solution would be to not pass the port when it's the scheme's default one.
Fixing.

**Comment by slandelle** [comment]
As a workaround, you can explicitly set the Host header in the request.

**Comment by slandelle** [comment]
@yatindra Fixed, thanks for reporting!
Do you have more issues to report?

**Comment by yatindra** [comment]
Thanks a lot.

**Comment by yatindra** [comment]
By the way when would you be releasing 1.9.26?

**Comment by slandelle** [comment]
> Will it be possible to get the final set of cookies that were propagated in the response received at AsyncHandler?

Implement `AsyncHandlerExtensions` and inspect `onSendRequest` parameter.

> By the way when would you be releasing 1.9.26?

Just did. Wait for sync to happen on central.

**Comment by yatindra** [comment]
Great thanks.
