### ISSUE TITLE
Netty: Use HTTP/1.0 when connection pooling is disabled

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#909]

**Comment by gerdriesselmann** [comment]
Excuse me for bring this old topic up, but what's the reason behind this change? We never had issues with connection pooling disabled and HTTP 1.1 requests.

**Comment by slandelle** [comment]
What's the point in asking the server to maintain connections when the client will close it as soon as it receives the response?

**Comment by gerdriesselmann** [comment]
The problem is that HTTP 1.0 does not support a couple of features that are essential for the modern web. Namely compression.

On the other hand, as far as I understand, HTTP 1.1. RFC states that "HTTP implementations SHOULD implement persistent connections", but they must not. So it is perfectly legal to have a HTTP 1.1 non-persistent connection, unless you are sending a "connection: close" HTTP header.

**Comment by slandelle** [comment]
OK, you have a point. But then, it means that we need a different parameter for controlling the protocol version.

**Comment by Noki** [comment]
Having such a parameter is a really good idea, especially with HTTP/2 in mind.

**Comment by slandelle** [comment]
@Noki Yeah... I hope you realize bringing HTTP/2.0 support is not just about changing the protocol version in the request header :smile:

**Comment by Noki** [comment]
I am well aware of that. ;-)

**Comment by gerdriesselmann** [comment]
I wonder though, if it is really required at the moment. With connection pooling disabled and the HTTP 1.1 protocol forced, I get the following request using Netty:

    GET / HTTP/1.1
    Accept-Encoding: gzip,deflate
    Connection: close
    Host: localhost:8080
    Accept: */*
    User-Agent: test-agent

Which seems fine to me. The response of a Jetty server looks like this:

    HTTP/1.1 200 OK
    Content-Type: application/json; charset=utf-8
    Connection: close
    Server: Jetty(8.1.13.v20130916)
    Content-Encoding: gzip

Just returning to the previous code which was

    HttpVersion httpVersion = method == HttpMethod.CONNECT && proxyServer.isForceHttp10()
      ? HttpVersion.HTTP_1_0
      : HttpVersion.HTTP_1_1;

should be sufficient for now.

**Comment by slandelle** [comment]
Done, see #1053
