### ISSUE TITLE
Fix for #921 breaks all OAuth requests

### ISSUE THREAD

**Issue by henningp** [AsyncHttpClient/async-http-client#922]
The fix for issue #921 breaks all OAuth requests, even those that were previously working.

The problem is that the nonce is not urlencoded, breaking the request (e.g. "&oauth_nonce=cDEwXIeEzLcTYN/tSKZOCg==").

**Comment by slandelle** [comment]
@henningp Ouch. In the samples I got, the nonce token didn't need encoding... Fixed, thanks for reporting!

**Comment by henningp** [comment]
Added pull request: https://github.com/AsyncHttpClient/async-http-client/pull/923

**Comment by henningp** [comment]
Ah, that was fast! :) Looking forward to the release, we're running a monkeypatched version as of now.

**Comment by slandelle** [comment]
@henningp I just released 1.9.29.

**Comment by henningp** [comment]
Nice, thanks!
