### ISSUE TITLE
how to handle double slash in a url path?

### ISSUE THREAD

**Issue by fwz** [AsyncHttpClient/async-http-client#924]
Hi,

Today I encounter an issue when calling a server, which could not handle double slash in an URL.

i.e. it could accept "http://foo/bar", but could not handle "http://foo//bar" (which return 404 error).

I know that the second one is an invalid URL. I could handle it by replacing "//" to "/" from its second occurrence, but I am just wondering whether there is a built-in way to do that.

Thanks a lot!

**Comment by slandelle** [comment]
1. If you're actually using loopj and not our project, go ask there: https://github.com/loopj/android-async-http/issues/876. 
2. Otherwise (but I doubt it, "http://foo//bar" is properly turned into "http://foo/bar" with our library), please use our Google Group for questions.

**Comment by fwz** [comment]
@slandelle , Thank you for your quick response.

I start a post in https://groups.google.com/forum/#!topic/asynchttpclient/6ka112HxfPw with more detail and sample code, could you please help take a look? 

Thanks!

**Comment by bryanmau1** [comment]
Sorry for resurrecting an old thread.  @slandelle did your # 2 disappear with 2.0?

**Comment by slandelle** [comment]
@bryanmau1 Did you give it a try yourself? If so and you have an issue, could you please provide a reproducer?

**Comment by bryanmau1** [comment]
We encountered this issue in production when trying to migrate our code from Play 2.4 to Play 2.5.  Under the hood Play 2.5 uses the new AHC 2.0.

Also, I was able to reproduce this locally on an sbt console.
```
scala> val c = new org.asynchttpclient.DefaultAsyncHttpClient()
c: org.asynchttpclient.DefaultAsyncHttpClient = org.asynchttpclient.DefaultAsyncHttpClient@33b051ff

scala> c.prepareGet("http://localhost:9000/campaigns/manage").execute().get()
res1: org.asynchttpclient.Response =
NettyResponse {
	statusCode=200
...

scala> c.prepareGet("http://localhost:9000//campaigns/manage").execute().get()
res2: org.asynchttpclient.Response =
NettyResponse {
	statusCode=404
...

```

As you can see the first call only has one slash after the host:port whereas the second has two slashes.

**Comment by slandelle** [comment]
@gmethvin Thanks for your feedback. You're right, and there's no reason to remove empty path segments.
