### ISSUE TITLE
Run all threads as daemons, possibly by configuration

### ISSUE THREAD

**Issue by HaydenSikh** [AsyncHttpClient/async-http-client#926]
Possibly can be merged with https://github.com/AsyncHttpClient/async-http-client/issues/384.

Considering the following minimal application:

```java
import com.ning.http.client.AsyncHttpClient;

class Example {
    public static void main(String[] args) throws Exception {
        AsyncHttpClient client = new AsyncHttpClient();
    }
}
```

Despite doing nothing other than creating an instance of `AsyncHttpClient`, the program will hang until killed.  It appears this occurs because the `New I/O Boss` thread is not run as a daemon.

Adding an invocation of `client.close()` does free up the threads and allow the JVM to exit, but this may not be available to us.

Specifically, in our case we don't create any `AsyncHttpClient` instances directly but use several libraries which do.  This usage can be fairly deeply nested, not reachable by our code, and may not be gracefully shutdown.  In particular we have some exceptional code paths which should be fatal to the application, either so we can generate an alert for manual inspection of the failure or have a process monitor which should try restarting the service.  In these scenarios a graceful shutdown may not be feasible and so the application just hangs.

**Comment by slandelle** [comment]
> Specifically, in our case we don't create any AsyncHttpClient instances directly but use several libraries which do. This usage can be fairly deeply nested, not reachable by our code, and may not be gracefully shutdown.

So don't you think that's an issue for those other libraries?

**Comment by HaydenSikh** [comment]
Yes and no.  It's an issue for those libraries and will help in the cases where a graceful shutdown is viable, and for that reason I'm following up with them as well.  That said, graceful shutdowns are not always viable.  Unfortunately the current functionality of async-http-client means that in those cases where something goes fatally wrong, a bad situation is made worse since the most direct and expected signal of the error -- termination of the app -- is prevented.
