### ISSUE TITLE
Disable SSlv2ClientHello by default

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#934]
Since PODDLE, most servers have harden their protocol configuration. Sometimes, SSLv2Hello got disabled along the way, causing handshake to fail.

Let's only enable TSL by default.

See #925 and https://groups.google.com/forum/#!topic/asynchttpclient/pSxiChVJwiI

Workaround is to explicitly configure the enabled protocols.

**Comment by mgrandi** [comment]
Setting in your AsyncHttpClientConfig.Builder

```
builder.setEnabledProtocols(new String[] {"TLSv1.2", "TLSv1.1", "TLSv1"});
```
fixes it for now, until the next release comes out that has those protocols set as the default.
