### ISSUE TITLE
Cookie object bad api

### ISSUE THREAD

**Issue by marenzo** [AsyncHttpClient/async-http-client#935]
After upgrading from 1.9.11 to 1.9.30, I saw there were some changes with the Cookie object:
deprecation of expires, changing maxAge to be long and adding wrap parameter.
While it's all nice, the Cookie.newValidCookie is strange.
First of all, it's still accepts expires, although it doesn't do anything with the value.
Second, it accepts maxAge as int while the getter of maxAge returns long, which seems to me
kind of strange.

What I think should be is removing expires parameter from the newValidCookie method, and changing signature of maxAge to be long

**Comment by slandelle** [comment]
I deprecated this factory (can't remove it in a fix for compatibility) and introduced a new one.
Thanks for reporting.
