### ISSUE TITLE
Issue when redirect url is of https protocol

### ISSUE THREAD

**Issue by iampiyush** [AsyncHttpClient/async-http-client#936]
My requests either got cancelled or timeout, when redirect url is of type https protocol

**Comment by slandelle** [comment]
Which version do you use?
Which provider do you use?
Can you provide a reproducer please?

**Comment by vvsh** [comment]
Version: 1.9.30
Provider: Netty
Reproducer: I don't know what is it)

**Comment by slandelle** [comment]
A reproducer is a way to reproduce the issue you describe.

**Comment by slandelle** [comment]
No information from user. Closing.
