### ISSUE TITLE
Keep alive and dns caching

### ISSUE THREAD

**Issue by davehagler** [AsyncHttpClient/async-http-client#937]
Does keep alive interfere with dns caching ttl?  

When my application is under constant load and making rapid http client connections, I have observed when networkaddress.cache.ttl is set to something other than the default -1 in the security properties, and a dns entry changes, the new entry never takes effect.  

When the application is not under constant load and there is a break in http client connections, then the new dns takes effect.

Does keep alive mean the connection will never be re-established and dns lookup will never take place if client http requests are rapid enough?

The application is Play Framework 2.3 with Async HTTP Client 1.8.15

**Comment by slandelle** [comment]
AHC uses Java's DNS resolution which is a black box, so it has no way of being notified of a DNS change.
In AHC 1.9, you can use NettyAsyncHttpProviderConfig.setConnectionStrategy to not pool the connection back into the pool when you know what the response look like when the address has changed and yet the connection is still open.

Please use our [Google Group](https://groups.google.com/forum/#!forum/asynchttpclient) for questions.
