### ISSUE TITLE
Compatibility with java 6

### ISSUE THREAD

**Issue by vvsh** [AsyncHttpClient/async-http-client#938]
Hi

There are problem with library when I trying to run it on android < 5.0.
Problem in MaxRedirectException class that uses Exception constructor with 4 arguments that was introduced in java 7, and my android application crashes in runtime, when I tried to create instance of AsyncHttpClient.

Can you change the constructor which calls new api?
Thanks in advance.

**Comment by slandelle** [comment]
Definitively no. Android compatibility is not a concern here.
Blame Google and the manufacturers for the mess they're turning the Android platform into.

**Comment by vvsh** [comment]
I agree with you, but android before 5.0 version uses java 6, and no one can't do something.

**Comment by slandelle** [comment]
* In regular/real Java world, Java 7 is eol'ed, and more and more library developers, including me, are VERY tempted to target Java 8 and design lambda oriented APIs. Android still doesn't support Java 8.
* Android is such a poor Java citizen. Even SDK 5 is actually not Java 7 compatible. For example, [SSLParameters#setEndpointIdentificationAlgorithm](http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String)) is missing?!
* Manufacturers are responsible for fragmentation. Asking library developers to cope with their mess is not a solution. Forcing them to provide a way for their customers to easily upgrade is.
