### ISSUE TITLE
Feature request: new callback in AsyncHandlerExtensions for TCP connection establishment

### ISSUE THREAD

**Issue by jonas-ren** [AsyncHttpClient/async-http-client#940]
I'm trying to use OnConnectionOpen() to measure connection time and OnSslHandshakeComplete() to measure handshake time for HTTPS requests. However, I noticed that onConnectionOpen() callback is only invoked when the HTTPS connection is established, so it's almost always the same as handshake time, which makes it meaningless. 

Can you guys add a callback like OnTcpConnectionEstablished()? Thinking it would be useful in general.

Thanks!

**Comment by slandelle** [comment]
Should be pretty easy to contribute ;)

**Comment by slandelle** [comment]
> However, I noticed that onConnectionOpen() callback is only invoked when the HTTPS connection is established

You probably meant `onConnectionOpened`.

As of #968, `onConnectionOpened` was replaced by `onConnectionSuccess` and `onConnectionFailure` that are called before the SSL handshake.
