### ISSUE TITLE
Grizzly provider always uses Basic auth when using a proxy

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#941]
Using version 1.9.27, I have a ProxyServer with NTLM as scheme in my AsyncHttpClientConfig but requests are sent with Proxy-Authorization: Basic.

**Comment by oleksiys** [comment]
Hi,
just curious, did it work before?

Thanks.

**Comment by afelisatti** [comment]
I've seen some commits and past issues that were fixed (with contributions I believe) for 1.8.x, that is, before NTLM was broken on that branch.

**Comment by oleksiys** [comment]
I see, I guess it never worked properly. I'll fix the proxy authorization.
Thank you!

**Comment by afelisatti** [comment]
Hi, @oleksiys. Thank you for that. Any idea on when this might be available?

**Comment by oleksiys** [comment]
Hi Ana,
I think tomorrow I'll have it done.
Will let you know.

Thanks!

**Comment by oleksiys** [comment]
Hi Ana,

I've just commited a change to 1.9.x workspace [1], I'd appreciate if you
can test it.

Thank you.

WBR,
Alexey.

[1]
https://github.com/AsyncHttpClient/async-http-client/commit/68c9e7a20c96dff7a872c242496743bdbef08d3e

**Comment by afelisatti** [comment]
Hi, @oleksiys. Thanks for that.
I haven't been able to find a proper proxy for testing but I built a mock one. I tested it using Netty getting the following successful exchange: http://pastebin.com/Guejn0a7 . When trying Grizzly, however, it seems like the 407 response from the proxy was not handled correctly. This was the exchange: http://pastebin.com/CNwrCfxY . 
Let me know if you need any more details.
Thanks again,
Ana

**Comment by oleksiys** [comment]
Hi Ana,

I see, could you pls. share your client code - I'll make sure it works and
commit the fix tomorrow.

Thanks.

WBR,
Alexey.

**Comment by afelisatti** [comment]
Hi, Alexey. 
Thought adding a test would be the best way to share the client and mock server code with you. I opened the above PR (#955) with it. The test is based on the existing NTLM one, but using the proxy headers and status codes. Still trying to find a real proxy to test this against. Let me know if that works. 
Thanks,
Ana

**Comment by oleksiys** [comment]
done, your test passed.

Thank you!

**Comment by afelisatti** [comment]
Thank you, Alexey! 
Everything seems to work, except now HttpTransactionContext's getAsyncHandler() is not public and we were using it. Could this be made public again?

**Comment by afelisatti** [comment]
Disregard previous comment. Everything works great, thanks a lot, Alexey!
