### ISSUE TITLE
Option to specify http client instance name

### ISSUE THREAD

**Issue by stepancheg** [AsyncHttpClient/async-http-client#952]
Requesting a `String` option for http client instance name.

(a field in `AsyncHttpClientConfig.Builder`)

It has two applications: for thread names, and for debugging.

## Thread name

Currently I have hunders of threads like "New I/O worker 120". That's because I have several async http client instances, and "New I/O worker" is a default thread name for Netty.

Requesting async http client simple `String` option: `name`, which is a name of http client instance.

And that name (if specified) should be used by AsyncHttpProvider implementations as a prefix for thread names/pool names.

It is currently possible to specify thread names by manually supplying AsyncHttpProviderConfig with thread factories, but that's too much work for the most use cases.

## Debugging

String field in http client would be helpful to distinguish between multiple instance of http client when setting a breakpoint inside AsyncHttpClient.

**Comment by slandelle** [comment]
Is this something you plan on contributing?

**Comment by stepancheg** [comment]
@slandelle  If you are ready to accept patch like that, I can do it.

**Comment by slandelle** [comment]
Absolutely, contributions are mostly welcome.
Please just implement it on master for both providers: Netty 3 and Netty 4.

IIRC, I had a look at this a long time ago, and it was a bit tricky, as Netty 3 was renaming the threads (see `ThreadRenamingRunnable`).

Thanks!
