### ISSUE TITLE
Shouldn't Response implementations override toString()?

### ISSUE THREAD

**Issue by ayushvora** [AsyncHttpClient/async-http-client#957]
I mean, the [doc](https://github.com/AsyncHttpClient/async-http-client/blob/master/api/src/main/java/org/asynchttpclient/Response.java#L128) also says so but I don't see it overriden. I'm unsure of what can be expected from it but maybe the HTTP status code and the response body?

**Comment by slandelle** [comment]
Contributions welcome :)

**Comment by ayushvora** [comment]
Alright :)
In which case, I'd ask for little help/clarification.
The [doc](https://github.com/AsyncHttpClient/async-http-client/blob/master/api/src/main/java/org/asynchttpclient/Response.java#L128) mentioned says:

> identifies the request for logging

Should it be *identifies the request* or *the response*? 
Also, I was, kinda, coming from the utility of print debugging so, as I said, I was thinking of including the HTTP code and body in the override. How will it affect in the logging if at all the users are doing it?

**Comment by slandelle** [comment]
Forget about what the doc states: it was probably something the original author intended to implement but never did.

Just do something useful: build a String with the response status, headers and body.

Yes, of course, building and printing those is a perf killer that you don't want to do on production.

**Comment by slandelle** [comment]
Closed by #958
