### ISSUE TITLE
Grizzly: 401 response lost when no WWW-Authenticate header is present

### ISSUE THREAD

**Issue by afelisatti** [AsyncHttpClient/async-http-client#959]
When a server responds with a 401 status code but no WWW-Authenticate header, the Grizzly provider throws an exception. Although I understand that this header should be present, many servers don't add it, for example, twitter. The response is lost and so there's no way of knowing what was wrong with your request. You can see an example in a test here that hits the twitter API: https://gist.github.com/afelisatti/98b60503fb5aa577424a . Notice that if the provider is changed to Netty the test passes since you get the expected 401.

**Comment by slandelle** [comment]
:v:

**Comment by oleksiys** [comment]
I'll take a look :)

On Thu, Aug 27, 2015 at 3:48 PM, Stephane Landelle <notifications@github.com

**Comment by oleksiys** [comment]
should be fixed now.

**Comment by afelisatti** [comment]
Thanks, Alexey! 
Just wondering, when can I expect a new release with all these latest fixes?

**Comment by oleksiys** [comment]
@slandelle could you pls. share the plans for the next release?
Thanks.

**Comment by slandelle** [comment]
@oleksiys I wanted to check #960 first. I'll try to release next Monday.

**Comment by oleksiys** [comment]
Thank you!

**Comment by slandelle** [comment]
1.9.31 is out

**Comment by tetsu100** [comment]
@oleksiys I apologize this comment is unrelated to the thread but I am unsure how else to contact you. If possible, can you reply with the Glassifsh revision number(s) for either or both of these issues?

https://java.net/jira/browse/GLASSFISH-19067

https://java.net/jira/browse/GLASSFISH-19035

I will remove this comment shortly, and thank-you for your help if you are able to do so.

**Comment by oleksiys** [comment]
@tetsu100 you can directly comment on the issues you mentioned.
If you're interested in GF SVN revision #, I think it's 61410, the one where Grizzly 2.3.1 was integrated.

**Comment by tetsu100** [comment]
@oleksiys Thank-you very much, deleting these comments tomorrow morning.
