### ISSUE TITLE
OAuth signing duplicates query parameters

### ISSUE THREAD

**Issue by nadavsamet** [AsyncHttpClient/async-http-client#960]
I encountered unexpected behavior of the OAuthSignatureCalculator. I'd love to get your thoughts about it.

If I define a request as following `val request = dispatch.url("http://www.example.com").setMethod("GET").setQueryParameters(Map("page" -> Seq("1"))`
The result of `request.toRequest.getUrl` will be `http://www.example.com?page=1`.

If I sign it using `val signedRequest = request.sign(consumer, token)` and then run `signedRequest.toRequest.getUrl`, the result will be `http://www.example.com?page=1&page=1`.

A workaround can be `request
  .setParameters(Map())
  .sign(consumer, token)
  .setQueryParameters(request.toRequest.getQueryParams.map(p => p.getName -> Seq(p.getValue)).toMap)`.

Any idea what happened to OAuthSignatureCalculator? I think it was introduced a couple of versions ago.

Thanks!

**Comment by slandelle** [comment]
Could you please try with bare latest AHC 1.9.30 to check that:
* it's not a bug in the Dispatch wrapper?
* it's not a bug that's already been fixed but Dispatch is still using an old version?

**Comment by nadavsamet** [comment]
I forgot to mention - I already use AHC 1.9.30 and Dispatch 0.11.3. Unfortunately, it still doesn't work.
I can't say for sure if it's Dispatch or AHC.

**Comment by slandelle** [comment]
The bug is in Dispatch, see AHC test.
