### ISSUE TITLE
JDK provider does not call any callback handler for some exceptions

### ISSUE THREAD

**Issue by stsiano** [AsyncHttpClient/async-http-client#965]
The JDK provider (in the 1.9.x branch) does not call any callback handler if an exception is thrown within the call() method of JDKAsyncHttpProvider.AsyncHttpUrlConnection.
From my understanding this is wrong; a 
asyncHandler.onThrowable(t); 
call should be added at the end of the catch block.

**Comment by slandelle** [comment]
Feel free to provide a fix.
But note that the JDK provider is deprecated and is dropped in AHC2.

**Comment by stsiano** [comment]
I have created a pull request for this.

**Comment by slandelle** [comment]
Thanks
