### ISSUE TITLE
Spawning AHC 2.0 w/ Netty 4 instances very fast leads to fd/thread/memory starvation

### ISSUE THREAD

**Issue by dotta** [AsyncHttpClient/async-http-client#969]
After updating the Play codebase to AHC 2.0-alpha9, I've started to experience issues with non terminating tests because of `OutOfMemoryException`. Until today, I wrongly assumed this was caused by the changes I made in AHC to support reactive streams, but the assumption turned out to be wrong. In fact, I can reproduce even by using AHC 2.0-alpha8, which doesn't include the reactive stream support.

Here is a link to the truly long thread dump demonstrating that AHC 2.0-alpha8 is leaking threads 
https://gist.github.com/dotta/6e388962cf0d904e8170

This issue is currently preventing https://github.com/playframework/playframework/pull/5082 to successfully build.

**Comment by dotta** [comment]
I'm going to try to create a test to reproduce the faulty behaviour.

**Comment by slandelle** [comment]
3 possibilities:
* Netty 4 issue
* AsyncHttpClient#close doesn't properly close all resources (the EventLoop, it seems)
* you're not properly closing, either because you're not closing AHC instances, or because you're providing some external resources, like a ThreadFactory, instead of letting AHC create its own. In this case you have to manage them yourself, AHC#close won't close them for you.

**Comment by dotta** [comment]
I'm speculating this is not a bad usage on the Play side because the problem started to manifest itself by updating AHC from 1.9.29 to 2.0.0-alpha8. But I don't have stronger evidence.

**Comment by dotta** [comment]
I just managed to reproduce the issue with AHC alone. I simply took a random test that creates a `AsyncHttpClient` client in the netty4 provider project, and surrounded the test code with a `while(true)`, and you'll very quickly get a `java.lang.OutOfMemoryError: unable to create new native thread`, which is exactly the issue I'm seeing on the Play side.

**Comment by slandelle** [comment]
Could you please share your full sample?

**Comment by dotta** [comment]
Yep, I was going to do that, just needed time to properly package it. Also, the described issue only occurs with the netty4 extension. Here is a commit with the test to reproduce the problem https://github.com/dotta/async-http-client/commit/67f9c32bac326b15fae018fb6c0f4e38d751f854

**Comment by dotta** [comment]
Upgrading AHC to Netty 4.0.31 final doesn't help.

By the way, if the test I pushed doesn't fail for you, increase the number of iterations https://github.com/dotta/async-http-client/commit/67f9c32bac326b15fae018fb6c0f4e38d751f854#diff-64bc638cdb34d229f29fabdf5721d4cfR7

**Comment by slandelle** [comment]
`AHC#close()` calls at some point `EventExecutorGroup#shutdownGracefully()` which is a shortcut for `EventExecutorGroup#shutdownGracefully(quietPeriod = 2, timeout = 15, SECONDS)`.

It means that an `AHC` instance doesn't close immediately, but let ongoing requests fly for 2 seconds before actually trying to shut down.

It your test, you're spawning too fast.

Using those default values make sense for real world use cases. They might not for tests. I guess we could make those configurable.

**Comment by dotta** [comment]
Makes sense. And, indeed, if I change the call to `shutdownGracefully` with `shutdown`, then the test I wrote doesn't fail anymore. And that seems to be true also on the Play side, as I don't seem to be able to reproduce the OOM with AHC modified as described above.

@slandelle Thanks a lot for the super-quick follow up on this.

**Comment by dotta** [comment]
So, where should we add the configuration values, in `AsyncHttpClientConfig`?

**Comment by slandelle** [comment]
I guess so, yes. Under way.

**Comment by jfarcand** [comment]
@slandelle Since it's Netty specific, should it be in `NettyAsyncHttpProviderConfig`?

**Comment by dotta** [comment]
> I guess so, yes. Under way.

That is awesome. Thanks!

**Comment by slandelle** [comment]
@jfarcand This is a Netty 4 only behavior, hence AHC2 where, hopefully, Netty 4+ will be the main target.

**Comment by dotta** [comment]
Nice. Could you release a 2.0.0-alpha10 (pretty please :smile_cat:)

**Comment by slandelle** [comment]
Absolutely not! But I can surely release alpha11 ;-)

**Comment by slandelle** [comment]
Before I release, could you check that it works for you, please?

**Comment by dotta** [comment]
Sure. Give me ~ 10 minutes

**Comment by dotta** [comment]
Mmmm, `mvn install -DskipTests` fails on master

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project async-http-client-netty4: Compilation failure: Compilation failure:
[ERROR] /Users/mirco/Projects/oos/async-http-client/providers/netty4/src/test/java/org/asynchttpclient/netty/ntlm/NettyNtlmTest.java:[27,48] incompatible types: org.asynchttpclient.AsyncHttpClientConfig cannot be converted to org.asynchttpclient.AsyncHttpClientConfig.Builder
[ERROR] /Users/mirco/Projects/oos/async-http-client/providers/netty4/src/test/java/org/asynchttpclient/netty/NettyPostRedirectGetTest.java:[24,48] incompatible types: org.asynchttpclient.AsyncHttpClientConfig cannot be converted to org.asynchttpclient.AsyncHttpClientConfig.Builder
[...]

**Comment by slandelle** [comment]
Yeah, I accidentally pushed a file I thought I had reverted. Already fixed.

**Comment by dotta** [comment]
@slandelle With your fix, I'm able to run the Play test suite locally without incurring into OOME (it succeeded 3 times out of 3). Time to release :-)

**Comment by slandelle** [comment]
@dotta Done

**Comment by dotta** [comment]
Awesome. Thx!
