### ISSUE TITLE
Update CHMV8 backport from latest JSR166

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#970]

**Comment by slandelle** [comment]
ping @jfarcand

**Comment by jfarcand** [comment]
@slandelle Thanks, will only use those classes if jdk6 is used from now on in Atmosphere. Maintaining those require too much time :-)

**Comment by slandelle** [comment]
It's just a matter of downloading, moving files and changing packages.

As I really need new computeIfAbsent API, I'll either keep on forking, or drop JDK7 support and use regular JDK8.
