### ISSUE TITLE
Redesign Proxy API to have one single ProxyServer instance for both HTTP and HTTPS

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#972]
A very common mistake is to not set the proxy protocol, hence using default HTTP, and then sending an HTTPS request, causing it to timeout.

HTTPS shouldn't be a protocol, but an additional secure port that would be default to the same port than unsecure. That's how things are being done in Gatling, and no one ever complained.

**Comment by slandelle** [comment]
@dotta @jroper Beware, breaking change in next AHC2 alpha.

**Comment by dotta** [comment]
@slandelle Thanks for the note! Let me know when you release the next alpha, and I'll take care of the necessary changes on the Play side.
