### ISSUE TITLE
HTTP error 502 "Bad Gateway" is not handled properly and results in app crash

### ISSUE THREAD

**Issue by acrolink** [AsyncHttpClient/async-http-client#981]
I have followed the instructions at AsyncHttpClient pages and placed a code that makes HTTP post requests to a URL. Under certain conditions the remote server can return HTTP error 502 "Bad Gateway". This particular error is not handled properly by AsyncHttpClient, a thing that leads to immediate app crash.

**Comment by slandelle** [comment]
Could you elaborate, please?

**Comment by acrolink** [comment]
Please put this on hold in the mean time since I suspect that the issue is caused by an unhandlet situation in my app code. I will check this and report back. Thanks.

**Comment by acrolink** [comment]
It turned out that the issue was due to an error in my code. This issue can be closed. AsyncHttpClient works as designed and expected.
