### ISSUE TITLE
Have a more generic way of forcing connection closing

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#982]
We currently have:
* `ConnectionStrategy#keepAlive` that takes a `HttpRequest` and a `HttpResponse` so it doesn't know anything about the body
* `NettyResponseBodyPart#closeConnection`: ugly as it's a mutable field, and that's aware of the `HttpResponse` and the body parts, but not the request

We could have a cleaner solution:
* a Handler can be aware of the `HttpRequest` if it extends `AsyncHandlerExtensions`
* instead of using a mutable field, we could add new `State`s: `ABORT_AND_CLOSE` and `CONTINUE_AND_CLOSE`

@jfarcand WDYT?

**Comment by jfarcand** [comment]
@slandelle Could we also have `ABORT_AND _CONTINUE`.+1 for the proposal.

**Comment by slandelle** [comment]
@jfarcand Sorry, but I don't get it. CONTINUE and ABORT are exclusive. You'd have:

* ABORT: abort and keep alive
* CONTINUE: continue and keep alive
* ABORT_AND_CLOSE
* CONTINUE_AND_CLOSE

WDYM by ABORT_AND _CONTINUE?

**Comment by jfarcand** [comment]
@slandelle I means ABORT :-) OK I completely forgto what ABORT was doing.

**Comment by slandelle** [comment]
@jfarcand Actually, I'm considering dropping current `NettyResponseBodyPart#closeConnection`. From c5a7ea54aae5dfed7c817e5f190c0fb89910a416, it seems this was introduced for having a graceful shutdown. This is what #384 is about. If users want a real safe shutdown (and cope with possibly timing out requests), they have to keep track of flying requests.

IMO,  controlling connection pooling based on response body doesn't really make sense, on contrary to HTTP status, and possibly headers.

WDYT?

**Comment by slandelle** [comment]
Actually, let's always close the connection when `AsyncHandler.onBodyPartReceived` doesn't return `CONTINUE`.
