### ISSUE TITLE
Drop FluentCaseInsensitiveStringsMap

### ISSUE THREAD

**Issue by slandelle** [AsyncHttpClient/async-http-client#987]
Completely useless as we later push the entries into Netty's `HttpHeaders` which is case sensitive.

Question is now: what should we use? Should we keep on hiding Netty API, or should we embrace it?

@jfarcand Thoughts?

**Comment by jfarcand** [comment]
@slandelle Embrace it, to reduce the number of objects on the heap. Will also reduce the code coverage/adjustement we need to make on every new Netty release :-)

**Comment by slandelle** [comment]
Answer I was hoping for :) Thanks

**Comment by slandelle** [comment]
@jfarcand FYI, we won't really reduce heap allocations for now, as `DefaultHttpMessage` eagerly creates a HttpHeader instance.

**Comment by slandelle** [comment]
see https://github.com/netty/netty/issues/4315
