### ISSUE TITLE
SSL Handshake issues after upgrading from 1.8.15 to 1.9.31

### ISSUE THREAD

**Issue by hhimanshu** [AsyncHttpClient/async-http-client#995]
Our existing code uses following code to bypass the validation as 
```
SSLContext context = SSLContext.getInstance("SSL");
        X509TrustManager xtm = new X509TrustManager() {
            public void checkClientTrusted(X509Certificate[] arg0, String arg1) throws CertificateException {
            }

            public void checkServerTrusted(X509Certificate[] arg0, String arg1) throws CertificateException {
            }

            public X509Certificate[] getAcceptedIssuers() {
                return null;
            }
        };
        context.init((KeyManager[])null, new TrustManager[]{xtm}, (SecureRandom)null);
        this.setSSLContext(context);
```

This was working fin with `1.8.15`. But today we upgraded to `1.9.31` and it started failing.
I enabled SSL Debug `-Djavax.net.debug=all` and ran the test, this is what I see

```
java.security.cert.CertificateException: No subject alternative DNS name matching localhost found.
```

What is the possible issue?
If I change the version to `1.8.15`, things start to work

**Comment by wsargent** [comment]
First -- you shouldn't do this.  Write a script to add your self signed certificate to your trust store with keytool.  Either use a custom trust store with all your root certificates plus the extra one and define it with `-Djavax.net.ssl.trustStore=mytruststore.jks` 

You can do it from the [command line](https://www.playframework.com/documentation/2.4.x/CertificateGeneration), or you can use [Keytool Explorer](http://keystore-explorer.sourceforge.net/downloads.php) if you like using a GUI better.

The reason this doesn't work -- you have a self signed certificate that uses "localhost" as the hostname, but you are connecting to a different URL -- your subjectAltName (SAN) is incorrect.

See [fixing hostname verification](https://tersesystems.com/2014/03/23/fixing-hostname-verification/) and [testing hostname verification](https://tersesystems.com/2014/03/31/testing-hostname-verification/) for details.

**Comment by slandelle** [comment]
If you want to bypass validation (definitely something you shouldn't do on production), there's a parameter for that in the config named "acceptAllCertificates".
