### ISSUE TITLE
Proxy Basic auth is broken

### ISSUE THREAD

**Issue by pbostrom** [AsyncHttpClient/async-http-client#996]
Hi, I have a proxy server running on regular http, and I'm trying to make a request to an https address. I create a ProxyServer with my host, port, principal and password and set the client's ProxyServer. When I make a http request everything works fine. When I request an https host, the proxy returns 407 Proxy Authentication Required. This works with version 1.8.16. I've just recently been trying to 1.9.31, it seems like this stopped working with 1.9.0.
I have a small testcase I can provide (in Clojure) if that would help. I need to clean it up a little bit first.

**Comment by slandelle** [comment]
@pbostrom If you can provide a proxy with auth, I can manage.

**Comment by pbostrom** [comment]
Ok, give me a couple days, I'll get it set up.

**Comment by slandelle** [comment]
Cool, thanks!

**Comment by slandelle** [comment]
Note that, for whatever reason, before AHC2, you're supposed to set if the proxy is supposed to be used over HTTP or HTTPS. If you don't, ProxyServer defaults to HTTP and will be ignored for HTTPS.

See https://github.com/AsyncHttpClient/async-http-client/blob/1.9.x/src/main/java/com/ning/http/client/ProxyServer.java#L83

**Comment by pbostrom** [comment]
Yes, the proxy is set up for HTTP. But any traffic going out from the proxy can be either http or https. This is what the equivalent would look like in curl:
curl --proxy-user username:password --proxy http://myproxy.com:8080 https://www.google.com
I will email you the info for my proxy.

**Comment by slandelle** [comment]
As I said, ProxyServer API was broken in AHC1, and I couldn't fix it it 1.9. Implementation was broken in 1.8 too, that led you think things were working as expected in 1.8 (connection pooling was broken).

Have a look at the protocols, and please tell me what HTTP and HTTPS have to do with NTLM, KERBEROS and SPNEGO?

So, in AHC1, because of this weird protocol thing, and as ProxyServer only takes one single port, and not two (one for HTTP, one for HTTPS, possibly the same), if you mix HTTP and HTTPS requests, you can't define the proxy at config level. You have to set the proper one on the request.

**Comment by pbostrom** [comment]
Setting a proxy server with (HTTPS specified) per request does not seem to have any affect. As far as I can tell, AHC 1.9 is not sending the Proxy-Authorization/Proxy-Connection headers with the initial HTTP CONNECT call to the proxy, whereas AHC 1.8 and curl both send the header. See the attached screenshots:
AHC 1.9
<img width="371" alt="screen shot 2015-10-11 at 10 08 09 pm" src="https://cloud.githubusercontent.com/assets/1334481/10420579/256ee236-7065-11e5-953a-c9c7132052f3.png">
AHC 1.8
<img width="494" alt="screen shot 2015-10-11 at 10 09 22 pm" src="https://cloud.githubusercontent.com/assets/1334481/10420580/256f5ed2-7065-11e5-9386-0e4ab6818ddd.png">
Curl
<img width="507" alt="screen shot 2015-10-11 at 10 09 53 pm" src="https://cloud.githubusercontent.com/assets/1334481/10420581/257403a6-7065-11e5-811c-f41517a35cb1.png">

**Comment by slandelle** [comment]
OK, so now, that's a bug :)
If you can get the proxy set up, I'll gladly fix it.

**Comment by pbostrom** [comment]
I emailed you the proxy server and credentials to the email on your gh profile.

**Comment by slandelle** [comment]
Fix in master, but code base and API is very different, so backport isn't straightfoward.

**Comment by pbostrom** [comment]
After inspecting the 1.9 branch I found a workaround to use in the interim. Create a Realm using the auth credentials of the proxy with setTargetProxy(true) and setUsePreemptiveAuth(true). This workaround should work at either the client config level or per request.

**Comment by slandelle** [comment]
Great, thanks for investigating this!

**Comment by ialekseev** [comment]
@pbostrom, could you please elaborate on how to configure it in more details. I would really appreciate it.

**Comment by pbostrom** [comment]
@ialekseev I'm using Clojure but I'll try to port it to Java, consider this pseudocode, it may not compile. This works for basic auth but I haven't tested it with digest.
```java
import com.ning.http.client.Realm;
import com.ning.http.client.AsyncHttpClient;
import com.ning.http.client.AsyncHttpClientConfig;

Realm.RealmBuilder rb = new Realm.RealmBuilder();

rb.setScheme(Realm.AuthScheme.BASIC);
rb.setUsePreemptiveAuth(true);
rb.setTargetProxy(true);
rb.setPrincipal(username);
rb.setPassword(password);

AsyncHttpClientConfig.Builder cfgb = new AsyncHttpClientConfig.Builder();
cfgb.setRealm(rb.build());
// set remaining config options
AsyncHttpClient client = new AsyncHttpClient(cfgb.build());

**Comment by ialekseev** [comment]
@pbostrom, thank you so much

**Comment by gsfernandes** [comment]
Hi, I'm having the same issue, I've tried the workaround proposed in #996 but it does not work with version 1.9.37 and Grizzly 2.3.21. It seems to me that there were other changes from 1.9.31 that are invalidating the workaround proposed by @pbostrom. 
Even more same issue did not happen with 1.9.27 and Grizzly 2.3.21.
Is there any other workaround that you may know of that I could use to make this work?
Thank you!

**Comment by slandelle** [comment]
@gsfernandes This issue was targeting the Netty provider, not the Grizzly one. I can't help with this side. You can try opening a dedicated issue and hope @oleksiys will take a stab at it, or contribute. Proxy auth related issues are a pita to investigate because we've never been able to build embedded integration tests for those.

**Comment by gsfernandes** [comment]
Hi @slandelle, sure I'll create a new issue related to this but for grizzly and if I may I will contribute with a fix.
Thank you

**Comment by gsfernandes** [comment]
Hi @slandelle, I've created issue #1152 for Grizzly provider. I hope @oleksiys could take a look at it. Thank you.
