### ISSUE TITLE
Proxy NTLM auth doesn't work

### ISSUE THREAD

**Issue by zengelan** [AsyncHttpClient/async-http-client#997]
with 1.9.31 proxy authentication to McAfee Web Gateway fails. the McAfee web gateway supports two authentication schemes, basic and NTLM but with the latest version both authentication options fail.
It seems as if asynch-http-client always tries to use basic auth, even when NTLM is selected as proxy type. Also it looks like during the proxy auth phase, it is omitting the authentication for the actual website.
it should send both the proxy authentication credentials and the authentication credentials for the web site with the proxy auth request.
Please ping me via PM and I can supply the proxy details to reproduce the issue.
Packet captures and trace log can be sent via PM too

**Comment by slandelle** [comment]
@zengelan Your email is not in your Github profile, so I can hardly PM :)

**Comment by zengelan** [comment]
@slandelle  i replied to your email address with the mentioned details

**Comment by slandelle** [comment]
Fix in master, but code base and API is very different, so backport isn't straightfoward.

**Comment by zengelan** [comment]
Stephane,
Can you kick off a build with the proxy fixes? 

On 13 Oct 2015, at 11:38, Stephane Landelle <notifications@github.com> wrote:

Fix in master, but code base and API is very different, so backport isn't straightfoward.

**Comment by slandelle** [comment]
You mean that you want to try AHC2?

**Comment by zengelan** [comment]
i will give it a try

**Comment by slandelle** [comment]
If you have maven, it's very easy to build. You just need to download/git pull master and then `mvn clean install`. I know it would be great if I could set up a CI, but I could never find time, sorry.

Beware that AHC2 is a different beast: packages changes, API are changing and it depends on Netty 4 now.

If you manage to build, I can pass you my test that hits on your proxy.

**Comment by zengelan** [comment]
if APIs changed i won't be able to test it out. so i'll wait for a backport into 1.9.x

**Comment by slandelle** [comment]
Getting NTLM proxy auth right was a lot of work. I should be able to backport the basic auth fix from #996, but I'm very skeptical about this one.
